server.js

Gemnasium changed the SVG. The fix for this issue is small and simple.

Fix gemnasium badge

---

server.js
try.html

Working with CircleCI, decided to implement a shield, fixes badges/shields#313

Implement CircleCI integration

---

server.js
try.html

Also I refactored the crates.io backend code to be more data-driven.

rust license badge support

---

server.js
try.html

This adds basic support (version and license) for CTAN (TeX/LaTeX) package badges.

Add CTAN integration

---

server.js
try.html

This adds basic support (version and license) for CPAN (Perl) package badges.

Add CPAN integration

---

server.js
try.html

This PR:
* Rebases the Puppet Forge code on the v3 API
* Retrieves additional infos from the Forge API:
- 'dt': total downloads of a module
- 'e': endorsement of a module (approved/supported)
- 'f': feedback score (percentage)
* Add user statistics from the Forge API:
- 'rc': user's release count
- 'mc': user's module count

Improve Puppet Forge badges

---

try.html

Update try.html so sonarqube badge works for #399

---

server.js
try.html

dub integration

---

server.js
try.html

Add Scrutinizer Build integration

---

server.js
try.html

For Clojure, see: http://clojars.org/

Clojars support

---

server.js
try.html

Add support for SonarQube's technical debt ratio.
Also implemented #430.

SonarQube technical debt ratio

---

server.js
try.html

This pull request adds badges for Gems ranking, taken from bestgems.org:
* `/gem/rt/<gem>` for total ranking (consolidated)
* `/gem/rd/<gem>` for daily ranking

Add Gem ranking badges

---

server.js
try.html

Add docker stars integration

---

server.js

add functionality for Shippable Build Badges

---

try.html

Adding myself to the contributors list - I added TeamCity code coverage and NuGet download count last year, and the contributor list didn't exist at that time.
Also added some other people that were missing. Since the contributors are split onto three lines,  the list would have been misaligned if I just added myself. I just added two people that were missing based on commit count.

Add myself (and some others) to contributors list

---

server.js
templates/social-template.svg
try.html

This adds a badge which links to the twitter follow user page. Found myself wanting it and decided to make one. Fixes #527
This does not show a follower count, so I took the liberty of creating a new template to go along with it. There is also not an issue with rate-limiting from the twitter API, since this will not hit the API at all.

Add twitter follow badge

---

server.js

Fix `gemnasium badge` issue https://github.com/badges/shields/issues/591.

fix server gemnasium: update! -> up-to-date

---

server.js
try.html

I added support for branches in the codecav part (see #596 ).
However I couldn't test it since I only have a mac available and I wasn't succesfull in running the npm install (due to Failed at the canvas@1.1.6 install script 'node-gyp rebuild'.).
So if one of the reviewers can test it and let me know.
Thanks

added codacy branch support

---

server.js
try.html

Supersedes #387.
Rebased against current master, and added the requested fixes.

Add StackExchange integration

---

server.js

Tested via node CLI
```
> svgStr.match(/'14'>(.+)<\/text>\s+<\/g>/)
[ '\'14\'>up-to-date</text>\n  </g>',
'up-to-date',
index: 810,
input: '<svg height=\'20\' width=\'158\' xmlns=\'http://www.w3.org/2000/svg\'>\n  <linearGradient id=\'a\' x2=\'0\' y2=\'100%\'>\n    <stop offset=\'0\' stop-color=\'#bbb\' stop-opacity=\'0.1\'></stop>\n    <stop offset=\'1\' stop-opacity=\'0.1\'></stop>\n  </linearGradient>\n  <rect fill=\'#555\' height=\'20\' rx=\'3\' width=\'158\'></rect>\n  <rect fill=\'#4c1\' height=\'20\' rx=\'3\' width=\'70\' x=\'88\'></rect>\n  <rect fill=\'#4c1\' height=\'20\' width=\'4\' x=\'88\'></rect>\n  <rect fill=\'url(#a)\' height=\'20\' rx=\'3\' width=\'158\'></rect>\n  <g fill=\'#fff\' font-family=\'DejaVu Sans,Verdana,Geneva,sans-serif\' font-size=\'11\' …
```

fix(server.js): Gemnasium svg regex update

---

server.js
try.html

This scrapes the HTTP response when fetching the Magnum CI status badge.
Fixes #523.

New vendor: Magnum CI.

---

server.js
try.html

**URL**
Pattern: `/jira/issue/<protocol>/<host>/<issue-key>.<format>`
Example: `/jira/issue/https/issues.apache.org/jira/KAFKA-2896.svg`
**Auth**
Add `jira_username` and `jira_password` entries to the *./secret.json* file.

Add Jira issue vendor

---

server.js

Fix color of twitter that should now be blue (and not RED)
test on: 
http://localhost:1111/twitter/follow/ELLIOTTCABLE.svg?style=flat&label=followers 
cf #620

Fix twitter scheme color

---

server.js
try.html

Resolves #571.
I don't have the wherewithal to test this right now, so I'm hoping having just emulated existing code will be sufficient...

Add support for Code Climate issues

---

server.js
try.html

Add badge for the [Arch User Repository (AUR)](https://aur.archlinux.org).  Includes badges to
display the current version, number of votes, and license.
Unfortunately, their [API](https://aur.archlinux.org/rpc.php) does not display downloads at this stage.

Add AUR integration.

---

server.js
try.html

This PR adds support for beerpay.io, as requested in #659.
Fixes: #659 
Thanks for considering 👍
@colkito

added beerpay.io itegration

---

index.html
server.js
try.html

I add pullrequests & contributors integration

Enhance GitHub integration

---

server.js

Also fixes some small bugs
https://github.com/badges/shields/issues/710
`branchName` has been renamed to `branch`
https://github.com/badges/shields/issues/684
color was not correct
https://github.com/badges/shields/issues/667  
```
/shippable/56cc85b91895ca4474774f01/master.svg?label=production&successLabel=shippable
```
```
/shippable/56cc85b91895ca4474774f01/test.svg?label=test&successLabel=shippable&cancelledLabel=unshippable
```
```
/shippable/56cc85b91895ca4474774f01/staging.svg?label=staging&successLabel=shippable&cancelledLabel=unshippable
```
[1]:https://cloud.githubusercontent.com/assets/5207331/15151019/2f7bd23c-16ed-11e6-8267-97c5f673f3b6.png
[2]:https://cloud.githubusercontent.com/assets/5207331/15151118/80d5c598-16ed-11e6-853e-b0312a5659ab.png …

Adds ability to customize shippable badges

---

INSTALL.md

Should be `docker build` instead of `build`

Fix minor mistake in command

---

try.html

This was broken by 89affa49fec5

Fix badge preview on style change

---

server.js

Fix contributors badge

---

README.md

Add docs.rs as a standard-compliant service

---

server.js
try.html

example JSON URL:
http://crandb.r-pkg.org//devtools

add support for CRAN/METACRAN

---

index.html
try.html

Correctly apply changes from #898, and update build of index.html.

Disambiguate provider vs package: Package Control

---

lib/server-secrets.js
lib/suggest.js
server.js

- Quit witih an error when secrets can’t be loaded
- Refactor duplicated code
Resolves #894

Clarify that secrets are optional

---

server.js

Closes #946 “maintenance badge doesn't need a question mark”

---

package.json

At least this fixes deprecated uuid warning

Update request to 2.81.0

---

server.js

http://docs.sonarqube.org/display/SONAR/Metric+Definitions
through about doing anything containing _density but some lower density's are good->green this is the one i care about.

[SonarQube] Treat java doc ratio like a % with 100 best

---

templates/social-template.svg

Eliminate padding on social badges if rhs is empty

---

server.js
try.html

PS Gallery is nuget v2 based.  Fixes #1013.

Adding support for PowerShell Gallery

---

server.js
service-tests/gratipay.js

Fixes #1005, adds service tests to Gratipay
Previous merge request (#1006) was off of the maintenance branch.

fix(gratipay): distinguish between anonymous and 0 dollar projects

---

doc/TUTORIAL.md

Removed info about index.html in tutorial

---

server.js
service-tests/conda.js
try.html

Add conda badges

---

try.html

github "star" -> "stars"

---

lib/measure-text.spec.js
package.json

I merged some code earlier which touched this file, and realized it would be good to have a test around it.

Add test for measure-text

---

lib/luarocks-version.js
lib/luarocks-version.spec.js
lib/php-version.js
lib/text-formatters.js
server.js
service-tests/luarocks.js
try.html

This is an reopening of #766.
I've updated and rebased my changes onto upstream and added tests.
`/luarocks/v/USERNAME/PACKAGE.FORMAT`

[LuaRocks] package version badge

---

server.js
service-tests/mozilla.js

Closes #1026 
Closes #996 
Added tests
URL | Badge
:--- | :---:
`/amo/stars/indiegala-helper.svg?label=My%20Addon` | ![](https://img.shields.io/badge/My%20Addon-%E2%98%85%E2%98%85%E2%98%85%E2%98%85%E2%98%86-brightgreen.svg)

[amo] Custom labels & Tests

---

server.js

fixed ColorB issue for Docker Badge

---

try.html

Quick Added https://github.com/badges/shields/issues/985 😄

Discord social button added at very bottom of the page. #985

---

try.html

closes https://github.com/badges/shields/issues/1104

Add in text snippet for AsciiDoc image macro

---

lib/badge-data.js
server.js
service-tests/waffle.js

background color (ColorB) fixed.
fixes #1008 
**BTW, all test added against fake data**

[waffle] colorB fixes & Test added

---

server.js
service-tests/appveyor.js
try.html

This PR was based off of #817 but displays total passed, total failed and total tests.

Add AppVeyor tests badge

---

server.js
service-tests/bower.js
try.html

Fixes #1098 (Pre-release badge added)

[Bower] pre release badge added

---

try.html

Document the named logos feature from #1092.

Document named logos

---

server.js
service-tests/README.md
service-tests/amo.js
service-tests/ansible.js
service-tests/appveyor.js
service-tests/bower.js
service-tests/chrome-web-store.js
service-tests/codecov.js
service-tests/codetally.js
service-tests/conda.js
service-tests/continuousphp.js
service-tests/cran.js
service-tests/crates.js
service-tests/discord.js
service-tests/github.js
service-tests/helpers/validators.js
service-tests/hexpm.js
service-tests/jetbrains.js
service-tests/jitpack.js
service-tests/luarocks.js
service-tests/maven-central.js
service-tests/nexus.js
service-tests/vscode-marketplace.js
service-tests/waffle.js

- Consolidate regexes
- Use slimmer syntax where possible
- Fix bug caught by failing amo tests
All service tests passing locally when I apply the fix from #1118.

Clean up service tests

---

server.js
service-tests/github.js

[Github] issues: Accommodate multi-word labels

---

try.html

Github: Fix issue label in example badges

---

server.js
service-tests/readthedocs.js
try.html

Hello.
I tried to add support for **Read the Docs** builds (optionally versioned).
This PR is related to #136
I must admit that your tutorial to add a new badge is very very good, I was able to implement all this effortlessly. Thank you for the explanations. 👍 
If you want me to change anything, tell me.

[ReadTheDocs] Add initial support

---

lib/github-auth.js
lib/suggest.js
service-tests/suggest.js

This PR tries to resolve https://github.com/badges/shields/issues/821.

[suggest] Badge suggestions show incorrect license

---

server.js
service-tests/github.js
try.html

Hello,
As discussed in the review comments of #1160, here is a pull request for a new repository size badge.
Cheers,
Pyves

[GitHub] Repository size badge

---

server.js
service-tests/eclipse-marketplace.js
service-tests/helpers/validators.js
try.html

This pull request is related to issue #1165. I have implemented the four new badges suggested there and have created a new service test file to cover them.
All the code was added underneath the Visual Studio Marketplace integration, as it seemed to be the most closely related one.
Looking forward to comments and feedback! 👍 
Cheers,
Pyves

[eclipse-marketplace] New marketplace integration

---

lib/badge-data.js
lib/badge.js
templates/for-the-badge-template.svg
try.html

closes #818 
https://forthebadge.com/ style of badges
This PR | For The Badge
:---: | :---:
Also supports logos:

for the badge style badges

---

package.json

Reviewing the commits, it doens’t appear anything of significance has changed.

Upgrade dot

---

README.md

Based on info in https://github.com/badges/shields/pull/1129#discussion_r144972746

Add new maintainer and update history

---

server.js
service-tests/coveralls.js
try.html

- adds support for bitbucket in coveralls
- move to new coveralls api
- add test for coveralls
https://github.com/badges/shields/issues/793

[Coveralls] bitbucket support #793

---

lib/all-badge-examples.js
try.html

Add JetBrains plugin version to the front page

---

logo/postgresql.svg

The svg file is taken and optimized from https://wiki.postgresql.org/wiki/Logo

Add a PostgreSQL logo

---

lib/all-badge-examples.js
try.html

References:
- https://en.wikipedia.org/wiki/ITunes
- https://www.apple.com/itunes/

Fix style issue with iTunes App Store on homepage

---

lib/all-badge-examples.js
try.html

Added Funding category as described in #1054

Added Funding category

---

lib/request-handler.js
lib/request-handler.spec.js

Fix the cache bug introduced in #1186 that blocked today's deploy.

Cache keys should not be the same

---

doc/self-hosting.md

Add documentation for gh_token when self-hosting

---

lib/badge-cli.js
lib/make-badge.js
lib/make-badge.spec.js
lib/request-handler.js
lib/svg-badge-parser.spec.js
lib/svg-to-img.spec.js
server.js

Change makeBadge() to a synchronous function

---

lib/all-badge-examples.js
server.js
service-tests/bitrise.js

Added new service Bitrise.io requested in #574

[bitrise] Added new build service Bitrise.io

---

lib/github-auth.js

Fix production bug #1245 introduced in #1118

Use GitHub token rotation in production :P

---

lib/all-badge-examples.js
server.js
service-tests/elm-package.js

add [elm-package] badge

---

server.js

Hello,
Pull request related to #1246 and #1268. Nothing much going on here, just making sure the Elm Package version badge is consistent in terms of text and colour with other version badges!
Cheers,
Pyves

[elm-package] Cleaned up Elm Package version text and colour

---

package-lock.json
package.json

The version in Shields goes back to last August. I reviewed the commits and didn't see any obvious incompatibilities. Hopefully @espadrine can weigh in!

Upgrade camp

---

CONTRIBUTING.md

P.S. If anyone reading wants to get more involved in code review, please join in! Feel free to review my open changes, and reach out if you need help "plugging in" your skills.

CONTRIBUTING: Add code review to ways to help

---

package-lock.json
package.json

Fix https://github.com/mikec/sazerac/pull/12

Upgrade sazerac

---

package-lock.json
package.json

Upgrade moment

---

README.md

Readme: Fix logo link

---

lib/all-badge-examples.js

Fix some example and preview URLs

---

.travis.yml
Makefile
app.json
frontend/components/badge-examples.js
frontend/components/dynamic-badge-maker.js
frontend/components/footer.js
frontend/components/static-badge-maker.js
frontend/lib/resolve-uri.js
next.config.js
package-lock.json
package.json

- Do not use bogus `'undefined'` as base URI

Frontend: Allow BASE_URL to be unset

---

frontend/components/markup-modal.js

Fix markup modal when baseUri is unset

---

doc/self-hosting.md
lib/github-auth.js
lib/server-config.js
now.json
package.json
server.js

I'm experimenting with Zeit Now as another hosting option. These changes enable a working deployment.

Configure for deployment with zeit now

---

package-lock.json
package.json

I ran `npm run test:services -- --only=badge/dynamic/json` locally and everything looks good. 👍

Upgrade jsonpath [badge/dynamic/json]

---

frontend/components/markup-modal.js
frontend/components/usage.js
lib/badge-data.js
lib/badge-data.spec.js
lib/supported-features.js
lib/supported-features.spec.js

- Restore correct list of styles to markup modal
- DRY lists of styles
Fix #1330

Fix style picker in markup modal

---

package-lock.json
package.json

Using fix from mapbox/react-click-to-select#15.
From #1273

Fix validateDOMNesting warning

---

.eslintrc-frontend.yml
frontend/components/dynamic-badge-maker.js
frontend/lib/badge-url.js
frontend/lib/badge-url.spec.js

Fix dynamic badge URL generator

---

frontend/components/footer.js

minor changes in footer

---

server.spec.js

Increase the timeout on a test that often runs out of time

---

lib/make-badge.js
templates/flat-square-template.svg
templates/flat-template.svg
templates/for-the-badge-template.svg
templates/plastic-template.svg
templates/social-template.svg

This is a 5–15% speedup. It's hard to be more specific because I got some pretty different runtimes with and without this patch.
The main strategy was to avoid so many object accesses.

Optimization + cleanup in makeBadge

---

lib/text-formatters.spec.js

Fix January unit test

---

lib/lru-cache.spec.js

This is in preparation for a PR that adopts Chai for assertions, which I'll open separately.

Refactor LRU cache test asserts

---

service-tests/runner/pull-request-services-cli.js

Match work done in #1453 to our CI setup.
Added [cran] for testing.

Fix PR metadata auth [cran]

---

lib/all-badge-examples.js

clarify default for Uptime Robot ratio

---

server.js

update codacity urls

---

lib/all-badge-examples.js
server.js
service-tests/vaadin-directory.js

Vaadin Directory is a place which contains thousand of Web UI components for users. We want to make a dynamic badge so that authors can put into their projects.
- Tests have been added
- Also added the badge to all-badge-example.js

Added [Vaadin-Directory] badge service

---

lib/all-badge-examples.js
server.js
service-tests/depfu.js

Add the Depfu dependencies badge. Fixes #1523

Add [Depfu]

---

lib/badge-cli.js
lib/badge-cli.spec.js
lib/request-handler.spec.js
lib/svg-to-img.spec.js
server.spec.js
service-tests/runner/pull-request-services-cli.js

A big advantage of Node 8 is support for async–await. Our service code will particularly benefit from this, but so does the rest of our async code.
It's remarkable how much clearer these look!

Adopt async-await for most promise-based code

---

.circleci/config.yml

Possible fix for #1415.
I'm not sure if there's an easy way to test this before merging it.

Try to fix greenkeeper-lockfile not updating

---

services/appveyor.js

I noticed the new AppVeyor badges were gray. This fixes them.

Fix colors for new appveyor badge

---

lib/text-formatters.js
lib/text-formatters.spec.js

This pull request should resolve issue #1609.
Related pull request: #1615.

Number support for version text formatter

---

package-lock.json

package-lock fixes for glob

---

server.js

Officially out of beta on Monday https://pypi.org/help/#beta

update [pypi] to use warehouse (closes #1569)

---

logo/npm.svg

simplified vector NPM logo. 40x40px

Add NPM logo

---

doc/gh-badges.md

Just fixing 2 links
great project!

minor links fix

---

templates/flat-square-template.svg
templates/flat-template.svg
templates/for-the-badge-template.svg
templates/plastic-template.svg
templates/social-template.svg

This better supports the `<object data="..">` embed style
Closes #1665

open social badge links in new tab

---

server.js
services/homebrew/homebrew.tester.js

[formulae.brew.sh](formulae.brew.sh) has switched to a new JSON API which offers the complete formula data.

[homebrew] Adapt to new JSON API of formulae.brew.sh

---

package-lock.json
package.json

All of the tests which use sinon are run in the CI build - it is not used in any of the service integration tests

upgrade sinon

---

.github/probot.js

Description can be found in https://github.com/badges/shields/issues/1708

Probot workflow configuration with deployment status

---

lib/all-badge-examples.js
server.js
services/waffle/waffle.tester.js

- update URL and parsing code to use /columns endpoint
- add error handling for 'not found' case
- add missing test cases
- update home page example
Closes #1731
Refs https://github.com/waffleio/waffle.io/issues/3559

fix [waffle] labels badge

---

server.js
services/bitrise/bitrise.tester.js

Daily tests have been failing for the last few days.
Looks like the bitrise API doesn't respond on `www.` anymore

update [bitrise] URL

---

.github/probot.js

This is the last thing to be done in https://github.com/badges/shields/issues/1708

Probot uses badges from img.shields.io

---

lib/all-badge-examples.js
lib/deprecated-services.js
server.js
services/bithound/bithound.tester.js
services/magnumci/magnumci.tester.js

Deprecate [magnumci bithound]

---

services/appveyor/appveyor.tester.js
services/bitbucket/bitbucket.tester.js
services/buildkite/buildkite.tester.js
services/circleci/circleci.tester.js
services/codeship/codeship.tester.js
services/continuousphp/continuousphp.tester.js
services/docker/docker.tester.js
services/readthedocs/readthedocs.tester.js
services/scrutinizer/scrutinizer.tester.js
services/shippable/shippable.tester.js
services/test-validators.js
services/travis/travis.tester.js

[appveyor bitbucket buildkite circleci codeship continuousphp docker readthedocs scrutinizer shippable travis] Extracted isBuildStatus test validator

---

.eslintrc.yml
server.js

details [here](https://eslint.org/docs/rules/object-curly-spacing)
set `object-curly-spacing: ["error", "always"]`
A majority of our code already abides by this,
So i think it would be best to just make it an actual rule.
👎 Examples that will fail:
```javascript
var obj = {'foo': 'bar'};
var obj = {'foo': 'bar' };
var obj = { baz: {'foo': 'qux'}, bar};
var obj = {baz: { 'foo': 'qux' }, bar};
var obj = {'foo': 'bar'
};
var obj = {
'foo':'bar'};
var {x} = y;
import {foo } from 'bar';
```
👍  Examples that will pass:
```javascript
var obj = {};
var obj = { 'foo': 'bar' };
var obj = { 'foo': { 'bar': 'baz' }, 'qux': 'quxx' };
var obj = {
'foo': 'bar'
};
var { x } = y;
import { foo } from 'bar';
```

Eslint enable `object-curly-spacing`

---

package-lock.json
package.json

This isn't for a specific feature, just to use the latest. There's a feature I wanted to use, `inspectOnFailure`, but it's not working correctly so I'm opening a PR upstream.

Bump icedfrisby version

---

server.js
services/circleci/circleci.tester.js

This changes the badge so it requires all jobs in the build to pass in order for the status to be 'passing'
Closes #1792

Fix [circleci] badge

---

server.js
services/conda/conda.tester.js

This pull request addresses #1781.

[conda] Fixed wrong variable name

---

.circleci/config.yml

refs #1826
This is hard to test, but should do what we want.

don't run danger on dependabot PRs

---

services/github/github.tester.js

These two time out quite often
e.g. https://circleci.com/gh/badges/shields/9050

Lengthen timeout on a flaky service test

---

services/base.js

I ran into this while working on #1867, where ultimately I couldn't solve my problem by injecting config. This will make it easier in the future, though.

BaseService: Make it easier to add more config options; tested on [dynamic-json]

---

services/apm/apm.service.js
services/appveyor/appveyor.service.js
services/base-json.js
services/base-json.spec.js
services/base.js
services/base.spec.js
services/cdnjs/cdnjs.service.js
services/clojars/clojars.service.js
services/gem/gem-downloads.service.js
services/gem/gem-owner.service.js
services/gem/gem-rank.service.js
services/gem/gem-version.service.js
services/npm/npm-base.js
services/npm/npm-downloads.service.js
services/time/time.service.js

There’s a lot of behavior here, and going to be even more, so I think it makes sense to split these up as I’ve done with the tests.

Split BaseService and BaseJsonService into separate modules; tested on [clojars gem npm appveyor cdnjs]

---

services/service-tester.js

Was debugging this just now, and think this is easier to read and understand than the previous version.

ServiceTester: Minor readability tweak; test on [dynamic-json]

---

lib/all-badge-examples.js

It's really not a downloads badge.
As we're considering our groupings, it might be nice to add an Uptime section for this + UptimeRobot. I'm open to doing that now if folks think we should.

Create Monitoring category

---

services/base-json.js
services/librariesio/librariesio-base.js
services/librariesio/librariesio-dependent-repos.service.js
services/librariesio/librariesio-dependent-repos.tester.js
services/librariesio/librariesio-dependents.service.js
services/librariesio/librariesio-dependents.tester.js
services/npm/npm-base.js

Add badge for dependents and dependent repos using Libraries.io [librariesio-dependents librariesio-dependent-repos]

---

services/npm/npm-base.js
services/npm/npm.tester.js

I noticed this when I copied this code while I was working on #1895.

Fix an edge case in NpmBase

---

dangerfile.js
package-lock.json
package.json
services/github/github.tester.js
services/npm/npm.tester.js

As discussed breifly in https://github.com/badges/shields/pull/1922/files/0fbba07af7caf10c8ae921fce1842f4c4c6d4679#diff-7d81f97940c754ee6834b43e84fd001b

Prevent merging exclusive service tests

---

.circleci/config.yml

Disable CircleCI cache

---

doc/TUTORIAL.md

The old link moved. I corrected the link.

Fix link to service tests

---

doc/service-tests.md

- fixes https://github.com/badges/shields/issues/1971
Thanks @paulmelnikow. Now, it works.
I added my clarification to the documentation.

Clarify what is used to run the specific tests

---

services/wercker/wercker.service.js

- issue: https://github.com/badges/shields/issues/1961

make wercker preview badge static

---

.github/probot.js

Follow up to #1996
- highlighted discord channel
- combined last phrases and moved badge
@paulmelnikow @PyvesB Do you think that's an valid improvement?
Don't hesitate to simply close this if you don't see fit.

deploy bot msg: tweaks and streamlining

---

.prettierignore
dangerfile.js
next.config.js
server.js
server.spec.js

Prettify the files in the project root

---

services/pypi/pypi-helpers.spec.js

add additional test cases for pypi license helper

---

services/base.js

fixed the issue mentioned in #2057

fixed bug that prevented logo color from being changed

---

lib/all-badge-examples.js
lib/deprecated-services.js
services/libscore/libscore.service.js
services/libscore/libscore.tester.js

Deprecate [libscore]

---

services/cpan/cpan.service.js
services/cpan/cpan.tester.js

Unified cpan license badge.
before:
after:

unified [cpan] license badge

---

services/beerpay/beerpay.service.js
services/beerpay/beerpay.tester.js
services/test-validators.js

Hi! I've added basic tests for the beerpay service.

[Beerpay] test

---

services/bintray/bintray.service.js
services/bintray/bintray.tester.js

Hi! I've added basic tests for the bintray service.

[bintray] test

---

services/scrutinizer/scrutinizer.service.js
services/scrutinizer/scrutinizer.tester.js

lightgrey color in build [scrutinizer] badge for unknown status

---

services/ctan/ctan.service.js
services/ctan/ctan.tester.js

Hi! I've added some basic ctan service tests ;)

[ctan] add tests

---

frontend/components/examples-page.js
frontend/components/markup-modal.js

[Link to Issue](https://github.com/badges/shields/issues/2122)
Migrate componentWillReceiveProps to "fully uncontrolled component with key" base on [recommendation](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key) published on react blog.

remove use of componentWillReceiveProps()

---

services/gitter/gitter.service.js
services/gitter/gitter.tester.js

Hi! not really serious work, but hey 😉

[gitter] test "static" service behaviour

---

lib/suggest.js

This makes it easier to discover source code for the server part. The message is from 9883d2bd190c0a0ab526885a8489e5c384c771ac,

Document suggestion API endpoint

---

services/nuget/nuget.service.js
services/powershellgallery/powershellgallery.tester.js

refs #2078
Even if we deploy this and it breaks again soon, its better than just leaving it broken

switch [powershellgallery] to use temp url

---

services/eclipse-marketplace/eclipse-marketplace-license.service.js
services/eclipse-marketplace/eclipse-marketplace-license.tester.js

Simply an additional badge for our Eclipse marketplace integration.

[eclipse-marketplace] License badge

---

lib/all-badge-examples.js
services/swagger/swagger.service.js
services/swagger/swagger.tester.js

Also created `swagger.tester.js`

Refactor [Swagger] Service

---

frontend/components/suggestion-and-search.js
lib/php-version.js
lib/regular-update.js
lib/svg-to-img.js
services/php-eye/php-eye-php-version.service.js
services/travis/travis-php-version.service.js

In #2028 I suggested that we update as much of the code as possible to make consistent use of async await. This snags a bunch of the utility code and attempts to do that. Most of this work is cherry-picked from #2029.

[travis php-eye] Make more consistent use of async/await

---

now.json

This PR solves https://github.com/badges/shields/issues/2262
An example deployment https://github.com/badges/shields/issues/2262#issuecomment-435699831 + https://shields-prometheus-test-sijbgwyxts.now.sh

Now deploy fix - package-lock.json added to "files'"

---

lib/analytics.js
lib/service-test-runner/infer-pull-request.js
lib/suggest.js

Remove some uses of to-be-deprecated url.format and url.parse APIs

---

services/wordpress/wordpress-rating.service.js

round [wordpress] rating

---

services/clojars/clojars-downloads.service.js
services/clojars/clojars-downloads.tester.js

Since #1192 seems to have been abandoned, I had a go at creating a Clojars downloads badge myself.
For now just total downloads, although in the json response there are download counts for some recent versions.
Closes #1152.

[Clojars] Add downloads badge

---

services/static-badge/static-badge.service.js
services/static-badge/static-badge.tester.js

Fix regression with double-dash escaping in [StaticBadge]

---

README.md

I think this better captures the meaning of this badge, especially from an outsider perspective.

Readme: Update badge label

---

services/packagecontrol/packagecontrol.tester.js

One less service to add tests to!

Tests for [PackageControl] service

---

lib/request-handler.js
services/legacy-service.js

Fix crash in legacy service

---

frontend/components/usage.js

this makes them a bit nicer to copy & paste

show dynamic badge examples with a base

---

doc/rewriting-services.md

- use the right issue no and link to it
- fix the trace command example

couples of fixes to docs on porting legacy services

---

services/base.spec.js

Attempting to add some more tests as described in #2060 
This is my first time looking into the base service so hopefully these are valid/useful tests and inline with the ask!

Adds more tests for base class overrides

---

services/swagger/swagger.service.js

fix swagger example

---

services/npm/npm-base.js

Fix [npm] badges when a dependency points to a URL

---

services/dynamic/dynamic-xml.service.js
services/dynamic/dynamic-xml.tester.js
services/dynamic/dynamic-yaml.service.js
services/dynamic/dynamic-yaml.tester.js

Ref https://github.com/badges/shields/pull/2519#issuecomment-449511750

Fix import issue with [dynamic] badge

---

lib/server.js

This call was missed in #2519.

Register missing redirects [static]

---

services/github/github-api-provider.integration.js

e.g. https://circleci.com/gh/badges/shields/31681

Extend timeout on GitHub integration test

---

services/scrutinizer/scrutinizer.tester.js

Change [Scrutinizer] branch coverage test target

---

README.md
services/base.js
services/base.spec.js
services/transform-example.js
services/transform-example.spec.js

Remove support for exampleUrl

---

services/github/github-api-provider.integration.js

Unflake GitHub integration test

---

package.json

Without this change none of the badges load. Probably happened in #2626.

Fix frontend start script

---

doc/production-hosting.md

I found an old note to myself to document this.

We don't use Docker in production

---

.circleci/config.yml

See discussion in badges/daily-tests#4.

Rm unnecessary `mkdir` in Circle config

---

dangerfile.js

I found an old note to document this.

Add instructions for testing Danger locally

---

services/opencollective/opencollective-backers.tester.js
services/opencollective/opencollective-base.js
services/opencollective/opencollective-by-tier.service.js
services/opencollective/opencollective-by-tier.tester.js
services/opencollective/opencollective-sponsors.tester.js

Backers by tier badge now shows "unknown tier" as a label when the collective was not found
Closes #2699

Update [opencollective] error handling

---

services/bstats/bstats-players.service.js
services/bstats/bstats-players.tester.js
services/bstats/bstats-servers.service.js
services/bstats/bstats-servers.tester.js

This makes it a bit more consistent with the others.

Tweak formatting of [bstats] badge

---

doc/service-tests.md
lib/service-test-runner/cli.js

Wildcard to run all service tests

---

services/gem/gem-rank.tester.js

See https://circleci.com/gh/badges/shields/34350

Update [gemrank] regex to match "1st"

---

frontend/components/markup-modal/markup-modal-content.js

https://lgtm.com/projects/g/badges/shields/snapshot/39309c9c207b770716a37e481419a5d4ea028250/files/frontend/components/markup-modal/markup-modal-content.js?sort=name&dir=ASC&mode=heatmap#x9b1573629b59d42e:1

Remove some unused state to clear lgtm alerts

---

gh-badges/lib/make-badge.spec.js
gh-badges/templates/_shields_test-template.json
lib/badge-data.js
services/github/github-commits-since.tester.js

Ref: https://github.com/badges/shields/pull/2780#issuecomment-454873296

Fix color again, for legacy badges

---

package.json

Fix integration test pattern

---

core/server/server.spec.js

This test is being weirdly flaky in #2809. The problem seems to be in the test helper code, so I rewrote this using Joi.
I imagine the change has to do with a change to the test ordering. It's a bit puzzling.
However, the new test seems fine (and the endpoint is rarely used; not critical to begin with).

Rewrite test of analytics endpoint

---

services/github/github-commit-activity.service.js
services/github/github-commits-since.service.js
services/github/github-downloads.service.js
services/github/github-followers.service.js
services/github/github-forks.service.js
services/github/github-issue-detail.service.js
services/github/github-issues.service.js
services/github/github-languages.service.js
services/github/github-last-commit.service.js
services/github/github-license.service.js
services/github/github-release-date.service.js
services/github/github-release.service.js
services/github/github-repo-size.service.js
services/github/github-size.service.js
services/github/github-stars.service.js
services/github/github-tag.service.js
services/github/github-watchers.service.js
services/liberapay/liberapay.service.js
services/twitter/twitter.service.js

this was moved in #2796 but we missed updating some of the imports

fix logo imports in [twitter liberapay]

---

lib/load-simple-icons.js
lib/logos.js
lib/logos.spec.js

refs https://github.com/badges/shields/pull/2833#discussion_r249597638
was this what you had in mind?

pre-compute the 3 most common icon styles on server init

---

frontend/components/endpoint-page.js

refs https://github.com/badges/shields/issues/2838#issuecomment-456558266

clarify cache docs for endpoint badge

---

frontend/components/common.js
frontend/components/endpoint-page.js
frontend/components/main.js

Cherry-picked from #2906 (conflicts with that)
Partly addresses #2837 but does not resolve it

Endpoint page: improve formatting

---

services/circleci/circleci.tester.js
services/dynamic/dynamic-json.tester.js
services/nexus/nexus.tester.js
services/npm/npm-downloads.tester.js
services/steam/steam-workshop.tester.js
services/uptimerobot/uptimerobot-ratio.tester.js
services/uptimerobot/uptimerobot-status.tester.js

The one for npm is failing in CI:
https://circleci.com/gh/badges/daily-tests/133

Remove some obsolete .networkOff() tests

---

Makefile

Knock on wood, that deploy went remarkably well. 👔

Update deploy script for Gatsby build

---

config/custom-environment-variables.yml
config/default.yml
core/server/prometheus-metrics.js
core/server/prometheus-metrics.spec.js
core/server/server.js

Remove IP filtering code for prometheus metrics

---

.eslintrc.yml
frontend/components/usage.js
frontend/pages/endpoint.js
gatsby-browser.js

Fix #1954
https://shields-staging-pr-3058.herokuapp.com/#your-badge

Fix your-badge link

---

lib/version.js

I did a quick search and couldn't find any place this was being used.

Remove unused version helper

---

README.md
core/badge-urls/make-badge-url.js
core/badge-urls/make-badge-url.spec.js
core/base-service/cache-headers.js
core/base-service/cache-headers.spec.js
core/base-service/legacy-request-handler.js
core/base-service/legacy-request-handler.spec.js
frontend/components/usage.js
lib/badge-data.js
services/endpoint/endpoint.tester.js

Rename maxAge to cacheSeconds

---

frontend/components/footer.js

Fix discord footer link and remove trailing slash from repo URL

Fix footer links

---

services/bugzilla/bugzilla.service.js

Looks like I overlooked this in #3008 - oops

add schema for [bugzilla] service

---

services/amo/amo-downloads.tester.js

Make [AmoDownloads] test more reliable

---

frontend/components/usage.js

fixes https://github.com/badges/shields/issues/3203

add more helpful syntax links to dynamic badges

---

package-lock.json
package.json

Ref gatsbyjs/gatsby#11304
Fix #3209 Fix #3208

Bump gatsby-plugin-page-creator

---

services/github/github-issue-detail-redirect.service.js
services/github/github-issue-detail-redirect.tester.js
services/github/github-issue-detail.service.js
services/github/github-issue-detail.spec.js
services/github/github-issue-detail.tester.js

Some inline comments/questions added

refactor [GithubIssueDetail]

---

services/npm/npm-dependency-version.service.js
services/npm/npm-dependency-version.tester.js

Fixes #3271 to support scoped dependencies

Fix [NpmDependencyVersion] 

---

.eslintignore
gh-badges/package.json
package-lock.json

Nothing really changing, just a stable API.
By the way, if anyone wants maintainership on that project, let me know. It's always good to have backup.

Bump anafanafo from 0.1.0 to 1.0.0

---

services/dub/dub-download.service.js
services/dub/dub-download.tester.js

Consolidate [DubDownloads] into one service

---

.nycrc.json
package-lock.json
package.json

CI will pass after #3322 is merged.

[security] Bump nyc from 13.3.0 to 14.0.0

---

services/php-eye/php-eye-hhvm.service.js
services/php-eye/php-eye-hhvm.tester.js
services/php-eye/php-eye-php-version.service.js
services/php-eye/php-eye-php-version.tester.js

Deprecate [hhvm php-eye] badges

---

services/coverity/coverity-scan.service.js
services/maintenance/maintenance.service.js

Couple minor cleanup items:
* fix broken Maintenance badge example (I missed this in #3305)
* add inline comment in Coverity service to explain strict ssl disable (#3336)

minor cleanup

---

services/cii-best-practices/cii-best-practices.service.js

This could also use a `whichMap`. I debated changing that but ended up leaving the three render methods intact (after removing the unnecessary render method to which they all delegated).

Refactor [cii] for readability

---

services/cpan/cpan.js
services/npm/npm-type-definitions.service.js
services/npm/npm-version.service.js
services/opencollective/opencollective-all.service.js
services/opencollective/opencollective-backers.service.js
services/opencollective/opencollective-by-tier.service.js
services/opencollective/opencollective-sponsors.service.js
services/osslifecycle/osslifecycle.service.js
services/packagecontrol/packagecontrol.service.js
services/packagist/packagist-downloads.service.js
services/packagist/packagist-license.service.js
services/packagist/packagist-php-version.service.js
services/packagist/packagist-version.service.js
services/shippable/shippable.service.js
services/snyk/snyk-vulnerability-base.js
services/sonar/sonar-coverage.service.js
services/sonar/sonar-documented-api-density.service.js
services/sonar/sonar-fortify-rating.service.js
services/sonar/sonar-generic.service.js
services/sonar/sonar-quality-gate.service.js
services/sonar/sonar-tech-debt.service.js
services/sonar/sonar-violations.service.js
services/sourceforge/sourceforge.service.js
services/sourcegraph/sourcegraph.service.js
services/spiget/spiget-download-size.service.js
services/spiget/spiget-downloads.service.js
services/spiget/spiget-latest-version.service.js
services/spiget/spiget-rating.service.js
services/spiget/spiget-tested-versions.service.js

Unify order of another handful of services [npm opencollective osslifecycle packagecontrol packagist shippable sonar sourceforge sourcegraph spiget]

---

services/github/github-tag.service.js
services/github/github-tag.spec.js
services/github/github-tag.tester.js

Rewrite [GithubTag]

---

services/debian/debian.service.js
services/debian/debian.tester.js

https://wiki.debian.org/Services/api.ftp-master.debian.org

Add [Debian] package version support

---

services/github/github-downloads.service.js

case-insentitive asset name compare in [githubdownloads]

---

Procfile
README.md
doc/TUTORIAL.md
package-lock.json
package.json

While working on #2428 I found myself wanting to reload the server frequently. This is working great and reducing my iteration time significantly. I should have tackled this way sooner! 🙊 
I’ve left `verbose` on which seems useful, at least in the short term while we’re tuning the configuration.
Close #2426

Automatically reload the server when it changes

---

frontend/components/usage.js
frontend/pages/endpoint.js

Take the Endpoint badge out of beta

---

services/github/github-commits-since.service.js
services/github/github-commits-since.tester.js

Implements feature requested in #3204.

Support for branches in [GitHubCommitsSince] badge

---

core/base-service/legacy-request-handler.spec.js
core/server/prometheus-metrics.spec.js
core/server/server.spec.js
core/service-test-runner/pull-request-services-cli.js
entrypoint.spec.js
frontend/components/markup-modal/index.js
frontend/components/markup-modal/markup-modal-content.js
package-lock.json
package.json
services/github/auth/admin.spec.js

Fixes: badges#3432 and badges#3433

Update references to "WordPress"

---

services/microbadger/microbadger-layers.service.js
services/microbadger/microbadger-size.service.js

fix [microbadger] examples

---

services/wordpress/wordpress-rating.service.js

Fix [Wordpress] rating examples

---

services/github/github-release-date.tester.js

fix [GitHubReleaseDate] service tests

---

services/jitpack/jitpack-downloads.service.js
services/jitpack/jitpack-downloads.tester.js

deprecate [JitpackDownloads] badge (temporarily)

---

doc/TUTORIAL.md

This was mostly addressed in #3435 Just suggesting a couple more minor tweaks
closes #3440

improve docs on examples

---

frontend/components/markup-modal/index.js

This PR addresses the dropdown visibility issue described in https://github.com/badges/shields/issues/2806.

Make Dropdown Visible When Overflows

---

services/circleci/circleci.service.js

fix [circle] badge to work with private repositories

---

frontend/components/markup-modal/index.js

fix modal scroll bug

---

services/jitpack/jitpack-version.service.js

add gitee support to [JitpackVersion]

---

services/jitpack/jitpack-downloads.service.js

No idea how this managed to get through the PR validation builds in Circle, but it's causing a runtime crash

fix @hapi/joi import in [jitpackdownloads]

---

services/eclipse-marketplace/eclipse-marketplace-license.tester.js

fix [EclipseMarketplaceLicense] test

---

services/bitbucket/bitbucket-issues.service.js

Fixes #3561 
Atlassian has deprecated the v1 APIs that we were using for the Bitbucket Issues badges
https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/ 
This switches to the v2 API.
https://developer.atlassian.com/bitbucket/api/2/reference/resource/
https://developer.atlassian.com/bitbucket/api/2/reference/meta/filtering#query-issues

fix [Bitbucket] Issues badges

---

services/wordpress/wordpress-platform-redirect.service.js
services/wordpress/wordpress-platform-redirect.tester.js

fix [wordpress] /v redirect

---

services/azure-devops/azure-devops-build.tester.js

fix [AzureDevOpsBuild] test for partially succeeded build

---

services/jsdelivr/jsdelivr-hits-npm.service.js
services/jsdelivr/jsdelivr-hits-npm.tester.js

add scoped package support for [jsDelivrHitsNpm]

---

services/jenkins/jenkins-build.tester.js
services/jenkins/jenkins-tests.tester.js

fix some [Jenkins] service tests

---

services/codefactor/codefactor-grade.service.js
services/codefactor/codefactor-grade.spec.js
services/codefactor/codefactor-grade.tester.js
services/codefactor/codefactor-helpers.js

Closes #3518 
I've never used CodeFactor before but created an account to check it out as they don't really have any public documentation. There's a variety of metrics it shows/tracks in addition to the Grade (cyclomatic complexity, hotspots, duplication, etc.) so I named the classes/files with the idea that we may add other CodeFactor badges down the road

add [CodeFactor] grade badge

---

doc/TUTORIAL.md

Addresses some issues discussed in #3535 plus a few additional fixes and improvements.

Tutorial improvements and fixes

---

package-lock.json
package.json

Refs https://github.com/badges/shields/pull/3552#issuecomment-504615180
Revert version bump of nock to fix service test issues that appear with nock 11.0.0-beta.19

rollback nock to 11.0.0-beta.14

---

doc/production-hosting.md

Document raster server production hosting

---

doc/production-hosting.md

Addressing this ad hoc for now (https://github.com/badges/svg-to-image-proxy/pull/27/files#r300762988).
At some point we should address this question systematically (see #2577).
**Added:** Opened #3647.

Update Zeit members list

---

services/azure-devops/azure-devops-tests.service.js

Cherry-picked from #3410; should simplify reworking it.

Minor refactor in [azuredevopstests]

---

services/bitbucket/bitbucket-pull-request.service.js

This encapsulates the fetch methods slightly better. Cherrypicked from #3410, which needs to be reworked. This change should simplify dropping in the new auth method when that happens.

Refactor [Bitbucket] pull request

---

frontend/components/footer.js

Two small tweaks:
* reworded the text which I always found somewhat confusing. Let me know your thoughts.
* added a link to the Metrics page.

Footer update

---

services/github/github-package-json.service.js

This now relies on the order in which these are registered, though that seems okay. Exporting them as an array guarantees that.
Ref #3329

Convert a format to pattern in [githubpackagejson]

---

services/osslifecycle/osslifecycle.service.js

See https://github.com/badges/shields/pull/3618#issuecomment-507900899.

Documentation for OSS Lifecycle

---

core/server/monitor.js

Update serverSecrets reference in legacy monitor

---

services/github/github-api-provider.integration.js

This is one more like #3694.
Ref #3652 #3393

Refactor auth config checks in another test

---

core/base-service/base.js

Log internal errors to Sentry

---

core/token-pooling/redis-token-persistence.js

Encountered while testing #3332

Fix Redis prod issue for Node 9

---

doc/production-hosting.md

Document the production Redis hosting

---

services/discourse/discourse.service.js
services/jira/jira-issue.service.js
services/jira/jira-sprint.service.js
services/maven-metadata/maven-metadata.service.js
services/nexus/nexus.service.js
services/teamcity/teamcity-build.service.js
services/teamcity/teamcity-coverage.service.js
services/twitter/twitter.service.js
services/website/website.service.js

Add warnings alongside deprecated URL patterns

---

frontend/components/customizer/query-string-builder.js

Fix extraneous brackets in query string builder

---

services/dynamic/dynamic-json.service.js
services/dynamic/dynamic-json.tester.js

[DynamicJson] Catch jsonpath parse error

---

core/base-service/legacy-request-handler.js

Fix timeout logic

---

services/dynamic/dynamic-json.service.js
services/dynamic/dynamic-json.tester.js

Handle [DynamicJson] parse error

---

core/server/server.js

Fix regex match in notfound route

---

README.md
doc/TUTORIAL.md

Follow-on for #3717
🎉
This also removes `?cacheSeconds` parameters from static badges (which do not do anything).

Docs: Drop .svg extensions

---

services/codetally/codetally.tester.js

This test has been timeout fairly regularly during the daily service test runs

increase [codetally] test timeout

---

services/crates/crates-base.js
services/crates/crates-version.service.js
services/crates/crates-version.spec.js
services/crates/crates-version.tester.js

Fixes #3782, also some more detail here https://github.com/badges/shields/issues/3782#issuecomment-516630473

fix runtime type error in [crates] version

---

services/chrome-web-store/chrome-web-store-users.service.js
services/chrome-web-store/chrome-web-store-users.tester.js

Handle missing UserDownloads in [ChromeWebStoreUsers]

---

services/codefactor/codefactor-grade.service.js

fix runtime TypeError in [CodeFactorGrade] service

---

services/azure-devops/azure-devops-build.tester.js
services/azure-devops/azure-devops-helpers.js

tweak build schema for [AzureDevOpsBuild] to handle never built use case

---

services/f-droid/f-droid.service.js
services/f-droid/f-droid.tester.js

Fix trailing 0 in [F-Droid] yaml format

---

package-lock.json
package.json

fix sinon version in lockfile

---

services/aur/aur.tester.js

fix [aur] vote service test

---

services/osslifecycle/osslifecycle.tester.js

fix [OSSLifecycle] service test with new active target

---

gh-badges/README.md
gh-badges/lib/index.js
gh-badges/lib/index.spec.js

Following on from #3507 and #3586 here is another attempt. See https://github.com/badges/shields/pull/3586#issuecomment-513375146 for background.
This time I haven't used any library - I've just coded the validation rules by hand. Note again, the target branch is `v3-dev`.

Validate input to BadgeFactory.create()

---

gh-badges/README.md
gh-badges/lib/badge-cli.js
gh-badges/lib/index.js
gh-badges/lib/make-badge.js
gh-badges/lib/make-badge.spec.js

Another PR targetted at the `v3-dev` branch.
This one is mostly pretty straightforward (hopefully we can get this one landed in less than 2 months :D ). The only complexity is that it will probably give us a bit of a merge conflict at some point with the work in #3637 to remove dot.

remove deprecated properties

---

services/twitter/twitter.service.js
services/twitter/twitter.tester.js

Handle more [Twitter] invalid user inputs

---

core/base-service/base-non-memory-caching.js
core/base-service/base-static.js
core/base-service/base.js
core/base-service/metric-helper.js
core/base-service/redirector.js
core/server/prometheus-metrics.js
core/server/server.js

This completes the refactor suggested at https://github.com/badges/shields/pull/3662#issuecomment-509011229 and adds a response-time metric for #3874.
I haven't tested this yet though we should follow "how to test it" in the top comment of https://github.com/badges/shields/pull/3662#issue-295109085.
Supersedes #3947.

Add a response-time metric

---

services/scrutinizer/scrutinizer-base.js
services/scrutinizer/scrutinizer-quality.tester.js

Fix [Scrutinizer] error when using default branch without analysis data

---

services/dynamic/dynamic-json.service.js
services/dynamic/dynamic-json.tester.js

Fix AssertionError in [DynamicJson] when a non-object is in the JSON

---

services/debian/debian.service.js
services/debian/debian.tester.js

Fix TypeError for invalid [Debian] response

---

services/liberapay/liberapay-goal.service.js
services/liberapay/liberapay-goal.spec.js
services/liberapay/liberapay-goal.tester.js

fix [LiberapayGoal] type error when no receiving data exists

---

services/github/github-downloads.service.js
services/github/github-downloads.tester.js

fix [GitHubDownloads] type error on latest with pre-downloads

---

cypress/integration/main-page.spec.js
services/discourse/discourse-redirect.service.js
services/discourse/discourse-redirect.tester.js
services/discourse/discourse.service.js
services/discourse/discourse.tester.js

move [Discourse] url to query param

---

services/twitter/twitter.service.js

encode usernames for links in [Twitter] 

---

services/microbadger/microbadger-size.service.js

Adding some documentation to help users, as per #3988.

Add [MicrobadgerSize] documentation

---

services/endpoint/endpoint.tester.js

add [Endpoint] test for invalid url

---

services/drone/drone-build.service.js
services/drone/drone-build.tester.js

add `killed` to [Drone] schema

---

.eslintrc.yml
services/github/github-common-fetch.js
services/security-headers/security-headers.service.js

Make sure this gets linted in the future.
Fix #4111

Fix an undefined variable in [GithubPackageJson]

---

README.md

Let's include the new Hacktoberfest badge created in #4109 to our readme!

add new hacktoberfest badge to our readme

---

services/github/github-forks.service.js

Closes #4149 Explanation in https://github.com/badges/shields/issues/4149#issuecomment-539617144 for why this is needed.

change [githubforks] query

---

package-lock.json
package.json

Bump(deps-dev): bump to simple-icons 1.18 (#4175)

---

services/suggest.integration.js
services/suggest.js

Added a suggestion for a pipeline badge when a GitLab URL is entered. Fixes #2679.

Add GitLab pipline suggestion

---

doc/TUTORIAL.md

Going through `doc/Tutorial.md` I've prepared a few fixes.

Tutorial fixes

---

services/github/github-package-json.service.js
services/github/github-package-json.tester.js

Refs https://github.com/badges/shields/issues/2259#issuecomment-545485159

Add filename override to [GithubPackageJson]

---

services/gitlab/gitlab-pipeline-status.service.js

fix [gitlab] pipeline status service test

---

services/github/github-release.service.js
services/github/github-release.tester.js

With a couple minor stylistic changes for readability.
Closes #4303

Fix [GithubRelease] not found case with include_prereleases

---

services/mozilla-observatory/mozilla-observatory.tester.js

These tests have been pretty flaky, but I think this will finally stabilize them
Some recent failures:
https://circleci.com/gh/badges/daily-tests/722
https://circleci.com/gh/badges/daily-tests/720

fix flaky [mozillaobservatory] service tests

---

services/leanpub/leanpub-book-summary.service.js
services/leanpub/leanpub-book-summary.tester.js

deprecate [leanpub] badges

---

package-lock.json
package.json

It stopped being used in https://github.com/badges/shields/pull/3764

Remove lodash.throttle from dependencies

---

services/puppetforge/puppetforge-module-pdk-version.tester.js

fix [PuppetforgeModulePdkVersion] service test

---

services/maven-metadata/maven-metadata.service.js
services/maven-metadata/maven-metadata.tester.js

fix [MavenMetadata] service tests

---

.dependabot/config.yml

Add mkdirp to Dependabot exclusion list

---

services/nexus/nexus.service.js
services/nexus/nexus.tester.js

[Nexus] 3: set prerelease=false for /r/* badges

---

services/npm/npm-dependency-version.tester.js

fix npm dependency service test

---

.dependabot/config.yml

don't upgrade to sinon 9

---

frontend/components/customizer/path-builder.tsx
frontend/components/customizer/query-string-builder.tsx

Trim user input when building path and query string

---

package-lock.json
package.json

As an interim measure, lets downgrade while we figure out #4842

downgrade to mocha 6.2.3, run [appveyor travis]

---

.dependabot/config.yml

refs https://github.com/badges/shields/pull/4853

don't upgrade to chalk 4

---

.dependabot/config.yml

lower gatsby ignore version to 2.19.50

---

services/node/node-base.js
services/node/node-current.service.js
services/node/node-lts.service.js

node badges are missing descriptions #4871

---

services/jitpack/jitpack-downloads.service.js
services/jitpack/jitpack-downloads.tester.js

deprecate [JitPack] downloads badge

---

doc/self-hosting.md

Node.js 8.x LTS Carbon is no longer actively supported!

updating node js version

---

services/symfony/symfony-insight-base.js
services/symfony/symfony-insight-base.spec.js

Fix TypeError in [SymfonyInsight] transform

---

services/docker/docker-version.service.js
services/docker/docker-version.spec.js

Refs #4904. It should actually fix that issue but going to defer closing it for now to confirm there's no more issues reported in Sentry

fix TypeError in [DockerVersion] badge

---

badge-maker/lib/badge-renderers.js

fix logo placement with custom logoWidth value

---

services/aur/aur.service.js
services/aur/aur.tester.js

Hello there! I'm adding two additional badges to the `AUR` service, [_related issue_]( https://github.com/badges/shields/issues/4656):
- ![image](https://user-images.githubusercontent.com/26286907/80294697-d30c2a00-8773-11ea-92a9-61dec3649a59.png)
-  ![image](https://user-images.githubusercontent.com/26286907/80294683-a3f5b880-8773-11ea-82f4-121305c28a13.png)
Thanks for the awesome service!

Add [AUR] maintainer and last modified badges

---

frontend/components/usage.tsx

document request header size limit

---

services/cocoapods/cocoapods-base.js
services/cocoapods/cocoapods-license.service.js
services/cocoapods/cocoapods-license.tester.js

Fix missing [Cocoapods] license

---

services/dynamic/dynamic-json.tester.js
services/dynamic/json-path.js

[dynamicjson] Fix unexpected token in JSONPath query

---

services/nuget/nuget-v2-service-family.js

Allow a numeric version for NuGet v2 [chocolatey powershellgallery resharper]

---

services/endpoint/endpoint.tester.js

fix endpoint mocked cache tests

---

Dockerfile

We need to do this anyway.
It might also fix  #5054

bump to node 10 for self-hosting users

---

badge-maker/CHANGELOG.md
badge-maker/package.json

add missing dependency

---

services/github/github-all-contributors.service.js
services/github/github-all-contributors.tester.js

Implements #5161
Adds the 'all contributors' badge, using the contributor count color scale.

Implement All Contributors Badge, run [GitHubAllContributors]

---

services/github/github-manifest.service.js
services/github/github-manifest.tester.js

support custom manifest path for [GitHubManifest] and fix service tests

---

services/website/website.tester.js

increase [website] test timeout

---

badge-maker/CHANGELOG.md
badge-maker/package.json

package 3.2.0

---

README.md

Nothing impressive going on here, a few numbers we had left behind.

Update Node.js versions in README

---

.github/ISSUE_TEMPLATE/config.yml

Add a emoji (❓) for "Support Question" in new issue.

Add emoji for "Support Question" in config.yml

---

services/gitlab/gitlab-pipeline-status.service.js
services/gitlab/gitlab-pipeline-status.tester.js

Resolves #5282 via option 1 described in that thread
Mutually exclusive alternative to #5537

Fix [GitlabPipeline] not found repo service test

---

services/jira/jira-issue.service.js
services/jira/jira-sprint.service.js
services/jitpack/jitpack-version.service.js
services/jsdelivr/jsdelivr-hits-github.service.js
services/jsdelivr/jsdelivr-hits-npm.service.js
services/keybase/keybase-btc.service.js
services/keybase/keybase-pgp.service.js
services/keybase/keybase-xlm.service.js
services/keybase/keybase-zec.service.js

@calebcartwright please review this.

Refactor [jira jitpack jsdelivr keybase] service files

---

package-lock.json
package.json

@types/styled-components causes a conflict with @types/react-native. See DefinitelyTyped/DefinitelyTyped#33311.
Close #5294

Work around DT conflict; bump TS and @types/styled-components

---

services/github/github-common-fetch.js

Looks like I overlooked this one in #5234. I think this is the only issue in this category
closes #5584

use HEAD ref in [github] fetchJsonFromRepo

---

services/nuget/nuget-v2-service-family.js
services/nuget/nuget-v3-service-family.js
services/nuget/nuget.service.js
services/nycrc/nycrc.service.js
services/opencollective/opencollective-all.service.js
services/opencollective/opencollective-backers.service.js
services/opencollective/opencollective-by-tier.service.js
services/opencollective/opencollective-sponsors.service.js
services/opm/opm-version.service.js

@calebcartwright  please review these changes.

Refactor [nuget nycrc opencollective opm] services

---

core/server/monitor.js

This never worked in prod (see #1460)

Remove obsolete WebSocket logs monitor

---

services/osslifecycle/osslifecycle.service.js
services/packagecontrol/packagecontrol.service.js
services/packagist/packagist-downloads.service.js
services/packagist/packagist-license.service.js
services/packagist/packagist-php-version.service.js
services/packagist/packagist-stars.service.js
services/packagist/packagist-version.service.js
services/pkgreview/package-rating.service.js
services/poeditor/poeditor.service.js

Hi @calebcartwright please review these changes Thanks !

Refactor [osslifecycle packagecontrol packagist pkgreview poeditor] service files

---

services/powershellgallery/powershellgallery.service.js
services/pub/pub.service.js
services/puppetforge/puppetforge-module-downloads.service.js
services/puppetforge/puppetforge-module-endorsement.service.js
services/puppetforge/puppetforge-module-feedback.service.js
services/puppetforge/puppetforge-module-pdk-version.service.js
services/puppetforge/puppetforge-module-version.service.js
services/puppetforge/puppetforge-user-module-count.service.js
services/puppetforge/puppetforge-user-release-count.service.js
services/pypi/pypi-django-versions.service.js
services/pypi/pypi-downloads.service.js
services/pypi/pypi-format.service.js
services/pypi/pypi-implementation.service.js
services/pypi/pypi-license.service.js
services/pypi/pypi-python-versions.service.js
services/pypi/pypi-status.service.js
services/pypi/pypi-version.service.js
services/pypi/pypi-wheel.service.js

@calebcartwright  please review this Thanks !

Refactor [powershellgallery pub puppetforge pypi] services

---

services/visual-studio-app-center/visual-studio-app-center-builds.service.js
services/visual-studio-app-center/visual-studio-app-center-releases-osversion.service.js
services/visual-studio-app-center/visual-studio-app-center-releases-size.service.js
services/visual-studio-app-center/visual-studio-app-center-releases-version.service.js
services/visual-studio-marketplace/visual-studio-marketplace-azure-devops-installs.service.js
services/visual-studio-marketplace/visual-studio-marketplace-downloads.service.js
services/visual-studio-marketplace/visual-studio-marketplace-last-updated.service.js
services/visual-studio-marketplace/visual-studio-marketplace-rating.service.js
services/visual-studio-marketplace/visual-studio-marketplace-release-date.service.js
services/visual-studio-marketplace/visual-studio-marketplace-version.service.js
services/w3c/w3c-validation.service.js

@calebcartwright Completed conversion for the following Services
Which I was assigned in #5555

Converted Service Classes to Static Fields, run [visualstudio w3c]

---

badge-maker/CHANGELOG.md
badge-maker/package.json

Related:
* #5467
* #5508
* #5533
* #5534
* #5616
* #5615

Update badge-maker to version 3.3.0

---

dangerfile.js

Update Danger rule for joi

---

services/aur/aur.spec.js
services/aur/aur.tester.js

Resolves #5698
Mutually exclusive alternative to #5699

switch to unit test for [aur] package out of date test

---

services/packagist/packagist-version.tester.js

fix [Packagist] Version service test

---

services/issuestats/issuestats.service.js

We've got a bunch of other deprecated services that look like this.
Ref #3329

Change [issuestats] redirector from format to pattern

---

.circleci/config.yml
__snapshots__/make-badge.spec.js
scripts/run_package_tests.sh

Fail in CI when package tests fail

---

services/github/github-search.service.js
services/github/github-size.service.js
services/github/github-stars.service.js
services/github/github-tag.service.js
services/github/github-top-language.service.js
services/github/github-watchers.service.js
services/github/github-workflow-status.service.js

> That means that most/all of the service classes inclusively from GitHubSearch (https://github.com/badges/shields/blob/master/services/github/github-search.service.js) through GitHubWorkFlowStatus probably still need to be refactored if you (or anyone else) wants to work on those
The following services have been refactored:
- GithubSearch
- GithubSize
- GithubStars 
- GithubTag 
- GithubTopLanguage
- GithubWatchers
- GithubWorkflowStatus
#5555

Refactor remaining [github] services

---

README.md

Standard cleanup to remove the hacktoberfest badge from our readme file now that hacktoberfest has ended

cleanup hacktoberfest readme material

---

services/open-vsx/open-vsx-base.js
services/open-vsx/open-vsx-downloads.service.js
services/open-vsx/open-vsx-downloads.tester.js
services/open-vsx/open-vsx-rating.service.js
services/open-vsx/open-vsx-rating.spec.js
services/open-vsx/open-vsx-rating.tester.js
services/open-vsx/open-vsx-release-date.service.js
services/open-vsx/open-vsx-release-date.tester.js
services/open-vsx/open-vsx-version.service.js
services/open-vsx/open-vsx-version.tester.js

Add [OpenVSX] registry badges

---

services/pkgreview/package-rating.service.js

Refs https://github.com/badges/shields/issues/4641#issuecomment-727176687

Add inline contact info for pkgreview badge

---

config/custom-environment-variables.yml

closes #5839
This creates a slight inconsistency, but its the least disruptive option. See conversation in #5839

map REDIRECT_URI env var to redirectUrl setting

---

frontend/components/customizer/customizer.tsx
frontend/components/development/logo-page.tsx
frontend/components/development/style-page.tsx
frontend/components/main.tsx
frontend/constants.ts
frontend/pages/community.tsx
frontend/pages/endpoint.tsx

refs #5014
Turns out this wasn't a big deal. Hopefully this is the last piece of the jigsaw :crossed_fingers:

special case generating baseUrl for production

---

services/github/github-sponsors.service.js

remove [GitHubSponsors] style override

---

doc/production-hosting.md
frontend/pages/community.tsx

should have done these in #5977 we're no longer using netlify

remove refs to netlify from docs

---

services/wordpress/wordpress-platform.service.js
services/wordpress/wordpress-platform.tester.js

fix [wordpress] 'Can't generate version color for false'

---

.github/actions/draft-release/entrypoint.sh

As noted in https://github.com/badges/shields/pull/6132#issuecomment-771076613 after the first run of this I picked out a couple of tweaks I wanted to make to the script
Closes #5866

Improve changelog entries

---

services/pkgreview/package-rating.service.js

update [pkgreview] url

---

services/liberapay/liberapay-base.js
services/liberapay/liberapay-gives.tester.js
services/liberapay/liberapay-goal.tester.js

allow missing 'goal' key in [liberapay] badges

---

services/symfony/sensiolabs-redirect.tester.js
services/symfony/symfony-insight-grade.service.js
services/symfony/symfony-insight-stars.service.js
services/symfony/symfony-insight-violations.service.js
services/symfony/symfony-insight-violations.tester.js
services/symfony/symfony-test-helpers.js

Fix [Symfony] tests

---

frontend/components/usage.tsx

This changes the example so that you don't get a 404.

Fix raster example

---

services/netlify/netlify.service.js

Added new colour schema to fix netlify service badge.
Fixes #6334

[Netlify] added changes to use new color schema

---

spec/SPECIFICATION.md

I added more accessible alt text to the sample badges in the `SPECIFICATION` file, so it is more accessible to users who cannot see the images.

Specification: Add better alt-text

---

services/github/github-sponsors.service.js

correct [GitHubSponsors] example

---

services/myget/myget.service.js
services/myget/myget.tester.js

fix [MyGet] tenant-based service tests and examples

---

services/bower/bower-base.js
services/bower/bower-version.service.js

fix [Bower] version tests

---

package-lock.json

`npm audit fix` was able to auto-fix some vulns in transitive packages

upgrade some vulnerable packages

---

services/discord/discord.service.js

convert [discord] to use static properties

---

badge-maker/CHANGELOG.md
badge-maker/package.json
package-lock.json

Having had this running in production for a bit, we've had no reported issues. Once we merge this I'll create a tag and push the package to NPM.

badge-maker 3.3.1 release

---

package-lock.json
package.json

Build(deps): bump webextension-store-meta from 1.0.3 to 1.0.4, run [ChromeWebStore]

---

frontend/components/usage.tsx

fix usage style

---

doc/production-hosting.md
frontend/components/footer.tsx

Fixes #6598.
Note that I've already pulled out the custom domain setup from the Cloudfare configuration.

Fix UptimeRobot status endpoint

---

services/build-status.js
services/build-status.spec.js

fix [ScrutinizerBuild] service test

---

services/aur/aur.service.js
services/aur/aur.tester.js
services/licenses.js
services/licenses.spec.js

use v5 API for [AUR] badges

---

services/gitlab/gitlab-pipeline-status.tester.js

this repo doesn't have a master branch anymore

update failing [gitlab] test

---

package-lock.json
package.json

switch from husky to simple-git-hooks

---

services/requires/requires.service.js
services/requires/requires.tester.js

update [requires] test/example

---

__snapshots__/make-badge.spec.js
badge-maker/lib/badge-renderers.js
badge-maker/lib/make-badge.spec.js

Closes #6936
One line fix for the bug, but this highlighted a gap in our test coverage which I have addressed.

fix incorrect colorsForBackground detection

---

services/myget/myget.service.js
services/myget/myget.tester.js

Fix [MyGet] version example and test

---

CHANGELOG.md
doc/production-hosting.md

Update Shields production access doc

---

core/legacy/regular-update.js
services/jenkins/jenkins-plugin-version.service.js
services/myget/myget.tester.js
services/node/node-version-color.js
services/nuget/nuget-helpers.js
services/php-version.js
services/wordpress/wordpress-version-color.js

Closes #7214
Refs #4655
This PR migrates `regularUpdate()` from request and callbacks to got and async/await and all the knock-on effects of that.

Continue request --> got migration; affects [travis wordpress myget jenkins-plugin node nuget]

---

services/npm/npm-version.service.js
services/npm/npm-version.tester.js

fix [npmversion] tagged service test

---

package-lock.json
package.json

revert to eslint 7

---

.github/actions/close-bot/helpers.js

Resolves #7344 
Found myself wondering if we should have unit tests for some of these helper functions. They're easy to enough to eyeball, but might be helpful to be able to have tests where we toss snippets from the PR bodies?

update filtering logic for useless dep bumps

---

services/reddit/user-karma.service.js
services/reddit/user-karma.tester.js

There are a couple of things from https://github.com/badges/shields/pull/7411 that we should apply here too

minor [reddit] improvements

---

services/nexus/nexus.tester.js

Fix [Nexus] tests

---

services/codefactor/codefactor-grade.service.js
services/codefactor/codefactor-grade.tester.js

I found these examples advertised on the CodeFactor homepage, hopefully they'll be less likely to break.

Fix [CodeFactor] tests and example

---

services/codacy/codacy-coverage.service.js
services/codacy/codacy-coverage.tester.js

No more coverage available for the previous project: https://app.codacy.com/gh/Seagate/cortx-s3server/dashboard

Fix [CodacyCoverage] tests and examples

---

services/hackernews/hackernews-user-karma.service.js
services/hackernews/hackernews-user-karma.tester.js

Change defaultLabel [HackerNews]

---

services/drone/drone-build.service.js
services/drone/drone-build.tester.js

Fix [Drone] tests and examples

---

.github/workflows/build-docker-image.yml
.github/workflows/publish-docker-next.yml

Closes #7573
`${GITHUB_SHA::7}` is a bash subscript syntax, so we need to run it with bash and write it to a var

fix docker image user agent

---

services/piwheels/piwheels-version.service.js
services/piwheels/piwheels-version.spec.js
services/piwheels/piwheels-version.tester.js

Closes #6506
I don't often do PRs adding a new badge these days, but I'd like this one to exist :)
The transform method is fairly comprehensively unit tested, so I've kept the live tests fairly light-touch.

Add [piwheels] version badge

---

services/piwheels/piwheels-version.service.js
services/piwheels/piwheels-version.spec.js

Refs conversation in https://github.com/piwheels/piwheels/issues/216#issuecomment-1061178476
Only include versions which have >=1 compiled wheels.

[piwheels], filter out versions with no files

---

core/server/server.js

y'know - just in case anyone wants to do that

allow `requireCloudflare` setting to work when hosted on fly.io

---

services/packagist/packagist-base.js
services/packagist/packagist-version.service.js

two fixes for [packagist] schemas

---

CHANGELOG.md

add note to server-2022-04-03 changelog about ioredis connection string breaking change

add note to changelog about ioredis connection string change

---

services/bitrise/bitrise.service.js
services/bitrise/bitrise.tester.js

fix [bitrise] example & service test

---

services/sonar/sonar-documented-api-density.tester.js
services/sonar/sonar-tech-debt.tester.js
services/sonar/sonar-violations.tester.js

fix various [sonar] service tests

---

services/github/github-language-count.service.js

This is also related to the changes in #7877.

Stringify [githublanguagecount] message

---

config/shields-io-production.yml

- Refs https://github.com/badges/shields-ops/issues/16
- Refs https://github.com/badges/shields-ops/pull/22

move all public production config into yaml

---

services/scoop/scoop-version.service.js

Scoop moved to ScoopInstaller/Scoop, this PR changes the Scoop Service accordingly.

Change lukesampson/scoop to ScoopInstaller/Scoop, run[scoop]

---

services/gitlab/gitlab-contributors.service.js
services/gitlab/gitlab-contributors.tester.js

re #8077 
/assign @calebcartwright

feat: add [gitlab] contributors service

---

services/ore/ore-version.tester.js

accept version with suffix in [ore] service tests

---

services/aur/aur.service.js

increase cache length on AUR version badge, run [AUR]

---

core/service-test-runner/infer-pull-request.js

ci: support new circle PR url variable

---

services/gitlab/gitlab-base.js
services/gitlab/gitlab-contributors.service.js
services/gitlab/gitlab-contributors.tester.js
services/gitlab/gitlab-release.spec.js

closes #8143
I feel like one way and another we collectively dropped the ball a bit on code review with these gitlab badges

moar fixes for [gitlab] auth

---

services/conda/conda-version.service.js
services/conda/conda-version.tester.js

As discussed in https://github.com/badges/shields/pull/8169#discussion_r917443156 - this is a bit clearer

add spaces round pipe in [conda] version badge

---

doc/service-tests.md

Fix of a typo in documentation

Fix typo in service-tests.md

---

doc/code-walkthrough.md

Fix wording and number of parameters in code-walkthrough.md

Fix wording in code-walkthrough.md

---

services/pypi/pypi-base.js
services/pypi/pypi-helpers.js
services/pypi/pypi-helpers.spec.js
services/pypi/pypi-license.tester.js
services/pypi/pypi-version.tester.js

[pypi] Service calls according to new Warehouse API

---

services/bountysource/bountysource.service.js

Hey, this PR closes #8313. I verified locally that the fix works, should I include this in the tests as well somehow? Not sure how.

[BountySource] Fix: Broken Badge generation for decimal activity values

---

cypress/e2e/main-page.cy.js
package-lock.json
package.json
tsconfig.json

boom :boom:
- conflicts resolved
- no new security vulns
- tests passing
I've labelled this blocker because I'd quite like to merge this before dependabot pops up on Friday and we get a bunch of merge conflicts on `package-lock.json`, although if I do need to do it again, I can.

upgrade gatsby

---

services/build-status.js
services/dynamic-common.js
services/endpoint-common.js

Smol PR to update the type for Joi schemas for all the previous docstring PRs.

Update type for Joi schemas in docstrings

---

services/github/github-hacktoberfest.service.js

Added support for github hacktoberfest badge for this year!

[GitHubHacktoberfest] Support for the year of 2022

---

CONTRIBUTING.md
services/freecodecamp/freecodecamp-points.service.js

Very petty PR, I originally had these commits on my last PR that was rejected.
Since that won't get merged, figured I'd just PR these changes separately. A bit minor though. ^-^'

docs: update wording and url for freecodecamp usernames

---

services/jenkins/jenkins-plugin-installs.tester.js

The version we are using before has disappeared from the API response so I've updated the example. If this continues to be unstable, we could consider mocking this one.

update [JenkinsPluginInstalls] test example

---

services/powershellgallery/powershellgallery.service.js
services/powershellgallery/powershellgallery.tester.js

This package seems to have gone away. Here's another one that declares a platform.

update [powershellgallery] platform example

---

services/github/github-last-commit.service.js

refs https://github.com/badges/shields/pull/8508#discussion_r1003320861

require array to have at least 1 item in [githublastcommit]

---

services/pypi/pypi-helpers.js

quick bit of follow up from https://github.com/badges/shields/pull/8690#discussion_r1048782469

add a clarifying comment to [pypi] getLicenses

---

.github/actions/close-bot/action.yml

run close-bot on node 16

---

services/vpm/vpm-version.service.js
services/vpm/vpm-version.tester.js

add [VpmVersion] badge

---

services/pipenv-helpers.js

- Added docstrings for `pipenv-helpers` service

Add docstrings for pipenv helpers

---

.github/workflows/build-docker-image.yml
.github/workflows/create-release.yml
.github/workflows/publish-docker-next.yml

Refs
- https://community.fly.io/t/deployments-failing-using-docker-hub-image/10376/2
- https://community.fly.io/t/deploying-to-fly-via-github-action-failing/10171/19

build docker images with buildkit v0.9.1

---

frontend/components/search.tsx

closes #8926
Tested this on my phone. Can confirm
a) it happens and
b) its annoying

don't autofocus search

---

server.js

fix TypeError: console.warning is not a function

---

services/netlify/netlify.service.js

Closes #8970
Example of passing badge ![](https://api.netlify.com/api/v1/badges/d8d15c8e-40aa-4648-8a48-e7f3b53647c5/deploy-status)  
Example of failing badge ![](https://api.netlify.com/api/v1/badges/9a73ea20-6de8-43f9-b43d-aaa893c2fb67/deploy-status)

[Netlify] upgrade colors for SVG parsing

---

.github/workflows/create-release.yml
.github/workflows/publish-docker-next.yml

https://github.com/badges/shields/pull/9008 did not work first time :smile:

push images to both GHCR and DockerHub (2)

---

scripts/mocha2md.js

closes https://github.com/badges/shields/issues/8987
Not 100% sure why I wrote this to exit if there are pending tests, but this fixes it. Included services are just so we can view an example output, not because those services are affected by this change.

fix markdown summary if there are pending tests; run [amo youtube]

---

services/sourceforge/sourceforge-downloads.service.js

Refs https://github.com/badges/shields/pull/9078#issuecomment-1515465044
Refs https://github.com/badges/shields/pull/9101

fix [sourceforge] downloads

---

doc/TUTORIAL.md
frontend/components/footer.tsx

https://github.com/badges/shields/issues/9152#issuecomment-1537534258

Correct issue template in footer (new badge requests url is incorrect)

---

services/github/github-sponsors.service.js

Closes https://github.com/badges/shields/issues/9120

count private sponsors on [GithubSponsors] badge

---

services/github/github-commit-activity.tester.js

fix typo in test name

---

services/php-version.js

php-version.js: Fix typos

---

services/youtube/youtube-base.js

Refs #8605
(everyone's favourite issue)

embiggen youtube cache, again

---

frontend/src/css/custom.css
frontend/src/pages/community.md

Closes https://github.com/badges/shields/issues/9296
Also fixes some invalid HTML - self-closing `<object>` tag is not valid

adapt opencollective images to theme background

---

.github/scripts/deploy-review-app.sh

Resolves #9316
This changed the `git merge` command to `git checkout`. Sometimes we may not need to merge master.
We can merge the master by clicking the <kbd>Update branch</kbd> button on the pull request page:

Adjust `deploy-review-app` script

---

services/date/date.service.js
services/date/date.tester.js

closes https://github.com/badges/shields/issues/9303

allow negative timestamps in relative [date] badge

---

services/github/github-issues-search.service.js

improve docs for github issues search badge

---

services/lemmy/lemmy.service.js
services/lemmy/lemmy.tester.js

Closes #9367 
I'm a bit stuck when it comes to writing tests for this currently.

Add support for [Lemmy]

---

.github/actions/draft-release/Dockerfile

fix 'draft release' action

---

.github/actions/draft-release/entrypoint.sh

got a bit trigger happy on the last one :grimacing:

fix 'draft release' action part 2

---

README.md

Replace localhost with domain in example link.

Replace localhost with domain in example link.

---

README.md

Small follow up to #9542, to make the security policy more discoverable.

Point to security policy in README

---

services/testspace/testspace-base.js

Closes https://github.com/badges/shields/issues/9515

Fix [testspace] badges

---

services/aur/aur.tester.js

Just an example that needs updating here

fix [aur] service tests

---

services/github/github-hacktoberfest.service.js

This PR adds hacktoberfest 2023 support (#9636)

[GitHubHacktoberfest] 2023 support

---

README.md
frontend/docusaurus.config.cjs

Refs #9677
Tbh, we could just drop linking to this.
@PyvesB - are you still checking https://twitter.com/shields_io ? I think you're the only person who has access to it.

twitter isn't twitter any more

---

doc/server-secrets.md

fix typo in docs

---

services/clojars/clojars-base.js
services/clojars/clojars-downloads.service.js
services/clojars/clojars-version.service.js
services/f-droid/f-droid.service.js
services/packagist/packagist-base.js
services/packagist/packagist-dependency-version.service.js
services/packagist/packagist-downloads.service.js
services/packagist/packagist-license.service.js
services/packagist/packagist-stars.service.js
services/packagist/packagist-version.service.js
services/piwheels/piwheels-version.service.js
services/vpm/vpm-version.service.js

Refs https://github.com/badges/shields/issues/9285 Really starting to get into the services with query params now.
Also in this PR I have carried forward the assumptions from https://github.com/badges/shields/pull/9715 and documented these services in a similar style.

migrate examples to openApi part 21; affects [clojars f-droid packagist piwheels vpm]

---

services/steam/steam-workshop.service.js

Refs #9285
I'm starting to feel like a broken record at this point.

migrate examples to openApi part 22; affects [steam]

---

services/bstats/bstats-players.service.js
services/bstats/bstats-servers.service.js
services/bugzilla/bugzilla.service.js
services/eclipse-marketplace/eclipse-marketplace-base.js
services/eclipse-marketplace/eclipse-marketplace-downloads.service.js
services/eclipse-marketplace/eclipse-marketplace-favorites.service.js
services/eclipse-marketplace/eclipse-marketplace-license.service.js
services/eclipse-marketplace/eclipse-marketplace-update.service.js
services/eclipse-marketplace/eclipse-marketplace-version.service.js

Refs https://github.com/badges/shields/issues/9285.
@chris48s was having all the fun on his own, I simply wanted to have a small slice of the cake as well.

migrate examples to openApi part 27; affects [bstats bugzilla eclipse]

---

core/base-service/openapi.js
core/base-service/openapi.spec.js

Tbh, I don't really know why we didn't already do this 🤔

convert 'style' param to enum

---

services/dub/dub-download.service.js
services/eclipse-marketplace/eclipse-marketplace-downloads.service.js
services/hexpm/hexpm.service.js
services/homebrew/homebrew-downloads.service.js
services/packagist/packagist-downloads.service.js
services/wordpress/wordpress-downloads.service.js

Add a description to every interval enum param

add description to interval enums

---

services/youtube/youtube-base.js
services/youtube/youtube-likes.service.js

Nothing much going on here, some minor leftovers from #7410, noticed this whilst I was looking into migrating the service to OpenAPI.

Small [YouTube] cleanup

---

services/aur/aur.service.js
services/cran/cran.service.js
services/jsdelivr/jsdelivr-hits-github.service.js
services/jsdelivr/jsdelivr-hits-npm.service.js
services/mastodon/mastodon-follow.service.js
services/matrix/matrix.service.js
services/npm-stat/npm-stat-downloads.service.js
services/nycrc/nycrc.service.js
services/thunderstore/thunderstore-base.js
services/thunderstore/thunderstore-downloads.service.js
services/thunderstore/thunderstore-likes.service.js
services/thunderstore/thunderstore-version.service.js
services/twitter/twitter.service.js

Refs #9285
I think all of these are pretty straightforward.

migrate some services from examples to openApi part 28; affects [aur cran mastodon matrix npmstat nyc thunderstore twitter]

---

services/azure-devops/azure-devops-build.service.js
services/azure-devops/azure-devops-helpers.js
services/azure-devops/azure-devops-tests.service.js
services/youtube/youtube-base.js
services/youtube/youtube-channel-views.service.js
services/youtube/youtube-comments.service.js
services/youtube/youtube-likes.service.js
services/youtube/youtube-subscribers.service.js
services/youtube/youtube-views.service.js

Refs https://github.com/badges/shields/issues/9285.

migrate examples to openApi part 32; affects [azuredevops youtube]

---

services/testspace/testspace-test-count.service.js
services/testspace/testspace-test-summary.service.js
services/twitch/twitch.service.js
services/w3c/w3c-validation-helper.js
services/w3c/w3c-validation.service.js
services/weblate/weblate-base.js
services/weblate/weblate-component-license.service.js
services/weblate/weblate-entities.service.js
services/weblate/weblate-project-translated-percentage.service.js
services/weblate/weblate-user-statistic.service.js
services/whatpulse/whatpulse.service.js

Refs #9285
How do you eat an elephant? One bite at a time.

migrate some services from examples to openApi part 29; affects [testspace twitch w3c weblate whatpulse]

---

services/poeditor/poeditor.service.js
services/pypi/pypi-downloads.service.js
services/pypi/pypi-framework-versions.service.js
services/symfony/symfony-insight-base.js
services/symfony/symfony-insight-grade.service.js
services/symfony/symfony-insight-stars.service.js
services/symfony/symfony-insight-violations.service.js
services/teamcity/teamcity-build.service.js
services/teamcity/teamcity-coverage.service.js

migrate some services from examples to openApi part 30; affects [poeditor pypi symfony teamcity]

---

core/base-service/openapi.js
core/base-service/openapi.spec.js

closes #9867
follow up from #9859

fix default style docs for social badges

---

services/myget/myget.service.js
services/nuget/nuget-v2-service-family.js
services/nuget/nuget-v3-service-family.js
services/nuget/nuget.service.js
services/resharper/resharper.tester.js

migrate examples to openApi part 36; affects [myget nuget resharper chocolatey powershellgallery]

---

services/github/github-downloads.service.js
services/github/github-followers.service.js
services/github/github-forks.service.js
services/github/github-r-package.service.js
services/github/github-size.service.js
services/github/github-watchers.service.js

migrate examples to openApi part 38; affects [github]

---

services/codecov/codecov.service.js
services/obs/obs.service.js
services/scrutinizer/scrutinizer-build.service.js
services/scrutinizer/scrutinizer-coverage.service.js
services/scrutinizer/scrutinizer-quality.service.js
services/sourceforge/sourceforge-downloads.service.js

I'm really starting to feel like the end is in sight.

migrate some services from examples to openApi part 40; affects [codecov obs scrutinizer sourceforge]

---

services/github/github-commits-difference.service.js
services/github/github-directory-file-count.service.js
services/github/github-discussions-custom-search.service.js
services/github/github-issues-search.service.js
services/github/github-stars.service.js

migrate some services from examples to openApi part 41; affects [github]

---

services/github/github-hacktoberfest.service.js
services/github/github-last-commit.service.js
services/github/github-manifest.service.js
services/github/github-package-json.service.js
services/github/github-total-star.service.js

migrate some services from examples to openApi part 42; affects [github]

---

services/jenkins/jenkins-build.service.js
services/jenkins/jenkins-build.tester.js
services/jenkins/jenkins-coverage.service.js
services/jenkins/jenkins-coverage.tester.js
services/jenkins/jenkins-tests.service.js

migrate some services from examples to openApi part 43; affects [jenkins]

---

services/visual-studio-app-center/visual-studio-app-center-releases-version.service.js
services/visual-studio-app-center/visual-studio-app-center-releases-version.tester.js

Closes https://github.com/badges/shields/issues/9950

tolerate missing short_version in [visualstudioappcenter]

---

core/base-service/openapi.js
cypress/e2e/main-page.cy.js
services/coveralls/coveralls.service.js
services/github/github-issues.service.js
services/github/github-pipenv.service.js
services/github/github-release-date.service.js
services/visual-studio-marketplace/visual-studio-marketplace-azure-devops-installs.service.js
services/visual-studio-marketplace/visual-studio-marketplace-version.service.js

After this, I reckon there are probably 2 more of these PRs to go, and then we're done.

migrate some services from examples to openApi part 45; affects [github coveralls visualstudiomarketplace]

---

services/website/website.service.js
services/website/website.tester.js

[Website] Render `status: down` badge if website is unresponsive

---

services/scoop/scoop-version.service.js
services/scoop/scoop-version.tester.js

Added custom bucket url support for [Scoop]

---

services/color-formatters.js
services/color-formatters.spec.js
services/github/github-created-at.service.js
services/github/github-created-at.tester.js

[GithubCreatedAt] Add Created At Badge for Github

---

services/npm/npm-downloads-redirect.service.js
services/npm/npm-downloads.service.js
services/npm/npm-downloads.spec.js
services/npm/npm-downloads.tester.js

Closes https://github.com/badges/shields/issues/10024
This PR implements the suggestion from https://github.com/badges/shields/issues/10024#issuecomment-2004720161

redirect [npm] /dt to /d18m

---

services/librariesio/librariesio-dependencies.service.js

Hello! I work on libraries.io. The endpoint used by shields for the librariesio repository dependencies badge is pretty expensive and can return a large payload, most of which was not useful to shields. Not to mention additional work is being incurred on your end.
We have created a new dedicated endpoint which returns only the two values shields cares about, and should have a much quicker response time.  This PR switches to the new endpoint.

Perf: librariesio repo dependencies

---

package-lock.json
package.json

Closes https://github.com/badges/shields/pull/10070
Closes https://github.com/badges/shields/pull/10067
No changes needed to the customised components

upgrade @docusaurus/core and docusaurus-openapi

---

config/custom-environment-variables.yml
config/default.yml
core/server/server.js
doc/server-secrets.md
services/pypi/pypi-base.js
services/pypi/pypi-downloads.service.js
services/pypi/pypi-format.service.js
services/pypi/pypi-framework-versions.service.js
services/pypi/pypi-implementation.service.js
services/pypi/pypi-license.service.js
services/pypi/pypi-python-versions.service.js
services/pypi/pypi-status.service.js
services/pypi/pypi-version.service.js
services/pypi/pypi-wheel.service.js

fix https://github.com/badges/shields/issues/6760
This pr make pypiBaseUrl configurable with both config.yaml and queryParameter.

support setting pypiBaseUrl by environment variables and queryParameters; affects [pypi]

---

frontend/blog/2024-06-01-simpleicons12.md

Refs https://github.com/badges/shields/issues/10216
Refs https://github.com/badges/shields/pull/10212
Since we launched the new frontend, I've been putting these on the https://shields.io/blog
Feels like a good place to announce changes that impact end users
This is basically just a copy of https://github.com/badges/shields/issues/10216

simpleicons 12 blog

---

.github/dependabot.yml
package-lock.json
package.json

Improve Docusaurus Dependabot setup

---

services/chocolatey/chocolatey.service.js
services/nuget/nuget-v2-service-family.js
services/powershellgallery/powershellgallery.service.js
services/resharper/resharper.service.js

Small cleanup opportunity that I noticed when working on #10344.

Remove unused parameters in [Chocolatey Resharper PowershellGallery]

---

services/docker/docker-version.service.js
services/github/github-deployments.service.js
services/github/github-milestone-detail.service.js
services/github/github-milestone.service.js
services/netlify/netlify.service.js
services/obs/obs-build-status.js
services/obs/obs.service.js
services/wordpress/wordpress-last-update.service.js

Nothing much going on here, did a quick cleanup pass with things that were being flagged by my IDE.

Cleanup unused bits and pieces, affects [dockerversion githubdeployments githubmilestone netlify obs wordpress]

---

services/jenkins/jenkins-coverage.service.js
services/jenkins/jenkins-coverage.tester.js

This test broke again. As promised in #10217, I've gone ahead and mocked it.

Mock [JenkinsCoverage] Cobertura job found test

---

services/gerrit/gerrit.tester.js

Change number 2013 was apparently deleted.

Fix [Gerrit] new change test

---

core/base-service/legacy-result-sender.js
core/server/server.js
core/server/server.spec.js

Closes https://github.com/badges/shields/issues/10419

send Cross-Origin-Resource-Policy header on all responses

---

services/crates/crates-dependents.service.js
services/crates/crates-dependents.tester.js

Closes #10204 
- FYI: `librariesio-dependents.service.js` helped me implementing this service.

[Crates] Implement Dependents Badge

---

services/github/github-go-mod.service.js

Closes https://github.com/badges/shields/issues/10442

move go version badge to platform support category

---

services/treeware/treeware-trees.service.js
services/treeware/treeware-trees.tester.js

Use Ecologi API to power [Treeware] badges

---

services/pepy/pepy-downloads.service.js

fix typo in pepy downloads

---

.github/workflows/create-release.yml
.github/workflows/publish-docker-next.yml
doc/self-hosting.md

This reverts commit 4a37203da76aa141be52e9157fc3d942bc560eae
Refs https://github.com/badges/shields/pull/10441#issuecomment-2308978789

Revert PR 10441 (linux/arm64 docker build)

---

config/custom-environment-variables.yml

[Gitea] Fix Environment Variables Missing 

---

services/codecov/codecov.service.js

[Codecov] Fix incorrect config link

---

CHANGELOG.md

call out security advisory in changelog

---

frontend/blog/2024-09-25-rce.md

publish blog about security vuln

---

services/text-formatters.js
services/text-formatters.spec.js

ignore commit hash in addv
Fixes #10591 - see issue for more info

remove prefix v for commit hash version

---

services/youtube/youtube-base.js

Add YouTube-specific privacy notes

---

services/codeclimate/codeclimate-analysis.service.js

Swaps summaries of 2 Code Climate endpoints.

Fixed mixed up summaries of 2 Code climate endpoints

---

services/chrome-web-store/chrome-web-store-size.service.js
services/chrome-web-store/chrome-web-store-size.spec.js

allow [chromewebstore] size to contain decimal point

---

SECURITY.md

update security policy: clarify we don't pay bounties

---

server.js

The main entrypoint now handles the SIGTERM signal and stops the server.

graceful shutdown

---

services/codecov/codecov.service.js

Fixes https://github.com/badges/shields/issues/10970

fix(#10970): [codecov] branch badge

---

frontend/static/img/icon.svg

Closes #11106
Related to #11106 and https://github.com/simple-icons/simple-icons/pull/13358.
Just upload a copy to the repository.

add icon svg

---

.github/workflows/test-package-cli.yml
.github/workflows/test-package-lib.yml
badge-maker/CHANGELOG.md
badge-maker/README.md
badge-maker/package.json
package-lock.json
package.json

After merging this I'll push a tag and publish to NPM

badge-maker 5.0.0

---

frontend/blog/2025-07-26-CVE-2025-54313.md

While not directly vulnerable to this, users might be affected so it's worth raising awareness IMO.
For full info read PR changes.
Read more here:
https://www.endorlabs.com/learn/cve-2025-54313-eslint-config-prettier-compromise----high-severity-but-windows-only
https://github.com/prettier/eslint-config-prettier/issues/339

docs: add CVE-2025-54313 vulnerability report blog post

---

services/bitrise/bitrise.service.js
services/bitrise/bitrise.tester.js

The previous project has gone stale. I reached out in https://github.com/pakerwreah/Calendr/issues/476 to ask whether it would be okay to use Calendr's token in our tests, we've got the green light. :)

Fix [Bitrise] tests

---

services/scoop/scoop-license.tester.js

Fix [ScoopLicense] test

---

package-lock.json
package.json

Fix [ChromeWebStore] null-check missing store extension
