server.js

Badges are not ads. See https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md
Mentioned in https://github.com/badges/shields/issues/313#issuecomment-72124562

Replace 'CircleCi' key with 'build'.

---

templates/flat-square-template.svg

This solves an issue I've been having where you can't color match due to there
being a transparent rect sitting on top of the background colors.
It also fixes a fuzzy gray line around the edge of the right color due to
antialiasing on squares (shape-rendering="crispEdges")
I'm also trying to figure out why scaling doesn't work properly in IE.  I'll
put that in another PR when I manage to figure that out though.
Before:
After:

Minor fixes to the flat-square template.

---

templates/flat-template.svg

Before:
After:
This also increases the file size by five bytes.  I don't see an easy way to
reduce that though.  (Yet.  Still experimenting with SVGs.)

Fix fuzzy edges on the flat template

---

server.js
try.html

This commit adds support for packagist vpre. #319
For example:
- stable symfony/symfony: ![stable symfony framework](http://cl.ly/ZhQF/direct), latest dev: ![latest dev symfony framework](http://cl.ly/Zhr3/direct)
- stable laravel/framework: ![stable laravel framework](http://cl.ly/ZheA/direct), latest dev: ![latest laravel framework](http://cl.ly/Zhcu/direct)

Packagist vpre support.

---

server.js

Fixes badges/shields#337
The reason my repository does not work with github release badge is because the "latestVersion" call modifies the version strings from "x.x" to "x.x.0" - after comparison it then returns the modified version. However, to check for prerelease flag, it tries to find the modified version in the version list and of course, does not find it, and errors. This results in a "none" release badge.
This PR fixes latestVersion so after it finds the latest version, it always returns the original string, not the modified one.
Will raise another PR to utilise the /latest API in GitHub release badge shortly - this next PR will likely make this irrelevant in the context of #377 - but I expect the issue addressed by this PR may affect other places unknowingly.

Fix latestVersion returning a version string not in the given version list

---

try.html

WordPress has a capital P just like CocoaPods

WordPress has a capital P

---

try.html

I've often wanted to point people to http://shields.io/#styles, but couldn't, because the \<h2> had no ID.  Let's fix that!

Add anchors for direct linking

---

server.js
try.html

Added a license badge using the new [GitHub license API](https://developer.github.com/v3/licenses/#get-a-repositorys-license). Not sure what happened to #280 & #315 but the badge wasn't available in master and using the official API seems to be a better solution.

Add github license integration

---

server.js

This way David badges behave the same as Gemnasium.

Make David badge green for "dependencies: none". Fix #413

---

server.js
try.html

Based on the work already done by @erwan in this PR #388 
I've added the new endpoint to Clojars, with a simpler versioning:
https://github.com/ato/clojars-web/pull/315
This change parses the version data, that looks something like:
https://clojars.org/overtone/overtone/latest-version.json
or
https://clojars.org/overtone/latest-version.json
What do you think? Thanks

Clojars version support

---

index.html
server.js
try.html

possible combinations:
- `/github/downloads/:user/:repo/latest/total.svg`
- `/github/downloads/:user/:repo/:release_id/total.svg`
- `/github/downloads/:user/:repo/:release_id/:asset_name.svg`

Github Releases Download counter

---

server.js

Instead of the current:
v + clojar-version number: v1.1.2
e.g.: [![pdfboxing](https://img.shields.io/clojars/v/pdfboxing.svg)](http://clojars.org/pdfboxing)
use full name and version (which can be cut & pasted and included in a project): [clojar-name "1.1.2"]
e.g. [!["clojars"](https://img.shields.io/badge/clojars.org-[pdfboxing%20"0.1.5"]-brightgreen.svg?style=flat-square)](https://clojars.org/pdfboxing) 
As per discussion: https://github.com/ato/clojars-web/pull/315#issuecomment-94726248

Display the clojar name in clojure fashion

---

server.js

As reported in #429, this PR allows support for npm scopes via encoding the package name. The issue is that scopes use a separator character which is the same as the URL path separator.
```shell
curl -i https://registry.npmjs.org/@wilmoore/accessor/latest
```
```
HTTP/1.1 401 Unauthorized
npm-notice: ERROR: you cannot fetch versions for scoped packages
```
```shell
curl -i https://registry.npmjs.org/%40wilmoore%2Faccessor/latest
```
```
HTTP/1.1 200 OK
Content-Type: application/json
```
```json
{
"name": "@wilmoore/accessor",
"description": "Higher-Order getter/setter.",
"version": "0.2.0",
"author": {
"name": "Wil Moore III",
"email": "wil.moore@wilmoore.com"
},
"bugs": {
"url": "https://github.com/wilmoore/accessor.js/issues"
},
"dependencies": {},
"devDependencies": {
"istanbul": …
```

Support npm scopes

---

server.js
try.html

This PR adds the ability for CodeCov badges to be generated for private repositories. CodeCov supports a badge token which can be passed via a the `token` query param. 
Also added documentation to `try.html`

Add CodeCov Private Repository Support

---

index.html
server.js
try.html

This allows users to specify a owner + application name, instead of a application ID. 
Made the regex for the old endpoint a bit more strict so it wouldn't conflict with the new one.
It also uses the public, supported API.

Add wercker v3 integration

---

server.js

I wasn't able to test it in my machine though (problems with node-gyp)...
Anyways, I think it should work that way..

added support for shippable

---

index.html

The badge demonstrating use of style `flat-square` was titled "flat-square*d*" (extra "d" at the end), which invited confusion.

Badge text modified to reflect actual style name

---

server.js
try.html

Please review it. Thanks.
Related Issues: https://github.com/badges/pypipins/issues/39 https://github.com/badges/pypipins/issues/37

Add wheel/python-version/python-implementation/status badage for PyPI.

---

server.js

Changed to default to metric(value) instead of value + '%'.  % is shown for any coverage metrics.  Added special handling for fortify-security-rating metric.  Changed to use brightgreen instead of green for the "best" value for metrics to be more consistent with other badges.
Note:
I originally had another pull request that I closed, https://github.com/badges/shields/pull/447.  I didn't realize you could add ?label= and some of the changes I made in that pull request are unnecessary.

sonar - do not default to %, more metric support

---

server.js

I spotted a bunch of 404s in the packagist logs that are due to people publishing things like https://github.com/thephpleague/skeleton and other people not editing the READMEs before publishing I suppose. 
Anyway I hope the fix is appropriate and acceptable.

Avoid sending dummy requests to packagist

---

server.js

Before it would only match strings such as:
```python
Programming Language :: Python :: 2.6
```
And not match strings such as:
```python
Programming Language :: Python :: 3
```

Updated python version matching to work with whole numbers too.

---

server.js

This should remove redundant version numbers such as:
```{2, 2.6, 2.7} -> {2.6, 2.7}```
or
```{2, 3.2} -> {2, 3.2}```
or
```{3, 3.0} -> {3.0}```

Updated matching to remove redundant python versions.

---

server.js
try.html

Hi. I've implemented #471.
Snap CI is
https://snap-ci.com
Thanks.

Support Snap CI

---

index.html
server.js
try.html

Addresses #58 by supporting a badge showing the latest version of
a Bintray package.
Ran a test locally and it seemed to work fine. You'd need to get an API key from Bintray to put in `secret.json` and work with them on the rate limit question.

Support for Bintray version badge.

---

index.html
server.js
try.html

This adds support for the total downloads for the given project.
I use the range rest service of npm to fetch the info.

npm total downloads support

---

server.js

I noticed all the Node.js versions badges were suddenly grey. Looks like with the Node.js 4.0 launch, they also changed from SHA1 to SHA256 and changed the name of the file with it. This updates the URL to get the current version of Node.js from.

Fix grey Node.js version badges

---

server.js

This updates the logic for the Gratipay badge for a change in the Gratipay API where the "receiving" field was renamed to "taking" as part of their migration to teams.

Update Gratipay badge for API change

---

Dockerfile
INSTALL.md

As I was working on #538, I ran the server in Docker. But the default `Dockerfile` was broken. I updated to use the official Node image with `ONBUILD` hooks instead. Also added some information about it in the docs (the two commands I were using together to build and run).
I did try Node 4.0.0, but it looks like some other dependencies are still broken on 4.0.0 (namely https://github.com/socketio/socket.io/issues/2228).

Fix broken Dockerfile to use official node image instead

---

server.js
try.html

This shield displays the percentage of a Pod's API that is documented as returned by the CocoaPods metrics API. It can be quite useful when figuring out if you'd like to bring in a third-party dependency.
The entire list of metrics is available [here](http://metrics.cocoapods.org/api/v1/pods/AFNetworking). This  endpoint could easily be expanded to support more metrics as needed.

Add CocoaPods documentation percentage

---

server.js

Hello,
Looks like when you request a build status for a branch it ignores the branch!
Seems a typo in the code.
Jason

Fix broken travis branches

---

index.html
server.js
try.html

Recreated the original pull request (#526) based on comments and with latest badges repo to avoid conflict issues.

total github downloads for all releases + all tags

---

.editorconfig

Based on my experience with previous pull requests, since I was using different formatting rules, it was a bit hard to work with my IDE which kept on formatting the file based on different rules.
This basic editorconfig settings should help out with that and enable contributors to set their IDEs/Editors to use it and prevent mistakes.
For me personally the issue was with the indent set to 4 spaces for js files in my projects while in this project you use 2 spaces. And since it is a bit not standard, this should help out.
Naturally contributors would need to actually use it.

.editorconfig file to help all contributors to align to a common project standards

---

server.js
try.html

This adds a ImageLayers.io badge (which resembles the same data in their own badge). I wanted to use their badge. But it didn't conform to the look of all the other ones I was already using from shields.io.
This also adds a small `filesize` package. It was a quick way to do humanized file sizes. If this undesirable, I can try and rework it without.

Add ImageLayers.io Docker Hub layer information service

---

server.js

Consistently use "passing" (previously 4 vendors) instead of "passed" (4), "success" (1), or "shippable" (1).  I arbitrarily picked "passing", but I'm not married to that particular choice.
Affected vendors are: Shippable, Wercker (also V3), TeamCity, Codeship, Scrutinizer, and Snap CI.
Fixes part of #575.

Consistently use "passing".

---

server.js
try.html

This provides a new route to get code coverage from Jenkins. It uses the [Cobertura plugin](https://wiki.jenkins-ci.org/display/JENKINS/Cobertura+Plugin) to get the coverage results of the last build.
For example: `https://img.shields.io/jenkins/c/https/jenkins.qa.ubuntu.com/address-book-service-utopic-i386-ci.svg`
This PR uses Jenkins HTTP auth suggested in https://github.com/badges/shields/pull/579.

Add route for Jenkins code coverage

---

server.js

Some private Jenkins instances are protected and need an HTTP authentication. This feature allows setting a Jenkins username and password or token (preferred) in the `secret.json` file.

Allow HTTP authentication on Jenkins

---

server.js
try.html

Hi!
I added PackageControl to the supported providers. I copied the code from the Packagist block right above since their behaviour is the same.
Here is an example of the response format : https://packagecontrol.io/packages/Laravel%205%20Snippets.json
Also, I haven't been able to test it, since I don't have a development environment setup.
Thanks!

Add Package Control support

---

server.js

Coverity also consistently uses "passing".

---

.travis.yml

Fixes Travis CI build error:
https://travis-ci.org/badges/shields/builds/97102831
$ sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libgif-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source
E: Package 'libgif-dev' has no installation candidate
The command "sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++" failed and exited with 100 during .

Run apt-get update before installing packages

---

server.js
try.html

Adds support for Visual Studio Oline build badges.  This uses the `fetchFromSvg` function to read a string from the badge SVG data.
Test cases:
`/vso/build/schwabencode/1838fe47-1e26-4f59-924a-59ea28e64d6a/9.svg`
`/vso/build/larsbrinkhoff/953a34b9-5966-4923-a48a-c41874cfb5f5/1.svg`
Fixes #522.

Visual Studio Online build integration.

---

server.js

This allows connecting to github using a private token, accessing to private and enterprise github repositories.

Allow token authentication on github

---

server.js
try.html

Support for npm version for scoped packages at `registry.npmjs.org/[package]/latest` seems to have been removed. However, you can get the version from `registry.npmjs.org/-/package/[package]/dist-tags`.
This pull request partially addresses #429. For full support (download counts) we'll need to wait on npm. Looks like they are working on it though https://github.com/npm/download-counts/issues/23

fix npm version badge for scoped packages

---

server.js

CodeShip badge show build inaccessible now.
https://img.shields.io/codeship/9d423a50-5ace-0133-11b8-624f61fe64ff.svg
According to CodeShip document, it use `codeship.com`, and `https://www.codeship.io` have SSL certificate problem.
https://codeship.com/documentation/faq/codeship-badge/

Change CodeShip domain

---

Dockerfile

Mostly to speed up the image pull. It was painfully slow.
Confirmed to work on latest docker.

chore(docker): do not target a specific minor

---

badge.js
measure-text.js
package.json

This removes the dependency on the native "canvas" module and instead uses pdfkit.  I did this because I was unable to get canvas installed on my machine.  I'm not sure if this will perform better or worse, but it seems like something that may be worth benchmarking.

Use pdfkit instead of canvas

---

server.js
try.html

This pull requests allows to display the Sourceforge download count of a project folder.
On Sourceforge, projects are like organisations on Github. They may contain multiple repositories and download areas for individual software developed by the same group.
For example the [Arianne Project](https://sourceforge.net/projects/arianne/) consists of [Stendhal](https://sourceforge.net/projects/arianne/files/stendhal/) and [Marauroa](https://sourceforge.net/projects/arianne/files/marauroa/). So in the Github readme file of [Stendhal](https://github.com/arianne/stendhal) and [Marauroa](https://github.com/arianne/marauroa) I like to display their individual counts. Not the download count of the complete Arianne project/organisation.
The attached pull requests allows to optionally specify a …

added support for download counter on folders at Sourceforge

---

index.html
server.js
try.html

Visual Studio Online has been renamed Visual Studio Team Services
Also, you could change the vso in the link into vsts (or add an alias to have backward compatibility)
Regards,
Thomas P.

Visual Studio Online has been renamed Visual Studio Team Services

---

server.js
try.html

Based on the conversation in #257 and the available API referenced in waffleio/waffle.io#2466 I've modified the existing shield to work with the new endpoint.
**Some Examples:**
- waffle/cards/evancohen/smart-mirror/next.svg 
- waffle/cards/evancohen/smart-mirror/in%20progress.svg
- waffle/cards/evancohen/smart-mirror/needs%20review.svg
**Restrictions**
- Unfortunately the current API does not let you look at cards that are unlabeled, for instance you could not have a count of the number of cards in [backlog](https://waffle.io/evancohen/smart-mirror).
- By default Waffle comes with a label called `ready`. This is used for the "default" badge, ie: 
waffle/cards/evancohen/smart-mirror.svg. 
This becomes a problem when you remove the default label, at which point it wont return anything and …

shield for the Waffle API

---

package.json
server.js
try.html

* Version, Downloads, Price, Rating and Rating Count for chrome app,
chrome extension and chrome theme.
* Google does not provide a public API for chrome web store.
* Use `chrome-web-store-item-property`.
* Gather meta information from chrome web store.
see #505, #636
I re-send pull request. #505 still works fine :)

Add chrome extension support

---

index.html
server.js
try.html

This relates to #638 where a request was made to support querying of homebrew package version, using the API provided by http://braumeister.org/.
I am very new to shields.io, so I may not have done this correctly.  I stitched this together by referencing a number of similar systems.
Please let me know if there is anything that needs to change.

(GH-638) Added basic badge integration for homebrew

---

server.js

The ``registry.hub.docker.com`` domain name has been deprecated, and we should use ``hub.docker.com`` now instead. 
This PR updates the hostname, so that shields will not break when ``registry.hub.docker.com`` is removed in the future.

Update Docker API hostname

---

server.js

From several months ago, ansible role badges show `errored`.
For example, https://img.shields.io/ansible/role/3078.svg on http://shields.io/ got [![Ansible Role](https://img.shields.io/ansible/role/3078.svg)]().
Ansible Galaxy API now returns `namespace` instead of `summary_fields.owner.username`.
see https://galaxy.ansible.com/api/v1/roles/3078/.

fix errored in ansible role badge

---

server.js

up-to-date appears twice here, and update! nowhere. This causes badges like https://img.shields.io/gemnasium/resque/resque-web.svg to appear undefined, while there are actually red: https://gemnasium.com/resque/resque-web.svg

Fix Gemnasium badge when status is update!

---

README.md
server.js
try.html

I've just started using Codacy in preference to Scrutinizer. I noticed Shields had a Codacy grade indicator, but no coverage indicator, so here's the implementation.
+ The existing grade badge has been changed, but is backwards compatible (so people using the URL _without_ the `grade/` part still continue getting the correct grade.
+ New URLs for Codacy shields identify the `grade/` or `coverage/`.
Tested locally, please let me know if there are any questions.

Implement Codacy coverage badge

---

server.js
try.html

This can be useful for a [documentation|online] badge, for example, to avoid putting an always-green one.
Please do review the code from a security standpoint, as I'm not a node.js expert. I just based myself on the other vendors. Among other concerns, since it's accepting and fetching a user-provided URL, are there any port number or IPs on the server's local network that an attacker could somehow probe with this?

Added support for online/offline website badge.

---

server.js
try.html

Expands CocoaPods integration using `metrics.cocoapods.org`.
Tried my best to match the existing style for other package managers.
Also cc @orta @segiddins @kylef as core CocoaPods people.

Add CocoaPods downloads badges.

---

try.html

The project ID used with the Shippable samples has changed.  With this change, the badge will display `build passing` again.

Shippable sample project ID changed.

---

server.js
try.html

This commit adds support for issuestats.com, as requested in #351.  The implementation is straight-forward, with the exception of the handling of `not found` which currently returns `text/html` with status code `200` (see hstove/issue_stats#38).  The URL parsing is somewhat lax to allow future support for other hosting platforms which may not follow GitHub's `user/repo` URL scheme.  It also passes through the `concise` query parameter, if present, which shortens the text a bit.
Fixes: #351
Thanks for considering,
Kevin

Add support for issuestats.com

---

server.js
templates/flat-square-template.svg

I'm really not sure this would work, I just copied a code chunk from flat.

Attempt to add logo to flat-square template

---

index.html
server.js
try.html

badges/shields#241
Query https://registry.hub.docker.com/v2/repositories/USER/IMAGE/ to get the boolean 'is_automated'
'automated build' for the left part, 'docker automated' or 'docker automated build' didn't sound as good.

PR for Docker Hub Automated Builds

---

server.js

Useful for GitHub Enterprise installations.  Docker containers for enterprise can be easily built then by adding:
```Dockerfile
ENV GITHUB_URL "https://github.enterprisedomain.com/api/v3"
```
and then deployed inside of the firewall

Allowing GitHub API URL override

---

server.js

Out of the supported 5 Chrome web store related badges, overriding the default label fails with chrome-web-store/d, chrome-web-store/rating and chrome-web-store/reating-count type badge.
Example:
`https://img.shields.io/chrome-web-store/d/nimelepbpejjlbmoobocpfnjhihnpked.svg?label=testing`
[![Chrome Web Store](https://img.shields.io/chrome-web-store/d/nimelepbpejjlbmoobocpfnjhihnpked.svg?label=testing)](https://img.shields.io/chrome-web-store/d/nimelepbpejjlbmoobocpfnjhihnpked.svg?label=testing)
The above badge's label should show testing instead of downloads

Allow label overriding in all Chrome web store badges

---

index.html
server.js
try.html

To show the latest(and usually the stable) version on CDNJS via CDNJS api.
cc cdnjs/cdnjs#5060

Add CDNJS version integration

---

.dockerignore
Dockerfile
INSTALL.md

Current `Dockerfile` was not working and documentation was lacking regarding
Fixed Dockerfile and improved doc regarding `secret.json`.
```
$ docker run --rm -p 8080:80 -v "$(pwd)/secret.json":/usr/src/app/secret.json --name shields shields
> gh-badges@1.2.2 start /usr/src/app
> node server.js
http://[::1]:80/try.html
```

Fixed Dockerfile and improved doc regarding `secret.json`.

---

README.md

Add a link to the Linux Foundation Core Infrastructure Initiative (CII)
best practices badge, which uses the shields.io spec.
To see this, visit: https://bestpractices.coreinfrastructure.org/
and select "Projects".

Add CII Best Practices

---

index.html
server.js
try.html

Fixes #791 @sholladay
url structure:
`/circleci/token/YOURTOKEN/project/github/RedSparr0w/node-csgo-parser/master.svg`
part of url | required | explanation
--- | --- | ---
/token/YOURTOKEN | no | token if private Repo
/github | yes | can either be github or bitbucket depending where repo hosted
/RedSparr0w | yes | Username
/node-csgo-parser | yes | Repository
/master | no | Branch

Fix Circle CI Integration | Circle CI API v1.1

---

INSTALL.md
server.js
try.html

Add support for github OSSMETADATA osslifecycle.  This is heavily used by Netflix OSS and is being considered by use across the TODO Group (Facebook, Yahoo, Microsoft, etc.).
also, fixed the command for docker ... didn't seem right as is

fix docker command, add NetflixOSS OSSMETADATA osslifecycle support

---

server.js
try.html

Amended to allow '/' in Jenkins job name. It also allows user to just copy and paste the Job URL to get the badge.
```
https://img.shields.io/jenkins/s/https/jenkins.qa.ubuntu.com/view/Precise/view/All%20Precise/job/precise-desktop-amd64_default.svg
```
For backward compatibility, ``https://img.shields.io/jenkins/s/https/jenkins.qa.ubuntu.com/precise-desktop-amd64_default.svg`` style URL is kept to work.
Fixes #858.

Fix Jenkins job name with '/'

---

.eslintrc.yml
lib/github-auth.js
package.json
server.js
suggest.js
svg-to-img.js
test/test.js

This is the first pass of automated linting, to be checked and enforced by PRs. Discussed this a bit with @espadrine, who requested it.
Manually checking style enforcement in PRs is time consuming. Automatic checking not only makes PRs go faster – it also lets contributors find and fix their own problems, which is less frustrating too.
These semicolon fixes were applied automatically, so there's no need to comb over them. I'll turn on more checks in the next couple passes, some of which will need to be resolved manually. That means there's room for error and someone needs to check them. Keeping the diff small and readable will ensure we don't introduce any new bugs in the process.

First pass for linting on PRs

---

.eslintrc.yml
server.js
test/lru-cache.js

This turns on a lint rule for a common, likely error: the redeclaration of a variable.
In a few of the fixes of the existing rules, you'll see that I used `let`.
[Block scope](https://ariya.io/2013/05/es6-and-block-scope) is one of the great features in ES6. It allows the programmer to limit a variable's scope to the block in which it's defined. `var` is always function-scoped for compatibility with ES5, while `const` and `let` are always block-scoped. Using `const` or `let` is preferable to using `var`, since they match the semantics expected by programmers accustomed to C-style languages. Not only do they prevent these accidental re-use errors, they also [eliminate the need for an IIFE](http://wesbos.com/es6-block-scope-iife/).
`let` and `const` have been enabled by default since the …

Disallow variable redeclaration

---

index.html

Spent some time trying to figure out how this was supposed to work :P

Disambiguate provider vs package: Package Control

---

INSTALL.md

Problem: I wanted to know what color schema is available
Solution: Add links to directly reach the predefined schemes and templates

add format documentation links

---

lib/github-auth.js

The server.js fails if this variable is not defined with a sensible default value.

fix default value for githubUserTokens

---

try.html

Sets all the shield images to be 20px. Also allows the table to be wider than 50% so that the columns don't look squashed due to long urls.

Reduce page jumping while all the badges are loading

---

server.js

Ah, it makes sense that the lint test will only run on branches that have incorporated the commits which pulled them in. 😄
So the in-PR test results will be more reliable for new PRs than for old ones.

Clean lint from #1275

---

server.js

From several weeks ago, image layers badges has been unavailable.
- https://img.shields.io/imagelayers/image-size/_/ubuntu/latest.svg (without maxAge)
- https://img.shields.io/imagelayers/layers/_/ubuntu/latest.svg (without maxAge)
Currently https://imagelayers.io/ works with POST https://imagelayers.io/registry/analyze instead of https://imagelayers.io:8888/registry/analyze, access to 8888 port timed out.
``` console
$ openssl s_client -connect imagelayers.io:8888                                                                                                                       
connect: Operation timed out
connect:errno=60
```
It seems no changes on API response without port number.
``` console
$ curl -s -X POST -d '{"repos": [{"name": "library/ubuntu", "tag": "latest"}]}' …
```

remove imagelayers.io port number

---

server.js

Projects that have zero technical debt would otherwise receive a lightgrey badge instead of a brightgreen one.

[SonarQube] Use greater-equals for tech_debt colors

---

lib/load-logos.js
lib/svg-to-img.js
server.js

The following warning is emitted by Node.js:
> DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new
> Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or
> `Buffer.alloc()` instead.
This patch removes this warning.
@paulmelnikow may you review this patch, please?

Use `new Buffer()` instead of `Buffer()`

---

server.js

Affects David, Gemnasium and requires.io
David's own badges use spaces, the other two services use `-`. I think it's better to use spaces.

Use spaces in "up to date" and "out of date" statuses

---

server.js
try.html

The [OpenAPI Specification](http://swagger.io/specification/) (formerly known as the Swagger RESTful API Documentation Specification) defines a format for describing RESTful APIs.  The Swagger project provides a set of tools for working with this format, including a [hosted validator](https://github.com/swagger-api/validator-badge) which provides a validation badge and JSON result.  This commit adds shields.io support for this badge.
The service currently only provides validation of files conforming to version 2.0 of the OpenAPI Specification.  This commit adds a path component for specifying the version under the assumption that the validator may support version 3.0 or later as they are released.
It accepts the URL to validate as two path components, a scheme followed by the rest of the …

Add support for swagger.io validator

---

server.js
try.html

Allows for getting the npm version of a tag by appending `/<tag>` to the url.
[x-ref] #925

Enable npm version for specific tag

---

server.js

Disallowing unused variables (#916) revealed that the result of `versionColor` was not being used for Clojars. It's one of the only badges using a non-standard version color. Seems like consistency is a good thing, helpful for users.
Tested locally, and works as intended.

Use standard version color for clojars

---

server.js
try.html

Fix #921 
I started work today on some vcr-style tests. They send requests to the server, record the responses to vendor requests, and then play the vendor requests back later. The library I'm using is a little buggy. The suite isn't ready for prime time. I'll add tests as I go. Hopefully there will be a meaningful amount of coverage by the time I've gotten the library under control.
I'm very open to input: https://github.com/paulmelnikow/shields-tests
These are the CTAN tests:
https://github.com/paulmelnikow/shields-tests/blob/master/vendor/ctan/spec.js

Improve CTAN error handling and fix non-svg 404 badges

---

.travis.yml

When merging someone else's PR with edits, it's helpful to to push a branch
and make sure the tests are also passing in CI.
Related: any reason not to discard these?
- old-master
- redundant-mit-license

Build branches

---

server.js

@espadrine Thanks for merging PR #639. I tested it a bit, and it seems it doesn't work when a path is given (instead of just a domain name).
I think I found the cause of the bug, it seems I got caught by a greedy regexp when separating the domain name from the rest of the URL in the syntax, and part of the domain + URL is gobbled up in the group matching the protocol. Hopefully this patch fixes that.

Fix bug in website badge (regexp was too greedy)

---

server.js
try.html

[NuGet download badges giveth](https://github.com/badges/shields/pull/179), and [NuGet download badges taketh away](https://github.com/badges/shields/commit/4df74acd6ce78d480fa37d11319ba13682e482f5).
Now they're back, in ~~[pog](https://www.youtube.com/watch?v=M_UR201plc8)~~ V3 form.
I switched the NuGet badges from the `SearchAutocompleteService` to the `SearchQueryService`. The SearchQueryService returns download counts in addition to version numbers.
This works for both NuGet and MyGet:
I also verified that the version number badges still work as expected:
I tried to keep the style as close to the original code as possible, although this code could do with some modernization (like using promises rather than callbacks) at some point. I'm happy to help with that 😃 
Closes #678

Add badge for NuGet download count, again

---

.gitignore
index.html
server.js
try.html

Add shields for Uptime Robot

---

server.js
try.html

@paulmelnikow Thanks for merging #720.
I double-checked the regexp, and realised that there was still a bug when the `up-down` and colour options were specified. Sorry about that, hopefully this regexp fixes these issues (I tested it more thoroughly at https://regex101.com/r/xTAHin/1).
I also added support for specifying the left part of the badge, so that one can easily make badges that look like `docs|online`, `downloads|online`, `official site|up` and so on. This change is backwards-compatible, as it can only occur when an odd number of options is present (either `SiteName`, or `up-down-SiteName`, or `up-down-green-red-SiteName`, in addition to the previously supported formats “empty”, `up-down` and `up-down-green-red` which all had an even number of options).
Could you have a look at …

Fix bug in website badge, allow specifying website name (left part of badge)

---

INSTALL.md

`shields.io` requires Node.js 6, but this was not specified in INSTALL.md.

Quick installation steps for Node.js 6 in INSTALL.md

---

server.js
try.html

Fixes #688 
Added the `/github/release/user/repo/all.svg` endpoint that shows the latest release, including pre-releases.

GitHub (pre-)releases

---

server.js
try.html

@paulmelnikow Following your suggestion in https://github.com/badges/shields/pull/949#issuecomment-297454871, I removed the part of the regexp concerned with the badge's label, and adjusted the code accordingly.
The new version seems to work fine, I re-ran the tests below (moving the label to a query parameter where applicable).
```
http://127.0.0.1/website/https/img.shields.io/nonexistant/foo-bar-green.svg.svg?label=si-t-e/do/-cs
si-t-e/do/-cs|offline (red)
http://127.0.0.1/website/https/img.shields.io/badge/foo-bar-green.svg.svg?label=si-t-e/do/-cs
si-t-e/do/-cs|online (green)
http://127.0.0.1/website-up-down/https/img.shields.io/nonexistant/foo-bar-green.svg.svg?label=si-t-e/do/-cs
si-t-e/do/-cs|down (red)
http://127.0.0.1/website-up-down/https/img.shields.io/badge/foo-bar-green.svg.svg …
```

Removed ability to specify the badge's label for the “website” service

---

test/cli-test.js
test/server-test.js
test/test.spec.js

`server-test.js` is not used anymore, and `gh-badge.js` can be used directly.

Remove unused / unnecessary test fixtures

---

package.json

The decision to drop support for Node 5 was discussed in #902 and #964. Windows Vista is not even [supported by Microsoft anymore](https://support.microsoft.com/en-us/help/22882/windows-vista-end-of-support). Developing for old platforms puts drag on the Node community as a whole. No one likes developing for old platforms, and the good resources for learning JavaScript are in ES6.
There are reasonable arguments for keeping long-term support, like wide use across many projects. They might apply to the gh-pages library, and could consider supporting Node 6 in the library for as long as it's in LTS. However they do not apply to the Shields server. Even users who are self-hosting should be able to run current Node somehow (in Docker, if nothing else). We should be mindful of our limited …

Record minimum Node version

---

package.json
service-tests/runner/cli.js

The coverage script was introduced in 5c147b8d91ca4f014dbdfb4f672246926bd9aa0a,
and the spec files were moved in c3ef232bf75e13f419af1ff832650f348c05804c.
Also, correct a small typo.
@paulmelnikow Could you review this patch, please?

Set the coverage npm script to use current specs

---

.eslintignore
package.json
service-tests/README.md

This fixes two issues:
1. We don't want to lint `/coverage`, which is where we're sending the coverage reports.
2. The `--delay` argument was received by `istanbul` instead of `_mocha`, so `global.run` is `undefined`. That resulted in this stack trace:
```
$ npm run coverage:test:services -- -- --only=maven-central
> gh-badges@1.3.0 coverage:test:services /Users/fabriziocucci/git/shields
> istanbul cover _mocha --delay service-tests/runner/cli.js --dir coverage/services "--" "--only=maven-central"
=============================================================================
Writing coverage object [/Users/fabriziocucci/git/shields/coverage/services/coverage.json]
Writing coverage reports at [/Users/fabriziocucci/git/shields/coverage/services] …
```

Fix service coverage script and linting

---

service-tests/runner/cli.js

According to the [Mozilla documentation about regular expressions](https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions), the special character `\w` is equivalent to `[A-Za-z0-9_]`, which does not include the hype charachter (i.e. '-'). This cause the matching of services containing an hype fail (e.g. 'maven-central').
~Also, both starting character (i.e. '[') and ending character (i.e. ']') have been enforced in the regular expression.~
Another option (probably less readable) could be ~`/^\[([\w\-]+)\]$/`~ `/\[([\w\-]+)\]/`.
This has been reported by @paulmelnikow [here](https://github.com/badges/shields/pull/957#issuecomment-298206267).

Fix regexp used for matching services in pull requests

---

server.js
service-tests/discord.js
try.html

Adds a badge for Discord, along with a test.
For reference, their official badge looks like this:

Add [Discord] badge

---

server.js
service-tests/github.js

Currently they 404 if they contain a / (such as stable/v1.0.0). I've tested this and it doesn't break any of the other download count badges.

Support [GitHub] releases containing a / in the tag

---

server.js

Otherwise, this creates cryptic error messages in the server logs.
@paulmelnikow Could you review this change, please?

Return when a vendor request fails

---

server.js

I noticed that http://code.perlhacks.com/ wasn't working very well. This small change fixes it.

MetaCPAN API v0 has been switched off. Change to use v1.

---

service-tests/README.md

Service tests guideline uses out-of-date constructor of ServiceTester.

Up-to-date ServiceTester's constructor in Service tests example

---

server.js
service-tests/gratipay.js
try.html

See https://github.com/gratipay/grtp.co/issues/163.
This PR updates "tips" to "receives" on the Gratipay shields to better reflect recent terminology and creates a new group called "Funding" where related shields can be placed.
- ~~copy changes in `try.html` to `index.html`.~~ supposedly generated from `try.html`.

Update Gratipay shields

---

README.md

<https://semaphoreci.com> is now our primary domain.

Changing 'semaphoreapp.com' to 'semaphoreci.com'

---

package.json
server.js

- Avoid downloading bower packages via git
- Service is well resourced: https://libraries.io/team
- Same service used by https://bower.io/search/
A standard API key with https://libraries.io/ covers 60 requests per minute. Will that be enough for the public server?
Do you see any reason not to use `let`, `const`, template strings, and arrow functions in new code?

Fetch Bower data using libraries.io

---

server.js

Only url of contributors is hard-coded.

fix: contributors for GitHub Enterprise

---

Dockerfile
lib/measure-text.js

Current Docker image computes width using the 'Helvetica-Bold' fallback font from pdfkit, (because Verdana.ttf can't be found). Width computation is not correct when using some non-Latin characters, like привет, which leads to overlapping texts.
Also only svg rendering works, as the imagemagick libs and DejaVu font are not installed.
This pull request fixes both issues by installing the missing libs and adding a `FALLBACK_FONT_PATH` environment variable. If Verdana.ttf can't be loaded, the font file pointed by `FALLBACK_FONT_PATH` will be loaded. In the docker image, `FALLBACK_FONT_PATH` is set to `/usr/share/fonts/ttf-dejavu/DejaVuSans.ttf`.

Fix .png generation and width computation with Docker image

---

server.js
service-tests/github.js
try.html

These badges would be used to show, for example, how many `goto` statements
your project has.

Add [GitHub] search hit counter badge

---

server.js
service-tests/maven-central.js
try.html

On my github project page, I need to be able to display the latest version of each maintenance branch.
This is currently impossible, since maven badge display the latest version without any consideration to branches.
E.g `https://img.shields.io/maven-central/v/org.apache.maven/apache-maven` displays version `v3.5.0`
With this PR you can define the badge as:
`https://img.shields.io/maven-central/v/org.apache.maven/apache-maven/3.3.svg` to display the latest 3.3 version which is currently `v3.3.9`.
This is not a breaking change. The first url will keep working.

[maven-central] Add the ability to filter by version prefix

---

logo/codetally-white.svg
server.js
service-tests/codetally.js
try.html

Looking to add codetally to the shields project.

Added [codetally] to shields project.

---

server.js
service-tests/crates.js

License data was moved to crate versions in rust-lang/crates.io#803. Closes #1059.

Fix [crates] license badge

---

try.html

Hello, this is a quick fix related to the implementation of continuousphp badge https://github.com/badges/shields/pull/1051
The provider are missing in the example link.

fix(continuousphp) link badge example

---

package.json

Refer #1101 
Provide relative path to `_mocha` for `istanbul`
Currently creates errors on windows machines when trying to run a coverage test
closes #1101

Fix Windows coverage errors

---

server.js
service-tests/chrome-web-store.js
try.html

Update 'downloads'->'users' as label,
added `/users/` as option,
kept `/d/` as an option for backwards compatibility,
moved example from 'Downloads'->'Misc' section,
Removed 'total' from badge value (keep it consistent with amo badges).
example old badge: ![](https://img.shields.io/badge/downloads-1k%20total-brightgreen.svg)
example new badge: ![](https://img.shields.io/badge/users-1k-brightgreen.svg)
Closes #1016

[chrome-web-store] Add tests, update labels

---

.travis.yml

Alternate to #1094 for fixing #979.

Fix [Github] rate limits in CI

---

service-tests/runner/cli.js

#1095 fixed the server's use of Github, but the test harness uses it too.
Have tested locally to make sure this still works when `GITHUB_TOKEN` is unset.
Fix #979

Fix rate limiting for test harness's use of Github

---

.travis.yml
package.json
service-tests/runner/cli.js
service-tests/runner/pull-request-services-cli.js

The intended behavior of the bracketed **[github]**, **[bower]**, **[discord]** service names in the pull request title is to trigger the designated service tests. That way, affected services can be proven working during code review, without needing to run tests on a dev machine, nor running all the slow (and flaky) service tests.
Example pull request titles:
- [Travis] Fix timeout issues
- [Travis Sonar] Support user token authentication
- [CRAN CPAN CTAN] Add test coverage
The observed behavior is that, whenever bracketed service names are provided, _all_ of the service tests run.
This is due to a Mocha limitation, which is that exclusive tests (`it.only` and `describe.only`) can only be applied synchronously. In other words, if we try to fetch the PR title and then add exclusive tests …

In PR's, exclusively run the designated service tests e.g. [cran discord]

---

lib/text-formatters.js
lib/text-formatters.spec.js
server.js
service-tests/conda.js

This changeset audits all the badges with test coverage, looking for badges which assign `badgeData.text[0]`. The right hand of those assignments are replaced with a function which takes the query data `?label=` into account.

Always allow overriding the label [hexpm cran conda]

---

INSTALL.md

The link to the colorscheme.json was broken.
This will fix it 👍

Fix colorscheme link

---

lib/github-auth.js
lib/github-provider.js
lib/lru-cache.js
lib/nexus-version.js
lib/npm-provider.js
lib/php-version.js
lib/regular-update.js
lib/result-sender.js
lib/suggest.js
lib/version.js
service-tests/bower.js
service-tests/codecov.js

Clean up some helpers

---

.travis.yml

With this patch, the service tests run in a separate Travis job. That makes it easy to see whether a PR failure is resulting from unit tests/lint failures, or service tests, which are inherently flakier.
By running these in a single build stage, they will both run, even if the unit tests + lint fail. This is good, because it's helpful to see the result of a failed integration test, even when there's a lint or unit test failure.
I'm hoping this will appear as two separate jobs in Github… let's see!

Run service tests in a separate Travis job

---

service-tests/runner/pull-request-services-cli.js

Use the endpoint on img.shields.io added in #1114 to fetch the PR title.
This sidesteps the authentication requirement, and helps with #979 – except for PRs that need to run the Github service tests, which will need a separate solution.
~~#1114 hasn't been deployed, so don't merge yet.~~
Update: It's now been deployed, so this is good to go.

Get pull request metadata from shields.io

---

lib/github-provider.js
server.js
service-tests/github.js
try.html

URI : `github/release-date/:user/:repo/all.svg`
Actually, there has URI for *release version* badge like that -
[/github/release/Cockatrice/Cockatrice.svg](https://img.shields.io/github/release/Cockatrice/Cockatrice.svg) `full release`
[/github/release/Cockatrice/Cockatrice/all.svg](https://img.shields.io/github/release/Cockatrice/Cockatrice/all.svg) `included pre-release`
So, for consistency, I've done *release date* like that - 
[/github/release-date/Cockatrice/Cockatrice.svg](https://img.shields.io/github/release-date/Cockatrice/Cockatrice.svg) `full release` (Previously Merged #1122)
[/github/release-date/Cockatrice/Cockatrice/all.svg](https://img.shields.io/github/release-date/Cockatrice/Cockatrice/all.svg) `included pre-release` (This PR) …

[GitHub] badge for (pre-)release date

---

try.html

I think the link is not prefixed by `https://img.shield.io` because of double inverted comma `"`
[Sorry, I made that mistake #1096 ]
At `makefie`
https://github.com/badges/shields/blob/2d157b39281c692441b75e4325631b633af5072a/Makefile#L17-L18

Broken Discord Link at Button

---

.istanbul.yml

Also, include `lib/suggest.js` which is part of the server, and rename `vendor` to `service-tests` to match the names the files got when they were merged

Exclude tests from coverage

---

templates/flat-square-template.svg
templates/flat-template.svg
templates/plastic-template.svg
templates/social-template.svg

Fixes #746 
Fixes #848 
Works by making the font-size `110px` instead of `11px` so the browser doesnt enforce the minimum font size and then scales the text down to 10%.
Also fixes the padding issue on Firefox
Tested on the following:
Browser | Version | Status
:-- | :-- | :--:
Chrome | 61.0 | working
Firefox | 56.0 | working
Edge | 25 | working
IE | 11 | working
Mobile Safari | 9.3 | working

Fix enlarged text when min-font-size is enabled

---

server.js
service-tests/discord.js

Implements #981.
The Discord API occasionally returns Cloudflare HTML errors or invalid JSON, so in those cases it will fallback to the standard `'inaccessible'` message. Some of the returned errors have uppercase letters, so `toLowerCase()` is used to stay consistent with the rest of shields.

Attempt to show [Discord]-provided error message

---

package.json

When debugging, it's often useful to run just one or two tests. With this change, it's possible to do that.
In this example, only the first and third tests will run:
```js
t.create('gets the package version of left-pad')
.get('/v/left-pad.json')
.only()
.expectJSONTypes(Joi.object().keys({ name: 'npm', value: isSemver }));
t.create('gets the package version of @cycle/core')
.get('/v/@cycle/core.json')
.expectJSONTypes(Joi.object().keys({ name: 'npm', value: isSemver }));
t.create('gets the tagged package version of npm')
.get('/v/npm/next.json')
.only()
.expectJSONTypes(Joi.object().keys({ name: 'npm@next', value: isSemver }));
```

Upgrade IcedFrisby to version supporting only()

---

app.json

This will allow us to create a [review app](https://devcenter.heroku.com/articles/github-integration-review-apps) for a pull request. A review app is a transient deploy of Shields with a unique URI. We can use it to interactively test new PRs without needing to run the branch locally.
Review apps would be especially useful, in conjunction with something like Netlify (#960), to test issues affecting SVG badge rendering on different browsers (#1132).
I created a Heroku app and did a test deploy of Shields, which worked right out of the box!
https://shields-staging.herokuapp.com/try.html

Set up Heroku review apps

---

server.js
service-tests/github.js
try.html

This pull request is related to issue #1139 .
In addition to the main programming language badge discussed there, these commits also add two additional badges making use of the same [languages API endpoint](https://developer.github.com/v3/repos/#list-languages), but parsing the received data slightly differently.
The resulting badges should look similar to the following:
- top language ![top](https://img.shields.io/badge/JavaScript-68.1%25-blue.svg)
- count of languages ![count](https://img.shields.io/badge/languages-3-blue.svg)
- code size in bytes ![bytes](https://img.shields.io/badge/code%20size-547kB-blue.svg)
Hope I have followed the guidelines correctly and looking forward to any review comments and feedback! :thumbsup:
Cheers,
Pyves

[GitHub] Top language, languages count and code size badges

---

server.js
service-tests/jetbrains.js

It should be look like:
I don't have a node.js local environment. If test fail please do tell me.

[JetBrains] Plugin version badge

---

try.html

This adds documentation for
- combining several custom parameters for one badge
- needed url-encoding
I went with a different link than you suggested.
My motivation to do so is that w3school provides more information and most likely never change.
Your proposal is more practical and might help quicker - [the tool](https://meyerweb.com/eric/tools/dencoder/) might not be available in the future though.
Other ideas?
Just saw your other link to https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding, which one do we prefer?
(fixes https://github.com/badges/shields/issues/1170)

expand documenation

---

try.html

use `shields.io` for the github badge at bottom of page instead of `ghbtns.com`
change from `<a href='...'><img src='...'>` -> `<object data='...?link=...'>` for the social badges at the bottom of the page,
I didn't change any of the examples though not sure if they should be `img` or `object`?
_note: this slightly relies on #1172 being merged for the links to function correctly without adding a second `&link=`_

Use shields.io for the fork badge & use objects for social badges

---

server.js
service-tests/README.md
service-tests/dotnetstatus.js
service-tests/github.js
service-tests/gratipay.js
service-tests/helpers/validators.js
service-tests/hexpm.js
service-tests/wordpress.js

This is a follow up pull request, related to some discussions in #1175.
It covers the following aspects:
* extended the usage of the `isMetric` and `isMetricOverTimePeriod` validators where possible.
* removed calls to `Joi.equal` for bare string literals. The service-test documentation was also updated accordingly.
* fixed some Wordpress tests. A couple of tests for plugins were actually using a theme project instead. The mistake became apparent when switching from a catch all `Joi.string` to a more specific metric validator.
Cheers,
Pyves

[dotnetstatus github gratipay hexpm wordpress] General test improvements

---

lib/text-formatters.js
lib/text-formatters.spec.js
server.js
service-tests/helpers/validators.js

This is another follow up pull request, related to some discussions in #1177.
Brief outline of the problem, for people who haven't read the previous comments. The `starRating` method was previously displaying stars floored to the nearest integer. If 4.99 was passed in as an argument, it would display ★★★★☆. Even if the value was rounded before passing it as an argument (this was done for the Chrome badges), values such as 4.49 would be brought down to ★★★★☆, which seems rough.
This pull request attempts to solve the problem by making use of three additional UTF-8 characters. Badges will now display ratings such as the following:
* ★★★¼☆
* ★★★★½
* ★★¾☆☆
* ...
Again, lacking UTF-8 characters such as half stars is not ideal, but this is a trade-off between having a badge that looks perfect …

[amo chrome-web-store wordpress] Enhanced star display

---

templates/flat-square-template.svg
templates/flat-template.svg
templates/plastic-template.svg
templates/social-template.svg

Relates to:
#852 
#598 
closes #1079 
Add link support to the following badges:
- flat
- flat-square
- plastic
Adjust social badge
- if only 1 link supplied the whole badge will use that link
- only use hover effects if badge contains a link
- remove link if no link specified (currently links to `undefined`)
For all badges if only 1 link is supplied the whole badge will use that link ~~(currently no way to manually specify a second link)~~ you can specify the second link using `link=//firstlink.com&link=//secondlink.com`
Also the only way i know of that a badge will show the links is if it is included via:
`<object data="linktobadge.svg"/>`

Add link support for all badges

---

doc/TUTORIAL.md
package.json

- `make setup` (i.e. `make`) in the dev tutorial seems an unnecessary step. When I open try.html without running that first, badges load from my local server.

Add standard npm start script + rm unnecessary make step

---

README.md
server.js
service-tests/github.js

Now "good first issue" badges in README works properly.

On [Github] issues badge, add quotes around multi-word labels

---

server.js
service-tests/jenkins.js
try.html

Closes #622 
Added simple badge for Jenkins plugins: shows latest version published to Jenkins' repository (fetched from: <https://updates.jenkins.io/update-center.actual.json>).
This uses the URL format: `/jenkins/plugin/v/:pluginId.:format`
Created service-test cases and added under Version in `try.html`.
This is my first contribution here, so let me know if I need to change something.

[Jenkins] Support for Jenkins plugin version

---

lib/text-formatters.js
lib/text-formatters.spec.js

This pull request simply adds missing unit tests for the text formatter functions.
As a side note, I noticed something that may not be intended behaviour when writing the tests. The text formatter `metric` formats values such as 999998 to '1000k', because the value is rounded. Shouldn't this instead be formatted as '1M'? If so, I'm happy tweak the tests and the implementation to reflect this.
Cheers,
Pyves

Better test coverage of text formatters

---

service-tests/bower.js

- Fix failing test
- Tidy up test titles (no need to repeat what is in the assertion)
```
3) Bower
custom label for pre version. eg. pre verison|v0.2.5-alpha-rc-pre
[ GET http://localhost:1111/bower/vpre/bootstrap.json?label="pre verison" ]:
ValidationError: child "value" fails because ["value" with value "v4.0.0-beta.2" fails to match the required pattern: /^v\d+(\.\d+)?(\.\d+)?(-?\w)+?$/]
```

Fix [Bower] service test

---

server.js
service-tests/github.js
service-tests/helpers/validators.js

- `isMetric` tests must be > 0 to pass.
- Fix downloads badge bug introduced in #1140. (So much for [being clever](https://github.com/badges/shields/pull/1140#discussion_r143544396)!)
- Fix 1 week activity badge by returning the previous week instead of the current week.

Fix downloads and commit activity badges showing zero

---

lib/all-badge-examples.js
server.js
service-tests/eclipse-marketplace.js
try.html

This pull request implements a fifth Eclipse Marketplace badge, which displays the "date" when the plugin was last updated on the marketplace. For instance:
Cheers,
Pyves

[eclipse-marketplace] New last updated Eclipse badge

---

lib/version.js
lib/version.spec.js

Currently badge for latest GitHub tag does not support tags with prefix other than `v`. For projects with such custom prefix (https://github.com/mrdoob/three.js - "r" prefix, https://github.com/square/picasso - "picasso-parent-" prefix) we get "tag | none". This change solves this problem.

Latest tag with any prefix

---

package.json

- Dangerous semver range (>) in engines.node
https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

Fix Herkou staging deploy

---

server.js

Support showing PR's & Issues when searching for specific label containing spaces:
Example from README.md:
Currently: ![](https://img.shields.io/github/issues/badges/shields/good%20first%20issue.svg)
Should Be: ![](https://img.shields.io/badge/"good%20first%20issue"%20issues-52%20open-yellow.svg)

[github] Issues/PR support labels with spaces

---

server.js

This reverts #1240, which introduced this issue:
http://localhost:8080/github/issues-raw/badges/shields.json
0d1e4c0 (merge of #1240)
```
{
name: "open undefined issues",
value: "0"
}
```
ad4a8b4 (previous commit)
```
{
name: "open issues",
value: "114"
}
```
I believe the bug was already fixed in #1135.

[github] Revert "github issue/pr support labels with spaces (#1240)"

---

server.js

Hello,
Quite a few badges were ignoring the override label set by the user (using `?label=healthinesses` in the URL for instance), and were just imposing their own value with calls such as `badgeData.text[0] = 'format';`. Admittedly, some of the badges submitted in my previous pull requests were also misbehaving like this! :sweat_smile:
This piece of work makes sure preference is given to the user defined value if any, by adding missing calls to `getLabel` when the value of `badgeData.text[0]` is reassigned.
Everything seems to still pass locally, nevertheless not sure what to put in the pull request title as the list of service tests to run would probably be a bit too long.
Cheers,
Pyves

Consistent overriding of labels set by the user

---

lib/github-auth.js

This fix #1243, a merge error introduced in #1118.
This line went out:
```
const baseUrl = process.env.BASE_URL || 'https://img.shields.io';
```
And this one went in:
```
const baseUrl = process.env.BASE_URL || 'https://shields.io';
```

Fix Github OAuth error again

---

lib/all-badge-examples.js
server.js
service-tests/codeclimate.js

One think to note: unlike the previous CC badges, the new API uses badge tokens associated with repos to retrieve SVG badges for users (as opposed to just the repo name). As a result, the new badges have to first make a request to the CC API to get the token associated with the repo, then make another request to get information regarding the badge. Also due to this, it was difficult to write tests that test for invalid response headers. Everything else should be covered though.

Added support for new Code Climate scores

---

frontend/fragments/try-footer.html
frontend/fragments/try-header.html

Closes #1206 
_IMO it looks a little strange, but makes sense to display it the real size_
Added `social` & `for-the-badge` style to badge creation dropdown list
& close `<option>` tags

Update Homepage - Styles

---

spec/SPECIFICATION.md

Super minor fix for the docs. "Open Sans" has a space in it, just making that consistent.

Spec: Fix "Open Sans" space typo

---

frontend/fragments/try-footer.html

Logo wasn't matching the used parameter.

fix "flat-square" example badge

---

lib/all-badge-examples.js
server.js
service-tests/sonarqube.js

Update of #931 
Closes #877 
The depreciated api example does not seem to work, I suspect the project no longer exist.
If anyone has a badge which we could use that uses the old api for the example/tests would be great!
to-do's
_currently failing due to no tests_

[sonar] support new SonarQube api

---

lib/color-formatters.js
lib/color-formatters.spec.js
lib/text-formatters.js
lib/text-formatters.spec.js
server.js
service-tests/nexus.js

Hello,
This is a pull request related to issue #1181. It aims at providing greater consistency for badges related to versions. It's a slightly ambitious pull request, I'll try to give a clear outline of what was done:
- the `version` function in `color-formatters` was previously returning the colour of the badge, but also its text with a leading _v_. It was broken down into two separate functions and the text formatting part was moved to `text-formatters`, where it really belongs.
- unit tests were added for these two functions in `color-formatters.spec` and `text-formatters.spec`, using Sazerac.
- as discussed in #1181, the leading _v_ was omitted  for _xxxx-yy-zz_ date patterns. Any future exceptions can easily be added to the `ignoredVersionPatterns` pattern.
- the badge colour was …

Consistent version formatting

---

app.json
doc/self-hosting.md
lib/server-config.js
package.json
server.js
shields.example.env

Redirect the root only when configured

---

lib/all-badge-examples.js
lib/npm-badge-helpers.js
lib/npm-provider.js
server.js
service-tests/node.js
service-tests/npm.js

there are two types of custom npm registries:
* public: due to geographical or maybe political reasons https://registry.npm.taobao.org/—essentially copy of https://registry.npmjs.org/
* private: due to legal requirements (my case) or redundancy reasoning—either npm enterprise or sinopia
affected endpoints:
* _npm node version integration_ now supports `/npm/https/registry.npm.taobao.org/v/express.svg`:
```diff
-/^\/npm\/v\/(?:@([^/]+))?\/?([^/]*)\/?([^/]*)\.(svg|png|gif|jpg|json)$/
+/^\/npm(?:\/(http(?:s)?)\/([^/]+))?\/v\/(?:@([^/]+))?\/?([^/]*)\/?([^/]*)\.(svg|png|gif|jpg|json)$/
```
* _npm license integration_ now supports `/npm/https/registry.npm.taobao.org/l/express.svg`:
```diff
-/^\/npm\/l\/(?:@([^/]+)\/)?([^/]+)\.(svg|png|gif|jpg|json)$/ …
```

[npm node] support for custom npm registry

---

lib/make-badge.js
lib/make-badge.spec.js
templates/for-the-badge-template.svg

Closes #1280 
was previously trying to convert any numbers to uppercase,
will now convert the label to a string and then to uppercase.
Also removed `.toUpperCase()` from the template as it shouldn't be needed.
Edit: Updated title as it was breaking the tests

For-the-badge | Convert labels to string then uppercase

---

doc/self-hosting.md
lib/server-config.js
lib/suggest.js
server.js

- Support single-server testing and a local dev server (#1273) that is on a different port from the shields server
- Refactor config schema
With this change, the suggestions work locally in #1273.

Allow configuring allowed CORS origins for suggest

---

package-lock.json
package.json

For parshap/check-node-version#18.
Added < 9 to `server-depcheck` for #1290.

Upgrade check-node-version and print error in Node 9

---

service-tests/helpers/validators.js
service-tests/pypi.js

This will create a merge conflict with #1286. I think it makes more sense to review this one ahead of #1286 so I can rebase the changes in 7c5937d onto this, rather than the other way around.
Suggestions for a suitable example to use for the missing `format (egg)` test welcome.

[pypi] add test suite for PyPi service

---

lib/make-badge.js

c.f. https://github.com/badges/shields/pull/1167#discussion_r145313407

Use template strings in make-badge

---

lib/make-badge.js
lib/make-badge.spec.js

Hello there,
This pull request follows up discussions in #358.
A quick look at shields.io's homepage shows that a lot of badges share the same key (left hand side of the badge). Words such as "downloads", "coverage", "build", "license" keep coming over and over again. Even for badges with a unique key (for instance "eclipse marketplace"), there may be many requests for the same badge type but for different projects within a period of time. The text width of these strings is therefore computed redundantly, which has a performance hit on badge creation time.
The proposed solution is to insert a cache layer, so that a given string width is only computed once. I used our existing `lru-cache` implementation.
Obviously, it would be interesting to benchmark this in a production-like environment. …

Optimisation of makeBadge key width computation

---

README.md

- fixed link to github contributors from Open Collective template
- adjusted brackets around [contribute] to match style for backers and sponsors
(@asood123 you might want to double check your template, this is the second repo with a broken link on the nice contributors gallery)

readme: fix link

---

lib/all-badge-examples.js
lib/pypi-helpers.js
lib/pypi-helpers.spec.js
server.js
service-tests/pypi.js

This PR adds the django version support feature suggested in issue #1018
Having worked on this issue, I note that:
* There don't seem to be tests for the existing PyPi badges
* All the PyPi badges are defined in one big function (I am aware this PR makes this situation worse, not better)
As a further piece of work, I would also be interested in adding more tests to support refactoring this into a number of smaller functions and also having a go at some of that refactoring work. Would you be open to receiving some further PRs?
Closes #1018

[pypi] Add badge for django version support

---

lib/github-auth.js

c.f. https://github.com/badges/shields/issues/1314#issuecomment-348803814

Github admin endpoint: use basic auth password instead of username

---

README.md
doc/self-hosting.md

Re https://github.com/badges/shields/issues/1314#issuecomment-348803814

Update docs re production builds

---

server.js
service-tests/bitbucket.js
service-tests/github.js
service-tests/helpers/validators.js

* Add test suite for BitBucket service integration
* Present BitBucket issues as a metric (for consistency with BitBucket PR endpoint and GitHub endpoints)
* Factor out a shared regex
* Fail cleanly if count is `undefined`
i.e: do this: ![invalid](https://user-images.githubusercontent.com/6025893/33528467-b8d5f5a2-d858-11e7-9e9a-f9139f3769e3.png)
not this: ![undefined_open](https://user-images.githubusercontent.com/6025893/33528470-c5af2712-d858-11e7-98b1-6e289613cd09.png)

[BitBucket GitHub] fixes and tests for BitBucket service integration

---

lib/all-badge-examples.js
server.js
service-tests/discourse.js

References https://github.com/badges/shields/issues/1325
API:
`/discourse/SCHEME/DISCOURSE_HOST/topics.svg`
`/discourse/SCHEME/DISCOURSE_HOST/posts.svg`
`/discourse/SCHEME/DISCOURSE_HOST/users.svg`
`/discourse/SCHEME/DISCOURSE_HOST/likes.svg`
`/discourse/SCHEME/DISCOURSE_HOST/status.svg`
Preview:

Add [Discourse] status/stats shield

---

templates/social-template.svg

Removes 4px from the width of the svg element on the social style badge
Current:
This PR:

remove extra whitespace from social badge

---

frontend/components/dynamic-badge-maker.js

little frontend change
in conformity with "begin to standardize on URL, not URI" (https://github.com/badges/shields/pull/1322)
ordinary users are confused by the term `uri`

uri --> url

---

server.js

As @platan correctly notes in https://github.com/badges/shields/pull/1315#discussion_r155084514 we should check the status code first before attempting to parse the response body.

[BitBucket] check status code before parsing body

---

.circleci/config.yml
.circleci/images/README.md
.circleci/images/node-6/Dockerfile
.circleci/images/node-8/Dockerfile
.circleci/images/prepare-container.sh
README.md
package.json
service-tests/runner/infer-pull-request.js
service-tests/runner/infer-pull-request.spec.js
service-tests/runner/pull-request-services-cli.js

I don’t like that our build goes red on master all the time due to flaky service tests. I thought I’d look into other CI services that would make it possible to run the scheduled tests nightly without causing those messages to show up.
CircleCI, Heroku CI, and Codeship were obvious choices. Heroku CI wasn’t free and I didn’t have any experience with Codeship, so I looked into CircleCI. I’ve used their 1.0 system a lot though this was my first time on their 2.0 system. As with earlier versions, they’ve put a lot of work into making the build fast – perhaps more than any other CI system I’ve seen.
I had such good results, my goal shifted from scheduled daily builds (that don’t litter our commit history with red builds) to improving the CI experience as a whole.
This change made a big …

Set up CircleCI (including [github] tests)

---

frontend/components/footer.js

Closes #1334 
Adds spacing between the badges in the footer,
Current:
This PR:

add spacing between badges in footer

---

server.js
service-tests/bountysource.js

* Add service tests for bountysource badge
* switch to use ES6 style variable declarations
* Fail cleanly on bad responses.
i.e:
don't do this ![bad](https://user-images.githubusercontent.com/6025893/33736687-6f5fa478-db8b-11e7-929e-0a9c50b931f3.png)
do this ![good](https://user-images.githubusercontent.com/6025893/33736696-77ccb218-db8b-11e7-96ab-cf70d6d88f77.png)
or this ![good2](https://user-images.githubusercontent.com/6025893/33736702-7d2ca470-db8b-11e7-9736-27171db70cae.png)
I suspect there will be several more service badges with this class of error. I'll continue to look for them as I add tests.
@PyvesB - apologies again for our mixup yesterday. If you're in the mood to look at a PR please feel free to provide feedback. I'm sure your comments will be helpful :)

[bountysource] tests and fixes for bountysource service integration

---

lib/server-config.js

As argued for in
https://github.com/badges/shields/issues/1314#issuecomment-350564524.
It populates large quantities of text in the logs, where I wish to only
see errors.

Default to not logging GitHub token debugging

---

lib/badge-data.js
lib/badge-data.spec.js

Hello there,
Nothing much going on here. I noticed that we were checking for string prefixes in a slightly odd way in _badge-data.js_, probably due to the lack of ECMA Script 6 at the time. Switched to using `startsWith` instead and reworked a few tests around the `prependPrefix` function.
Cheers,
Pyves

Removal of hasPrefix function in badge-data.js

---

server.js
service-tests/codeclimate.js

Hello there,
This pull request takes care of issue #1329. 
I had a closer look at the API documentation and managed to find a way to retrieve the now missing code coverage score in a different way. As before, the code is making a call to the [get repository](https://developer.codeclimate.com/#get-repository) endpoint, but instead of firing a second call to retrieve the headers of Code Climate's own badges, it's now calling the [get snapshot](https://developer.codeclimate.com/#get-snapshot) or [get test coverage reports](https://developer.codeclimate.com/#get-test-coverage-reports) endpoint to get the scores. In essence the coverage and maintainability badges are now generated only via API body responses rather than trying to do pattern matching on returned headers, which should hopefully …

[CodeClimate] Fix coverage and maintainability score badges

---

package-lock.json

`package-lock.json` wasn't updated in https://github.com/badges/shields/pull/1367. This PR updates it to version from `package.json`

Prettier updated to 1.9.2 in package-lock

---

dangerfile.js

Avoid issuing [this warning](https://github.com/badges/shields/pull/1374#issuecomment-351957752):
This PR modified helper functions in lib/ but not accompanying tests. That's okay so long as it's refactoring existing code.
When only the badge examples have been edited.

Danger: badge examples are not lib/ + wordsmith

---

service-tests/bower.js

test was previously testing custom labels with `?label="my licence"` including the quote marks which is causing tests to fail.
Have updated to exclude the quote marks.
Though not sure why this is suddenly becoming an issue, as it previously has passed with quote marks.
And when i test it on the staging server or shields.io i get the [correct response](https://img.shields.io/bower/l/bootstrap.json?label=%22my%20licence%22): ![](https://img.shields.io/bower/l/bootstrap.svg?label=%22my%20licence%22)
But best to remove the quote marks as they are not needed.
```cmd
1) Bower
custom label for licence
[ GET http://localhost:1111/bower/l/bootstrap.json?label="my licence" ]:
AssertionError: expected { name: '"my licence"', value: 'MIT' } to deeply equal { name: 'my licence', value: 'MIT' }
+ …
```

Fix [bower] service tests

---

lib/project/critical-services.yml

I have a branch going to automatically generate stats on which services have tests, and make a line chart over time. I'm having a lot of fun with that so I'll keep at it.
Meanwhile, here is my list of critical services, for #1358.

Add list of critical services

---

frontend/components/badge-examples.js
frontend/components/suggestion-and-search.js
frontend/lib/filter-examples.js
frontend/lib/prepare-examples.js
pages/index.js
static/main.css

Alternative: Improve search performance

---

lib/suggest.js
service-tests/suggest.js

Fix tests for [suggest] endpoint

---

server.js
service-tests/twitter.js

Add test for twitter,
Add error handling messages to right hand side of badge: `invalid`, `inaccessible`, `invalid user`

Add [twitter] tests

---

lib/nuget-provider.js
lib/php-version.js
lib/regular-update.js
server.js

For #1359
- DRY getPhpReleases()
- Pass named options to regularUpdate
- Add json option
- php-version: Move helpers before functions, and move exports to end

[travis php-eye jenkins] Use github auth in php-v badges

---

server.js

[braumeister.org](http://braumeister.org) is now part of Homebrew and available at [formulae.brew.sh](http://formulae.brew.sh).
formulae.brew.sh is the new canonical URL and braumeister.org is still available, but may vanish someday.

Update URL for Homebrew formula versions

---

.circleci/config.yml

These should be switched over to Node 9, but disabling them in Node 6 should get the build back to green.

Disable Node 6 tests on node-8 branch

---

server.js
service-tests/hackage.js

Note there is no check for the 'not found' case on the `hackage-deps` endpoint.
* A package where all the dependencies are up-to-date returns an empty feed: http://packdeps.haskellers.com/feed/AbortT-mtl
* ..and a package that doesn't exist returns an empty feed: http://packdeps.haskellers.com/feed/not-a-package
In order to add a not found case, we'd have to add a second API call so that the `hackage-deps` endpoint calls https://hackage.haskell.org/ first to check if the package exists and then makes a subsequent call to http://packdeps.haskellers.com if it does. Is it worth adding that additional overhead to cover the not found case?

add tests for [hackage]

---

.eslintrc-preferred.yml
lib/badge-cli.spec.js
lib/badge-data.spec.js
lib/lru-cache.spec.js
lib/make-badge.spec.js
lib/nodeify-sync.spec.js
lib/register-chai-plugins.spec.js
lib/request-handler.spec.js
lib/svg-badge-parser.spec.js
lib/svg-to-img.spec.js
lib/text-measurer.spec.js
package-lock.json
package.json
server.spec.js
service-tests/node.js

This idea has come up a couple times before in PRs. This updates everything except the LRU cache asserts, which are in conflict with #1418.
@PyvesB was it you who'd mentioned it?

Adopt Chai for assertions

---

package.json

We can't upgrade Joi until we upgrade to Node 8.

Add Joi to greenkeeper ignore

---

lib/unhandled-rejection.spec.js
service-tests/runner/cli.js

I added this while doing some error-handling work on the `node-8` branch, and it seems like it will not hurt anything to add it to master as well.

Log + fail tests on unhandled promise rejections

---

services/appveyor.js
services/base.js
services/base.spec.js

- Adjust test grouping
- Rename data -> queryParams, text -> message
In the process of adding and testing some error-handling code to the base services, I factored out a couple methods. The diff is a bit gnarly. I think those changes will be easier to read if this is reviewed separately.

BaseService: Factor out a couple methods

---

service-tests/codecov.js
service-tests/coveralls.js
service-tests/helpers/validators.js
service-tests/sonarqube.js
service-tests/uptimerobot.js

For #1359
This failure from https://circleci.com/gh/badges/shields/1411?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
26) Uptime Robot
Uptime Robot: Percentage (valid)
[ GET http://localhost:1111/uptimerobot/ratio/m778918918-3e92c097147760ee39d02d36.json ]:
ValidationError: child "value" fails because ["value" with value "99.992%" fails to match the required pattern: /^[0-9]+%$/]
at Object.exports.process (node_modules/joi/lib/errors.js:190:19)
at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:669:31)
at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:139:23)
at Object.pathMatch.matchJSONTypes (node_modules/icedfrisby/lib/pathMatch.js:303:9)
at …
```

[UptimeRobot] Test with regex that accepts decimals

---

server.js
service-tests/json.js

Closes #1442 
All dynamic badges are currently showing `brightgreen` on right hand side even on error.
This PR causes the right hand side to be `red` if no uri specified or `lightgrey` on other errors.
This also adds an error if the jsonpath/`?query` returns an empty array `no result`
**Notes:**
Was failing due to trying to set `colorB = 'lightgrey'` instead of `colorB = '#9f9f9f'`
Also tried using `colorscheme = 'lightgrey'` but that didn't work due to the users color choice always taking priority and the user needing to specify `?colorB=10ADED` for any color other than brightgreen

[badge/dynamic/json] fix colorscheme on error

---

service-tests/runner/pull-request-services-cli.js

Rather than depend on Shields production, use the GitHub auth info from CI. It's disorienting to have our own CI go down when production is down. It also makes it harder to review PRs when there are ops issues.

For service tests, get PR metadata from Github API

---

lib/error-helper.js
lib/error-helper.spec.js
server.js
service-tests/docker.js

* Add tests for docker(hub) badges
* Add or standardise error handling (as applicable)
Note that I haven't been able to find a test case for the library case on the build status endpoint. Everything I've tried doesn't return a useful output e.g:
https://registry.hub.docker.com/v2/repositories/library/ubuntu/buildhistory/
https://registry.hub.docker.com/v2/repositories/library/nginx/buildhistory/
https://registry.hub.docker.com/v2/repositories/library/python/buildhistory/
https://registry.hub.docker.com/v2/repositories/library/elixir/buildhistory/
https://registry.hub.docker.com/v2/repositories/library/alpine/buildhistory/
I wonder if anyone can provide an example?

service tests for [docker]

---

lib/badge-data.js
services/base.js
services/base.spec.js

Based on feedback in #1425.
@platan @RedSparr0w

BaseService: make serviceData and badgeData explicit and declarative

---

frontend/components/footer.js
lib/all-badge-examples.js
lib/badge-data.js

Closes #1452 
Logos are currently not showing on social style badges where a logo should be showing by default.
Not sure if i should also revert https://github.com/badges/shields/commit/61fa22b7e4d7986e94b826e39db95f1f6910c2a7 incase of any future prolems it should help the problem be noticed earlier.
Unless tests are also added for logos.
**Notes:**
Was broken due to `overrides.logo` being set to `undefined` [earlier in the code](https://github.com/badges/shields/blob/master/lib/badge-data.js#L98).
Which in turn means `'logo' in overrides` returns `true` as it is defined as `undefined`.

Fix logo showing by default on social badges

---

lib/all-badge-examples.js
lib/color-formatters.js
lib/color-formatters.spec.js
server.js
service-tests/codeclimate.js

Hello there,
This pull request is related to discussions in #1368 and #1329. @RedSparr0w would probably be the ideal person to review this as he has been involved in the discussions and the previous pull request. 😉 
We should now have five functional Code Climate badges, with tests:
* `/codeclimate/c`: coverage score (letter).
* `/codeclimate/coverage`: coverage percentage.
* `/codeclimate`: technical debt percentage (related to the maintainability of the project).
* `/codeclimate/maintainability`:  maintainability score (letter).
* `/codeclimate/issues`:  number of issues.
Nevertheless, I'm still unhappy with the current state of our code for several reasons:
- the distinction between `/codeclimate/coverage` and `/codeclimate/c` is confusing for both users and developers. One is a …

[CodeClimate] Fix remaining badges

---

service-tests/codeclimate.js

Fixes https://github.com/badges/shields/pull/1387#issuecomment-362390066 
Looks like the validator changed in https://github.com/badges/shields/commit/6b26affb5ff916fc4c1348f36496b5cf0149c4d5 from `isPercentage` -> `isIntegerPercentage`

[codeclimate] update tests

---

server.js
service-tests/cocoapods.js

* Add tests for CocoaPods Endpoints
Bug fixes:
* Call `metrics.cocoapods.org` API endpoints over HTTPs
* Show correct left-side badge text on error in version/platform/license badges
* Handle null doc coverage gracefully (i.e: do this ![zerobadge](https://user-images.githubusercontent.com/6025893/35485627-42568c7e-045a-11e8-8dfc-e255c8d9209a.png) not this ![nullbadge](https://user-images.githubusercontent.com/6025893/35485628-485ad0c6-045a-11e8-879c-761dc2b79aab.png) )
* Add handling for 'not found' responses

service tests for [cocoapods]

---

lib/nuget-provider.js
service-tests/chocolatey.js
service-tests/helpers/nuget-fixtures.js
service-tests/helpers/validators.js
service-tests/powershellgallery.js

If you merge #1471 ahead of this, I will rebase and refactor the 'unexpected' cases to use the abstraction @platan has added there.

[chocolatey powershellgallery] add service tests for NuGet v2 services

---

server.js

Closes #1498
Switch to the `/licenses` endpoint to see if the package exists on the `hackage-deps` badge.
Unrelated: one of the other hackage tests failed due to some trailing whitespace on a version number, so I've also added a fix for that.

[hackage] switch to the `/licenses` endpoint

---

lib/all-badge-examples.js
server.js
service-tests/bitbucket.js

Adding support for Bitbucket Pipelines builds: #1509 . 
The format is the same as for the other Bitbucket badges:
`/bitbucket/pipelines/<user>/<repo>.svg`
and
`/bitbucket/pipelines/<user>/<repo>/<branch>.svg`
The implementation is looking at the last completed build result (ignoring builds that are about to start or in progress). It supports all current Pipelines result states:
- passing
- failing
- error
- stopped
- expired
The tests cover 100% of the added lines.
Let me know what you think, thanks a lot!

[Bitbucket] #1509 - Add Bitbucket Pipelines service

---

server.js
service-tests/hhvm.js

http://hhvm.h4cc.de... -> https://php-eye.com/api/v1/package...

[hhvm] #1499 - update hhvm service

---

lib/make-badge.js
server.spec.js

Our fuzzer found a TypeError triggered by:
`http://localhost:8080/circleci/project/github/RedSparr0w/node-csgo-parser.svg?link=1`
`http://localhost:8080/circleci/project/github/RedSparr0w/node-csgo-parser.svg?link=true`
```
0222045033 Vendor hook error: TypeError: s.replace is not a function
at escapeXml (/home/fuzzstati0n/shields/lib/make-badge.js:71:12)
at Array.map (<anonymous>)
at makeBadge (/home/fuzzstati0n/shields/lib/make-badge.js:157:18)
at data (/home/fuzzstati0n/shields/lib/make-badge.js:174:40)
at sendBadge (/home/fuzzstati0n/shields/lib/request-handler.js:193:23)
at /home/fuzzstati0n/shields/server.js:5961:7
at Request.request [as _callback] (/home/fuzzstati0n/shields/lib/request-handler.js:166:9)
at Request.self.callback …
```

Uncaught TypeError crashes server on numeric or boolean 'link' parameter

---

service-tests/travis.js

Currently one service test of travis fails:
```
1) PHP version from .travis.yml
gets the package version of yii
[ GET http://localhost:1111/travis/php-v/yiisoft/yii.json ]:
AssertionError: expected { name: 'PHP', value: '>= 5.3, HHVM' } to deeply equal { Object (name, value) }
+ expected - actual
{
"name": "PHP"
-  "value": ">= 5.3, HHVM"
+  "value": "5.3 - 7.1, HHVM"
}
```
Version 7.2 was added to https://github.com/yiisoft/yii/blob/master/.travis.yml on Jan 25, 2018. This version is currently the newest version of PHP https://github.com/php/php-src/releases.

[travis] Updated an expected value in a service test of Travis PHP version badge

---

lib/badge-data.js
lib/badge-data.spec.js

currently you need to replace any base64 logos `+` characters with `%2B` in order for the logo to show correctly:
using `+`:
```
data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48c3ZnIHZlcnNpb249IjEuMSIgaWQ9IlRyYWNlIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCIgdmlld0JveD0iMCAwIDIwNSAyMDUiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDIwNSAyMDU7IiB4bWw6c3BhY2U9InByZXNlcnZlIj48c3R5bGUgdHlwZT0idGV4dC9jc3MiPi5zdDB7ZmlsbDojRTY5MzBCO30uc3Qxe2ZpbGw6I0ZFRkRGQzt9LnN0MntmaWxsOiNEQjczMDM7fS5zdDN7ZmlsbDojRjhCNjJCO30uc3Q0e2ZpbGw6I0ZGMDAwMDt9PC9zdHlsZT48cGF0aCBjbGFzcz0ic3QwIiBkPSJNMTUuMywxMDIuNmMtMC43LTQ3LjksNDAuNS04OC4xLDg4LjYtODcuOWM0NSwwLjIsODkuOCwzOC41LDg3LjUsOTIuN2MtMS45LDQ0LjQtMzkuNiw4NC41L …
```

logo data uri encoding

---

lib/all-badge-examples.js
server.js
service-tests/microbadger.js

I noticed that we had one failing MicroBadger test as well as an error badge on our homepage.
Turns out that some API responses now come back with no top-level `DownloadSize` field (for instance [this query](https://api.microbadger.com/v1/images/library/centos)). Our parsing currently throws an exception resulting in the error MicroBadger badge.
This pull request handles things more cleanly with a new "unknown" badge, and fixes the test and homepage example.
@goozler as you submitted the MicroBadger implementation a few months ago, could you please give this a look and see whether we're on the right track here? 😉

[microbadger] Handle no DownloadSize being returned

---

server.js
service-tests/gratipay.js

Gratipay is gone :(
For #1359
This failure from https://circleci.com/gh/badges/shields/1411?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
7) Gratipay
Receiving
[ GET http://localhost:1111/gratipay/Gratipay.json ]:
ValidationError: child "value" fails because ["value" with value "invalid" fails to match the required pattern: /^\$[0-9]+(\.[0-9]{2})?\/week/]
at Object.exports.process (node_modules/joi/lib/errors.js:190:19)
at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:669:31)
at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:139:23)
at Object.pathMatch.matchJSONTypes (node_modules/icedfrisby/lib/pathMatch.js:303:9)
at node_modules/icedfrisby/lib/icedfrisby.js:703:10
at …
```

[Gratipay] Replace with error message

---

README.md

Adds logos to the discord & twitter badges in README.md
The social badge by default does have a logo, but the current live badges exclude the logo on social badges (fixed in #1456)

README.md add logos to badges

---

lib/all-badge-examples.js
server.js
service-tests/snap-ci.js

Hello,
This prepares the work needed to close #1466. There are still discussions around colour in #1449, so I have left out any colour assignments for now. This pull request should therefore probably not be merged until then.
No tests previously existed, so I simply added a "no longer available" test, which will also tick one item from the top table in #1358.
Cheers,
Pyves

[Snap-CI] Replace with error message

---

lib/all-badge-examples.js
server.js
service-tests/cauditor.js

Wait to merge until discussions in #1449 resolved.
Cauditor seems to no longer be a service:
[cauditor.org](http://cauditor.org)
[github](https://github.com/cauditor) - hasn't been updated since 2016

[Cauditor] Replace with error message

---

services/base.js
services/base.spec.js

Fix unit test failures with isValidStyle https://circleci.com/gh/badges/shields/2840
as noted in #1543

node-8 fix isValidStyle test failures

---

frontend/components/dynamic-badge-maker.js
frontend/components/usage.js
frontend/lib/badge-url.js
frontend/lib/badge-url.spec.js
package-lock.json
package.json
server.js
service-tests/json.js
service-tests/xml.js

Continuation of #820
This PR Adds XML support to the dynamic badges.
**Other:**
_added a test for query param specified_
_changed `uri` param to `url` (`uri` still supported)_
_[All examples based on this XML](https://services.addons.mozilla.org/en-US/firefox/api/1.5/addon/707078)_
`?query=` param | badge
:-- | :--
`/addon/name` | ![](https://img.shields.io/:name-IndieGala%20Helper-brightgreen.svg)
`/addon/@id` | ![](https://img.shields.io/:ID-707078-brightgreen.svg)
`//version` | ![](https://img.shields.io/:version-4.5.1-brightgreen.svg)
`/addon/reviews/@num` | ![](https://img.shields.io/:total%20reviews-7-brightgreen.svg)
`//daily_users` | ![](https://img.shields.io/:daily%20users-160-brightgreen.svg)
`?a=b` params | Usage | Example | Example Badge
:--: | :-- | :-- | :--:
`uri` …

User defined XML source badge [dynamic-xml dynamic-json]

---

lib/all-badge-examples.js
lib/deprecated-services.js
lib/deprecation-helpers.js
lib/deprecation-helpers.spec.js
server.js
service-tests/gemnasium.js

As noted in #1523 gemnasium will shut down their service on May 15th.
I'm not suggesting merging this now, but once that happens, this can be merged to replace the badge with an error.
Also refs #1449 - if I need to update based on that I will do :)

[gratipay gemnasium snap-ci cauditor] add deprecation helpers, deprecate gemnasium

---

lib/badge-data.js
lib/badge-data.spec.js

closes #1540 
Replaces all spaces with `+` symbol's (#1527), then removes all remaining whitespace (newlines, tabs etc)

remove whitespace from data URIs

---

lib/deprecation-helpers.spec.js

These tests were failing locally and I suspect it’s because I’m in a different time zone.
@chris48s would you mind giving this a once-over?

Make isDeprecated tests more resilient to time zone

---

server.js
service-tests/dub.js

- add tests
- improve error handling
- switch to https
For the moment I have commented out the test for "total downloads, specific version (valid)" because the endpoint used in this call seems to frequently take more than the 5 second timeout to respond so that test often fails. Is there a way to increase the timeout for one specific test? All the others seem to consistently complete inside the expected time.
Simultaneously, another question that arises here is: does it provide good user experience to have a badge which often takes >5 seconds to render?

service tests for [dub]

---

.eslintignore
README.md
__snapshots__/make-badge.spec.js
lib/make-badge.spec.js
package-lock.json
package.json

These tests should fail if something is accidentally changed that affects the SVG or JSON files. In the case of deliberate changes, we can update the snapshots.
This is my test nerd solution for #1473.

Add snapshot tests for SVG and JSON

---

dangerfile.js

Refs #1553
I've added a couple of simple checks in this PR, but I'm going to hold off on doing anything that reads the diff because I hit a couple of issues with danger.js:
https://github.com/danger/danger-js/issues/531
https://github.com/danger/danger-js/issues/532
I'll have to revisit those checks.

Add some more rules to dangerfile

---

lib/all-badge-examples.js
lib/npm-badge-helpers.js
lib/npm-badge-helpers.spec.js
lib/version.js
lib/version.spec.js
server.js
service-tests/npm.js

Let a package show off its type definitions based on devDependency data in the published npm package.
Close #1252

Add [npm] type definitions badge

---

frontend/lib/prepare-examples.js
frontend/lib/prepare-examples.spec.js
package.json

Searches with regex control characters should not crash

---

server.js
service-tests/json.js
service-tests/xml.js

This change is specifically for CircleCI API but it could occur for others. The problem is CircleCI's API requires the requester to set `Accept: application/json` else it returns plain text and pretty printed json which fails JSON.parse. Adding the header makes CircleCI return expected JSON payload.
CircleCIs API Doc: https://circleci.com/docs/api/v1-reference/#accept-header
This shouldn't affect any existing request it's just including an extra header now.

[dynamic-xml dynamic-json] Set request options for dynamic json badges.

---

CONTRIBUTING.md
README.md

We’ve cleared the backlog of pull requests needing adoption and closed the old ones out, so it seems best to remove this from the contributing guidelines.

We have no more pull requests to adopt

---

services/base.js
services/base.spec.js

Breaking `invokeHandler` into its own function makes it easy to test the error handling, and also to expand the error handling as I've done in this WIP branch: https://github.com/badges/shields/compare/master...paulmelnikow:rewrite-npm-typedefs

Add tests for BaseService + fix hex colors

---

lib/suggest.js

This resolves the following error occurring in production:
```
TypeError: Cannot read property 'slice' of null
/home/m/shields/lib/suggest.js in findSuggestions at line 40:33
const userRepo = url.pathname.slice(1).split('/');
```

Only compute user/repo if suggesting badges for GitHub

---

lib/suggest.js

This resolves the following error occurring in production:
```
TypeError: Cannot read property 'slice' of null
/home/m/shields/lib/suggest.js in twitterPage at line 63:31
const schema = url.protocol.slice(0, -1);
```

Skip Twitter suggestion if URL does not have protocol

---

lib/all-badge-examples.js
services/microbadger/microbadger.tester.js

This pull request should fix the failing MicroBadger tests reported in #1591 (`image size without a specified tag` and `image size without a specified tag and no download size data returned`). If they start failing again in the near future, I suggest we rethink our testing strategy for this service (perhaps looser validation?), but for now, let's give it another try!

[microbadger] Fix tests

---

lib/color-formatters.js
lib/color-formatters.spec.js

This pull request is related to discussions in #1599.
Tests to cover cases where the version is provided as a numerical value were added. I thought of several different ways of tackling the implementation and went with one, but a more experienced Javascript reviewer may have some better ideas. 👍

Number support for version color formatter

---

server.js
services/circleci/circleci.tester.js

This pull request should resolve issue #1608.

[CircleCI] Extended existing try-catch block

---

README.md

Currently we have a "last deployed" badge in README which shows date of the last deployment and it links to https://github.com/badges/shields/commits/gh-pages branch (the `gh-pages` branch contains changes deployed to production). 
This PR replace this badge with a "commits to be deployed" which shows number of commits waiting for deployment to production (number of commits between the `gh-pages` and the `master`) and it links to https://github.com/badges/shields/compare/gh-pages...master with a diff between branches.
Use "View" button to see rendered README (or use this link https://github.com/platan/shields/blob/6dde98d77f9444e00684f4e2c3a85a0e5cb34db1/README.md)
Why this change? I often want to check if some change is already deployed to production. This badge helps in this case. 
What …

Badge with changes waiting for deployment in README

---

lib/make-badge.js
lib/make-badge.spec.js

This pull request addresses issue #1606. We now also have some tests for the `social` badge template!

Capitalization with empty keys

---

server.js
services/codeclimate/codeclimate.tester.js

This pull request should resolve #1607. I believe we were missing a try/catch block for the inner API request. It seems that were are kind of duplicating the same try/catch block twice for this service, but I'm unsure how to handle that in a better way. 😉

[CodeClimate] Added missing try-catch block

---

server.js
services/ansible/ansible.tester.js

This pull request addresses #1624. I managed to write a test that produced a similar error to the one we were seeing in production and consequently strengthened the existing `if` condition. Also switched the `var`s to `const`s while I was at it.

[Ansible] Handle no data responses

---

lib/all-badge-examples.js
lib/deprecated-services.js
server.js
services/dotnetstatus/dotnetstatus.tester.js

This pull request is related to discussions in #1591. It's now been over a month that the tests are failing due to the service being down (see [this issue](https://github.com/jaredcnance/dotnet-status/issues/18)). There is no news from the author, I suggest we deprecate the service.

[DotnetStatus] Service deprecation

---

lib/all-badge-examples.js
lib/all-badge-examples.spec.js
services/base.js
services/index.js

This cleans up the work from #1582, clarifying concerns, removing a bit of duplication, and renaming for clarity.

Minor refactor of examples preparation

---

server.js
services/sourceforge/sourceforge.tester.js

This pull request goes through the following tasks:
- narrowing down the regex to only match what the implementation actually supports. I believe this should fix #1610.
- adding some simple tests, which non existent for this service. This should tick one box of the table in #1358.
- performing a small functional change to remove the `/total` in the badge display for total downloads. In addition to being slightly odd, it was inconsistent with what other badges do for total downloads.
- cleaning up the implementation a bit. Nothing too ambitious, but it should help provide a cleaner starting point for #1573.
Looking forward to feedback! 👍

[SourceForge] Fixes, tests and cleaning up

---

server.js
services/librariesio/librariesio.tester.js
services/test-validators.js

This pull request should close #1621 by adding our usual try/catch block. There weren't any tests for this service, so I implemented a simple test suite (one extra box ticked in #1358! 👍 ) and also got rid of the `var` keyword in favour of more appropriate identifiers.

[librariesio] Missing try/catch block and tests

---

lib/request-handler.js
lib/request-handler.spec.js

closes #1650
currently when using `?maxAge=` the `cache-control` header is set correctly but the `expires` header is always set to the current time.
```text
Cache-Control: max-age=3600
Date: Mon, 16 Apr 2018 21:57:47 GMT
Expires: Mon, 16 Apr 2018 22:57:47 GMT
```
```text
cache-control: max-age=3600
date: Mon, 16 Apr 2018 21:55:33 GMT
expires: Mon, 16 Apr 2018 21:55:33 GMT
```

set expires header corresponding to maxAge

---

lib/all-badge-examples.js
server.js
services/buildkite/buildkite.tester.js

Fixes https://github.com/badges/shields/issues/1261 by providing Buildkite support for Shield.
Usage is:
- `/buildkite/{id}/{name}` for the default Buildkite shield `eg Buildkite | passing`

Add [buildkite] service

---

server.js

We don't need to match the file extension to determine the status.
This should fix #1654 .

[Codeship] fix status checking regexp & add new statuses

---

services/github/github.tester.js

This is a suggested quick fix for the last failure identified in issue #1591
This test is failing because the license on our repo is not recognised as being CC0. If we hit https://api.github.com/repos/badges/shields GH describes our license as:
```
...
"license": {
"key": "other",
"name": "Other",
"spdx_id": null,
"url": null
},
...
```
This PR just switches the test to use an example which GH does identify as CC0 licensed to get the tests passing agiain.
There is a second issue though which is that GH no longer recognises our repo as being CC0 licensed. If we look at https://github.com/badges/shields/blob/master/LICENSE.md there is no banner but if we look at https://github.com/github/gitignore/blob/master/LICENSE there is. This is obviously something in the way GH identifies licenses …

change CC0 example in [github] service tests

---

doc/service-tests.md
server.js

I think we should recommend using `checkErrorResponse` in the documentation. This will help new users in creating a good code from the beginning and should reduce amount of work in code review (https://github.com/badges/shields/pull/1645#discussion_r181862274, https://github.com/badges/shields/pull/1657#discussion_r183265223)

checkErrorResponse documented in service tests

---

lib/all-badge-examples.js
lib/error-helper.js
server.js
services/cdnjs/cdnjs.js

Found some time to get stuck into some refactoring. Lets start small and work up :)

refactor [cdnjs] integration

---

lib/all-badge-examples.js
server.js
services/lgtm/lgtm.tester.js

This PR adds the lgtm.com alerts count for a particular project, using the public-facing API.
Full disclosure, I work at Semmle on lgtm.com.

Add [LGTM] service

---

services/microbadger/microbadger.tester.js

The stability of our MicroBadger service tests has been quite variable lately, due to temporary losses of metadata (in particular the download size) in some of the images we were using.
I opened [an issue](https://github.com/microscaling/microbadger/issues/38) on their service repository, which they promptly resolved by doing a full refresh of their data. I haven't noticed anything unexpected since then.
Consequently, I've rearranged the tests once again, with the hope that we won't have to revisit this again in a few weeks.
* our two"happy"  image size tests use images that haven't changed in a few years, in order to minimise the risk of the data from being lost/taking too long to be refreshed when updated.
* the "unhappy" test where no `DownloadSize` is present in the response is now …

[MicroBadger] Fix tests - new attempt

---

doc/TUTORIAL.md

This is a follow-up to https://github.com/badges/shields/pull/1670
This change contains:
- up-to-date code example from `server.js`
- `checkErrorResponse` function mentioned in tutorial
- static badges as example of errors (https://img.shields.io/docker/automated/,/ubuntu-remix.svg is no longer "invalid")
- up-to-date links to `server.js`

checkErrorResponse documented in the tutorial

---

lib/all-badge-examples.js
server.js
services/lgtm/lgtm.tester.js

We've just launched project grades on lgtm: https://discuss.lgtm.com/t/announcing-project-grades-on-lgtm-com/1003
And this PR uses this data (that's exposed over the API) to add a new lgtm badge that displays the grade for a particular language.
EG:
Added new tests as appropriate.

Add grade badge for [lgtm]

---

lib/error-helper.js
lib/request-handler.js
services/errors.js
services/gem/gem.js

As I've been working on the new service code, I've had a couple of thoughts on the exception classes:
https://github.com/badges/shields/pull/1590#issuecomment-377359085
https://github.com/badges/shields/pull/1680#discussion_r187159093
I think its worth looking at this before we are using this code in too many places and it becomes difficult to change the constructor signatures. This PR proposes the following changes:
* All exception classes now have the same signature. I find this confusing:
```js
class InvalidResponse extends Error {
constructor(prettyMessage = 'invalid', underlyingError) {
// ...
}
}
class Inaccessible extends Error {
constructor(underlyingError, prettyMessage = 'inaccessible') {
// ...
}
}
```
* Passing a `props` object means `underlyingError` and `prettyMessage` are …

[cdnjs gem] make exception classes more consistent

---

server.js
services/docker/docker.tester.js

Problem described here: https://github.com/badges/shields/pull/1675#discussion_r186843360
Before:
After:

Bugfix: override colorB in [docker] badges

---

lib/all-badge-examples.js
server.js
services/david/david.tester.js

This PR adds support for David's `path` query parameter (used to specify in which folder the package.json file is located).
The diff is a bit messy because the indentation had to be changed, but all it really does is adding the path query param declaration and an if block to append `?path=x` when sending the HTTP request.
Note: this closes #637

[david] add support for path

---

package-lock.json
package.json

Now that we are running node 8 we can safely upgrade to Joi 13.
V12 -> V13 is a major version change because it drops support for older versions of node, but [does not change the public API surface](https://github.com/hapijs/joi/compare/v12.0.0...v13.0.0#diff-88333ba11114e014e87198d04680144d) so no code changes are required to support the upgrade.
Includes update to transitive dependency on `hoek`

upgrade to Joi 13.3.0

---

lib/color-formatters.js
lib/color-formatters.spec.js

I'm having a look through the failing service tests on the daily build.
It looks like several of the test failures are due to the behaviour change to `version()` introduced in #1615. Examples: https://circleci.com/gh/badges/shields/5328 I've picked bower and clojars to run in this PR just to demonstrate but I think there are others.
There are some badges which were relying on `version.toLowerCase()` throwing an error when passed an input like `null` or `undefined`. Now that we're turning everything into a string at the start of the function this no longer happens.
My proposed solution is we should explicitly throw an `Error` on invalid inputs to this function.

[bower clojars] version() should throw on invalid inputs

---

Dockerfile

The `envsubst` cmd isnt invoked, and so `secret.json` doesnt exist.

Ensure both docker CMDs are invoked

---

lib/all-badge-examples.js
server.js
services/github/github.tester.js

Implements https://github.com/badges/shields/issues/1616#issue-309141574. Probot app has access to merge commit sha, so we don't need more useful API (described here https://github.com/badges/shields/issues/1616#issuecomment-377700209).
Service tests describes all cases I was able to come up with. Feel free to suggest other cases.

[github] Commit merge status badge

---

dangerfile.js
package-lock.json
package.json

* Update `danger.js` to the latest version (includes fixes for https://github.com/danger/danger-js/issues/532 and https://github.com/danger/danger-js/issues/531 )
* If PR contains tests using `assert`, suggest `expect` syntax (refs #1553 ).
* If PR touches service, check service tester also touched (more specific version of the "This PR modified the server but none of the service tests." rule for the new service architecture)

add more rules to dangerfile

---

services/npm/npm.tester.js

* Expect `TypeScript vX.Y | Flow vX.Y` instead of `TypeScript vX.Y Flow vX.Y`
* Allow version numbers to have more than >1 digit after the point

fix typescript regex in [npm] tests

---

services/cocoapods/cocoapods.tester.js

There are a couple of `cocoapods` tests failing because the package we are testing against has been getting 0 downloads/week (how sad :disappointed: ) and the `isMetricOverTimePeriod` regex didn't allow `0/week`. In principle though, it should also be valid to have 0 open issues + so on, so I've changed the others

[cocoapods] fix Metric regexes

---

lib/all-badge-examples.js
server.js
services/resharper/resharper.tester.js

Also changed the description from 'JetBrains Plugins' to 'JetBrains IntelliJ IDEA Plugins'. Otherwise, it would be ambiguous.

Add ReSharper gallery badge.

---

lib/nuget-provider.js
services/chocolatey/chocolatey.tester.js
services/powershellgallery/powershellgallery.tester.js
services/resharper/resharper.tester.js

Downloads badges based on NuGet v2 have its service name as a badge name. 
Other downloads badges (like Nuget, MyGet) uses "downloads" as a badge name. This PR changes name of NuGet v2 based downloads badge to "downloads".

[resharper chocolatey powershellgallery nuget myget] Standard name in nuget v2 downloads badge

---

server.js

NPM changed the error body, breaking the not found case
Fix this by checking the status code instead of relying on the errror message in the body.

fix 'not found' case in [node] badge

---

services/dub/dub.tester.js

The version we were testing against seems to have gone away - spooky :ghost:
https://code.dlang.org/api/packages/vibe-d/0.7.23/stats
Switch to a version that exists:
https://code.dlang.org/api/packages/vibe-d/0.7.27/stats

fix [dub] service test

---

services/cocoapods/cocoapods.tester.js

It appears this does not only happen on the weekly stats.
refs https://github.com/badges/shields/pull/1713

allow 0 in all [cocoapods] download tests

---

now.json

I tried to [deploy Shields to Now](https://github.com/badges/shields/blob/master/doc/self-hosting.md#zeit-now) but it didn't work for me. I think that [files](https://zeit.co/docs/features/configuration#files-(array)) in `now.json` in does not support file patterns (there wasn't `server.js` after deployment and there were `*.spec.js` files). This PR add required files and directories. Working instance https://shields-pr-1718.now.sh/ (will be running as long as this PR is open). 
List of files before this change:
After:

Required files added to now.json

---

lib/all-badge-examples.js

The issue badges deliver the same information for pr's, too!
Alternative, shorter wording, would be `pr`.
Any preferences here?

GitHub badges: extend for pr in title

---

lib/all-badge-examples.js
server.js
services/appveyor/appveyor.js
services/base.js
services/base.spec.js
services/cdnjs/cdnjs.js
services/clojars/clojars.js
services/gem/gem.js

Refactored the clojars version badge. While I was doing it, I decided we really need to get the abstraction discussed [here](https://github.com/badges/shields/pull/1590#discussion_r176240097) in place sooner rather than later.
Doing this makes the code for simple badges really terse. For example this reduces the gem version badge implementation down to:
```js
async handle({repo}) {
const apiUrl = 'https://rubygems.org/api/v1/gems/' + repo + '.json';
const json = await this._requestJson(apiUrl);
const version = json.version;
return {
message: versionText(version),
color: versionColor(version)
};
}
```

[gem cdnjs appveyor clojars] refactor clojars, establish BaseJsonService

---

lib/all-badge-examples.js
server.js
services/travis/travis.tester.js

Add new badges for `travis-ci.com` using two new possible paths (maintaining consistency with travis-ci.org badges): 
`/travis/com/USER/REPO.(svg|png|gif|jpg|json)`
`/travis-ci/com/USER/REPO.(svg|png|gif|jpg|json)`
close #1674  #1710

[Travis] Add travis-ci.com support

---

lib/text-measurer.spec.js

This message gets spit out a lot by the tests:
```
`sandbox.create()` is deprecated. Use default sandbox at `sinon.sandbox` or create new sandboxes with `sinon.createSandbox()`
```

Fix sinon deprecation warning

---

services/sonarqube/sonarqube.tester.js

The service tests for
* Tech Debt (legacy API unsupported)
* Coverage (legacy API unsupported)
have been failing consistently on the daily build for some time. It looks like their API now only returns the error response over HTTPS and times out over HTTP:
```
$ curl "https://sonarqube.com/api/resources?resource=com.github.dannil:scb-java-client&depth=0&metrics=sqale_debt_ratio&includetrends=true"
{"errors":[{"msg":"Unknown url : /api/resources"}]}
$ curl "http://sonarqube.com/api/resources?resource=com.github.dannil:scb-java-client&depth=0&metrics=sqale_debt_ratio&includetrends=true"
curl: (7) Failed to connect to sonarqube.com port 80: Connection timed out
```
Hence
https://img.shields.io/sonar/4.2/https/sonarqube.com/com.github.dannil:scb-java-client/tech_debt.svg does render a badge: …

fix [sonar] legacy/unsupported service tests

---

server.js
services/dependabot/dependabot.tester.js

After some feedback from users, I think `semver stability` is a better name for this badge than `semver compatibility`. This PR implements the change.

Rename semver compatibility badge to semver stability

---

lib/all-badge-examples.js
server.js
services/scrutinizer/scrutinizer.tester.js

This pull request covers the following:
* the NaN error reported in #1739 was fixed, as well as the example updated on the homepage.
* a proper test suite was added.
* the service code was refactored. We had three handler functions which were mostly copy-pasted code, which were merged into one. When we get round to modularising this service, we'll be able to break down the bulky _if_ statements into nice separate functions. I also modernised and rearranged the existing code.
I noticed that we had very similar `isBuildStatus` validators in several service tests, I'm planning on extracting them to _test-validators.js_ once this is merged. 😉 
As usual, looking forward to feedback! 👍

[scrutinizer] Fix #1739, add tests and refactor

---

server.js

Daily tests have been failing for the last few days.
Looks like the API has changed slightly so the `namespace` property is the namespace id, not the namespace name.

fix [ansible] galaxy role name badge

---

lib/all-badge-examples.js
server.js
services/jenkins/jenkins.tester.js

This PR added a new badge support for Jenkins Jacoco Code Coverage using `/jenkins/j` in the route.
> https://img.shields.io/jenkins/j/https/[jenkins-project-url].svg
Url Pattern for Jenkins Jacoco coverage report in json format.
> https://[jenkins-host]/job/[project]/job/[branch]/lastBuild/jacoco/api/json
Sample Jenkins Jacoco coverage report in json format.
```
{
"_class":"hudson.plugins.jacoco.report.CoverageReport",
"branchCoverage":{
"covered":1796,
"missed":819,
"percentage":69,
"percentageFloat":68.68069,
"total":2615
},
"classCoverage":{
"covered":235,
"missed":48,
"percentage":83,
"percentageFloat":83.038864,
"total":283
},
"complexityScore":{
"covered":2398,
"missed":1205,
"percentage":67,
"percentageFloat":66.55565,
"total":3603
},
"instructionCoverage":{
"covered":39498, …
```

Add [Jenkins] Jacoco coverage badge ☘

---

services/cocoapods/cocoapods.tester.js
services/david/david.tester.js
services/lgtm/lgtm.tester.js

This PR standardize mocking a invalid JSON in service tests. This is a follow-up to https://github.com/badges/shields/pull/1755. I tried to find all custom mocks of the invalid JSON using grep, but I could miss something.

[cocoapods david lgtm] An invalid JSON is mocked using invalidJSON in all service tests

---

lib/php-version.spec.js

There have been various discussions about whether we should change the behaviour of our code for comparing versions from composer. For the moment I'm not going to propose any functional changes to this, but one of the problems we have here is that that our code for comparing and ordering composer versions is non-trivial and has no tests. This makes it difficult to change.
This PR helps this by adding tests to formalise the 'happy path' behaviour of the `compare()` function (i.e: when processing valid version strings). Note that `compare()` exhibits some spurious behaviour when processing invalid versions. For example:
```js
> const { compare } = require("./lib/php-version");
> compare('1.0.0-aardvarks', '1.0.0-alpha');  // 1.0.0-aardvarks is not a valid version
0 …
```

add tests for composer version compare function

---

doc/service-tests.md

This pull request adds info about `invalidJSON` fixture to the service tests documentation. This should increase awareness about existence of this fixture. 
Not all tests which mocks an invalid JSON use this fixture. We can improve it in a separate PR :-)

invalidJSON fixture documented

---

server.js

This fixes issue #1776. The issue was caused because the following api call: 
https://builds.apache.org/job/Any23-trunk/lastBuild/api/json?tree=actions[failCount,skipCount,totalCount]
returns a 400 BAD REQUEST due to the "invalid characters" `[` and `]`.  
I simply URL-encoded these characters.

fix for invalid [jenkins] tests

---

server.js
services/json/json.tester.js

Closes #1779
returns ![](https://img.shields.io/:badge-malformed%20url-red.svg) on error
```javascript
decodeURIComponent('%1') // URI Malformed
decodeURIComponent('%01') // ''
```

handle malformed url [dynamic-json]

---

CNAME
Makefile
next.config.js

This addresses some long-standing comments in https://github.com/badges/shields/issues/1458#issuecomment-368270996
We should also adopt Gatsby, create-react-app, or something similar designed for static sites, to eliminate the unnecessary runtime dependency on Next.js while also letting someone else maintain our front-end tooling. :-D These alternative tools might work just fine in subdirectories without config, and we might be able to leave Jekyll turned on (though we don’t need it). However these git-related changes are orthogonal.
- Don’t check out master, making it possible to deploy the currently checked-out commit
- Disable Jekyll which we don’t need. This allows _next folders to be deployed, and the related URL rewriting to be removed.
- ~~Set NEXT_ASSET_PREFIX so the site works at …

Fixes for github deploy

---

.prettierignore

This causes extremely strange failures in CircleCI. `npm install`, oddly, rewrites and reformats package.json. We hash package.json to determine the cache keys, and oddly enough Circle computes a new hash when we write the cache. `npm-install` writes to one cache key. The tasks that follow read from another. Nothing runs.
I'm running into this because I'm using prettier auto-format on another project, and the presence of a `.prettierrc` means it's started trying to format Shields code.
In separate news, I'm loving auto-formatting!

Do not prettify package.json

---

server.js

Closes #1799 
`colorB` override should now have priority on the static badges

Fix colorB override not working for static badges

---

lib/error-helper.js
services/base-json.spec.js
services/cdnjs/cdnjs.tester.js
services/clojars/clojars.tester.js
services/gem/gem.tester.js
services/npm/npm.tester.js

This message **unparseable json response** is consistent with the error messaging in #1743. That's a fair amount of test, though that doesn't seem like a big problem since it's not something we expect users to see terribly often.

Provide a descriptive message when json can’t be parsed [cdnjs clojars gem]

---

lib/all-badge-examples.js
services/gem/gem.js

Following on from https://github.com/badges/shields/pull/1762#issuecomment-406896626 I've extracted the changes to the examples. This re-shuffles the examples into categories:
- Build
- Chat
- Dependencies
- Downloads
- Funding
- Issue Tracking
- License
- Rating
- Social
- Version
- Other
#1762 can be rebased on to this later.

re-organise badge examples

---

services/bugzilla/bugzilla.tester.js
services/bundlephobia/bundlephobia.tester.js

I’m guessing something has changed with the way rounding happens in bundlephobia. I don’t expect this to happen again, but if it does we can change this to a regex.
For #1359

Fix [bundlephobia] tests and rm errant inspectJSON

---

server.spec.js

increase timeout from `2000ms` → `5000ms` for `colorscheme PNG badge` test.
As this test is often [failing with](https://circleci.com/gh/badges/shields/7231):
```console
1) The server
should produce colorscheme PNG badges:
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

increase timeout for `colorscheme PNG badge` test

---

.eslintrc.yml
dangerfile.js
server.js

https://eslint.org/docs/rules/comma-dangle#always-multiline
Also worth noting that all lib/service files are currently following this rule.
:-1: Examples of incorrect code for this rule with the "always-multiline" option:
```javascript
var foo = {
bar: "baz",
qux: "quux"
};
var foo = { bar: "baz", qux: "quux", };
var arr = [1,2,];
var arr = [1,
2,];
var arr = [
1,
2
];
foo({
bar: "baz",
qux: "quux"
});
```
:+1: Examples of correct code for this rule with the "always-multiline" option:
```javascript
var foo = {
bar: "baz",
qux: "quux",
};
var foo = {bar: "baz", qux: "quux"};
var arr = [1,2];
var arr = [1,
2];
var arr = [
1,
2,
];
foo({
bar: "baz",
qux: "quux",
});
```

eslint enable comma-dangle always-multiline

---

package-lock.json
package.json

This fixes 154 of the 355 vulnerabilities. Many of the vulnerabilities are in dev dependencies, though it doesn't hurt to clean these up. Otherwise we won't see the important ones when they pop up.

Update several lockfile dependencies using `npm audit fix`

---

frontend/components/usage.js
lib/request-handler.js
lib/request-handler.spec.js

This is related to discussions in #1806. Until that pull request is merged and we have an easy way of configuring the environment variables on the server, we should have a non-0 value in the meantime.
@paulmelnikow suggested 60 seconds whereas @Nyholm was advocating larger values (300, 600), so I've opted for something intermediary, 120 seconds. We can easily change it if need-be and revert it once the other PR is merged.

Increased default BADGE_MAX_AGE_SECONDS

---

README.md

This is a rather confusing behavior of CircleCI's API and our badge: it shows the status of the latest build, not the latest build on the default branch.
That seems like it's almost never what anyone would want. I wonder if we should require a branch going forward, and deprecate the option to show the latest build.

Show test status on master, not latest build

---

lib/github-helpers.js
lib/github-helpers.spec.js
package-lock.json
server.js
services/github/github.tester.js

This pull request addresses issue #1768.
I noticed that many other GitHub badges were suffering from this same problem, but for now I've only fixed it for the "issues" badge and will wait for some initial feedback before tackling the other ones. 😉

[GitHub] Fix undefined badges

---

templates/flat-square-template.svg
templates/flat-template.svg
templates/for-the-badge-template.svg
templates/plastic-template.svg
templates/popout-square-template.svg
templates/popout-template.svg

Closes #1881 
Style | `colorA` present | no `colorA`
:--: | :--: | :--:
flat | [![nintendo switch](https://svgshare.com/i/7oq.svg)](https://svgshare.com/i/7oq.svg) | [![nintendo switch](https://svgshare.com/i/7nV.svg)](https://svgshare.com/i/7nV.svg)
flat-square | [![nintendo switch](https://svgshare.com/i/7p1.svg)](https://svgshare.com/i/7p1.svg) | [![nintendo switch](https://svgshare.com/i/7p2.svg)](https://svgshare.com/i/7p2.svg)
for-the-badge| [![nintendo switch](https://svgshare.com/i/7n5.svg)](https://svgshare.com/i/7n5.svg) | [![nintendo switch](https://svgshare.com/i/7or.svg)](https://svgshare.com/i/7or.svg)
plastic | [![nintendo switch](https://svgshare.com/i/7pB.svg)](https://svgshare.com/i/7pB.svg) | [![nintendo switch](https://svgshare.com/i/7oK.svg)](https://svgshare.com/i/7oK …

support for colorA + logo

---

lib/error-helper.js
lib/error-helper.spec.js
services/base.js
services/base.spec.js
services/errors.js

This came up while I was rewriting uptimerobot, which for usability reasons has some internal validation of one of its parameters.
https://github.com/badges/shields/blob/09be682963da4c3643e7c80a44d9f2ad39a46fd8/server.js#L6773-L6777
Also it seems that the shields error message for a 5xx error is **inaccessible**, not **invalid**.

Add InvalidParameter runtime error and return inaccessible for 5xx errors

---

lib/github-auth.js
lib/sys/secret-is-valid.js
services/github/auth/admin.js
services/github/auth/admin.spec.js

Fix regressions in the github admin and token acceptor endpoints, introduced in #1813.

Fix and test the github admin route

---

services/apm/apm.service.js
services/apm/apm.tester.js
services/appveyor/appveyor.service.js
services/cdnjs/cdnjs.service.js
services/cdnjs/cdnjs.tester.js
services/clojars/clojars.service.js
services/clojars/clojars.tester.js
services/gem/gem-downloads.service.js
services/gem/gem-owner.service.js
services/gem/gem-rank.service.js
services/gem/gem-version.service.js
services/gem/gem.tester.js

Once this is in, I will pick up #1740 again

use fetch/render pattern in [apm appveyor cdnjs clojars gem]

---

doc/self-hosting.md

Env variable set before sudo is not visible for node command (alternatively we can use `SENTRY_DSN=https://xxx:yyy@sentry.io/zzz sudo -E node server`). 
Before:
```bash
SENTRY_DSN=https://abc@sentry.io/123 sudo node server
raven@2.4.2 alert: no DSN provided, error reporting disabled
0817203057 Server is starting up: http://[::]:80/
```
After:
```bash
sudo SENTRY_DSN=https://abc@sentry.io/123 node server
0817203112 Server is starting up: http://[::]:80/
```

Example command for starting server with SENTRY_DSN after sudo

---

services/base-json.js
services/base-json.spec.js

This fixes a regression introduced in #1929 which was caught by service tests post-merge.

Fix and test trace logging in BaseJsonService

---

CONTRIBUTING.md

The section for documentation contribution is quite short.
This adds examples of when to make a contribution.

add examples for documentation contributions

---

services/librariesio/librariesio-base.js

Addresses #1959. The bug managed to slip in between the merger of #1895 and #1888!

[librariesio] Fixed error handling

---

dangerfile.js

- fixes https://github.com/badges/shields/issues/1968
- adds the desired notice

danger: help users to write server tests

---

doc/TUTORIAL.md

The headline was one level too high.
Or it should be `(5) Write Tests` instead `(4.4) Write Tests`

tutorial: fix headline

---

frontend/lib/generate-image-markup.js
services/base.js
services/pypi/pypi.tester.js

https://lgtm.com/projects/g/badges/shields/alerts/?mode=list
To help us keep up to date on this, We could consider adding the readme badge and/or the GitHub integration.

Clean up some alerts detected by LGTM [pypi]

---

services/pypi/pypi-base.js
services/pypi/pypi-helpers.js
services/pypi/pypi-helpers.spec.js
services/pypi/pypi-license.service.js
services/pypi/pypi.tester.js

- When license is empty, get license from trove classifiers
- Allow empty classifiers array
Closes #2022

[pypi]: Fix broken badges

---

services/base-json.js
services/base-json.spec.js

The fix beef866 was simple. This adds two failing tests.
Issues like this is a good reason to be careful about unit testing base functionality, even when it is used by many services!
Fixes #2034 #2030

Fix unparseable json in [circleci uptimerobot]

---

services/wercker/wercker.service.js

refs #1994
Still need to think about how to improve the base class, but lets fix this one example as a first step.

fix wercker examples

---

pages/index.js

refs https://github.com/badges/shields/issues/1954#issuecomment-417513823
I don't know if this is objectively the best solution to this, but it does seem to work.

render category links correctly on initial page load

---

CONTRIBUTING.md
lib/badge-data.js
lib/badge-data.spec.js
services/aur/aur.service.js
services/aur/aur.tester.js
services/david/david.service.js
services/david/david.tester.js
services/github/github.tester.js
services/jitpack/jitpack.service.js
services/jitpack/jitpack.tester.js
services/osstracker/osstracker.service.js
services/packagist/packagist-php-version.service.js
services/packagist/packagist.tester.js
services/php-eye/php-eye-php-version.service.js
services/php-eye/php-eye.tester.js
services/travis/travis-php-version.service.js
services/travis/travis.tester.js
services/twitter/twitter.service.js
services/twitter/twitter.tester.js
services/vaadin-directory/vaadin-directory.service.js
services/vaadin-directory/vaadin-directory.tester.js

This pull request addresses issue #1997.
I implemented lower casing of the left-handside of badges in the `makeLabel` function, but only for `defaultLabel`. If the user specifies a label override, he can use upper case characters freely.
Note that when the function was called with hardcoded sting values (e.g. `getBadgeData('AUR', data)`), I lower cased the strings at the point of call (`getBadgeData('aur', data)`) as well to avoid any confusion in the code.
Query parameters specifying special styles are not affected (i.e. capitalisation for social badges, full upper casing for for-the-badge).

[aur packagist php-eye travis vaadin-directory github david jitpack twitter] Enforced lowercase badge labels

---

__snapshots__/make-badge.spec.js
lib/make-badge.spec.js
package-lock.json
package.json

The test `should always produce the same JSON (unless we have changed something!)` was systematically failing on my laptop. If my understanding is correct, the snapshot data for the test was generated on a Unix platform and therefore uses Unix line endings (`\n`).
On Windows, when loading and preparing the badge templates, Windows line endings are used (`\r\n`). The comparison with the snapshot was therefore failing.
When run on Windows, the test suite will now use a different snapshot, with the proper line endings.

Made JSON snapshot test pass on Windows

---

services/vso/vso.service.js

Newly created build definitions on VSTS does not support old badge endpoint. Instead, a new one has been provided and supports all build definitions.

Better support for VSTS build badges

---

lib/svg-badge-parser.js
lib/svg-badge-parser.spec.js
services/codacy/codacy-coverage.service.js
services/codacy/codacy-grade.service.js
services/codacy/codacy.tester.js
services/readthedocs/readthedocs.service.js
services/vso/vso.service.js

This pull request addresses #1985.
The current `getValue` regex in _svg-badge-parser.js_ was no longer properly parsing Codacy's SVG badges, and that service's coverage and grade badges were also inconsistent with one another. The proposed solution is to make the regex customisable on a per service basis.
If we implement a _BaseSvgService_ in #2031, we could implement a function returning a regex which can be overriden by implementations.

Fixed [Codacy] badges (affects [vso readthedocs])

---

services/circleci/circleci.service.js
services/circleci/circleci.tester.js

* Add tests for urls with token (just basic one that the server can handle such urls).
* Fix URL to make the test passed.
Urls like `/circleci/:token/project/:vcsType/:owner/:repo/:branch.svg` don't work, but we need them to let the server fetch data from CircleCI API by passing token.

Fix [circleci] urls with token (for private projects)

---

lib/all-badge-examples.js
services/codacy/codacy-coverage.service.js
services/codacy/codacy.tester.js

The project used on the homepage doesn't have any relevant coverage data: ![](https://img.shields.io/codacy/coverage/e27821fb6289410b8f58338c7e0bc686.svg)
I've switched it to one that does: ![](https://img.shields.io/codacy/coverage/59d607d0e311408885e418004068ea58.svg)
As you can see above the unknown coverage case is handled pretty poorly, with the exclamation mark and the bright green colour. From now on, such a badge would render as: ![](https://img.shields.io/badge/coverage-unknown-lightgrey.svg)

Fixed [Codacy] coverage examples and improved unknown coverage handling

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/1_Bug_report.md
.github/ISSUE_TEMPLATE/2_Badge_request.md
.github/ISSUE_TEMPLATE/3_Feature_request.md
.github/ISSUE_TEMPLATE/4_Support_question.md
CONTRIBUTING.md
doc/TUTORIAL.md

Following up on @platan 's suggestion in #1678 I've had a go at writing some issue templates.
It is a bit hard to review what this will look like when we merge it so to make this easier I've also pushed the templates in this PR up to a test repo. You can preview at https://github.com/chris48s/templates-test/issues/new/choose
closes #1678

Add multiple issue templates

---

services/jenkins/jenkins-plugin-installs.service.js
services/jenkins/jenkins-plugin-installs.tester.js

This adds a badge that shows the number of installations of a particular Jenkins plugin. You can show the total number of installations across all versions or pick a particular version.
The data is retrieved from the [official statistics](https://stats.jenkins.io/) that the Jenkins project provides. For example, the data for the [View Job Filters Plugin](https://plugins.jenkins.io/view-job-filters) can be found here:
https://stats.jenkins.io/plugin-installation-trend/view-job-filters.stats.json
Note that these are actual installs, not downloads (i.e if somebody uninstalls a plugin, the number goes down). I've still added the badge to the downloads category because that's the closest category there is.

Add [JenkinsPluginInstalls] service

---

lib/all-badge-examples.js
services/dub/dub.tester.js

Before:
after:
Version `0.7.23` is not available anymore: https://code.dlang.org/packages/vibe-d/versions
I've updated example and service test with the newest one `0.8.4`.

[Dub] downloads badge with available version

---

lib/all-badge-examples.js

Following on from #2095 this updates the remaining occurrences of "Github" to "GitHub"

consistently style Github as GitHub in examples

---

lib/all-badge-examples.js

These examples currently appear twice in the index because they are also defined in the service classes:
https://github.com/badges/shields/blob/10e8232ffae70800be65290150d805e1db9aa9fa/services/pypi/pypi-djversions.service.js#L19-L27
https://github.com/badges/shields/blob/10e8232ffae70800be65290150d805e1db9aa9fa/services/pypi/pypi-pyversions.service.js#L19-L27

remove duplicate PyPI examples

---

services/base.js

Adds a couple of sanity checks. All our current badges pass them
closes #1994

require exampleUrl and urlPattern if using staticExample

---

lib/all-badge-examples.spec.js
services/base.js
services/base.spec.js

**How to reproduce**
Go to [shields.io](https://shields.io/) and search for `ruby`. There will be 0 results.
**Expected result**
There should be 8 badge examples being found:
* 4 from [`GemDownloads`](https://github.com/badges/shields/blob/362db466bb551154897b415a76305ae04262f2d5/services/gem/gem-downloads.service.js#L121-L164)
* 1 from [`GemOwner`](https://github.com/badges/shields/blob/362db466bb551154897b415a76305ae04262f2d5/services/gem/gem-owner.service.js#L48-L58)
* 2 from [`GemRank`](https://github.com/badges/shields/blob/362db466bb551154897b415a76305ae04262f2d5/services/gem/gem-rank.service.js#L72-L89)
* 1 from [`GemVersion`](https://github.com/badges/shields/blob/362db466bb551154897b415a76305ae04262f2d5/services/gem/gem-version.service.js#L50-L60)
All of these specify the `ruby` …

Fix: keywords not found when searching examples

---

lib/all-badge-examples.js
services/github/github-license.service.js
services/github/github-release.service.js
services/github/github-tag.service.js
services/github/github.tester.js

Following on from https://github.com/badges/shields/issues/2117#issuecomment-425558353
* I've modified the `/release` badge so we can use `/release-pre` and changed the home pages example. The legacy `/all` suffix will still work (for backwards-compatibility) but its not documented.
* I haven't changed anything else on `/release`. Looking into it, we're using the `prerelease` key there rather than assuming semver so we don't have the same issue there that we do with tags.
* I've added a `tag-date` endpoint. I changed my mind and decided not to go with `sort=semver/sort=date` for 2 reasons:
* It allows `/tag-pre/username/repo.svg?sort=date` which is a bit odd/unclear
* We don't really have a good way to get the querystring in `BaseJsonService`. This is going to be a problem with a few …

Allow [GitHub] tag badge to sort by date

---

CONTRIBUTING.md
package-lock.json
package.json

This PR adds precommit hook which runs ESLint and Prettier against staged git files. Why is it a good idea: https://www.npmjs.com/package/lint-staged#why? It uses [lint-staged](https://www.npmjs.com/package/lint-staged) and [husky](https://www.npmjs.com/package/husky). I've added the autofix (`--fix`) option to ESLint, because a lot of problems can be fixed automatically (https://eslint.org/docs/rules/). 
What do you think about this?

Precommit hook with Prettier and ESLint

---

frontend/components/usage.js

Fix for a warning shown below. Warning can be reproduced by starting (`npm run start`) shields locally.
```
[frontend] Check the top-level render call using <td>. See https://fb.me/react-warning-keys for more information.
[frontend]     in span (at usage.js:73)
[frontend]     in Usage (at examples-page.js:97)
[frontend]     in div (at examples-page.js:73)
[frontend]     in ExamplesPage
[frontend]     in Route (at pages/index.js:9)
[frontend]     in div (at pages/index.js:8)
[frontend]     in Router
[frontend]     in StaticRouter (at pages/index.js:21)
[frontend]     in Router
[frontend]     in AppContainer
[frontend]     in Container
[frontend]     in App
```
`logos` array contains unique values, so it can be used as keys.

remove react-warning-keys warning in renderNamedLogos

---

doc/self-hosting.md
secret.tpl.json
services/npm/npm-base.js

This PR adds support for private npm packages via an `npm_token` secret.  This allows anyone running their own shields.io service to create badges for their private packages.

Add support for private [npm] packages

---

lib/all-badge-examples.js
services/ctan/ctan.service.js
services/ctan/ctan.tester.js

Refactor ctan service, fixing single licenses along the way (ie. https://img.shields.io/ctan/l/tex.svg from unknown -> knuth)

[ctan] refactor service

---

lib/licenses.js
lib/licenses.spec.js

Hello, I'd like to propose a solution for a TODO left in `lib/licenses.js` 😄 
I think that since something is available under many licenses, it can be obtained under the most permissive one, thus we can set the badge color to that specific one.
What do you think? I'm open for discussion 😃

use most permissive license color

---

services/github/github-stars.service.js
services/github/github.tester.js

Fix #2170 
Hi. I believe this is a Bug fix. So I'm not sure whether I should add a test, but added it anyway.

Fix: colorB override not working for [Github] Stars

---

lib/all-badge-examples.js
services/codeclimate/codeclimate.service.js

We've hit a wall in #1518, our Code Climate badges have been unreliable for months now.
This pull request aims at sparing some of our limited API quota by switching to static examples on the homepage.
I'm not willing to migrate the badges to the new service architecture at this point as we've already put in quite a lot of investigation and development effort in these badges. The least we can say is that @CodeClimate have not been very cooperative and have been dragging their feet since one of our users first contacted them back in April.

Static Code Climate examples

---

frontend/components/usage.js
lib/request-handler.js
lib/request-handler.spec.js
services/base.js
services/discord/discord.service.js

This PR adds the ability for us to override `BADGE_MAX_AGE_SECONDS` with a different value for a category or a specific badge. This will allow us to set a long cache on badges that change infrequently (like license) and a shorter cache on badges that change more frequently (like build status). I've set some values in this PR:
license: 1 hour
version: 5 minutes
build: 30 seconds
as a starting point, but I'm not wedded to them. I'm more interested in feedback on the approach for now.
This only applies to the services we've already refactored, but as we refactor more of the codebase, this becomes an increasingly helpful feature :)
I've also shown an example in fe3552a of how we can use this feature to override the default in a specific badge. 2 mins cache is fine for most of the 'chat' …

allow badge maxAge to be set by category; affects [discord]

---

lib/all-badge-examples.js
services/vso/vso.service.js
services/vso/vso.tester.js

Per #2082, this PR aims at renaming VSTS into Azure DevOps. I also updated the service documentation so that it is easier to create badges for both builds and releases.

Rename VSTS into Azure DevOps

---

package.json

This PR attempts to fix #2223 
>The production server runs `npm install` every deploy, though it doesn’t respect package-lock.
I've changed the required version to `1.9.9` (removed the `^` char) as i assume dependabot will update the required version in `package.json` if it doesn't match the current pattern?
Another option could be `latest`?
But this could cause problems if/when `simple-icons` moves to `2.0.0`.
**Note:**
I was going to change it to use `~1.9.9`, but figured we would still end up behind every patch, and only end up updating every minor version, so removed the tilde aswell.

bump simple-icons version

---

README.md

* removed build status as the real badge equivalent is displayed just above in the Readme.
* replaced Code Climate by Codacy as the badges for the former service are unreliable (#1518). Also, as Code Climate are not being very cooperative there is no point in giving them free advertising.
* replaced Gratipay by Liberapay, its maintained fork.
* added three new examples which showcase different usages of our badges.
I'm wondering though, why do we not insert real badge examples here? With a high `maxAge` parameter and static badges, it would probably put little extra load on the server.

Readme examples

---

.eslintrc.yml
frontend/components/examples-page.js
lib/badge-cli.js
lib/github-auth.js
lib/request-handler.js
lib/suggest.js
services/aur/aur.service.js
services/gem/gem-downloads.service.js
services/gem/gem-rank.service.js
services/hexpm/hexpm.service.js
services/imagelayers/imagelayers.service.js
services/jenkins/jenkins-plugin-installs.service.js
services/librariesio/librariesio-dependencies.service.js
services/requires/requires.service.js
services/steam/steam-base.js
services/steam/steam-workshop.service.js
services/swagger/swagger.service.js
services/wercker/wercker.service.js
services/wordpress/wordpress-base.js
services/wordpress/wordpress-downloads.service.js
services/wordpress/wordpress-platform.service.js

I had to track down the right lint rule for this. We have no-useless-rename for destructuring and import/export. The one for object literals is object-shorthand.

Enforce property shorthand

---

package-lock.json
package.json

This fixes remaining vulnerabilities raised by `npm audit`.
Follow-up to https://github.com/badges/shields/pull/2258.
Related issues from dependencies:
- camp upgrade: https://github.com/espadrine/sc/issues/64
- socket.io vulnerability: https://github.com/get/parsejson/issues/4

Upgrade to camp 17.2.2

---

services/azure-devops/azure-devops-build.service.js
services/azure-devops/azure-devops-release.service.js

While checking out the deployment I suddenly realized the renaming has made these badges harder to find. This should help.

Add vso keyword to azure badges

---

services/hackage/1.json

This snuck in on 52ab84c89f41cab5188364235c67b04735650f6d and I missed it in review.

Remove extra file checked in by mistake

---

services/base.js
services/base.spec.js

This regression from #2284 was causing `{ message: 22 }` to render as `'n/a'`, as in this test run: https://circleci.com/gh/badges/shields/23680
This is a deploy blocker.

Allow handle() to return a numeric message

---

.circleci/config.yml

Circle: Remove obsolete check

---

lib/all-badge-examples.js
services/chocolatey/chocolatey.service.js
services/myget/myget.service.js
services/nuget/nuget-v2-service-family.js
services/nuget/nuget.service.js
services/powershellgallery/powershellgallery.service.js
services/resharper/resharper.service.js

With the v3 services, I extended the services after exporting them. With the v2 services, a simpler approach seemed possible so I went with that. PowerShell is an independent badge, so that one was straightforward.
Blocking further refactoring work on badge examples.

The last of the badge examples

---

services/stackexchange/stackexchange.tester.js

Per part of issue #2378, tests for StackExchange have been implemented
to help with porting the existing badge with the new BaseJsonService class.
If merged, the next steps would be to port the badge, then add a new
StackOverflow badge part of #2378

Add tests for [StackExchange]

---

services/aur/aur.service.js
services/aur/aur.tester.js

Tweak [AUR] and add static examples

---

frontend/components/usage.js

- `longCache` should not be appearing in the displayed URLs for the usage examples.
- `maxAge` is ignored for static badges.

Remove `longCache` from static examples

---

gh-badges/lib/make-badge.js

This is a little fix I’ve been meaning to make for a while. Normally it manifests in the codetally badge, but that badge isn’t working right now.
Here’s a static example, where the right text is wrapped in spaces:
https://img.shields.io/badge/foo-%20bar%20-blue.svg
The spaces get included in width computation, though I suppose ignored when the svg renders, resulting in bad letter spacing.
With this fix, the spaces are ignored.
production: ![](https://img.shields.io/badge/foo-%20bar%20-blue.svg)
this PR: ![](https://shields-staging-pr-2475.herokuapp.com/badge/foo-%20bar%20-blue.svg)

Prevent bad letter spacing when whitespace surrounds badge text

---

services/codetally/codetally.tester.js

This was caused by #2475 and fixes the mocked test. It's not related to #2480 which is causing the other one to fail.
Not running the [Codetally] tests in CI because they're failing.

Fix whitespace in mocked Codetally test

---

services/azure-devops/azure-devops-base.js
services/azure-devops/azure-devops-coverage.service.js
services/azure-devops/azure-devops-coverage.tester.js
services/azure-devops/azure-devops-tests.service.js
services/azure-devops/azure-devops-tests.tester.js

This is in response to [this conversation](https://github.com/badges/shields/issues/2237#issuecomment-446812796). The change turned out being even easier than I had anticipated because the [API supports a buildStatus filter](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-5.0#buildstatus). I did quite a bit of local testing to make sure this is solid. I also ran tests and checked coverage.
One thing I thought might be slightly odd is the [name of this class](https://github.com/badges/shields/blob/master/services/azure-devops/azure-devops-base.js#L18) doesn't match the file name. Not an issue and I'm not sure if it's intentional, but figured it was worth noting.

Refactor [AzureDevOpsCoverage AzureDevOpsTests] to only report on completed builds; test all [azuredevops]

---

lib/deprecated-services.js
services/coverity/coverity-on-demand.service.js
services/coverity/coverity-on-demand.tester.js
services/coverity/coverity-scan.service.js
services/coverity/coverity-scan.tester.js

* Migrate Coverity Scan to new service model (and adds tests) refs #1358 
* Deprecate Coverity On Demand badges (and adds tests)
Everything I've seen indicates that Coverity On Demand has been decommissioned for a while, although I haven't seen any _official_ announcements from Coverity/Snyopsys. If anyone knows otherwise please let me know, but for now I believe deprecation is the best course of action.
All of the on-demand endpoints are down/inaccessible:
* https://ondemand.coverity.com/ 
* http://ondemand.coverity.com/
* https://api.ondemand.coverity.com
* https://api.ondemand.coverity.com/streams/44b25sjc9l3ntc2ngfi29tngro/badge
* https://api.ondemand.coverity.com/jobs/p4tmm8031t4i971r0im4s7lckk/badge 
And the few online references I have found for Coverity On Demand speak about it in …

Migrate [Coverity] to new service model

---

services/cache-headers.spec.js

Adds fake timers to the cache-headers tests for serverHasBeenUpSinceResourceCached, fixes #2571

Fix intermittent test failures for serverHasBeenUpSinceResourceCached

---

lib/server.js

Ref https://github.com/badges/shields/issues/2420#issuecomment-450400904

Fix [suggest]

---

lib/server.spec.js

Fixes #2611. I added a 10 second to the `before` and `teardown` functions directly so only those functions will be impacted (timeout period for the tests remains the default 2 seconds)

Add timeout for server test setup/teardown

---

README.md

Replaced badges rendered by open collective with the newly added ones

Use shields instead of open collective badges in README.md

---

pages/_document.js

Currently HTML code of shields.io contains two `<title>` elements. This PR removes an extra title element. 
Before change:
```bash
> curl https://shields.io -s | egrep "<title.*/title>" -o 
<title class="next-head">Shields.io: Quality metadata badges for open source projects</title>
<title>My page</title>
```
After change:
```bash
> curl http://localhost:8080 -s | egrep "<title.*/title>" -o
<title class="next-head">Shields.io: Quality metadata badges for open source projects</title>
```

Unwanted title removed

---

services/github/github-api-provider.js
services/github/github-api-provider.spec.js

This code isn't being run during tests, though let's fix that later as part of #2733. Specifically:
> However _the pool itself_ could be used all the time; there's not a big advantage in turning that off when it doesn't need to be used.
Fix #2728

Fix github auth again

---

scripts/github_token_backup.fish

Seems better to have this checked in here than sitting on my dev machine.

Add a script used for backing up the production GitHub tokens

---

services/coverity/coverity-scan.service.js
services/coverity/coverity-scan.tester.js
services/deprecated-service.js
services/deprecated-service.spec.js

* temporarily deprecates Coverity Scan badges due to extended outage of the service, discussion in #2722 
* https://community.synopsys.com/s/article/Coverity-Scan-Update
* updates `deprecatedService` function to enable custom deprecation badge messages
* adds unit tests for `DeprecatedService` definition
I did **not** add Coverity Scan to the deprecated services lists given that this is only temporary, but let me know if it needs to be added anyway

Temporarily deprecate [CoverityScan] 

---

server.js

This fixes e.g. `node server 8080 0.0.0.0`.
Ref #2772.

Fix overriding bind address on CLI

---

lib/build-status.js
lib/build-status.spec.js
services/azure-devops/azure-devops-build.tester.js

I guess because of the missing message, I just get a `vendor unresponsive` badge.

Fix orange statuses, run tests for [AppveyorCi AzureDevOps Bitbucket CircleCi Gitlab Readthedocs Shippable Wercker]

---

lib/badge-data.js
services/base.js
services/base.spec.js
services/github/github-languages.tester.js
services/static-badge/static-badge.tester.js

Numeric colors weren't properly being handled by `makeBadge` after #2742.
Since this function really does not need to be accepting colors as strings, rather than make the function more lenient to work with Scoutcamp, I coerced the types of the colors on the way in.
Two tests cover the functionality in the modern service. I don't feel strongly that the legacy version needs coverage at this point, though I've added one for the moment on the github languages badge where this manifested.
Fix #2778

Fix numeric colorB [static githublanguages]

---

services/base.js

As I was working on refactoring the logo code, I thought of a way to compute the color in a way more befitting the declarative style of the function.

BaseService: Minor stylistic refactor of color computation

---

.gitpod.yml
README.md
package-lock.json

Hi @paulmelnikow, I've finally managed to make it work. 🎉 Thanks a lot for your help! 😄 
As a reminder, Gitpod is a service that provides free readily configured workspaces in the cloud, complete with a lightweight IDE, a terminal, and a web preview.
What this pull request does is to pre-configure all Shields workspaces with ports `8080` and `3000` exposed, and on start-up they will automatically run `npm install`, `npm run build` and finally start the server with `node server 8080 0.0.0.0`.
A few caveats:
- Opening the web app in a Browser tab works better than the Preview pane, because the latter has a dark background.
- I haven't pre-installed `ImageMagick`, but I can still add it just in case
If you'd like to try out this Gitpod configuration, here is a snapshot:
[![GitHub issues …

Make code contributions easier with Gitpod

---

dangerfile.js

This avoids making lots of parallel API calls on big PRs and getting us abuse-limited.
- https://twitter.com/orta/status/1087439065321033735
- https://github.com/badges/shields/pull/2823#issuecomment-456182984
Combining the loops cuts our calls in half. I picked the cutoff of 100 without much information; we could choose a smaller number, too.
Close #2826

Optimize diffing in Danger

---

.circleci/config.yml

These tests fail more often than others, and sometimes we run into abuse rate limits. It's inconvenient to hold up merging when the changes are unrelated.

Split integration tests into their own stage

---

core/base-service/legacy-request-handler.js

`ShieldsRuntimeError` is in `services/errors.js` but not `services/index.js`. Oops!
Close #2834

Fix production crash

---

core/base-service/base.js
core/base-service/validate.js
core/base-service/validate.spec.js
services/endpoint/endpoint.service.js
services/endpoint/endpoint.tester.js

Ref https://github.com/badges/shields/issues/2838#issuecomment-456594803

Provide friendlier error messages for [endpoint]

---

services/jenkins/jenkins-coverage.service.js

This small pull request closes #2648. The previous project targeted by the example no longer seems to be using the Jacoco plugin, so I've hunted down another one:
https://img.shields.io/jenkins/j/https/builds.apache.org/job/Derby-JaCoCo.svg

Fixed JaCoCo example

---

README.md

As per RawGit's index, the service is being shut down in October 2019. They mention:
>If you're currently using RawGit, please stop using it as soon as you can.
They recommend using jsDelivr or a few other CDNs going forward. jsDelivr has an easy [transfer page](https://www.jsdelivr.com/rawgit) available
See [rawgit.com](https://rawgit.com) for details on the sunset phase.

Update from RawGit to local path

---

lib/build-status.js
lib/build-status.spec.js

Fixes #2848 
Appveyor briefly has a status of `starting` before the job begins, so adding `starting` to the list of `otherStatuses` to prevent the Appveyor badges from showing `invalid response data` during that window

Update build status list 

---

services/nexus/nexus.tester.js
services/test-validators.js
services/validators.js

Fixes #2978 
Changes the regex to allow a + in semver for the validator used in Nexus, following [semver guidelines](https://semver.org/#spec-item-10)

Allow plus in semver [Nexus aur bintray chocolatey dubversion myget nuget powershellgallery resharper] 

---

services/jsdelivr/jsdelivr-hits-github.service.js
services/jsdelivr/jsdelivr-hits-npm.service.js

`headers` is not destructured; it needs to go in `options`.
`Shields.io` is set as the `User-Agent` by code in `legacy-request-handler.js`.

Remove unused parameter in [jsdelivr]

---

.circleci/config.yml
.gitpod.yml
.prettierignore
Dockerfile
README.md
doc/TUTORIAL.md
doc/self-hosting.md

[npm ci](https://medium.com/better-things-digital/npm-ci-a-command-you-should-know-d8d67847884c) provides clean installs of packages, using the exact resolution in the lockfile. It's faster, and reliably produces results matching the lockfile.
The only time you really need `npm install` is when you're actually changing the dependencies, which doesn't apply to CI (where Dependabot writes the lockfile), or to any of the cases documented here.
For a while I thought `npm ci` was for **continuous improvement**, as in what you want to use in your CI server, though it seems that it actually means **clean install**.

npm install -> npm ci

---

services/maintenance/maintenance.service.js

As I mentioned at https://github.com/badges/shields/pull/3005/files#r257553498 this should use NonMemoryCachingBaseService as it doesn't fetch anything. It's a waste of the cache to store these values when they can be computed on the fly without taking up any space.
Added `(yes|no)` for the dropdown.

Tweak [maintenance] badge in UI; remove caching

---

lib/badge-data.js

While I was doing #3090 I realized the work in #3012 did not handle legacy services.
I tested this manually with `/librariesio/release/hex/phoenix.svg?color=blue` and it works.
The rewrite is almost done and I don't feel like we ought to invest in automated testing that's going to be thrown away, so I didn't write an automated test.

Fix color overriding for legacy services

---

doc/self-hosting.md

The Heroku setup instructions were outdated. There's no need for a build pack.

Update instructions for self-hosting Shields with Heroku

---

.prettierignore
doc/TUTORIAL.md

Close #3116, refs https://github.com/badges/shields/pull/3101#discussion_r261010695
Follow on to #3101 with a couple minor updates to the Tutorial. 
The updates include a couple link fixes to reflect the new code structure, and also moves the numbered comments in the code block above the line they refer to.  Originally all of the numbered comments were on the same line(s) and spaced out, but prettier scatters those comments all over the place. We'd been having prettier ignore this file altogether, but in discussion in the linked thread it seems like it would be easier to tweak those comments and use prettier to keep this file formatting consistent with all the others.
Moving the comments above the respective code blocks satisfies prettier and keeps them consistent. Open to suggestions if …

Minor tutorial updates

---

services/coveralls/coveralls.service.js
services/coveralls/coveralls.tester.js

The legacy service implementation used an interesting approach (used Coveralls' badge url to figure out the redirect header location which pointed to an S3 bucket that contained an svg with a name that included the coverage number)
There is a Coveralls API (https://docs.coveralls.io/api-introduction#getting-data-from-coveralls) that provides coverage in a JSON format so I figured that would be easier to use with our Base Services.
The noteworthy thing with the API is that it returns the latest published coverage results (regardless of branch) if no branch is explicitly specified, whereas Coveralls native badge (and thus the Shields.io Coveralls badges from the legacy service implementation) display coverage for the repository's default branch by default if no branch is explicitly …

Refactor [Coveralls]

---

core/service-test-runner/icedfrisby-shields.js
services/static-badge/static-badge.tester.js

This pull request allows `expectBadge` to be called with a `null` color, which is the value that the static badge returns for invalid input colors. We'll pretty much be done with #2687 after this!

Allow expectBadge to be called with null color, affects [StaticBadge]

---

doc/deprecating-badges.md
doc/rewriting-services.md

I updated the _service-tests.md_ documentation in #3097, but noticed that there were two other pieces of documentation that I had missed out.

Update remaining documentation for expectBadge

---

services/github/github-followers.service.js

Accidentally left the social style off the example in https://github.com/badges/shields/pull/3157#issuecomment-469527123

Fix GitHubFollowers example style

---

core/base-service/base.js

I believe I’ve added all the schemas to the new-style services in #3164, so this should be purely preventive.

Prevent queryParams from reaching handle() when no schema is defined

---

services/nuget/nuget-v2-service-family.js

closes #2331
The issue here was that if the version can be expressed as a number e.g: `0.3`, `d:Version` will be a number instead of a string

allow numeric version for NuGet v2 services [powershellgallery chocolatey resharper]

---

frontend/pages/index.js
gatsby-browser.js

The error was generated in the `onRouteUpdate` handler, which is invoked before the component. This moves redirecting responsibility to the handler, which seems like a better place for it anyway.

Fix console error before applying a frontend route redirect

---

core/base-service/errors.js
lib/error-helper.js
lib/error-helper.spec.js
services/github/github-commit-status.service.js
services/github/github-commit-status.tester.js

This decorates response errors with the response and response buffer, to make it easy for a service to parse an error response when it needs to. Since this is needed so rarely, I didn't put the error-parsing functionality in BaseJsonService, to save resources in the vast majority of cases.

Rewrite GitHub commit status

---

services/jsdelivr/jsdelivr-hits-github.tester.js
services/jsdelivr/jsdelivr-hits-npm.tester.js

These are failing pretty often in CI.

Lengthen timeouts on [jsdelivr] tests

---

services/packagist/packagist-base.js
services/packagist/packagist-downloads.service.js
services/packagist/packagist-license.service.js
services/packagist/packagist-version.service.js
services/packagist/packagist-version.spec.js
services/packagist/packagist-version.tester.js

Fix #3238 
- Moved definitions of schemas from base service class to their respective service classes (and simplified them accordingly), save for the one schema used in multiple places
- Updated version badge to re-add the logic used to properly select correct latest/pre version that existed in the legacy service implementation. I believe that when the legacy services were refactored that this was attempted to be handled within the schema, but that won't be able to cover all cases (as evident by the reported bugs)
- Added an additional live/integration test with packagist for a vpre badge
Note: some additional tests should be added in the future to cover some of the re-added logic in the transform function of the version badge service. However, I'd prefer to go ahead and merge this given …

Fix [packagist] badges

---

services/pypi/pypi-helpers.js
services/pypi/pypi-helpers.spec.js
services/pypi/pypi-license.tester.js
services/pypi/pypi.tester.js

Currently the trove-based license classifiers generate different formatting than the legacy license classifiers. This brings them into alignment.
Production:
This PR:
Think this is a good improvement; more consistent with most other badges, and will look better on readmes (see https://github.com/lace/vg for an example).

[pypi] Improve formatting of trove-based licenses

---

.circleci/config.yml
package.json

Fixes https://github.com/badges/shields/issues/3267
`npm run e2e` still starts server using `npm run start`, which is convenient for development.

In CI, run e2e tests on the build

---

services/node/node.tester.js

Nothing much going on here:
* made the tests check for the `message` field rather than the deprecated `value` one.
* removed the useless _Joi.string()_ checks. I added them in 1f29c22d3dd47794da72254d2b8527dc0232fea2 due to the limitations of `expectBadge` at the time, but the helper now supports omitting any of the fields in the input.

[Node] tests improvements

---

services/dynamic/dynamic-response-fixtures.js
services/dynamic/dynamic-xml.service.js
services/dynamic/dynamic-xml.tester.js

This fixes queries with an attribute filter in the middle, such as `//book[@id='bk102']/title`.
Close #3089

Rewrite [dynamicxml] tests, and fix issue with attribute filters

---

services/github/github-issue-detail-redirect.service.js
services/github/github-issue-detail-redirect.tester.js
services/github/github-issue-detail.service.js
services/github/github-issue-detail.spec.js
services/github/github-issue-detail.tester.js

I'm basically following other PRs -- I am not an expert on JS.
Please don't hesitate to spot any problems.
This PR addresses #1719

Enhance status badge for PRs in [GithubIssueDetail]

---

services/npm/npm-downloads.service.js
services/npm/npm-downloads.spec.js
services/npm/npm-downloads.tester.js

This moves the four npm download services into a single class, in line with #3174, and other service implementations we've written in the last couple months. 
1. Change the suffixes from **/m** to **/month** for consistency.
2. Add tests of one of the intervals besides total.
3. Rewrite mocked service tests as unit tests.
4. Use (and work with) the `intervalMap` pattern that I think @calebcartwright started us using.

Consolidate [NpmDownloads] into one service

---

services/coverity/coverity-scan.service.js
services/coverity/coverity-scan.tester.js

Close #3334 
As detailed in #3334, Coverity has a cert chain issue which prevents us from being able to render our Coverity badges (internally, we get `Inaccessible: unable to verify the first certificate` errors on cert chain issues, the badges render as `inaccessible`). We've seen this with a couple other services (or instances of self-hosted tools, like #1956)
Ideally the upstream providers would resolve, but our Coverity badge users have expressed understandable concern around the timeframe for if/when Coverity (Synopsys) would be able to resolve this. We receive the cert verification error on both Node 8.x and 10.x so I believe it's an issue that we'll need to address. 
This proposed solution adds a new a new query param `disableStrictSSL` that will allow the user to opt-in to …

add strictSSL query param toggle to [coverity]

---

core/service-test-runner/icedfrisby-shields.js
services/github/github-downloads.service.js
services/github/github-downloads.tester.js
services/php-version.js
services/php-version.spec.js
services/travis/travis-php-version-redirect.service.js
services/travis/travis-php-version.service.js
services/travis/travis-php-version.tester.js

The change in `expectBadge` prints a more helpful error when `message` is empty.
Ref #2863

Rewrite [travisphpversion]; improve error message in expectBadge

---

services/github/github-forks.service.js

Small detail that was left out in #3299. The non social version of the badge is now grey rather than [the previous blue](https://github.com/badges/shields/blob/11cd0bdbc59d7d244aa61112102224aabdb7ea5b/services/github/github-forks.service.js#L80).

Color fix for [GitHubForks] badge

---

services/test-validators.js

For example [Debian] uses them, typically for pre-releases.

Allow tilde as optional suffix separator

---

.circleci/config.yml

In https://github.com/badges/shields/pull/3390/files#diff-1d37e48f9ceff6d8030570cd36286a61 I added entrypoint tests to two jobs (node8/node-latest). It's time to remove this code duplication. I'm using the https://circleci.com/docs/2.0/writing-yaml/#merging-maps syntax. More info about this approach: https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/. CircleCI 2.1 has an alternative solution (https://circleci.com/docs/2.0/reusing-config/), but I think solution from this PR also OK.

Remove code duplication in CircleCI configuration; test on [jetbrains]

---

services/ubuntu/ubuntu.service.js
services/ubuntu/ubuntu.tester.js

https://api.launchpad.net/1.0/
Requires #3397 first for epoch version validation support.

Add [Ubuntu] package version support

---

doc/self-hosting.md

`METRICS_PROMETHEUS_ALLOWED_IPS` is not supported since https://github.com/badges/shields/pull/3059. 
Feel free to merge it after approve.

Remove IP filtering documentation for metrics

---

services/licenses.js
services/licenses.spec.js
services/pypi/pypi-license.tester.js

This covers some of the license strings used by the PyPI badges like **BSD** which currently shows up in lightgrey.
This PR:
Production:

Add some aliases for license colors; refactor; test colors for [PypiLicense]

---

CONTRIBUTING.md

I just noticed this but looks like the original link (http://amyciavolino.com/assets/MindfulCommunicationInCodeReviews.pdf) in our Contributing guide for code review guidelines no longer works and redirects here: https://amy.tech/. That site then has a link to what I assume is the original doc here: https://kickstarter.engineering/a-guide-to-mindful-communication-in-code-reviews-48aab5282e5e
Updating the link accordingly in our Contributing doc

Fix code review guidelines link in Contributing guide

---

services/aur/aur.service.js
services/aur/aur.tester.js

Fixes #3474 
There's apparently issues with the package (`yaourt`) used in many of the service tests (and examples), so I've updated both to use some different packages to resolve

fix [aur] service tests

---

services/jsdelivr/jsdelivr-hits-github.tester.js
services/jsdelivr/jsdelivr-hits-npm.tester.js

Refs #3478 - increasing the timeout on these tests to 10s to see if that helps resolve the recurring test timeouts. There are time windows (00:00-1:00 UTC) when the underlying API is known to have issues but hopefully this will fix the service test timeouts 🤞

increase [jsdelivr] test timeouts

---

.github/FUNDING.yml

See the [documentation](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository) for more information about this new GitHub feature.
The preview looked like this when creating the file through the UI:

Open Collective funding link

---

.dependabot/config.yml

Dependabot now allows config to be declared in a config file: https://dependabot.com/docs/config-file/
Merging this will move us to managing our dependabot settings in a yaml file in the repo instead of via the admin panel. This allows users who don't have access to the admin panel to view our config and propose changes to it.
However, the main reason I propose this change is the [ignored_updates](https://dependabot.com/docs/config-file/#ignored_updates) setting. An issue with things as they stand (in my opinion) is that if I say `@dependabot ignore this major`, dependabot internally preserves state based on the commands we issue but there is no way to inspect that state i.e: if someone told dependabot to "ignore this major" 2 months ago, the only place that information is recorded is in …

Switch dependabot to yaml config

---

.circleci/config.yml
gh-badges/README.md

This is an alternative approach to #3428 using NVM to run the tests on multiple node versions in a single container based on the discussion in that thread.

Run package tests on multiple node versions with nvm 

---

gh-badges/CHANGELOG.md
gh-badges/package.json

As noted in #3499 we've not done a gh-badges release in a while. Although bumping anafanafo isn't a massively important change, when I went to write the changelog entry, I was actually quite surprised at how much new stuff is backed up there :open_mouth: 
I've made the assumption that we're going to merge #3498 ahead of this and included the node version support work in the changelog entry.
Once this is reviewed/merged, I'll publish to NPM and close out #3499

cut a v2.2.0 release

---

.github/ISSUE_TEMPLATE/2_Failing_service_test.md

Had a poke about in https://github.com/badges/shields/issues/templates/edit and I've got a hunch that the reason this isn't being correctly picked up as an issue template is because the colons in `:green_heart:` are stopping the header from being parsed correctly:
vs
This should probably fix it :crossed_fingers:

(attempt to) fix 'failing service test' issue template

---

services/powershellgallery/powershellgallery.service.js

The example we were previously using (Az.Storage) now renders
This replaces the example with a package that gives us a valid result

switch [powershellgallery] platform example

---

gh-badges/lib/index.js
gh-badges/lib/make-badge.js

After pushing a new release earlier, I realised that we've [changed the spec for the format object](https://github.com/badges/shields/blob/master/gh-badges/CHANGELOG.md#deprecations) but didn't update the docblock. This PR updates the docblock, but it reminds me of a related issue which I've addressed in PR #3507

Fix BadgeFactory.create() docblock

---

gh-badges/CHANGELOG.md
gh-badges/lib/make-badge.js
gh-badges/package.json
lib/logos.js
lib/logos.spec.js

Also prepares a 2.2.1 release for NPM

improve logo escaping

---

services/mastodon/mastodon-follow.service.js
services/mastodon/mastodon-follow.tester.js

Closes #3458.
The API requires a user ID to get an account instead of their username.
I found the ID in a `<link>` tag in the header of a user's profile page.
Example: `<link href="{domain}/api/salmon/2214" rel="salmon">` (2214 is the user ID)
We should either add this to the documentation for the badge or find another solution to get the user ID.
Also posted on discord.

Add [Mastodon] service

---

services/librariesio/librariesio-dependencies.service.js

Allow nulls for boolean fields on Libraries.io APIs

---

services/spack/spack.service.js
services/spack/spack.tester.js

Add support for the Spack package manager (https://spack.io and repo at https://github.com/spack/spack).
Spack is a modern multi-language, multi-version, multi-variant software package manager in high-performance computing (HPC).
~~This pull-request is a draft since we are still in the process of deploying a continuous package index.~~ The package index is up :)

[Spack] Package Manager: Latest Version

---

Dockerfile

Noticed this in the Docker Hub build log:
https://cloud.docker.com/u/shieldsio/repository/registry-1.docker.io/shieldsio/shields/builds/de14f15e-0f10-4842-9ad2-42b8558bc2ff
Ref #3558

Docker: Don't installl Cypress

---

gh-badges/lib/make-badge.js

Closes #3613 
Refer https://github.com/badges/shields/issues/3613#issuecomment-508582465 https://github.com/badges/shields/issues/3613#issuecomment-506983441
This PR addresses an issue where the measured text size was using the `left`, `right` variables, but the `text[]` variable was being uppercased.

Fix for-the-badge spacing, uppercase left, right instead of text[] variables

---

core/base-service/legacy-request-handler.js

Cherry-picked from #3410; should simplify reworking it.

Minor refactor: expose custom promisify function from legacy request handler

---

config/test.yml
core/server/server.js
core/server/server.spec.js

This should fix the problem I noted at https://github.com/badges/shields/pull/3644#issuecomment-508952678 though it notes a bug, which is that the legacy static badge route `/label/message.png?color=green` does not work. That route is very, very old, and has never supported SVG, so I'm inclined to drop it, though if we want it to keep working, this redirect code is going to have to be changed in a more fundamental way. That route has always been registered last because it's difficult to distinguish from real badges.
I'm inclined to just drop the legacy static badge route since it probably isn't being used much (since it doesn't support SVG) and results in the server behaving differently with .svg and .png extensions at what is otherwise the same URL.
e.g. …

Fix raster redirect and drop the legacy static .png route

---

doc/production-hosting.md
scripts/github_token_backup.fish
services/github/auth/admin.js

Now that these s0.server.shields.io entries are set up through the main DNS on Cloudflare, we don't need the shields-server.com domain anymore. One less thing to maintain.

Deprecate shields-server.com domain

---

.circleci/config.yml

Node 11 is no longer current or maintained: https://nodejs.org/en/about/releases/

Per node support policy, drop tests for Node 11

---

core/service-test-runner/service-tester.js
doc/service-tests.md
services/archlinux/archlinux.tester.js
services/cii-best-practices/cii-best-practices.tester.js
services/cookbook/cookbook.tester.js
services/coverity/coverity-scan.tester.js
services/ctan/ctan.tester.js
services/debian/debian.tester.js
services/discourse/discourse.tester.js
services/endpoint/endpoint.tester.js
services/homebrew/homebrew.tester.js
services/jetbrains/jetbrains.tester.js
services/myget/myget.tester.js
services/nodeping/nodeping-status.tester.js
services/nodeping/nodeping-uptime.tester.js
services/nuget/nuget.tester.js
services/snyk/snyk-vulnerability-github.tester.js
services/snyk/snyk-vulnerability-npm.tester.js
services/swagger/swagger.tester.js
services/ubuntu/ubuntu.tester.js
services/visual-studio-marketplace/visual-studio-marketplace-azure-devops-installs.tester.js
services/visual-studio-marketplace/visual-studio-marketplace-downloads.tester.js
services/visual-studio-marketplace/visual-studio-marketplace-rating.tester.js
services/visual-studio-marketplace/visual-studio-marketplace-version.tester.js
services/wercker/wercker.tester.js
services/wordpress/wordpress-platform.tester.js

Close #2555
To avoid conflicts with #3652 I haven’t removed all the explicit annotations, though I’ve removed a bunch of them here.

Auto-annotate live and mock tests e.g. [nodeping]

---

core/server/server.js

Haven't seen error reports on these, so let's cache these a bit longer to reduce our server load.

Cache raster redirects longer

---

config/custom-environment-variables.yml
core/server/server.js
services/github/github-constellation.js

- Move to private
- Fix validation
- Don't log the URL
Ref #3332

Fix up Redis config

---

services/packagist/packagist-php-version.service.js
services/packagist/packagist-php-version.tester.js

Fixes #3767. Two slightly different error cases are now covered: for a given package version, no requirements at all or no PHP version requirement.

Cover missing PHP version requirement in [PackagistPhpVersion]

---

server.js

This one is spewing a bunch of recent http calls into each error log.
I get the benefit of these plugins though I'm curious what resources they might be using. And in this case, don't want the requests to end up e.g. in a GitHub issue.

Disable more default Sentry integrations

---

services/osslifecycle/osslifecycle.service.js

This function was resulting in eslint warnings about missing jsdoc that kept showing up. This adds jsdoc `param` and `return` declarations which resolve that warning.

add jsdoc to osslifecycle function

---

package-lock.json
package.json
scripts/redis-connectivity-test.js

ioredis 4.14.0 introduced an issue where custom TLS options are no longer honored. I reported it here: luin/ioredis#947
This has been preventing the server from using GitHub tokens, however I'm not sure whether or not this has been causing noticeable issues.
For now let's downgrade to the latest working version, which I've confirmed working via the script (checked in).

Fix TLS errors preventing Redis connections in production

---

services/nexus/nexus.tester.js

Same thing here as #3910 
the `search snapshot version valid snapshot artifact` service test for nexus is a regular timeout failure. this switches the target package (and nexus instance) used for the test. Admittedly anecdotal, but in my local env the original target timedout after 15 seconds on most runs, this new target is running in < 500 ms
https://circleci.com/build-insights/gh/badges/daily-tests/master

improve durability of [nexus] service test

---

services/dub/dub-download.tester.js

The specific version total downloads service test is frequent timeout failure in the daily test runs. This changes the target pacakge used for the test. In my local env, with this new target the test runs in < 1 sec. vs. the original package which ran in ~10 secs.
https://circleci.com/build-insights/gh/badges/daily-tests/master

update [DubDownload] service test to increase stability/reliability

---

services/github/github-labels.service.js
services/github/github-labels.tester.js

Hi, I created a small service for displaying labels of GitHub repos.
This is nice for mentioning labels across GitHub, as GitHub-flavored markdown does not offer the option to reference a label. It keeps the color in sync and you will easily recognize if a label does not exist anymore.
The endpoint is `/github/labels/{user}/{repo}/{label}`.
You can e.g. reference the **documentation** label of this repo with: `/github/labels/badges/shields/documentation`, which would look similar to:
A nonexistent label `/github/labels/badges/shields/gibberish` would look like:
Please feel free to make suggestions to my code as I am not used to writing JS or developing for node.
Thanks for offering such a cool service!

Add service for [GitHubLabels]

---

services/jenkins/jenkins-tests.service.js

I noticed that the example we had for JenkinsTest was no longer valid (the QA Ubuntu Jenkins instance was apparently taken offline some time back)

update JenkinsTests example

---

gh-badges/README.md
gh-badges/lib/index.js
gh-badges/lib/index.spec.js

Another one targetting v3-dev. This PR removes the `BadgeFactory` class (which we don't need now that all the text-measuring is being done by anafanafo instead of PDFKit) and just replaces it with a single function call `makeBadge()`.
The diff changes quite a lot, but its mostly just indentation. Probably the key thing here is: is `makeBadge()` the function name we want to expose?
I haven't switched our internal stuff to use the public interface of the package here yet, as there are still things (logos, links) that we support on shields.io but aren't exposed via the documented interface of the package yet.
I think I'm probably going to hold off on the other v3 changes (expose logos, rename the package, etc) until #3637 is done, as those jobs are going to create a big merge conflict with …

Remove BadgeFactory

---

.gitpod.yml
README.md

Hi @paulmelnikow! 👋 I hope you're well, and that you're enjoying the summer. 🌴 
I noticed the Shields repo is quite popular on Gitpod (🎉) and I wanted to circle back to ensure the experience is as good as it can be, and finish some of the work items from https://github.com/badges/shields/issues/2772.
In this Pull Request, I:
1. remove the word "Beta" from README.md, since [Gitpod launched](https://www.gitpod.io/blog/gitpod-launch/) officially in April 2019
2. add `onOpen: open-preview` to the port 8080 specification, so that the Shields web app gets automatically opened in a preview when it starts
3. set up [continuously prebuilt workspaces](https://www.gitpod.io/docs/46_prebuilds/) to speed up IDE loading times. This saves 2 minutes every time you start a new workspace, but requires …

Improve Gitpod automated setup

---

core/server/monitor.js
core/server/prometheus-metrics.js
core/server/server.js

See if GitHub outages are related to onboard rate limiting.
https://github.com/badges/shields/issues/3874#issuecomment-527904731
From https://shields-staging-pr-3950.herokuapp.com/metrics
```
rate_limit_exceeded_total{rate_limit_type="referrer"} 146
rate_limit_exceeded_total{rate_limit_type="ip"} 929
```

Exclude more in-use GitHub IPs from rate limiting and add metrics

---

services/build-status.js
services/netlify/netlify.service.js
services/netlify/netlify.spec.js
services/netlify/netlify.tester.js

This PR adds a status badge for Netlify, the static CDN and fixes #3953.
I tried making a PR in #3178 from scratch by using a "closest color matcher" many months ago, but I wasn't able to complete it. This time, it uses the SVG scraping service, and works pretty well (as long as Netlify doesn't update their badge colors, after which we'll update the service).
Thanks for the community for being so patient!

Add [Netlify] (fixed #3129)

---

services/dynamic/dynamic-xml.service.js
services/dynamic/dynamic-xml.tester.js

Closes #3796
Usually we don't directly bounce the exception message back to the user like this, but I reckon if you're trying to construct an xpath query, this is probably the most useful output and better than a runtime error.

[dynamicxml] wrap xpath errors

---

services/npm/npm-version.service.js
services/npm/npm-version.tester.js

Closes #3794
I think the reason we're seeing this is because (for some reason) sometimes we get a response back from NPM with no `latest` key. This modifies the schema to require the `latest` key to be present in order to accept the response.

[npmversion] require key 'latest' to exist

---

services/codefactor/codefactor-grade.service.js
services/codefactor/codefactor-grade.tester.js
services/codefactor/codefactor-helpers.js

It’s hard to understand how #3813 is persisting. The schema should reject keys not in the object… it’s very puzzling.
This replaces the code used to get the color with a function call that throws an explicit error when the key is missing. It should at least make it clear what the key value is when this fails in the future.

Throw explicit error on invalid [codefactorgrade] color
