services/website/website-redirect.service.js
services/website/website-redirect.tester.js
services/website/website.service.js
services/website/website.tester.js

move [Website] url to query param

---

doc/production-hosting.md

Just documenting a couple of missing OAuth app owners. Let me know if there are others that need adding.

Add Twitch and Wheelmap OAuth app owners

---

core/base-service/auth-helper.js
core/base-service/auth-helper.spec.js
services/azure-devops/azure-devops-base.js

Fixes #4037 
Request does not support basic auth with `undefined` for the user, so this updates our auth mechanism to allow a service class to use an empty string for the user.
I confirmed that this resolves the authentication issues for the Azure DevOps badges referenced in #4037
https://github.com/request/request/blob/master/lib/auth.js#L131

support basic auth with just pass token

---

package-lock.json
package.json

- Nintendo 3DS (simple-icons/simple-icons#1618)
- Zulip (simple-icons/simple-icons#1618)
- CodeFactor (simple-icons/simple-icons#1620)
- Showpad (simple-icons/simple-icons#1620)
- Svelte (simple-icons/simple-icons#1620)
- Expo (simple-icons/simple-icons#1621)
- Zalando (simple-icons/simple-icons#1630)
- Azure Artifacts (simple-icons/simple-icons#1630)
- GNU Privacy Guard (simple-icons/simple-icons#1632)
- VK (simple-icons/simple-icons#1618)

Update to Simple Icons 1.16.0

---

services/github/github-contributors.tester.js

Modified the tests for GithubContributors service to make use of repos under the badges organization.

fix: use repos from badges organization for [GithubContributors]  (#4104)

---

services/bugzilla/bugzilla.service.js
services/github/github-contributors.tester.js

This was tested against a test case with the bug id 1536094 as shown in the attached.
The test was not committed since the bug can be modified in future with the resolution field populated which will break the test. There is a way to query the the Bugzilla API and search by status providing a limit of 1 in order to create a robust test. But that involves changing the behavior of the service that is not much to do just for the test. So I am leaving out the unit test for this change

 fix: allow empty but required resolution property for [Bugzilla] (#4102)

---

frontend/components/usage.tsx

Before:
After:
Changes were made using Visual Studio Code + Prettier plugin. 
I've changed manually:
```jsx
We support <code>.svg</code> and <code>.json</code>. The default is
<code>.svg</code>, which can be omitted from the URL.
```
to
```jsx
We support <code>.svg</code> and <code>.json</code>. The default is <code>.svg</code>, which can be omitted from the URL.
```
At this stage problem was fixed. Then I formated code with the "Format Document" action and the code was changed to:
```jsx
We support <code>.svg</code> and <code>.json</code>. The default is{' '}
<code>.svg</code>, which can be omitted from the URL.
```

Missing spaces added do the usage section

---

core/base-service/base.spec.js

c.f. https://github.com/badges/shields/pull/4145#issuecomment-538768061
This is super-strange. I am curious what this is about! (Though not quite curious enough to go digging.)
The test failure is reproducible in Node 12.11.0 though not e.g. 10.6.3.
Example failure on master: https://circleci.com/gh/badges/shields/74325

Fix tests in Node 12

---

services/jsdelivr/jsdelivr-hits-github.tester.js
services/jsdelivr/jsdelivr-hits-npm.tester.js
services/microbadger/microbadger-layers.tester.js
services/microbadger/microbadger-size.tester.js
services/scrutinizer/scrutinizer-base.js
services/scrutinizer/scrutinizer-coverage.service.js
services/scrutinizer/scrutinizer-coverage.spec.js
services/scrutinizer/scrutinizer-quality.service.js

Resolves #4144 
Fixes the schema used for Scrutinzer Coverage and Quality badges to handle the API response (which can include branches missing statistics) and increases the timeouts on a couple service tests for Microbadger and jsDelivr that regularly timeout during the daily test runs

Update service tests for [Scrutinizer Microbadger jsDelivr]

---

services/librariesio/librariesio-common.js
services/librariesio/librariesio-dependencies.service.js
services/librariesio/librariesio-dependencies.tester.js
services/librariesio/librariesio-dependent-repos.service.js
services/librariesio/librariesio-dependent-repos.tester.js
services/librariesio/librariesio-dependents.service.js
services/librariesio/librariesio-dependents.tester.js
services/librariesio/librariesio-sourcerank.service.js
services/librariesio/librariesio-sourcerank.tester.js

This PR proposes an implementation of allowing libraries.io badges (dependents, sourcerank...) to work with scoped npm packages. It is inspired by how the current [bundlephobia service](https://github.com/badges/shields/blob/2.2.1/services/bundlephobia/bundlephobia.service.js#L23) handles it.
Once merged, it should solve #4025.
Please see if it looks good to you. Thanks!

Allow [librariesio] badges referencing scoped npm package (#4025)

---

services/jenkins/jenkins-coverage.service.js
services/jenkins/jenkins-coverage.tester.js

Closes #3785.
The plugin is called "Code Coverage API", so we could use `code-coverage-api` in the badge's path to mirror what we do with the JaCoCo and Cobertura plugins, but that gets quite lengthy and repeats the `coverage` word already present in the base path. Therefore, I went for the short and simple `api`.

Support [JenkinsCoverage] through the Code Coverage API plugin

---

core/service-test-runner/cli.js
core/service-test-runner/runner.js
core/service-test-runner/service-tester.js

This PR adds an option to retry all failed service tests. It uses IcedFrisby's [retry()](https://github.com/IcedFrisby/IcedFrisby/blob/master/API.md#retrycount-backoff) function. 
Usage:
```bash
RETRY_COUNT=3 RETRY_BACKOFF=0 npm run test:services -- --only=dynamicxml
```
Retried tests are marked with `R` in logs. An example:
```
[live] XML from url | invalid url
RR      ✓ 
[ GET .json?url=https://github.com/badges/shields/raw/master/notafile.xml&query=//version ] (413ms)
```
Default values:
- count: 0
- backoff: 0
I've tested it manually by setting different values of a timeout for specific service tests. 
I would like to use the functionality from this PR for https://github.com/badges/shields/issues/2688.

An option to retry a failed service; test on [dynamicxml]

---

core/server/server.js
core/server/server.spec.js

In Issue #3273 Prouser123 said to just `Access-Control-Allow-Origin: *` have as a header to every request.
I did exactly that. I have confirmed that this works by using an [heroku app](https://shields-cors.herokuapp.com/) and a [workshop file](https://steamcommunity.com/sharedfiles/filedetails/?id=1875923653) running the changes.
I don't know whether or not this is the correct method but it works for me.

Add CORS Header to every request

---

services/version.js
services/version.spec.js

Closes #4172 
We were previously using [semver's](https://github.com/npm/node-semver/) `rcompare` function which AFAICT does not include semver build qualifiers in the comparison. This updates our `latest`version comparison to leverage `semver`'s `compareBuild` function instead which, as you may suspect, does include the build qualifiers 😉 
https://github.com/npm/node-semver/blob/07244f913d0502d9400a88629710517ca9b7d702/semver.js#L645-L665
I've confirmed this fixes the version issue we were seeing in #4172 for `pub`, but also running the service tests for other service classes that leverage this same `latest` helper function

honor build qualifiers in latest version comparisons, run [pub Debian GemDownloads GitHubRelease GitHubTag PackagistVersion]

---

.circleci/config.yml

Agreed in https://github.com/badges/shields/pull/4166#issuecomment-541414778, this PR enables retries in service tests on CI. Similar change in daily test: https://github.com/badges/daily-tests/pull/15
I think it solves https://github.com/badges/shields/issues/2688.

Enable retries for service tests on CI

---

services/wordpress/wordpress-downloads.service.js
services/wordpress/wordpress-downloads.tester.js

I've cleaned up the `wordpress-downloads` service
I've also added an interval for theme downloads and removed unnecessary `DownloadsForInterval` function.
As well as added tests for the interval theme downloads and some missing year interval tests.

Refactor [wordpress] downloads and add interval to theme downloads

---

services/crates/crates-base.js
services/crates/crates-downloads.service.js
services/crates/crates-downloads.tester.js

Summary of the changes:
* Added a 'recent downloads' badge for Crates.io.
* I exposed it at `/crates/dr/:crate` (r for recent), as this seemed consistent with the existing routes in that namespace.
* The data for recent downloads is only available for the crate as a whole, not individual versions, so I made the service bail out early with an error if you try to do that, to avoid unneccecary calls to Crates.io.
* Cleaned up some of the existing code.
* Updated the examples.
* I left `/d/:crate/:version` out of the examples, because it does the same thing as `/dt/:crate/:version` and the latter makes more sense to me. The URL still works, though.
* The URLs in the examples now include the relevant variants instead of `:variant` - this seems to play nicer with the modal editor.
Hopefully …

Add Crates.io recent downloads badge (fixes #4186), run [Crates]

---

services/swagger/swagger.service.js
services/swagger/swagger.tester.js

The current used endpoint of swagger.io changed to a new one. See https://github.com/swagger-api/validator-badge. In their ReadMe they changed the URL to another subdomain. This new subdomain can also validate OAS3 Specs (as well as OAS2)

Adjust new [swagger] endpoint

---

services/homebrew/homebrew-cask.service.js
services/homebrew/homebrew-cask.tester.js

I went for the '/' route to distinguish regular and cask formulas, much like many other services
both regular and cask services are similar in implementation, but different schemas and api routes make it quite hard to find any common code to refactor, so I decided to leave it as it
this closes #1638

add [homebrew] cask service

---

services/maven-central/maven-central.tester.js
services/maven-metadata/maven-metadata.service.js
services/maven-metadata/maven-metadata.tester.js

This PR proposes a fix to #4188, where version numbers from `maven-metadata.xml` get trimmed erroneously in the `maven-metadata` service.
The fix is directly adapted from #3935 (done to `maven-central` by @reda-alaoui).

[MavenMetadata] should use version as string (#4188), also run [MavenCentral]

---

core/server/server.js
core/server/server.spec.js

Refs #4227 #4173 #4252
This is one of the two code changes that touched a lot of services which were part of the last deployment that preceeded the resource spikes/slow response times on the badge servers. 
Though we still don't know whether _any_ of the commits in that deployment played a role, opening this in case we want to try a deployment without this change to test/validate
cc @paulmelnikow

revert cors header injection #4171

---

services/version.js
services/version.spec.js

Refs #4227 #4173 #4253 
This is one of the two code changes that touched a lot of services which were part of the last deployment that preceeded the resource spikes/slow response times on the badge servers. 
Though we still don't know whether _any_ of the commits in that deployment played a role, opening this in case we want to try a deployment without this change to test/validate
cc @paulmelnikow

revert version comparison updates #4173, run [pub Debian GemDownloads GitHubRelease GitHubTag PackagistVersion]

---

frontend/components/markup-modal/markup-modal-content.tsx

A tiny code change, but a nice visual impact. Fixes #4170.

Align documentation to the left

---

core/base-service/base.js
core/base-service/base.spec.js

This should make it easier to debug #3784.

When serviceData fails validation, include the service class in the stack trace

---

README.md
services/github/github-hacktoberfest.service.js
services/github/github-hacktoberfest.spec.js
services/github/github-hacktoberfest.tester.js

Fixes #4298 
I also removed our Hacktoberfest badge from our readme now that we've transitioned into November. 
Related aside, while working on this I find myself wondering what this badge should look like outside October/Hacktoberfest. It looks like it will only display the `is over!` message if there are no `hacktoberfest`-labeled issues, there were no PRs opened during October, and October has ended.
Would it make sense to display `is over!` after Hacktoberfest has ended regardless?

fix [GitHubHacktoberfest] service test

---

package-lock.json
package.json

The latest release contains a handful of icons that are widely used in the industry, namely: C, arxiv, Notion, Zoom, etc.

Bump simple-icons from 1.19.0 to 1.19.1

---

services/github/github-deployments.service.js
services/github/github-deployments.spec.js
services/github/github-deployments.tester.js

My first attempt to add a badge here :) Few things worth mentioning:
- I could not find a good category, so I picked 'other'.
- I could not find a colouring scheme that fits deployments, so I created one.
- I tried to figure out how `*.tester.js` works, but the [documentation](https://github.com/badges/shields/blob/master/doc/service-tests.md) was not clear enough for me to do anything with (I still have no clue what `get()` is doing, and how to add anything to it). So I did not add any.
Btw, the [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) is very awesome and well written; thank you for that.
Curious what you think of this!
In case you want to test how the badge looks, you can use https://github.com/OpenTTD/website …

Add [GithubDeployments] badge (#4477)

---

services/teamcity/teamcity-build.service.js
services/teamcity/teamcity-build.tester.js

Build status is currently used as a pass through, so remove
regex, because it causes unnecessary failures.
Fix #4486

Fix [TeamCity] build status text schema

---

package-lock.json
package.json

Apparently v1.10.8 of `start-server-and-test` requires Node 10.x+ due to transitive dependencies
https://github.com/badges/shields/pull/4600#issuecomment-581162776

deps: pin `start-server-and-test` to 1.10.7

---

services/github/github-api-provider.integration.js

Given we know this is being caused by strange behaviour of an external service and we've got a PR in progress to fix it, lets just skip it for now so we can actually merge stuff. We can re-enable it once we've decided on the way forward in https://github.com/badges/shields/pull/4590

skip flakey test

---

.dependabot/config.yml

I'm starting to lose track of which dependencies we want to avoid merging.
Until we can sort out our production environment, lets add them all to [ignored_updates](https://dependabot.com/docs/config-file/#ignored_updates). This will stop dependabot from opening PRs to upgrade to these dependency versions. As we find more, we can add additional entires.
Once we get that upgrade done, we can remove them all and get back to these upgrades.

tell dependabot not to offer incompatible upgrades

---

.dependabot/config.yml

Correct the version number used for `start-server-and-test` in the dependabot ignore list as the change from v1.10.7 to v1.10.8 drops support for Node 8.x
Refs https://github.com/badges/shields/pull/4619#issuecomment-583710306

update dependabot ignore list

---

core/service-test-runner/pull-request-services-cli.js

use header for service test runner auth; test on [npm]

---

.dependabot/config.yml
package-lock.json
package.json

Removed in https://github.com/badges/shields/pull/2906/files
- @babel/plugin-proposal-class-properties
- @babel/plugin-proposal-object-rest-spread
- @babel/preset-env
Built in:
- url
No usage detected:
- mkdirp
- ~react-error-overlay~
- walkdir

Remove a couple of unused dependencies

---

services/wercker/wercker.service.js

Close #4715 
Adds inline documentation on the Wercker CI badges to provide guidance to users on the need to use the application id (and not the wercker badge key) and how they can lookup the app id

add inline wercker ci docs

---

services/jenkins/jenkins-plugin-installs.tester.js

Version 1.27-DRE1.00 of View Job Filters no longer seems to be a thing:
https://stats.jenkins.io/plugin-installation-trend/view-job-filters.stats.json
This PR switches the test to a different plugin with a similarly styled version string.

Fix failing [JenkinsPluginInstalls] test

---

.circleci/config.yml

Fix: https://github.com/badges/shields/issues/4719
Remove caching of node_modules in CI because it's unused when using `npm ci`, the `node_modules` folder being deleted when using that command. 
According to latest run times, this will save up to 30 seconds per CI job.
Another caching strategy can later be implemented (ie: ~/.npm folder).

Removed unused node_modules caching in CI

---

services/treeware/treeware-trees.service.js
services/treeware/treeware-trees.tester.js

This is related to https://github.com/badges/shields/issues/4728, it adds a badge for the [Treeware](https://treeware.earth) project.
The badge this adds contains tests, and displays the trees that have been planted by a package (based on a referer hash).

Add [Treeware] badge

---

services/jetbrains/jetbrains-rating.service.js
services/jetbrains/jetbrains-rating.tester.js

Hello! Please review this PR - first time doing node development, but followed existing JetBrains badge patterns among other badges. Added tests and tested via the local web interface.

Adding badges for JetBrains Plugin Ratings, run [JetBrainsRating]. #4897

---

services/nexus/nexus.tester.js

Fixes #4903. Tests were failing because `v2.11.0.rc1` does not match `/^v\d+(\.\d+)*([-+~].*)?$/`.
I've changed the test data rather than the regex. Unless I'm missing an obvious trick, the latter would be quite hard to change without making validation significantly looser. The obvious solution, `/^v\d+(\.\d+)*([-+~.].*)?$/` (extra dot in the allowed char list) would start validating strings such as `v2.11.0€rc1`, as it would capture from the previous dot - it would be pretty much equivalent to `/^v\d+(\.\d+)*(.*)?$/`.
Versions in the `v2.11.0.rc1` format are quite rare anyway, I figured there was little value in changing the validator for such an edge-case, but I can change things if you disagree!

Fix failing [Nexus] tests

---

services/codeclimate/codeclimate-analysis.tester.js
services/codeclimate/codeclimate-coverage.tester.js

These service tests have been failing for a few days, there no longer seem to be any test reports for the Jekyll project. Hopefully, they won't break again anytime soon with one of Code Climate's own repositories.
I've also added a link to the [explore page](https://codeclimate.com/explore); their UI has changed and I struggled to find it.

Fix [CodeclimateCoverage] tests

---

core/server/influx-metrics.spec.js

@calebcartwright [noticed](https://github.com/badges/shields/issues/4930#issue-604428004) errors regarding metrics logged by the daily tests. It was introduced in https://github.com/badges/shields/pull/4874 and we can easily get rid of them. 
Before:
```
NODE_CONFIG_ENV=test node_modules/.bin/mocha core/server/influx-metrics.spec.js
Influx metrics
"metrics" function
✓ should use an environment variable value as an instance label
✓ should use a hostname as an instance label
✓ should use a random string as an instance label
✓ should use a hostname alias as an instance label
startPushingMetrics
✓ should send metrics
sendMetrics
0422180208 Error: Cannot push metrics. Cause: NetConnectNotAllowedError: Nock: Disallowed net connect for "shields-metrics.io:80/metrics"
at InfluxMetrics.sendMetrics …
```

Do not log errors in influx tests

---

config/custom-environment-variables.yml
config/default.yml
core/server/server.js
services/discord/discord.service.js

There's more details on the underlying issue in our Discord channels, but for a tl;dr.. 
Discord throttles calls to their API, and they'd whitelisted our 3 OVH servers previously to allow us to get the requisite data. When we routed img.shields.io traffic over to our Heroku environment we lost that whitelisting and our badge servers (on Heroku) hit the rate limits pretty quickly resulting in `invalid` for all our Discord badges.
This is a temporary fix to get the Discord badges working by having our Heroku-based badge servers use the OVH servers as a proxy to get the Discord data.

Get data for [Discord] badges via OVH server proxies

---

.circleci/config.yml
badge-maker/CHANGELOG.md
doc/TUTORIAL.md
doc/self-hosting.md

Refs #4977
Refs #3404
Refs #4973
I haven't bothered to update the reference in https://github.com/badges/shields/blob/master/doc/production-hosting.md as that whole doc needs revamping. I'll deal with this as another PR
My thinking here is while we are deployed on node 10 and we want to upgrade to 12 soon, those are the two most important runtimes and that's what we should run our tests on. Once we're on to 12 in production, we can switch to tracking latest again. I think running the core/service tests against 3 runtimes bloats the matrix too much.

Update test matrix and docs

---

core/server/server.js

We're still seeing a few "Token pool is exhausted" errors at the moment the dynos are coming up. I'm wondering if this might help.
Ref #3771

Fill GitHub token pool on startup

---

services/check-services.spec.js

Refs (and _may_ resolve) #4930
It seems that when running with `nyc` coverage enabled that `checkNames` is pretty consistently exceeding mocha's default 2 second timeout which is causing failures in the daily-tests job
https://github.com/badges/shields/blob/d9c483abbebb32b3619e443f2505adfe2f47d8db/services/check-services.spec.js#L11-L13
https://app.circleci.com/pipelines/github/badges/daily-tests/196/workflows/fbf25f75-8ab5-4f77-821f-1d120d38d555/jobs/1091/steps

increase timeout on unique service names test

---

package.json

`git add` is no longer needed. We overlooked this one in https://github.com/badges/shields/pull/5022

remove git add from lint-staged action

---

package-lock.json

Running `npm audit fix`automatically resolves a bunch of security issues in transitive dependencies.
We were not able to do this while we were still tied to node <10 versions only, but I think now we're clear to update them all.

resolve some vulnerability warnings

---

services/steam/steam-workshop.service.js
services/steam/steam-workshop.tester.js

This adds the /steam/update-date badge, to also provide a badge that shows the date of a file on steam when it was last updated.
The code is pretty much straight forward, equal to the `steam/release-date` badge, except that it reads out `time_updated` instead of `time_created`.
If there is anything you would like to have changed, please let me know! 
Thank you for this amazing project!

Add the /steam/update-date badge, run [steam]

---

doc/TUTORIAL.md

I found a broken link in the tutorial document where it mentions the additional documentation for the URL conventions. changed this to a relative link to the Markdown File in question.

Fixed Badge Spec URL in Tutorial

---

package-lock.json

We missed a couple of updates to this:
* https://github.com/badges/shields/pull/5189 (I think the submitter manually edited the lockfile rather than using npm and I didn't notice)
* https://github.com/badges/shields/pull/5175 dependabot updated the `package.json` in `/badge-maker` (which doesn't have its own lockfile because its a package) but didn't update the root lockfile. This is always going to be an issue for dependabot updates in badge-maker. In fact, its probably happened before and we forgot..

fix lockfile

---

core/base-service/base.js
services/twitch/twitch-base.js
services/twitch/twitch.spec.js

Fixes #5214.
We broke Twitch badges back in #4729. I mostly fixed things in #4781, but I missed out on bit with led to the `Client-ID` not actually being set. The impact of this mistake only became visible recently for reasons outlined in #5214.
The improved spec test should prevent any regressions in the future.

Fix [Twitch] Client-ID header

---

services/ansible/ansible-quality.tester.js

Fixes #5283 
Apparently there's been some upstream changes in the API which is now returning a proper 404 response code in the unknown project id scenario whereas before it was a 200 response with a body that was identical to a valid/known project that had no score. 
This updates the existing test to handle the invalid project scenario and also adds an extra test to cover the `no score available` scenario (https://galaxy.ansible.com/s2504s/datadog). This was a project that was referenced as an example ~18 months ago when the badge was first added, so it seems to be a sufficiently stable test target.

fix [ansible] quality service test

---

doc/production-hosting.md

It doesn't seem worth calling out the OAuth app anymore, since it's now part of the badges org. 🙌

Update Cloudflare access + remove OAuth app

---

services/npm/npm-base.js
services/npm/npm-version.tester.js

closes #5364
@paulmelnikow Your suggestion did the trick. I implemented a test to cover this scenario.

[npm] Support tags containing slashes (/)

---

core/base-service/base-graphql.spec.js
core/base-service/base-json.spec.js
core/base-service/base-svg-scraping.spec.js
core/base-service/base-xml.spec.js
core/base-service/base-yaml.spec.js
core/base-service/base.js
core/base-service/base.spec.js
core/base-service/deprecated-service.js
core/base-service/loader-test-fixtures/valid-array.fixture.js
core/base-service/loader-test-fixtures/valid-class.fixture.js
core/base-service/loader-test-fixtures/valid-object.fixture.js
core/base-service/redirector.js
doc/TUTORIAL.md
doc/rewriting-services.md
services/amo/amo-base.js
services/amo/amo-downloads.service.js
services/amo/amo-rating.service.js
services/amo/amo-users.service.js
services/amo/amo-version.service.js

Since we've upgraded production to Node 12 (#5436) we can finally adopt static fields!
This starts the process by updating core and one of the service families.
I've left the static fields alone in the badge library since for now we're targeting Node 10+.

Adopt static fields in [amo] and core

---

services/github/github-workflow-status.service.js
services/github/github-workflow-status.tester.js

This adds support for the `event` query string parameter to the GithubWorkflowStatus service.
Closes #5439 
According to the [Badge URL guidelines](https://github.com/badges/shields/blob/master/doc/badge-urls.md), parameters like `branch`, etc. should be part of the URL's path. Does this also include parameters like `event` here? The reason why I've added this as a query string is that an event can be specified without a branch. Having two optional route path parameters next to each other, namely branch and event, is a bit weird. I've checked other services for similar patterns and couldn't find anything.
Also, to make `npm run test:services -- --only=GithubWorkflowStatus` succeed, I had to fix the workflow name in the tests, as the "Main workflow" doesn't exist on the …

[GithubWorkflowStatus] add event query string parameter

---

README.md

Whilst [badgerbadgerbadger](https://github.com/badges/badgerbadgerbadger) technically still works, it hasn't been updated for many years and generates badges that we have since deprecated (see https://github.com/badges/badgerbadgerbadger/issues/88 for example).
I suggest we stop advertising it in the README and replace it with [poser](https://github.com/badges/poser). Any ideas of other related projects are welcome!

Remove badgerbadgerbadger from related projects and add poser

---

README.md

This bit of the README was left behind in one of our refactors.

Update documentation about snapshot tests

---

services/chrome-web-store/chrome-web-store-rating.service.js
services/chrome-web-store/chrome-web-store-rating.tester.js

closes #5475
the next release of node-chrome-web-store-item-property will drop the `ratingCount` and `ratingValue` properties

deprecate [ChromeWebStoreRating] badges

---

badge-maker/lib/color.js
badge-maker/lib/color.spec.js
badge-maker/package.json
package-lock.json

This PR makes the code in _color.js_ slightly more complex, but gets rid of a dependency both in the main Shields server and the NPM package.
I ran a micro-benchmark to check that performance wasn't affected negatively (careful, you have to change to badge URL in _scripts/benchmark-performance.js_ to be a non-standard Shields colour): the new `isCSSColor` is actually ~10% faster on my machine - though as we're only talking about a few μs, I wouldn't treat this as a strong argument in favour of the PR.

Rework isCSSColor check

---

services/wordpress/wordpress-base.js
services/wordpress/wordpress-platform.tester.js

Related to #5493, the API Update has been split out into its own PR, to reduce the demand on the maintainers. This should also fix #5499 
The API change, required a couple of changes to schema and request, and related testing in platform tester. I also took this chance to split the plugin and theme schemas into their own separate entities to make adding the new badges from #5493 easier, however it doesn't introduce any of the schema required for those badges.
I have also `.required()` the schema as we should always receive those items for the current badge set, however I am open to exploring the option of not requiring them at the schema but dealing with errors in the badges instead.
I will handle converting service classes to static props as I continue to submit PR's for other aspects of …

[WordPress] API Update

---

services/github/github-commit-activity.tester.js
services/test-validators.js

I know there's some history behind why certain test validators like `isMetricOverTimePeriod` reject a value of `0` and I understand why we'd want a validator that required a positive integer. 
However, sometimes the value genuinely is 0 and historically the strategy to avoid those cases causing spurious service test failures in the past was to attempt to pick a test target that was unlikely to result in a 0. That doesn't always work though, for example from the daily test run a little earlier today: https://app.circleci.com/pipelines/github/badges/daily-tests/481/workflows/8627f386-28e0-46fb-b19c-d8c6d04b4cde/jobs/1379
I've opened this PR for consideration, which adds a _new_ validator for matching 0/timePeriod, that service tests could opt into using if needed with something …

add a validator for 0/{{time period}}, run [GitHubCommitActivity]

---

README.md

Some minor tweaks made to the contributing section to include the badge for Hacktoberfest 2020, and also included the one for 2019 just for fun. Happy to make changes if folks see fit, mostly just want to get the 2020 badge out there!
[![Hacktoberfest 2020](https://img.shields.io/github/hacktoberfest/2020/badges/shields?label=hacktoberfest%202020)](https://github.com/badges/shields/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest)
[![Hacktoberfest 2019](https://img.shields.io/github/hacktoberfest/2019/badges/shields?label=hacktoberfest%202019)](https://github.com/badges/shields/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest)

Add Hacktoberfest badges to readme

---

package-lock.json

Follow up from #5533. Apparently _package-lock.json_ needed manual updating to fully get rid of the dependency there as well.

Remove camelcase from package-lock.json

---

services/jsdelivr/jsdelivr-hits-github.tester.js
services/jsdelivr/jsdelivr-hits-npm.tester.js

https://app.circleci.com/pipelines/github/badges/daily-tests/495/workflows/4dcc5a2d-179a-40da-8956-0ffb7c3540fe/jobs/1393
Another batch of failing tests due to 0/week 
Leveraging a similar approach as #5583 for this one vs the approach in #5618 as I've found the jsdelivr service to be trickier to find good test targets

fix [jsdelivr] service tests

---

services/criterion/constants.js
services/criterion/criterion.service.js
services/criterion/criterion.tester.js

While adding support for the "no change" status I noticed the criterion api updates I made last week broke your tests.  We added a "noise level threshold" to the status calculation because the runner may have something going on while a benchmark is running which makes the performance _appear_ to have regressed.  Now if a benchmark is within, for example 2% of the previous measurement, we report "no change", instead of "regressed".
Thank you for helping out with the criterion badge, you are more than welcome to assign issues related to criterion to me in the future.

[Criterion] Add support for "no change" status

---

dangerfile.js

"serverSecrets" is no longer used to access auth in services, so it no longer makes sense to include it in this rule.
Ref #3393

Clean up Danger rule for serverSecrets

---

config/shields-io-production.yml
core/server/monitor.js
core/server/server.js
services/github/auth/acceptor.js
services/github/auth/acceptor.spec.js
services/github/auth/is-valid-token.js

Tokens are now shared exclusively through the Redis DB.
Ref #3393

Remove obsolete peer-to-peer GitHub token-sharing code

---

.vscode/extensions.json

Frequently when I open Shields in VS Code it pops up a message asking if I want to install the recommended plugins. I think for Shields to recommend a plugin, we should agree it is pretty much essential for working on the project.
I have never used any form of EditorConfig. I imagine it may be useful for some users on some platforms, though for the majority of users, it is definitely not essential.
Perhaps the users who need it (Windows users?) know who they are and can take it on themselves to install the plugin if PRs cause them problems.
Certainly open to discussion if people feel otherwise!

Remove EditorConfig from recommend VS Code plugins

---

doc/TUTORIAL.md

I found a wrong anchor during I'm trying to create a new badge.
Because of trailing whitespace, the link became `#45-write-tests-` instead `#45-write-tests`.

Fix wrong anchor for writing tests document

---

core/server/server.js

I tested this on staging and it seems to work as intended!
Ref #3027

Fix REQUIRE_CLOUDFLARE for Heroku

---

__snapshots__/make-badge.spec.js
badge-maker/lib/make-badge.spec.js

I’m running into some strange issues working on badge-maker in #5696, where the images look good but the snapshots have changed in unexpected ways. I’m finding them a little tricky to debug.
This saves the prettified snapshots instead, which I think will make them easier to compare and debug. They may have to be updated when we upgrade prettier.
I also inlined a few things in the test file.

Prettify the SVG snapshots (and a couple cleanups)

---

badge-maker/lib/index.js
badge-maker/lib/make-badge.js
badge-maker/lib/make-badge.spec.js
core/base-service/base-svg-scraping.spec.js
core/base-service/base.spec.js
core/base-service/coalesce-badge.js
core/base-service/coalesce-badge.spec.js
core/base-service/examples.js
core/base-service/legacy-request-handler.js
core/server/server.js

There is an internal `makeBadge()` function which is called from a few places in the server and from the public `makeBadge()` function which is a light wrapper. (Eventually we want to dogfood the public API: that's the work of #4950, and this helps with it by aligning the interfaces.)
Related to that is #3370, which is about aligning the `serviceData` schema (i.e. the result of `handle()`) with the public `makeBadge()` function.
A legacy quirk of the _private_ `makeBadge()` function is accepting a `text: ['label', 'message']` array instead of separate `{ label, message }` props like the rest of the codebase. `coalesceBadge()` has to translate from `{ label, message }` to `text: ['label', message']`. This removes that bit of indirection.
It also rewrites most of the tests of …

Align `label` and `message` props of `coalesceBadge()` with internal `makeBadge()`

---

frontend/pages/endpoint.tsx

If your endpoint specifies the `logoSvg` property you can _not_ specify the `logoColor` property. This will result in the 'invalid properties: logoColor' badge.
Related to #4749

Specifying logoColor does not work with logoSvg

---

badge-maker/lib/badge-renderers.js
badge-maker/lib/make-badge.js

These are aimed at improving readability and a bit of DRY.

A few straight refactors in badge-renderers

---

lib/logos.spec.js

This PR adds a test which verifies that `lib/logos.js#getSimpleIcon` properly handles `get` value. Related to https://github.com/badges/shields/issues/4263 and https://github.com/badges/shields/issues/4016.

getSimpleIcon handles 'get' icon

---

services/wordpress/wordpress-base.js
services/wordpress/wordpress-platform.service.js
services/wordpress/wordpress-platform.tester.js

Related to #5493, this PR refactors the existing class for Plugin required WP version to also cover themes. Also in this is a slight refactor of Plugin Tested Version class to convert to static props.
Sorry the #5493 split up has been pending a while, been fairly busy with work and starting uni!

[Wordpress] Added Theme Required WP Version Badge & refactor

---

services/docker/docker-fixtures.js
services/docker/docker-version.service.js
services/docker/docker-version.spec.js

Fixes https://github.com/badges/shields/issues/4911.
Changelog:

[Docker] version badge: Add architecture param

---

services/website/website.service.js
services/wercker/wercker.service.js
services/wheelmap/wheelmap.service.js
services/wordpress/wordpress-platform.service.js
services/youtube/youtube-base.js
services/youtube/youtube-comments.service.js
services/youtube/youtube-likes.service.js
services/youtube/youtube-views.service.js

This should end the refactor for #5555.
I did left the `static get examples() { ... }` in YouTube services as those are computed values.
Searching for `static get ` still gives some results that could be migrated to `static variable = ...`, should I address theses ?

Refactor `static get`:  [website wercker wheelmap wordpress youtube]

---

services/github/github-hacktoberfest.service.js

I was a little reckless with the copy/paste when updating our Hacktoberfest badge to work with the current year (it was previously hardcoded for 2019) and that resulted in a small bug in how the determination of the start date was made (refs #5637).
This PR corrects that by using October 1st (UTC) precisely

Fix calculation of start date for [GitHubHacktoberfest] badge

---

services/nuget/nuget-v3-service-family.js
services/nuget/nuget-v3-service-family.spec.js

Hi :wave:!
In this PR I refactored (and tested) the `nuget-v3-service-family`, mainly:
1. Simplified the `fetch` function,
2. Introduced the `transform` functions in each of the base implementations,
3. Tested both.
We talked about the changes with @calebcartwright in my previous PR.
There is also the possibility to unit-test the `buildRoute` and `apiUrl` functions, but I'm not quite sure whether it is worth it. We would need to expose them from the module, but the service tests validate it sufficiently. If you think otherwise then let me know and I will add these.
We could also do the same for `v2` but the `transform` method would be really a one-liner (as we get the necessary data directly from the API) and I don't think it is worth it.

Refactor the [nuget myget] service

---

package.json

not sure how we've managed to not notice this for so long :thinking:

lint/format typescript files in pre-commit hook

---

.github/workflows/auto-approve.yml

Gatsby changed their changelog format a bit. This should get us back to auto-closing gatsby PRs that don't do anything
https://github.com/chris48s/approve-bot/commit/d6963dd399d1424c7d8ec43fd07c0a6b84d83345

bump approve bot

---

doc/production-hosting.md
package-lock.json
package.json
server.js

As discussed in https://github.com/badges/shields/discussions/5773.

Drop .env support

---

config/shields-io-production.yml

Following on from the discussion in https://github.com/badges/shields/issues/5014#issuecomment-735231731 I have set up a page rule in CloudFlare to redirect `img.shields.io/` to `shields.io/` so this redirect is now being handled by CloudFlare before the request hits heroku.
This means we can now remove this setting without changing that behaviour.
I haven't set one up for `www.` I don't think serving the website on `www.` without redirecting is a particularly bad thing tbh, but I can add a rule for that too if anyone feels particularly strongly about it.
If someone can give me a ✔️ on this I will deploy and pick up the switchover tomorrow.

remove redirectUrl from prod settings

---

services/npm/npm-dependency-version.service.js

Base URL used to mount the NPM **peer** dependency version badge was pointing to **dev** dependencyies instead.

Fix base URL for npm peer dependencies

---

services/jetbrains/jetbrains-base.js
services/jetbrains/jetbrains-downloads.service.js
services/jetbrains/jetbrains-downloads.tester.js
services/jetbrains/jetbrains-rating.service.js
services/jetbrains/jetbrains-rating.tester.js
services/jetbrains/jetbrains-version.service.js
services/jetbrains/jetbrains-version.tester.js

This PR implements the solution I suggested in https://github.com/badges/shields/issues/5946#issuecomment-748237206 - use the new API if we've got a numeric ID. Fall back to the old (IntelliJ only) API otherwise.
This is a bit messy because the old API is XML-based whereas the new one uses JSON so I've made a base class that inherits from `BaseXmlService` and given it some methods to call/parse/validate JSON. At some point in future when the XML API is deprecated and we drop the string ID format we can just switch everything to inherit from `BaseJsonService` and tidy this up a bit.
closes #5946

use new plugin api for [jetbrains]

---

.github/workflows/deploy-docs.yml
package.json

Refs https://github.com/badges/shields/issues/5944
This bit adds an action to build the docs and push the output to gh-pages on a push to master. Once we get this merged, I'll look at swapping over the CNAME in CloudFlare and shutting down netlify (interestingly I think the docs have stopped deploying to netlify properly at some point and nobody noticed - hopefully putting them here will make it more obvious that they're working)
Note: its hard to verify this works in PR form, but I have tested this on a fork

deploy docs to gh-pages

---

services/spiget/spiget-rating.service.js

Spiget rating is too long, because we only need a few decimal places and the rests are pointless.
Spiget API that shields is using returned a float number, and it was rendered without sanitization.
When rendering shields, we round the rating to at most 2 decimal places.

Fix [Spiget] rating display issue

---

services/github/github-issues-search.service.js
services/github/github-issues-search.tester.js

Refs #5948
Open to feedback on this, but I decided to implement two variants of this badge:
* `/issues-search?query=`
* `/issues-search/:user/:repo?query=`
`/issues-search?query=` is more general. Because it doesn't require a repo to be specified, it allows you to implement queries like "all issues raised by user X in any repo" or "all issues with label Y in organization Z" for example.
I decided to also add a special-case route for `/issues-search/:user/:repo?query=`. This is less flexible, but I think it is worth having a route that allows the query param you paste in to be the exact same query you will construct in the filter box on your issues page (https://github.com/badges/shields/issues ) without having to remember to append `repo:badges/shields` to the query. All our existing …

add generic [GithubIssuesSearch] badges

---

services/github/auth/admin.js
services/github/auth/admin.spec.js

I merged #5998 deployed and invalidated the relevant cache in CF. Turned out CF still caches the "Invalid secret" response, so if you hit the endpoint without auth, you then can't log in afterwards 🙃 This PR does a few more things:
- Serve the "Invalid secret" response with an appropriate status code (not 200 OK)
- Explicitly set `cache-control: private` on the "Invalid secret" response
- Fix an outdated comment
- Add some tests for this (note the 'password is missing' test only runs if you invoke with `SLOW=true`)

github auth endpoint improvements

---

.github/workflows/tag-release.yml

This is one of the bits we need for issue #5866
Also refs #6049
When we merge a PR which is labelled with "release", this will create a tag called `server-YYYY-MM-DD` (for today's date). To show this working (and test it), I set up a demo repo using the action:
- https://github.com/chris48s/release-action-test
- https://github.com/chris48s/release-action-test/pull/1
- https://github.com/chris48s/release-action-test/pull/2
- https://github.com/chris48s/release-action-test/actions
- https://github.com/chris48s/release-action-test/releases
I have also created a release label for use with this: https://github.com/badges/shields/labels?q=release

add a github action to create tags from labelled PR

---

CHANGELOG.md

Refs #5866 #6069
The reason why I'm submitting this is that for the next part of #5866 I am going to write an action which
- Looks at what changed since our last `server-YY-MM-DD` tag
- Generates a changelog entry
This will be easier to develop if we can assume there is already a changelog file we can append to and the repo already has one `server-YYYY-MM-DD` tag (hence the release label). This PR just creates that baseline to work from.

Start a changelog, create a tag

---

.github/ISSUE_TEMPLATE/config.yml

We are seeing multiple issues per week asking "when will X icon be available" or "why doesn't Y icon work". While @calebcartwright  is exercising the patience of a saint replying to them all with a link to https://github.com/badges/shields/discussions/5369 maybe this will help :pray:

link to SimpleIcons update schedule on 'new issue' page

---

core/base-service/base.js
core/base-service/base.spec.js

I was trying to debug an issue earlier and spotted this issue - if we're making an API call with a query string, we don't display it properly in the logging output so we have to add debug statements to the code and assemble it by hand. I think I've actually hit this before, but today it annoyed me enough to actually fix it :)
Before:
```
...
Request  🏹 
https://repo.magicmq.dev/service/rest/v1/search
Response status code  🎯 
200
...
```
After:
```
...
Request  🏹 
https://repo.magicmq.dev/service/rest/v1/search?group=dev.magicmq&name=itemapi&sort=version&prerelease=false
{
"headers": {
"Accept": "application/json"
}
}
Response status code  🎯 
200
...
```

improve debug output for API calls with query strings

---

services/github/github-issues.tester.js

Fixes #6105 
Seems the upstream repo and associated package have been yanked from the internet. I figured it would be easier to just create my own repo with a label to match the original case/bug report instead of perusing GH to find a repo that had the same type of label

fix [GitHubIssues] service test

---

services/github/github-lerna-json.tester.js

Fixes #6106 
Babel has stopped using Lerna, apparently. The test with the branch was still passing because Babel have switched from `master` to `main` already, and their older `master` branch still had the `lerna.json` file. Changing the target for both tests though to prevent future breakage, as there's no telling how long Babel may keep the old branch around

fix [GitHubLerna] service test

---

.github/actions/draft-release/Dockerfile
.github/actions/draft-release/action.yml
.github/actions/draft-release/entrypoint.sh
.github/workflows/draft-release.yml

Refs #5866
This PR adds an action which will
* run once a month (but also allow us to trigger it manually)
* generate a changelog we can manually review
* open a PR tagged with "release" which we can review/merge
Coupled with https://github.com/badges/shields/blob/master/.github/workflows/tag-release.yml merging the PR will create the release tag.
This will generate a PR something like https://github.com/chris48s/release-action-test/pull/5 . The commit messages on this test repo are mostly junk from when I was debugging the action - ours will look like.
```md
- add a github action to create tags from labelled PR (#6069)
- fix [wordpress] 'Can't generate version color for false' (#6072)
- Update self-hosting.md documentation for running with Prometheus (#6052)
- fix: remove erroneous …
```

add a GH action to generate a changelog and submit a release PR

---

services/feedz/feedz.service.js
services/feedz/feedz.service.spec.js
services/feedz/feedz.tester.js

:wave: 
[Last time](https://github.com/badges/shields/pull/5753) I missed one thing - the `items` in the registration response (at the first level) represent _pages_, and if you have enough versions, you will get multiple entries there.
This PR fixes that - it no longer expects a single page and it is now able to get versions from all the pages.

Fix [feedz] service in case the registrations page gets paginated

---

CONTRIBUTING.md
frontend/components/usage.tsx
services/dependabot/dependabot.service.js
services/dependabot/dependabot.tester.js
services/github/github-milestone-detail.service.js
services/github/github-milestone-detail.tester.js
services/github/github-milestone.service.js
services/github/github-milestone.tester.js
spec/SPECIFICATION.md

Related to #6096.
Twitch is also another badge that doesn't follow this, however, I'm suggesting #6158 as a resolution instead.

Allow links only for social badges, affects [GitHubMilestone Dependabot]

---

services/flathub/flathub.service.js
services/flathub/flathub.tester.js

Flathub now throws a 404 for package not found, like a well-behaved API :)

update [flathub] error handling

---

core/base-service/redirector.js
core/base-service/redirector.spec.js

This fixes a bug that causes `setHeader()` to throw an unhandled `TypeError` if the path of the URL we are redirecting to contains unescaped characters which are invalid for a HTTP header.
Note this is only the url path affected. The querystring was already encoded correctly
Refs https://sentry.io/organizations/shields/issues/1867642393

ensure redirect target path is correctly encoded

---

core/base-service/got.js
core/base-service/got.spec.js

There was always going to be something that slipped through the cracks.
Closes #6251

send custom user agent when using got

---

core/server/influx-metrics.js
core/server/influx-metrics.spec.js

refs  #4655
Nice bit of low hanging fruit here :green_apple: 
Because this is stand-alone utility code and not part of the services I haven't routed it through `fetchFactory`/`sendRequest`. I've just gone straight from request to got.

use got to push influx metrics

---

cypress/integration/main-page.spec.js
frontend/components/customizer/query-string-builder.tsx
package-lock.json

Fixes #6182.
When running the e2e tests, I noticed the following warning:
```
warning Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```
The changes to _package-lock.json_ should address that.

Prevent duplication of parameters in badge examples

---

doc/releases.md

Opening this as a draft, both because there's some additional discussion needed to determine if this is a route we want to take, as well as the fact that it'd likely need some additional wordsmithing, accompanying updates in some other files etc. in order to proceed
The core idea is to document the different things we release along with any relevant info. IMO this is quite beneficial for the sake of clarity for the self-hosting case, but will also be beneficial in others (documents an answer to questions like "how frequently do Shields.io deploys happen). This **heavily** steals from the great work @chris48s did in #6156 but with a proposed additional section from me on self-hosting.
Some outstanding questions I have:
- are there any objections to having this explicitly documented? it's …

Add docs for all types of releases

---

frontend/components/meta.tsx
package-lock.json
package.json

This patch uses the [fontsource libraries](https://github.com/fontsource/fontsource) instead of using Google Fonts
in order to provide the fonts in the frontend. This way the web frontend
becomes more private, since it no longer shared visitors IPs with Google
and might even loads faster since modern web browsers isolate site
caches from each other and can re-use connections with HTTP/2 instead of
setting up a new connection to Google.[1]
It's basically the next iteration of my previous PR[2], that no longer
relies on a tool to download the fonts separately, but uses a library
instead. It also relates to issues that have been opened before[3] and
should be easily handled and upgraded by the regular NPM package
tooling[4], solving all related problems to that.
1: …

Use NPM packages to provide fonts instead of Google Fonts

---

services/youtube/youtube-base.js
services/youtube/youtube-comments.service.js
services/youtube/youtube-likes.service.js
services/youtube/youtube-likes.tester.js
services/youtube/youtube-views.service.js

As part of #6276, I've submitted a request to increase our API quota for YouTube badges. As a response, they've raised three concerns about potential violations of the YouTube terms and services:
* they are unsure whether we're using one or multiple Google projects IDs for our API client. We're only using one, so I'll confirm that with them. This point should be resolved easily.
* they asked us to display a link to their Terms of Service:
> API Clients must display a link to YouTube's Terms of Service (https://www.youtube.com/t/terms), and they must also state in their own terms of use that, by using those API Clients, users are agreeing to be bound by the YouTube Terms of Service.
This seems like a fair thing to ask for, so I've done so in the documentation of all four badges.
* they …

Address compliance issues with [YouTube] API Services Terms and Policies

---

services/nexus/nexus-version.js
services/nexus/nexus.tester.js

The SNAPSHOT version pre-check wouldn't match a SNAPSHOT version that includes a hash (git hash, a default convention when using [`sbt-dynver`](https://github.com/dwijnand/sbt-dynver)). Incidentally, it would match versions with hashes that end with `0-9`, but not with `a-f`.
There was a test in `nexus.tester.js` that tested a version with a hash that passed because the hash ended with `0-9`.
i.e.)
Match
```
7.0.1+19-8844c122-SNAPSHOT
```
No match
```
7.0.1+19-8844c12a-SNAPSHOT
```

Support git hash in [nexus] SNAPSHOT version

---

core/server/server.js

It is almost as if there is a good reason we don't usually write raw socket code :thinking: 
Turns out curl, got and firefox were all fine with `\n`. Heroku is not feeling it and throws a 503.
This now returns the correct error from heroku e.g:
```
curl --include "https://shields-staging-pr-6386.herokuapp.com/badge/dynamic/json.svg?label=CDN%20Data&url=https://yacdn.org/global-stats&query=$.cdnData&colorB=blue"
```
(I've set the `shields-staging-pr-6386` app up with a 5 sec timeout)
I think switching the timeouts to return this response was a red herring when it comes to the performance issue we saw today but if we hit a problem, we can roll back.

Fix Request Timeout responses

---

core/server/monitor.js
core/server/rate-limit.js

We are currently experimenting with less but larger servers to run Shields.io. The rate limit is not pooled across servers, therefore we need to increase it when running less of them.

Increase server request rate limits

---

services/david/david.service.js
services/david/david.tester.js

We've had persistent issues with the David tests (and badges) for a while a now, and an unfortunate side effect of this has been that our daily service test runs have been in a constant state of red/failure for a very long time now. I worry that this constantly failing status of our daily service test runs are starting to defeat the purpose of their existence, as it's human nature to start to ignore the jobs (I confess I rarely check each of the two daily runs anymore because of this).
The root cause of the David failures were upstream issues with the platform that largely seem to have been resolved by some infrastructure/runtime environment changes there, but we're still getting test timeout issues (https://app.circleci.com/pipelines/github/badges/daily-tests/659/workflows/eb63b021-d2a6-4 …

increase [David] service test timeouts

---

services/docker/docker-build.service.js
services/docker/docker-build.tester.js

These badges have been broken since at least January of this year (refs #6107), and accordingly the respective service tests have been failing for that long as well. Even when this badge was working it was only geared towards _really_ old repositories that predated the DockerHub merge, and just about every user was forced to use the "newer" DockerCloudBuild anyway.
I see no point in keeping this badge around in a broken state, particularly since there's been zero news or movement from the upstream provider for 4 months now.
Closes #6107

deprecate [DockerBuild] service

---

.circleci/config.yml
scripts/run_package_tests.sh

We dropped compatibility for node 10 in version 3.0.0 of badge-maker but we've still been running the tests on it. Meanwhile, Node 16 has been generally available for a couple of months. Time to update the CI build.

run package tests on node 16, drop node 10 testing

---

core/base-service/base.js
services/twitch/twitch.service.js

We serve a lot of download and social badges (collectively download and social categories account for ~25% of the traffic we serve from Heroku) and we serve them with the default max-age (2 mins).
In a lot of cases the upstream providers cache these totals and we also often present them as rounded numbers e.g:
* `downloads | 20k`
* `stars | 3k`
I think we can get away with cacheing these for longer and serve more of these badge requests from downstream cache without noticeably downgrading service for most users. Lets try setting them to 15 mins and see how it goes.
I've decided to manually exclude twitch status from this and actually set a shorter max-age on it as "live now" seems like it need to be more immediate to be useful. I think all other download and social badges can use the new …

increase max-age for download and social badges; affects [twitch]

---

services/codecov/codecov.service.js

Flags Must consist only of alphanumeric characters, '_', '-', or '.' and not exceed 45 characters. 
Flag names will be validated against the following regex. ^[\w\.\-]{1,45}$
re #6653

fix: fix regex to match [codecov]'s flags

---

services/weblate/weblate-component-license.service.js
services/weblate/weblate-component-license.tester.js
services/weblate/weblate-entity-count.service.js
services/weblate/weblate-entity-count.tester.js
services/weblate/weblate-project-translated-percentage.service.js
services/weblate/weblate-project-translated-percentage.tester.js
services/weblate/weblate-user-statistics.service.js
services/weblate/weblate-user-statistics.tester.js

This adds [Weblate](https://weblate.org/en/) badges to the repository.
Weblate is a free and open-source crowd translation platform.
Currently, it adds 8 badges:
| Name | Description |
|---|---|
| Weblate project translated | The number of strings of a project that has been translated. |
| Weblate component license | The license that a particular project component is under. |
| Weblate components/projects/users | The total that exist on a Weblate instance. |
| Weblate user translations/suggestions/languages | The number of user has made/done. |
Examples:
I might make more badges later, but for now, I wanted to get these right.
* Depends on https://github.com/badges/shields/pull/6684

Add [Weblate] badges

---

package.json

Avoids weird async await errors when running service tests!
Follow-on to #6652

Verify that Node 14 is installed in development

---

package-lock.json
package.json

Have confirmed that `npm run coverage:report:open` still works.
Related: #6332

Replace opn-cli with open-cli

---

services/weblate/weblate-component-license.tester.js
services/weblate/weblate-entities.tester.js
services/weblate/weblate-project-translated-percentage.tester.js
services/weblate/weblate-user-statistic.service.js
services/weblate/weblate-user-statistic.tester.js

Addresses the comments left in https://github.com/badges/shields/pull/6712
* In each test suite, change all tests to use the default server except 1.
* Add a test to a third-party server.
* Replace the transform/adapter logic to map our keys to the API. 
Hopefully, this time we'll be all good, then I'll just have to do add authentication.
Thanks for all the help/advice to help me get things right, @calebcartwright. 
Edit: Aaaa, I hate myself. Forgot "[weblate]" had to be in the name of the PR, may have to rerun CI.

chore: refactor weblate code [weblate]

---

services/bugzilla/bugzilla.tester.js

This has been failing because https://bugzilla.gnome.org/ is no longer  a bugzilla instance. Replaced with a different example that gives us a 404

update [bugzilla] not found test

---

services/coverity/coverity-scan.service.js

After posting https://github.com/badges/shields/issues/4655#issuecomment-897061551 yesterday, I started looking at the strictSSL/proxy thing and on digging into it.. it might be a non issue. There are two services where we currently do something with the `strictSSL` param, and I think they're both now pointless. In this PR: coverity
We added this in https://github.com/badges/shields/pull/3336 to work around an upstream issue with coverity's SSL cert. This issue now appears to be fixed upstream: https://www.ssllabs.com/ssltest/analyze.html?d=scan.coverity.com&hideResults=on and the tests pass without it. I think it can just be dropped.

enforce strict SSL checking for [coverity]

---

services/jenkins/jenkins-base.js
services/jenkins/jenkins-build.service.js
services/jenkins/jenkins-common.js
services/jenkins/jenkins-coverage.service.js
services/jenkins/jenkins-tests.service.js

After posting https://github.com/badges/shields/issues/4655#issuecomment-897061551 yesterday, I started looking at the strictSSL/proxy thing and on digging into it.. it might be a non issue. There are two services where we currently do something with the `strictSSL` param, and I think they're both now pointless. In this PR: jenkins
I was looking into how to test this param and I realised this param has actaully been broken for a very long time. Any attempt to use this will throw "strict ssl is required" e.g: https://img.shields.io/jenkins/build.svg?disableStrictSSL&jobUrl=https%3A%2F%2Fjenkins-oss.wixpress.com%2Fjob%2Fmulti-detox-master In order to make it work, you have to remove https://github.com/badges/shields/blob/23c0406bedfc6930735e8f5ea75dfe34faf1f290/core/base-service/auth-helper. …

remove disableStrictSsl param from [jenkins]

---

services/twitch/twitch-extension-version.service.js
services/twitch/twitch-extension-version.tester.js

Closes #6899
If you're wondering about `color: '6441A4'` it's taken from [here](https://dev.twitch.tv/docs/extensions/designing#panel-extension-guidelines): `Twitch Purple #6441A4`.

[TwitchExtensionVersion] New badge

---

server.js

Since #6651, we no longer need the `eslint-disable import/order` statement and can tidy things up a little bit.

Tidy up server.js imports

---

Dockerfile

Docker build was running using NPM 6. It was probably fine but generating some warnings. This ensures we're running 7 or above and `lockfileVersion: 2` will definitely be parsed correctly.

use the right version of NPM in docker build

---

services/reddit/user-karma.service.js

The API schema validation made the obviously wrong assumption that karma values would be 0 or more, resulting in "Invalid Data Response" for users with negative karma points. The type is changed from nonNegativeInteger to anyInteger, as indicated in the issue.

Fixed [reddit] Negative Karma Issue

---

services/matrix/matrix.service.js

The Riot Matrix client was renamed to Element in July 2020 (https://element.io/blog/welcome-to-element/). This updates the Matrix badge help text to match.

Rename Riot to Element in Matrix badge help

---

services/freecodecamp/freecodecamp-points.service.js

* Fixes https://github.com/badges/shields/issues/6998
The pattern I used in the `schema` instance in `freecodecamp-points.service.js` was wrong.
I used `\w` because I thought usernames could only have letters, numbers, hyphens and underscores. I wasn't aware they could have plus until now. Then `allowAndStripUnknownKeys` kicked off and removed the properties that didn't match the pattern defined, including usernames with a `+` in it.
I stole the pattern used to validate usernames from the official freeCodeCamp repository this time, so it should match this time.
> ```js
> const validCharsRE = /^[a-zA-Z0-9\-_+]*$/;
> ```
> 
> — https://github.com/freeCodeCamp/freeCodeCamp/blob/main/utils/validate.js#L14
Now it handles `+` symbols correctly.

[freecodecamp]: allow + symbol in username

---

services/spiget/spiget-download-size.tester.js
services/test-validators.js

Forgot to open an issue, but this test has been failing for a while. Something changed upstream with the target we were using for the non-externally hosted resource scenario, and that target now is externally hosted (don't know enough about the service to know what that actually means, but was a straightforward root cause analysis).

fix [SpigetDownloadSize] service test

---

services/docker/docker-version.tester.js

This has been failing for a while as apparently a non-semver compatible tag was published. Long term I think these tests could be revisited to for example, account for both sort orders, don't require a valid semver when the sort is date, etc. but keeping this as-is for now, both to get the test passing again and because we'll presumably need a valid semver target anyway

fix [DockerVersion] service test

---

config/custom-environment-variables.yml

Was banging my head against the desk trying to figure out why the Shields.io prod environment wasn't sending the auth info with gitlab.com bound requests... only to discover I left out this crucial piece :man_facepalming: 
I've been meaning to suggest some documentation for adding new server secrets, as I think it'd be a helpful reference for folks, plus I've clearly forgotten it myself on more than one occasion!

support gitlab token via env var

---

services/downloads.js
services/downloads.spec.js
services/hexpm/hexpm.service.js
services/homebrew/homebrew-downloads.service.js
services/jenkins/jenkins-plugin-installs.service.js
services/jetbrains/jetbrains-downloads.service.js
services/jsdelivr/jsdelivr-base.js
services/modrinth/modrinth.service.js

use downloads renderer in next batch of classes, run [hexpm homebrewdownloads jenkinsplugininstalls jetbrainsdownloads jsdelivr modrinth]]

---

core/base-service/base.js
core/base-service/got.js
services/github/github-api-provider.integration.js
services/github/github-api-provider.js
services/github/github-api-provider.spec.js
services/github/github-auth-service.js
services/github/github-auth-service.spec.js
services/librariesio/librariesio-api-provider.spec.js
services/librariesio/librariesio-base.js
services/suggest.js

Refs #4655
This PR deals with migrating request --> got in:
- https://github.com/badges/shields/blob/master/core/base-service/base.js
- https://github.com/badges/shields/blob/master/services/github/github-api-provider.integration.js
- https://github.com/badges/shields/blob/master/services/suggest.js
A lot of what is changing here is just updating tests
I've also made a couple of tweaks to libraries.io in this Pr. These changes are not _strictly_ related but I spotted a couple of minor things there while using that code as a base for porting the github token pooling from callbacks to async/await
---
Remaining uses of request not addressed in this PR:
- https://github.com/badges/shields/blob/master/services/github/auth/acceptor.js
- …

migrate github badges to use got instead of request; affects [github librariesio]

---

package-lock.json
package.json
services/github/auth/acceptor.js
services/github/auth/acceptor.spec.js

Refs #4655
This PR moves our last remaining module that calls request to use got instead. That said, I have quite a few [mop-up tasks](https://github.com/badges/shields/issues/4655#issuecomment-958152213) to fully "complete" the job. We're making progress though :)
A lot of this diff is just indenting changes due to callback --> async/await. Also improved the tests slightly.

migrate request --> got in [github] auth acceptor

---

core/base-service/resource-cache.js
core/base-service/resource-cache.spec.js
core/server/server.js
doc/production-hosting.md
services/jenkins/jenkins-plugin-version.service.js
services/myget/myget.tester.js
services/node/node-version-color.js
services/nuget/nuget-helpers.js
services/php-version.js
services/wordpress/wordpress-version-color.js

Closes #4655
Refs https://github.com/badges/shields/pull/7215#discussion_r741433020
This PR finishes up the last bit of tangential follow up from the refactoring work done under #4655
I opted not to bother taking on another cache dependency for this. I've tidied things up a bit, made the terminology a bit more normal and added some tests but I've pretty much left the implementation alone.

Clean up cache module; affects [feedz jenkinsplugin myget node nuget packagist travis wordpress]

---

package-lock.json
package.json

As I understand it, this dependency become unnecessary and irrelevant once we switched from nyc/istanbul to c8 for code coverage.
We've never been generating any coverage for the frontend (see https://coveralls.io/github/badges/shields), and testing locally against mater/this branch shows no substantial coverage changes (only a handful of line/statement differences that were caused by different service tests intermittently failing/passing)

deps: remove unused babel-plugin-istanbul

---

.circleci/config.yml

Not much code here, but it does require a bit of explanation :)
In our `package.json` we declare an engines key with our node/npm compatibility:
https://github.com/badges/shields/blob/24355a0773c4d4333399cbfcc4dec52cba62344f/package.json#L242-L245
By default if NPM installs a package which declares itself incompatible with our engines statement, NPM will just install anyway but emit an `EBADENGINE` warning. In general we tend to catch this because the tests fail but if the tests pass we either have to identify this ourselves from the changelog or the CI logs (dunno about anyone else, but I never read the install log for dependency bump PRs) or in some cases we might actually merge a package update which officially drops compatibility/testing with our target node version (probably not for …

check engine and peer deps before installing

---

services/youtube/youtube-base.js
services/youtube/youtube-likes.service.js
services/youtube/youtube-likes.tester.js

[YouTube] Drop support for removed dislikes

---

package.json

Just noticed we still had this in here. Obviously the value is wrong, but have opted to drop it altogether as (a) I don't think we want bug reports going over email regardless, and even if we do, (b) I don't think we've got a good address for it (afaik we only have `ops`, `security`, and a few other addresses for CoC)

remove old email from package.json

---

.github/dependabot.yml

I don't see our circumstances changing to need/be ready for v17 any time soon, and the package is updated frequently enough that I think we need a global ignore so that we don't have to do the weekly routine (e.g. #7417)

ignore @types/node updates (for now)

---

services/nexus/nexus.tester.js

Since #7472, version 8.0.0.5 was released despite 8.1.0.0 already being available, so the filter broke. Unless they decide to release `8.0.0.0-29`, this test should be fixed for good this time.

Fix [Nexus] test

---

services/aur/aur.service.js
services/aur/aur.tester.js

Before this fix, the AUR badges were showing "not found".
See https://github.com/Jguer/yay/issues/1684

[AUR] Fix RPC URL

---

core/base-service/base.js

One of the things to come out of #7584 is that rating and star badges don't have any explicit `cacheLength` set on them so they just use the default (120 sec). I've never bothered setting one because we serve so few of these in the grand scheme of things. In terms of the way we characterise badges based on how often we expect the values to change and how precise the values need to be, it is probably most sensible to think of these in the same bucket as a download counts.
I don't expect this to make much difference to our performance/load because they make up such a small proportion of our traffic, but it will reduce the amount of traffic on upstream APIs a bit.

Set a higher default `cacheLength` on rating/star category

---

services/wordpress/wordpress-base.js
services/wordpress/wordpress-downloads.service.js
services/wordpress/wordpress-downloads.tester.js
services/wordpress/wordpress-last-update.service.js
services/wordpress/wordpress-platform.service.js
services/wordpress/wordpress-rating.service.js
services/wordpress/wordpress-version.service.js

Remove no download handling and add API warning to [Wordpress] badges

---

services/security-headers/security-headers.tester.js

This seems to often need to trigger a full scan which in my local env is taking a tad north of 10 seconds fairly frequently, which in turn explains the recurring test failures.
If this is fairly common behavior then it does make me question how useful the badges are, but for now just want to get these off the regularly-failing list in the daily test runs

increase [SecurityHeaders] timeout

---

frontend/constants.ts

This is a minor thing, but at the moment our staging app and review apps generate links like this:
https://shields-staging.herokuapp.com:/appveyor/build/gruntjs/grunt
https://shields-staging-pr-7633.herokuapp.com:/galaxy-toolshed/v/sra_tools/iuc/fastq_dump
(with a trailing `:` character after the `.com`). They work, but I find it a minor irritation

generate links without trailing : if port not set

---

services/github/github-api-provider.js
services/github/github-api-provider.spec.js

Closes #7632
If a token is linked to a suspended account, I think it makes sense for us to remove it from the pool

remove suspended [github] tokens from the pool

---

services/github/github-deployments.service.js

The example color currently appears as grey on the homepage:
`render` expects the state to be passed in as uppercase.

Fix GitHub Deployments example color

---

services/github/github-all-contributors.service.js

I was wondering what the difference was between these two badges and had to go digging through the code to figure things out:
Changing the title slightly should help clarify this.

Clarify GitHub All Contributors badge

---

package-lock.json
package.json
services/color-formatters.js
services/color-formatters.spec.js
services/github/github-pipenv.service.js
services/piwheels/piwheels-version.service.js
services/pypi/pypi-version.service.js
services/version.js

After implementing the piwheels badge the other day I realised that I had just used `renderVersionBadge()` but our standard version formatter
https://github.com/badges/shields/blob/76a64a7896893bac4a1b52e683a0a542541b3bdb/services/color-formatters.js#L16-L20
isn't great for python packages because it will format something like `2.0.0rc1` or `2.0.0b2` as "stable".
Then I started pulling the thread and realised this problem actually also applies to some other python ecosystem badges.
so in this PR I have:
- Added a `pep440VersionColor()` formatter function which uses https://github.com/renovatebot/pep440 to parse versions
- Added the ability to pass `renderVersionBadge()` a custom formatter function as an optional param - this might be handy if we want to use a custom formatter for other …

Improve python version formatting 🐍 affects [pypi piwheels github]

---

services/librariesio/librariesio-dependencies.service.js
services/librariesio/librariesio-dependent-repos.service.js
services/librariesio/librariesio-dependents.service.js

We currently run with two libraries.io tokens, which is mostly enough.
Another useful thing we can do is reduce the number of requests we need to make in the first place by cacheing badges longer.
The bower license/version and libraries.io sourcerank badges already have a `cacheLength` set on them based on the category. There's also a bunch of libraries.io badges that don't have any specific `cacheLength` set so they just use the default. All the data on libraries.io gets fetched from other platforms/registries on a schedule. Changes take a while to propagate so I'm not concerned about setting a bit of a longer `cacheLength` on these. Not sure if 900 seconds is enough to make much of a difference but lets give it a go.
This isn't a fix for #7445. Independently I need to work that out and …

set a longer cacheLength on [librariesio] badges

---

services/shippable/shippable.service.js
services/shippable/shippable.tester.js

Service tests for Shippable have been failing for a few weeks. Turns out that the company was bought by JFrog and the service was shut down last year (https://twitter.com/BeShippable/status/1356355435029127171). I'm guessing the API endpoints were still kept running for a while longer.

Deprecate [Shippable] service

---

services/pub/pub-publisher.service.js

We discussed at the time that we would expect this value to change quite infrequently so we can cache it for the same amount of time we cache a license badge for.

cache [pub] publisher badge for an hour

---

services/pypi/pypi-base.js
services/pypi/pypi-helpers.spec.js

Closes #7728
Having dug into it a bit, I think I'm not going to split the schema. Makes more sense to just handle `null` the same as empty string.

fix [pypi] badges when package has null license

---

package-lock.json
package.json

to fix `peerDependencies` issue with npm >= 8.5.5

downgrade eslint-plugin-promise to 5.2.0

---

core/server/server.js

Refs https://sentry.io/organizations/shields/issues/3133159541/
I haven't really got to the bottom of why, but for some small subset of requests on fly (tens per hour) it seems the `fly-client-ip` header is not set which is causing us to throw an unhandled exception and crash the thread. Doing this will reject the request without throwing.

handle missing 'fly-client-ip'

---

.github/workflows/enforce-dependency-review.yml

There have been a number of high-profile supply chain attacks or issues in the NPM ecosystem, either due to packages being compromised by an attacker or sabotaged by their maintainer e.g:
- [node-ipc](https://security.snyk.io/vuln/SNYK-JS-NODEIPC-2426370)
- [faker/colors](https://github.com/advisories/GHSA-gh88-3pxp-6fm8)
- [coa](https://github.com/advisories/GHSA-73qr-pfmq-6rp8)
- [rc](https://github.com/advisories/GHSA-g2q5-5433-rhrf)
- [ua-parser-js](https://github.com/advisories/GHSA-pjwm-rvh2-c87w)
- [eslint-config-eslint/eslint-scope](https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes)
- [event-stream](https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream/)
- etc
Shields has mercifully not been directly affected by any of these, but this is …

Try out dependency-review-action

---

.github/workflows/create-release.yml
.github/workflows/deploy-docs.yml
.github/workflows/draft-release.yml
.github/workflows/enforce-dependency-review.yml

Following on from @naveensrinivasan 's suggestion in #7888 I agree with minimising the possible harm from token exposure but I think the approach we should actually adopt here is:
- Change our repo settings in https://github.com/badges/shields/settings/actions so that actions get "Read repository contents permission" by default (i.e: all actions get `contents: read` unless otherwise specified). This would bring us into line with GitHub's default for new repos. I haven't done this yet.
- Explicitly elevate permissions for the workflows that need more access (which I _think_ I've done correctly in this PR)

Set permissions for GitHub actions

---

services/pub/pub-likes.service.js
services/pub/pub-likes.tester.js

- Add a badge for `PUB` to show the likes for `Dart/Flutter` packages and plugins.
- Fix #7915.

add [PUB] likes badge

---

.github/workflows/auto-close.yml
.github/workflows/build-docker-image.yml
.github/workflows/create-release.yml
.github/workflows/deploy-docs.yml
.github/workflows/draft-release.yml
.github/workflows/publish-docker-next.yml

Have been meaning to submit this for a while but it kept slipping. The v2 version of this action is pinned to Node 12, which just went end of life a few weeks ago. The new v3 version uses Node 16, with the major version bump being applied out of an abundance of caution for GitHub Enterprise Server scenarios
https://github.com/actions/checkout#whats-new

update actions checkout step version

---

services/pub/pub-popularity.service.js
services/pub/pub-popularity.tester.js

- Add a badge for `PUB` to show the popularity for `Dart/Flutter` packages and plugins.
- Fix #7919.

add [PUB] popularity badge

---

services/pub/pub-points.service.js
services/pub/pub-points.tester.js

- Add a badge for `PUB` to show the points for `Dart/Flutter` packages and plugins.
- Fix #7917.

add [PUB] points badge

---

services/spack/spack.service.js

We transition our endpoints in Spack to a new location. This adjusts the new JSON files that we can query for shields.
cc Spack: @tgamblin @vsoch

[Spack] Package Manager: Update Endpoint

---

services/flathub/flathub-downloads.service.js
services/flathub/flathub-downloads.tester.js

Expands on #7724
Related https://github.com/badges/shields/issues/5506#issuecomment-1125903576
Naming was not 100% clear. Users have a certain understanding when reading "download".
It's not obvious that in this case it's only a subset of all downloads (only fresh installs, excluding downloads for updates).

[Flathub] Relabel new download badge

---

.circleci/config.yml

This is just a bit of routine maintenance to make sure we are running on the latest node 16/17 versions.

Update node images

---

doc/production-hosting.md
doc/self-hosting.md

There was actually less to update here than I thought.
There are a few bits of heroku-specific code knocking about like:
- https://github.com/badges/shields/blob/master/Procfile
- https://github.com/badges/shields/blob/6dff32138b7316228dbde6feffbf23610ec14570/package.json#L106
- https://github.com/badges/shields/blob/8821ff85fcd494ebb802bf9bb26ddcba11d21ec8/core/server/server.js#L312-L317
- https://github.com/badges/shields/blob/99bffd3a86cb85f4ca20a22599e64be6abf7efcb/core/base-service/got-config.js#L20-L22
I have decided to just leave them all where they are because we have documented heroku buildpack-based (as opposed to docker-based) deployment as a self-hosting option for a long time
https://github.com/badges/shields/blob/6dff32138b7316228dbde6feffbf23610ec14570/doc/self-hosting.md?pl …

update docs on production hosting

---

services/spack/spack.service.js

The domain endpoint of Spack packages moved. This fixes our shields.
cc Spack: @tgamblin @vsoch

[Spack] Package Manager: Update Domain

---

services/endpoint-common.js

- Added docstrings for `endpoint-common` service

Docstrings for endpoint-common service

---

services/gitlab/gitlab-license.service.js

re https://github.com/badges/shields/pull/8024#issuecomment-1153331982
Fixed the documentation and example of custom server, now they are displayed properly.
/assign @calebcartwright

fix: gitlab licence service docs and example

---

frontend/pages/endpoint.tsx

Fixes one spelling mistake and a few grammatical errors

Fix typos in endpoint badge docs

---

services/greasyfork/greasyfork-downloads.service.js

Noticing now that the daily downloads example is missing the "/day". The actual badge itself displays correctly, it is just an issue with the example.

[greasyfork] Greasy Fork daily downloads minor example fix

---

services/gitlab/gitlab-contributors.service.js
services/gitlab/gitlab-coverage.service.js
services/gitlab/gitlab-license.service.js
services/gitlab/gitlab-pipeline-status.service.js
services/gitlab/gitlab-release.service.js
services/gitlab/gitlab-tag.service.js

At present, there is no unified naming for the self-managed instance fields in GItLab Service, and the names that appear are: `self-host`, `custom server`, `custom instance`, in order to reduce the burden on the user's mind, the naming is unified here.
The name has been standardized to `self-managed`, a reference to the official GItLab naming scheme.
reference: https://docs.gitlab.com/ee/subscriptions/self_managed/index.html

style: unified self-managed [gitlab] instance name

---

services/bower/bower-version.tester.js

closes #8068 
There's something odd going on upstream with bootstrap specifically. https://libraries.io/api/bower/bootstrap shows it as having no stable versions, whereas of course it has many. This is an upstream issue specific to this package though so lets just change the test target.

update targets for [bower] service tests

---

services/gitlab/gitlab-contributors-redirect.service.js
services/gitlab/gitlab-contributors-redirect.tester.js
services/gitlab/gitlab-contributors.service.js
services/gitlab/gitlab-license-redirect.service.js
services/gitlab/gitlab-license-redirect.tester.js
services/gitlab/gitlab-license.service.js
services/gitlab/gitlab-release.tester.js

closes #8138 
As well as removing the `/v` I am also suggesting we switch the route from `/contributor` to `/contributors`. This matches the github route and is more in line with our usual approach. We tend to use the plural if there can be more than one of the noun. e.g: `/stars`, `/dependencies`, `/issues` rather than `/star`, `/dependency`, `/issue`

change routes for [gitlab] license and contributors badges

---

services/gitlab/gitlab-base.js
services/gitlab/gitlab-license.tester.js
services/gitlab/gitlab-tag.spec.js

Fixes the overwhelming majority, but not totality, of #8143.
I also added a dummy license to our private test repo under the shields-ops-group

fix [gitlab] auth

---

services/stackexchange/stackexchange-monthlyquestions.service.js
services/stackexchange/stackexchange-monthlyquestions.tester.js

Should fix `Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'moment' imported from /usr/src/app/services/stackexchange/stackexchange-monthlyquestions.service.js` from one file being missed in the PR #8192.

Fix missing conversion to `dayjs`, run [stackexchange]

---

services/ros/ros-version.service.js
services/ros/ros-version.tester.js

The version information that this service is fetching is the version for a whole repository of ROS packages which all share the same version. A repository may contain only a single package with the same name, but it may also contain multiple packages, and this badge service fetches version information based on the repo name, not the package name.

Fix variable naming for [ROS] version service

---

services/docker/docker-stars.service.js

fix [dockerstars] service

---

services/jitpack/jitpack-version-redirector.service.js
services/jitpack/jitpack-version-redirector.tester.js
services/jitpack/jitpack-version.service.js
services/jitpack/jitpack-version.tester.js

closes #8312 
Introduced a new `jitpack/version` endpoint: `jitpack/v` redirects to it, either with no VCS (still defaulting to GitHub), or with a VCS previously supported.
It uses the full `groupId` from jitpack as input (usually `com.github.user`, but custom domains, like `io.jitpack`, as well).

Custom domains for [JitPack] artifacts

---

.github/workflows/auto-close.yml
.github/workflows/build-docker-image.yml
.github/workflows/deploy-docs.yml
.github/workflows/draft-release.yml
.github/workflows/enforce-dependency-review.yml
.github/workflows/publish-docker-next.yml

I wanted to add `build-docker-image` as a required build to merge to master. Given we deploy to fly using that image now, I think that should be an essential check.
GitHub lists the checks you can use as a branch protection rule by job name, which is unhelpful if you've got 4 different jobs which are all called `build`. This PR gives each job a unique name which is the same as the name of the workflow file.

improve workflow job names

---

services/package-json-helpers.js
services/package-json-helpers.spec.js

- Added docstrings for package json helpers

Docstrings for package json helpers

---

services/github/github-package-json.service.js
services/npm/npm-dependency-version.service.js
services/package-json-helpers.js
services/package-json-helpers.spec.js

Cleanup for https://github.com/badges/shields/pull/8373#discussion_r962304386
> This function does currently return an object, but it doesn't really need to. I expect this is an artefact of some past refactoring. A nice cleanup we could do here would be to update this so it just returns a string and update the handful of places it is called accordingly.

Return string instead of object from getDependencyVersion function; affects [githubpackagejson npmdependencyversion]

---

services/reuse/reuse-compliance.tester.js

The 'not found' case on this badge seems to consistently take > 5 seconds for this service. Not much we can do about the upstream, but I'd like to get rid of the noise from the service tests.

increase timeout for [reuse] not found test

---

services/myget/myget.tester.js

I don't think there is any bug or upstream issue to chase down here. It seems this is another API where "total downloads" is actually downloads in the last N years. This test has been failing because the package we're using as an example has been reporting zero total downloads. I've updated the test to point at a more popular/active package.

fix [myget] downloads (tenant) test

---

services/bitbucket/bitbucket-pull-request.tester.js

closes #8067
BB cloud now serves a 404 for private repo that you don't have access to, rather than a 403.

update [bitbucket] private repo test

---

services/github/github-deployments.service.js
services/github/github-deployments.spec.js

Fix "invalid response data" badge label for GitHub deployments pending approval.
If a deployment is pending manual approval:
Then the GraphQL API reports the status as `PENDING`:
```
query {
repository(owner: "martincostello", name: "api") {
deployments(last: 1, environments: ["production"]) {
nodes {
latestStatus {
state
}
}
}
}
}
```
```
{
"data": {
"repository": {
"deployments": {
"nodes": [
{
"latestStatus": {
"state": "WAITING"
}
}
]
}
}
}
}
```
This then produces a badge that looks like this:
The status doesn't appear to be consistently documented, but definitely exists: https://github.com/octokit/webhooks.net/pull/52

fix: Support WAITING status for [GitHubDeployments]

---

services/testspace/testspace-base.js
services/testspace/testspace-test-count.service.js
services/testspace/testspace-test-count.spec.js
services/testspace/testspace-test-count.tester.js

Hello,
I noticed that all Testspace badges started returning "invalid response data" recently. The cause was a recent change in the response object of the Testspace web API: the `case_counts` array in the [Results object](https://help.testspace.com/reference/web-api#results) now has length 5 instead of 4. A new integer was appended to the end which represents the number of [untested](https://help.testspace.com/manual/execution-session#start) tests, which are [manual](https://help.testspace.com/manual/overview) tests that have not been run yet.
|Live example|Screenshot for posterity|
|---|---|
|![Testspace tests](https://img.shields.io/testspace/tests/swellaby/swellaby:testspace-sample/main)|![tests: invalid response data](https://user-images.githubusercontent.com/1417794/196314307-0b038778 …

Fix [Testspace] with new "untested" value in case_counts array

---

services/github/github-release-date.service.js
services/github/github-release-date.tester.js

closes #6309
For the GitHub Release Date badge by default we still use the `created_at` field.
Now, if the user gives the `display_date=published_at` query param, that field from the API response would be used.
https://api.github.com/repos/microsoft/vscode/releases/latest 
http://localhost:8080/github/release-date/microsoft/vscode
http://localhost:8080/github/release-date/microsoft/vscode?display_date=published_at

[GitHubReleaseDate] - published_at field

---

services/github/github-last-commit.service.js
services/github/github-last-commit.tester.js

closes #6236
I added  the `display_timestamp` queryParam, with options `author` and `committer`, defaulting to `author`.
```js
const queryParamSchema = Joi.object({
display_timestamp: Joi.string()
.valid('author', 'committer')
.default('author'),
}).required()
...
async handle({ user, repo, branch }, queryParams) {
const body = await this.fetch({ user, repo, branch })
return this.constructor.render({
commitDate: body[0].commit[queryParams.display_timestamp].date,
})
}
```
I checked a couple of repos (for example https://api.github.com/repos/zero-to-mastery/start-here-guidelines/commits) but I couldn't find an example with a different date for `author` and `committer`.
http://localhost:8080/github/last-commit/google/skia/infra/config?display_timestamp=committer

Add [GitHubLastCommit] by committer badge

---

services/lgtm/lgtm-alerts.tester.js

The upstream project has disappeared and unfortunately I'm not able to find another public project which is hosted on bitbucket and using LGTM. Given that the response we expect from LGTM is identical regardless of where the source is hosted and there's no difference in the logic there is no value in replacing with a mocked test IMO. I suggest we can just drop it.

remove failing [lgtm] test case

---

.github/workflows/auto-close.yml
.github/workflows/enforce-dependency-review.yml
.github/workflows/test-integration-17.yml
.github/workflows/test-integration.yml
.github/workflows/test-lint.yml
.github/workflows/test-main-17.yml
.github/workflows/test-main.yml
.github/workflows/test-package-cli.yml
.github/workflows/test-package-lib.yml

closes #8535
Right. A few things going on here:
First 2 commits should be pretty clear. Just trying to run fewer pointless builds really. Regardless of if the builds are consuming rate limit or not, this is good. Less noise, faster builds, etc
The crucial commit is actually the third one though. What I've done is set a Personal Access Token as both a [repo secret](https://github.com/badges/shields/settings/secrets/actions) and a [dependabot secret](https://github.com/badges/shields/settings/secrets/dependabot). Then in the build, we use the PAT if it is available, or fall back to the standard action token (which has the lower rate limit of 1000/hour) otherwise. This will mean PRs submitted from forks can use the standard token without us having to expose a PAT while pushes to master, …

fixes for integration test rate limit issues

---

services/codecov/codecov.service.js

closes #8545
Not sure if this has been wrong for a long time or if it is a recent change, but `/branch` is correct.

fix [codecov] badge for non-default branch

---

services/swagger/swagger.service.js

This one is odd. I'm not sure how we never hit this, but the existing code required the array to have >=1 items in it. I think what has happened is:
- Every schema we were testing against had at least one warning
- The upstream API has stopped returning warnings in the response, or stopped returning them by default
~~OR~~
- ~~There was a behaviour change in Joi at some point~~
~~but it is kinda hard to tell at this point.~~
I've checked some invalid examples and the upstream API does still seem to be returning errors. We don't need any additional error handling to account for this being `[]`. The `handle()` code itself was already expecting it as a possible value, but the schema was rejecting it.
edit: closes #8566

fix [swagger] service tests (allow array of 0 items)

---

services/ansible/ansible-collection.service.js
services/ansible/ansible-collection.tester.js

Add a badge for Ansible collections, almost identical to those for Ansible roles.
Unfortuntately, the `/api/v2/collections` endpoint (as opposed to `/api/v1/roles`) of Ansible Galaxy exposes neither download numbers nor quality scores, so there's only the name badge for now.

[Ansible] Add collection badge

---

services/factorio-mod-portal/factorio-mod-portal.service.js
services/factorio-mod-portal/factorio-mod-portal.tester.js

Saw this https://github.com/badges/shields/issues/8582 issue and thought I'd take a crack at closing it. I'm new to open-source contributions so I'm eager to hear any feedback/changes.
API: `https://mods.factorio.com/api/mods/{name}` where {name} is the name of the mod, e.g.
https://mods.factorio.com/api/mods/rso-mod
No authentication is required.
API is documented here: https://wiki.factorio.com/Mod_portal_API#/api/mods/

[factorio-mod-portal] services

---

services/coveralls/coveralls-redirector.service.js
services/coveralls/coveralls-redirector.tester.js

https://img.shields.io/coveralls/github/badges/shields
Hi @chris48s, 
I noticed that after my last changes to the Coveralls badge (PR https://github.com/badges/shields/pull/8584 ) there is one redirect missing (for the case without the specified branch).
I added it in this PR.
```js
base: 'coveralls',
pattern: ':vcsType(github|bitbucket)/:user/:repo',
```
EDIT:
Tested locally,
http://localhost:8080/coveralls/github/badges/shields 
correctly redirects to:
http://localhost:8080/coverallsCoverage/github/badges/shields.svg
Redirect for the option with specified branch also works correctly:
http://localhost:8080/coveralls/github/badges/shields/master ->
http://localhost:8080/coverallsCoverage/github/badges/shields.svg?branch=master

add a missing redirect to [coveralls]

---

services/github/github-actions-workflow-status.service.js
services/github/github-actions-workflow-status.tester.js

Closes #8716
It was always too much to ask for this to go _completely_ to plan :laughing: 
When a build is not completed yet, it has a null value for `.conclusion` e.g:
```js
status: 'in_progress',
conclusion: null,
```
This PR allows `.conclusion` to be `null` and requires a non-null value for `status` which we can fall back to.

handle workflow runs that do not have a conclusion in [githubactionsworkflowstatus]

---

services/github/github-actions-workflow-status.service.js
services/github/github-actions-workflow-status.tester.js

Closes https://github.com/badges/shields/issues/8720
Lets get a nice easy one out of the way first.
Tbh, I suspect this might be an issue that exists in other places, but I'm not going to shave that yak right this second. Squeaky wheel gets the grease today.

allow all numeric branch names in [githubactionsworkflowstatus]

---

core/base-service/base.js

This PR fixes an issue introduced in PR #8540 . @calebcartwright 's suggestion we deploy this in isolation came good :smile:  This was causing us to throw a `TypeError: Cannot convert undefined or null to object` in some situations.
This PR closes #8756 but it is probably a wider issue

don't try to call .entries on null or undefined

---

core/base-service/loader.js
core/base-service/loader.spec.js

Refs #8437
This doesn't fix the `:trace` variant but it does fix being able to run `npm run test:services -- only="myservice"` on Windows.
The core fix here is actually:
```diff
diff --git a/core/base-service/loader.js b/core/base-service/loader.js
index 9bbf0c948..5fd87cd87 100644
--- a/core/base-service/loader.js
+++ b/core/base-service/loader.js
@@ -103,7 +103,7 @@ async function collectDefinitions() {
async function loadTesters() {
return Promise.all(
glob
-      .sync(path.join(serviceDir, '**', '*.tester.js'))
+      .sync(toUnixPath(path.join(serviceDir, '**', '*.tester.js')))
.map(async path => await import(`file://${path}`))
)
}
```
(basically in https://github.com/badges/shields/pull/8350 we missed the tests loader).
My original plan was to do that and directly write tests for …

fix service tests on windows; run [crates] (to prove service tests still run)

---

dangerfile.js
package-lock.json
package.json

Turns out this is the thing that was trying to read from the local checkout:
https://github.com/macklinu/danger-plugin-no-test-shortcuts/blob/ebd8c91e333d96a7c6d6e5e6fa1411d0fb460a40/src/index.ts#L49
I think the short term solution is to just ditch this check to get danger working again.
Longer term, I'll make an issue to find another solution to this. One option would be to re-implement the check in danger but based on the diff instead of the local files (like we do with some of the other checks). The other option would be to try and write it as a lint/pre-commit check (we're basically checking the same thing for mocha tests via eslint: https://github.com/badges/shields/blob/2fb98897429c9a5bfa2960a85461a2df66654222/.eslintrc.yml#L115 ).

remove danger-plugin-no-test-shortcuts

---

services/twitter/twitter.service.js
services/twitter/twitter.tester.js

closes #8837
Maybe there will be another way we could re-implement this in future, but lets do this at least as a stop-gap.

replace [twitter] badge with static fallback

---

Dockerfile

If we don't explicitly specify a port, running `node server` will serve on port 80 if https://github.com/badges/shields/blob/a7368b86707e4953e63d4e83ab3719e077fa724a/config/custom-environment-variables.yml#L20 is false and 443 if it is true, but we don't expose 443 so if that var is true, the port we open in the dockerfile isn't the one the server is listening on.
We could explicitly tell the server to serve TLS on port 80, but I think it makes more sense to expose 443 to cover this case.
This related to https://github.com/badges/shields/issues/8424
The other thing we need to do on this repo is a PR bumping scoutcamp once we've done a release with https://github.com/badges/sc/pull/6 in it
Then once we've got a docker image with that in it, we're on to PRs in the super secret devops repo 🤫

expose port 443 in Dockerfile

---

services/npms-io/npms-io-score.service.js

This is another "get everything to play nice with openapi" PR.
In openapi, a route "segment" (the bit in-between 2 slashes basically) can either be a constant value or a variable parameter, but not a mix of both.
Shields almost universally sticks to this (its a fairly sensible rule), except for this one badge. Path-to-regexp lets us do this, but it doesn't translate well. This PR adjusts the npms-io route and adds a redirect for compatibility.

adjust route for [npmsio] badges

---

.github/workflows/build-docker-image.yml
.github/workflows/create-release.yml
.github/workflows/publish-docker-next.yml

Refs https://github.com/badges/shields/issues/8993
I've set up https://github.com/badges/shields/pkgs/container/shields but it is currently private because I don't have permission to make it public :upside_down_face: 
We should now be able to push to it from a GH action though. I totally haven't tested this yet. Think I'm just going to merge it and fix it if it doesn't work.

push images to both GHCR and DockerHub

---

services/dynamic/dynamic-json.tester.js
services/endpoint/endpoint.tester.js

As noted in https://github.com/badges/shields/pull/8966#issue-1611093392 there are a couple of failing service tests that were not related to the changes in #8966
The endpoint one, I think we broke in https://github.com/badges/shields/pull/8263 Custom logo with a colour never made any sense as a test case anyway.
For the dynamic one, I'm not sure where we broke this. Based on the commit history for the file https://github.com/badges/shields/commits/master/services/dynamic/dynamic-json.tester.js I suspect we upgraded got and the error message changed.

Fix tests for [dynamic endpoint] services

---

services/crates/crates-base.js
services/crates/crates-downloads.tester.js

By default the `/crates/:crate_name` API endpoint returns the categories and keywords related to the crates. Unfortunately this causes two additional database queries on the crates.io backend.
This commit change the request URL to use `?include=` to only include the additional metadata that is needed for the requested badges.

[crates] Use `?include=` to reduce crates.io backend load

---

.github/workflows/danger.yml
.github/workflows/enforce-dependency-review.yml
.github/workflows/test-e2e.yml
.github/workflows/test-frontend.yml
.github/workflows/test-integration-17.yml
.github/workflows/test-integration.yml
.github/workflows/test-lint.yml
.github/workflows/test-main-17.yml
.github/workflows/test-main.yml
.github/workflows/test-package-cli.yml
.github/workflows/test-package-lib.yml

When we have a lot of dependabot PRs to review, sometimes we use all our rate limit up and stuff starts failing.
I think one of the issues causing this is that because we trigger a build on `pull_request:edited`, as soon as dependabot edits the top post of a PR to say "dependabot is rebasing this PR", all the builds unnecessarily re-trigger. Then they retrigger again on `pull_request:synchronize` when it force-pushes the branch.
This PR removes the `pull_request:edited` trigger from most of the workflows. I've left it on the service tests because its quite useful that editing the PR title re-runs those.
Hopefully this should reduce the number of builds we run a bit and make it a bit easier to stay under the rate limit.

remove pull_request:edited trigger from most workflows

---

package-lock.json
package.json
services/dynamic/dynamic-xml.service.js

See the note at the top of the README on https://github.com/xmldom/xmldom
> Since version 0.7.0 this package is published to npm as [@xmldom/xmldom](https://www.npmjs.com/package/@xmldom/xmldom) and no longer as [xmldom](https://www.npmjs.com/package/xmldom), because https://github.com/xmldom/xmldom/issues/271.

switch from xmldom to @xmldom/xmldom; affects [DynamicXml]

---

.github/dependabot.yml

Dependabot made a change a while back which means every time we merge a dependabot PR, dependabot automatically rebases any other open dependabot PRs.
This means that when we're working through the weekly updates, we consume a lot of github rate limit points on re-triggering the same builds. Often I have to merge the updates in batches due to exhausting our rate limit.
This PR turns that off. It does increase the need for us to manually use `@dependabot rebase` when we actually do want a rebase but in the grand schema of things, I think this should make things smoother because we won't exhaust our rate limit so quickly.
Relevant docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#rebase-strategy

disable dependabot auto rebase

---

services/youtube/youtube-base.js

refs #9236
refs #9237
I've still not managed to catch this happening. If we think it is rate limit-related, lets bump the max age up on these.

increase default cache on youtube badges

---

services/netlify/netlify.service.js

Canceled deploys should have a 'canceled' message instead of the 'unknown' message that currently displays.

[Netlify] Prefer 'canceled' deploy status instead of 'unknown'

---

services/github/github-commit-activity.service.js
services/github/github-commit-activity.tester.js

Current code to handle invalid branch in Github Commit Activity (branch) never runs.
When GraphQL response with a bad repo it returns an error indicating the bad repo.
When GraphQL has the correct repo with a bad branch it will return null inside the repo object without an error object.
The existing code seems to try and use that but due to the current Joi schema not allowing null it did not work and an error due to bad schema would show instead.
This PR fixes this issue and adds a test for this case
Photo from production showing invalid response data due to response differ from schema:
Photo of PR changes on my local debug instance, handling invalid branch:

Fix: [GithubCommitActivity] invalid branch error handling

---

services/amo/amo-downloads.service.js
services/azure-devops/azure-devops-build.service.js
services/azure-devops/azure-devops-coverage.service.js
services/azure-devops/azure-devops-release.service.js
services/azure-devops/azure-devops-tests.service.js
services/endpoint/endpoint.service.js
services/github/github-all-contributors.service.js
services/github/github-hacktoberfest.service.js
services/github/github-helpers.js
services/github/github-pipenv.service.js
services/gitlab/gitlab-forks.service.js
services/gitlab/gitlab-helper.js
services/gitlab/gitlab-stars.service.js
services/hsts/hsts.service.js
services/jira/jira-sprint.service.js
services/mastodon/mastodon-follow.service.js
services/mozilla-observatory/mozilla-observatory.service.js
services/nycrc/nycrc.service.js
services/osslifecycle/osslifecycle.service.js
services/pingpong/pingpong-status.service.js
services/pingpong/pingpong-uptime.service.js
services/poeditor/poeditor.service.js
services/pypi/pypi-framework-versions.service.js
services/security-headers/security-headers.service.js
services/tokei/tokei.service.js
services/website/website.service.js
services/youtube/youtube-base.js

I'm not going to claim I have caught every single `documentation` string with a spacing issue, but I reckon I've got >90% of them. This also lays down a pattern for fixing them if we find any more I have missed.
I have mostly chosen to fix these by converting them to markdown (which we can now use instead of HTML, if we want). In one or two cases, I have moved ht HTML around a bit. In general, we might want to consider converting all of these to markdown, but that is a bigger job.
I won't go through every single page with a spacing issue, but here's a few before/after links
| before | after |
| ------ | ----- |
| https://shields.io/badges/git-hub-contributors-via-allcontributors-org | https://pr-9281-badges-shields.fly.dev/badges/git-hub-contributors-via-allcontributors-org |
| …

fix a load of spacing issues in frontend content

---

frontend/src/pages/index.js

This is shown when a link to shields.io is "unfurled"

set a sensible meta description

---

services/reddit/subreddit-subscribers.service.js
services/reddit/user-karma.service.js

Refs https://github.com/badges/shields/issues/9256
New Reddit API policies will come into effect on 30th June.
Lets crank the max age up on the badges in anticipation of that.
It may also be necessary to implement auth on this service, but lets do this as a starting point.

increase max age on [reddit] badges

---

services/travis/travis-build.service.js

We deprecated these in https://github.com/badges/shields/pull/9171 but I forgot to remove the .org examples (the class uses to cover both the .com and .org cases) so they are still (wrongly) shown in the frontend.

remove obsolete [travis] .org examples

---

frontend/src/css/custom.css

closes https://github.com/badges/shields/issues/9278
I've contributed a fix for this upstream at https://github.com/cloud-annotations/docusaurus-openapi/pull/250
Its not in a package release yet though, so while we wait for that I'm going to apply the fix here (by winning the selector specificity war). We can roll it back when docusaurus-theme-openapi@0.6.5 is available.

temp fix: wrap code examples tabs in narrow browser windows

---

frontend/src/css/custom.css

Refs https://github.com/badges/shields/discussions/9318
This just adds a little bit of border to text boxes when they're not focussed. Hopefully this makes it a bit clearer.
---
**Before:**
---
**After:**

add a bit of border to text boxes

---

services/youtube/youtube-base.js

I've been in discussions with the YouTube API Services team in order to get an API quota increase (see #8605). Unfortunately, there has been some push back, and the changes I made in #6304 are no longer deemed sufficient, even though the YouTube Developer API policy has not changed since then.
The latest response I got from the YouTube API Services team states the following:
> we appreciate you for adding the YouTube link in your website however as the YouTube API features are there in website kindly add the link of the[ http://www.google.com/policies/privacy](https://policies.google.com/privacy) in the same page by mentioning the website users are using the YouTube API services so that we can proceed further with your quota increase request
To that effect:
* I added a mention to the fact …

Mention YouTube API services and link to Google Privacy Policy

---

services/docker/docker-pulls.service.js
services/docker/docker-stars.service.js

Follows on from
https://github.com/badges/shields/pull/9343
https://github.com/badges/shields/issues/9342
We're still hitting the rate limits :sob: 
This PR increases the max age on the pulls badges again. Also the stars badge, which is not as popular but is also an indicative popularity measurement and usually presents a rounded number and hence a good candidate for a longer max-age.

increase max-age on [docker] badges, again

---

services/opencollective/opencollective-all.service.js
services/opencollective/opencollective-all.tester.js
services/opencollective/opencollective-backers.service.js
services/opencollective/opencollective-backers.tester.js
services/opencollective/opencollective-base.js
services/opencollective/opencollective-by-tier.service.js
services/opencollective/opencollective-sponsors.service.js
services/opencollective/opencollective-sponsors.tester.js

I'll post a more detailed summary of this shortly, but tl;dr:
- I deployed https://github.com/badges/shields/pull/9346
- All the OpenCollective badges are now returning "rate limited by upstream service"
For now I am going to roll back this change

Revert "[OpenCollective] update opencollective to api v2 (#9346)"

---

frontend/src/css/custom.css

This PR just updates a comment about styles we can remove when we next update docusaurus-theme-openapi. I have now also contributed an upstream fix for the form input borders too.

edit comment about styles to remove in future

---

services/docker/docker-automated.service.js
services/docker/docker-cloud-automated.service.js
services/docker/docker-pulls.service.js
services/docker/docker-size.service.js
services/docker/docker-stars.service.js

Refs https://github.com/badges/shields/issues/9342
It looks like the magic number we need to stay under is 180 reqs/minute.
We're still going over that at peak times, so I am going to hit it again with the only hammer we've got.
I'm going to leave build status and version badges on the default max-ages for those categories though.

cache docker badges for longer (take 3)

---

services/youtube/youtube-base.js

YouTube has finally granted the API quota increase.
I'm still trying to figure out what the new quota is, as the YouTube API team unhelpfully stated:
> We have increased your Quota by 200,000. The total quota for xxxx is now  200,000 units per day
The request form also insisted on how much _**additional**_ quota we wanted, our previous quota being 50,000, the new quota may actually be 250,000. Either way, we should have more than enough for many months to come. Let's set the cache back to its default value.

Go back to default YouTube cache

---

.github/workflows/build-docker-image.yml
.github/workflows/test-services-18.yml
.github/workflows/test-services.yml

refs #8892
I gave merge queues a quick spin. First problem I hit was that these builds are set to only trigger on pull requests so the queue doesn't try to run them, but then it never merges the thing at the head of the queue because its waiting for these builds (which haven't triggered) to run, so it just waits forever :upside_down_face: 
I suspect this won't be the only thing we need to change, but doing this should unblock finding out what the next one is..

run service/docker builds on merge queue builds

---

.github/workflows/test-bug-run-badge.yml

Devs run `npm run badge` often when getting a bug report for shields.io service. This PR automates this tests so the maintainer can get test results automaticly when getting into a new ticket. Add test-bug-run-badge.yml workflow for github actions automation.
Will only run if bug has the 'qeustion' label added by bug reporting template. And will only setup enviorment and perform the test if the link provided in the issue is valid and the issue is related to shields.io. Link to job results is sent as a new comment on the issue.
Resolves #9351
Image of the bot in action

devops: automate bug report tests

---

core/server/server.js

Checked https://github.com/badges/shields/pull/9347 on staging
Looks like sometimes get written to /assets/images as part of the build step

exclude assets dir from raster redirects

---

services/docsrs/docsrs.service.js

To simplify refactoring how our builds are processed I want to remove the `/builds.json` endpoint on docs.rs. As a replacement [I added](https://github.com/rust-lang/docs.rs/pull/2147) a new endpoint simply giving the status that sites like shields.io wants: are there docs for this version available to link to. This also fixes some small issues with the old endpoint (some edgecases meant the first build was successful but there were no docs, or there were docs but the first build was marked unsuccessful).

Migrate from [DocsRs]' builds API to status API

---

services/docsrs/docsrs.tester.js

While reviewing https://github.com/badges/shields/pull/9422 I noticed we are missing a couple of tests for the not found cases on this service.

add some tests for [docsrs]

---

services/github/github-api-provider.integration.js
services/github/github-api-provider.js
services/github/github-api-provider.spec.js
services/github/github-auth-service.js
services/github/github-auth-service.spec.js
services/github/github-constellation.js
services/github/github-search.service.js

Closes https://github.com/badges/shields/issues/2754
Refs https://github.com/badges/shields/pull/9386#discussion_r1264705287
This PR resolves a long-standing issue that even though GitHub allows anonymous access to the v3 API with a reasonable rate limit, you have to set a key locally to do any development on any GitHub badges. The changes in https://github.com/badges/shields/pull/9386 make it extra desirable to be able to call the GH API without auth if possible.
I've set this PR to run the github test suite. Five of them will fail, but I submitted another PR to fix the tests at https://github.com/badges/shields/pull/9425 so we could merge that first then rebase this onto it, although I think the integration tests are actually the critical ones here.

allow calling [github] without auth

---

services/archlinux/archlinux.service.js
services/bit/bit-components.service.js
services/bountysource/bountysource.service.js
services/cdnjs/cdnjs.service.js
services/chrome-web-store/chrome-web-store-price.service.js
services/chrome-web-store/chrome-web-store-users.service.js
services/chrome-web-store/chrome-web-store-version.service.js
services/clearlydefined/clearlydefined-score.service.js
services/clojars/clojars-downloads.service.js
services/cocoapods/cocoapods-docs.service.js
services/cocoapods/cocoapods-license.service.js
services/cocoapods/cocoapods-platform.service.js
services/cocoapods/cocoapods-version.service.js
services/codefactor/codefactor-grade.service.js
services/coincap/coincap-changepercent24hr.service.js
services/coincap/coincap-priceusd.service.js
services/coincap/coincap-rank.service.js
services/github/github-workflow-status.service.js

migrate `examples` to `openApi` part 2; affects [archlinux bitcomponents bountysource cdnjs chrome clearlydefined clojars cocoapods coincap]

---

.github/workflows/publish-docker-next.yml

Refs https://github.com/badges/shields/issues/9391 and https://github.com/badges/shields-ops/issues/34
We now need to deploy based on a DockerHub digest. We can't use a rolling tag. Finding the digest in the build log is possible, but it could be easier.
This PR outputs the DockerHub digest to a job summary, which will reduce the friction here.

output DockerHub digest in publish-docker-next workflow

---

.github/dependabot.yml

There are a few entries in `dependabot.yml` which relate to code or packages which we have now deleted.
The best time to remove these would have been in the original PRs removing the code or packages referenced. The second best time is now :)

remove obsolete entries from `dependabot.yml`

---

Dockerfile

Building our docker image outputs
```
npm WARN config production Use `--omit=dev` instead.
```
This fixes that deprecated flag.

update npm prune command

---

services/opencollective/opencollective-all.service.js
services/opencollective/opencollective-backers.service.js
services/opencollective/opencollective-sponsors.service.js
services/opm/opm-version.service.js
services/ossf-scorecard/ossf-scorecard.service.js
services/powershellgallery/powershellgallery.service.js
services/pub/pub-publisher.service.js
services/pypi/pypi-format.service.js
services/pypi/pypi-implementation.service.js
services/pypi/pypi-license.service.js
services/pypi/pypi-python-versions.service.js
services/pypi/pypi-status.service.js
services/pypi/pypi-version.service.js
services/pypi/pypi-wheel.service.js
services/reddit/subreddit-subscribers.service.js
services/repology/repology-repositories.service.js

migrate examples to openApi part 6; affects [opencollective opm ossf powershell pub pypi reddit repology]

---

services/bundlejs/bundlejs-package.service.js
services/bundlejs/bundlejs-package.tester.js

View [esbuild](https://github.com/evanw/esbuild) minified and [denoflate](https://github.com/hazae41/denoflate) gzipped size of a package or selected exports, via [bundlejs](https://bundlejs.com/).
Comparing to the existing bundlephobia service, bundlejs is more accurate in terms of treeshaking. It also supports displaying only the size of the selected exports.
cc @okikio

[bundlejs] add badge for the npm package size

---

services/website-status.js

- Add docstrings for website status service

Add docstrings for website status service

---

services/twitter/twitter.service.js

Closes #9479
I'm not going to get too bogged down in moving routes and files around as this is really just a pretty deprecation message, but this PR updates the name of the services in the docs and the default logo.
If you're explicitly using `logo=twitter`, then you'll continue to get the twitter logo. If simple-icons decide to make that slug an alias for the x logo in future, we'll inherit that decision.

[twitter] --> x

---

doc/TUTORIAL.md

In the docs at TUTORIAL.md the new base service BaseTomlService was missing in the list of base services.

Docs: update TUTORIAL.md add BaseTomlService

---

core/base-service/check-error-response.js
core/base-service/check-error-response.spec.js

I would quite like to get a notification in Sentry when an upstream service gives us a 429. Seems like hitting rate limits is something we would like to know about proactively rather than waiting for users to hit errors and let us know. This might turn out to be too noisy, but lets give it a try.

log an error to sentry if an upstream service responds with `429 Too Many Requests`

---

core/base-service/check-error-response.js
core/base-service/check-error-response.spec.js

Well.. that was exciting, wasn't it? :sweat_smile: 
Doing this has been useful. Just having this turned on for a couple of hours has revealed that there are:
1. Problems we need to solve
2. Categories of noise we need to silence in order for this to be useful
In its current form, I want to turn this off for now, otherwise we're just going to smash our sentry allowance for the month on ingesting events which are mostly duplicating things we now already know.
This will probably come back, but I'm going to go and do some work on the above points before we re-enable it it.

Stop logging 429s to sentry (for now)

---

core/base-service/index.js
services/dynamic/dynamic-toml.service.js
services/dynamic/dynamic-toml.tester.js

This adds a dynamic service for TOML files.
I kept everything as close to the other dynamic services as possible. To be able to use the `BaseTomlService` from #9438, I exported in the core where the other base services are exported.
For the tests and default values I used the [`toml-spec-example.toml`](https://github.com/squirrelchat/smol-toml/blob/mistress/bench/testfiles/toml-spec-example.toml) from [`smol-toml`](https://github.com/squirrelchat/smol-toml) because `smol-toml` is used in here and it is the same example TOML file that [toml.io](https://toml.io) shows on their homepage, sadly they do not host this toml themselves.
I mostly ported over the test from the dynamic YAML service.

Add dynamic TOML support via [DynamicToml] Service

---

services/ubuntu/ubuntu.service.js
services/uptimerobot/uptimerobot-status.service.js
services/vaadin-directory/vaadin-directory-rating-count.service.js
services/vaadin-directory/vaadin-directory-release-date.service.js
services/vaadin-directory/vaadin-directory-status.service.js
services/vaadin-directory/vaadin-directory-version.service.js
services/vcpkg/vcpkg-version.service.js
services/visual-studio-marketplace/visual-studio-marketplace-last-updated.service.js
services/visual-studio-marketplace/visual-studio-marketplace-release-date.service.js
services/wheelmap/wheelmap.service.js

migrate examples to openApi part 8; affects [ubuntu uptimerobot vaadin vcpkg visualstudiomarketplace wheelmap]

---

.github/workflows/test-bug-run-badge.yml

`github.event.issue.body` is potentially untrusted. Avoid using it directly in inline scripts. instead, pass it through an environment variable. 
See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions for more details

Fix command injection vulnerability in Github workflow

---

core/base-service/openapi.js
core/base-service/openapi.spec.js

Closes https://github.com/badges/shields/issues/9527

fix rSt code example

---

services/reuse/reuse-compliance.service.js
services/sourceforge/sourceforge-commit-count.service.js
services/sourceforge/sourceforge-contributors.service.js
services/sourceforge/sourceforge-languages.service.js
services/sourceforge/sourceforge-last-commit.service.js
services/sourceforge/sourceforge-platform.service.js
services/sourceforge/sourceforge-translations.service.js
services/sourcegraph/sourcegraph.service.js
services/spack/spack.service.js
services/stackexchange/stackexchange-monthlyquestions.service.js
services/stackexchange/stackexchange-reputation.service.js
services/stackexchange/stackexchange-taginfo.service.js
services/testspace/testspace-test-pass-ratio.service.js
services/treeware/treeware-trees.service.js
services/twitch/twitch-extension-version.service.js

migrate examples to openApi part 7; affects [reuse sourceforge sourcegraph spack stackexchange testspace treeware twitch]

---

services/dub/dub-score.service.js
services/dub/dub-score.tester.js
services/test-validators.js

Closes #8662 
- Add dub score badge service

Add [dub] score badge service

---

services/bower/bower-version.service.js
services/bower/bower-version.spec.js
services/bower/bower-version.tester.js

Our bower badges use the libraries.io API. Also bower is a low traffic badge/mostly abandoned service.
The version badge (which should be latest stable version) consistently returns "no releases" for pretty much any package.
This is because if you look at the API response for a bunch of packages e.g:
- https://libraries.io/api/bower/bootstrap
- https://libraries.io/api/bower/angular
- https://libraries.io/api/bower/backbone
- https://libraries.io/api/bower/Font-Awesome
- https://libraries.io/api/bower/grunt
- https://libraries.io/api/bower/gulp
- https://libraries.io/api/bower/jQuery
they all return `latest_stable_release_number: null`, although it is worth noting that all of them do have a proper version number against `latest_release_number`, so the `include_prereleases` variant works …

fix [bower] version badge

---

doc/TUTORIAL.md

Closes #9559
- Fix mismatch in documentation and examples given in tutorial

Fix mismatch in documentation and examples given in tutorial

---

services/redmine/redmine.service.js
services/redmine/redmine.tester.js

Redmine badges have been failing for some time due to a consistent 500 error from the upstream API.
- https://img.shields.io/redmine/plugin/stars/redmine_xlsx_format_issue_exporter
- https://www.redmine.org/plugins/redmine_xlsx_format_issue_exporter
- https://www.redmine.org/plugins/redmine_xlsx_format_issue_exporter.xml
The badge receives little traffic and despite being broken for months, nobody has complained. If we a look at a bunch of different redmine plugins, we see the same thing for all of them:
- https://www.redmine.org/plugins/redmine_issue_dynamic_edit.xml
- https://www.redmine.org/plugins/redmine-x-upgrade-plugin.xml
- https://www.redmine.org/plugins/redmine-x-gantt-chart-plugin.xml
- https://www.redmine.org/plugins/redmine_issue_to_email.xml
- etc
Suggest we deprecate this …

deprecate [redmine] plugin rating badges

---

.github/scripts/deploy-review-app.sh

I was having some issues with review apps today. Looks like there have been some upstream changes to fly.io which we need to account for:
1. Fly now auto-detects a node js app and tries to use a sort of "buildpack" like deploy strategy. We have to manually tell it to use our dockerfile, rather than that being the default
2. When you start a new app, by default fly give you 2 machines. We need to manually tell it to scale down to 1 after deploying
Going to just go ahead and merge this one as review apps are currently broken

fix review apps

---

services/bower/bower-license.service.js
services/conda/conda-license.service.js
services/freecodecamp/freecodecamp-points.service.js
services/freecodecamp/freecodecamp-points.tester.js
services/galaxytoolshed/galaxytoolshed-activity.service.js
services/galaxytoolshed/galaxytoolshed-downloads.service.js
services/jenkins/jenkins-plugin-version.service.js
services/npm/npm-type-definitions.service.js
services/puppetforge/puppetforge-module-downloads.service.js
services/puppetforge/puppetforge-module-endorsement.service.js
services/puppetforge/puppetforge-module-feedback.service.js
services/puppetforge/puppetforge-module-pdk-version.service.js
services/puppetforge/puppetforge-module-version.service.js
services/puppetforge/puppetforge-user-module-count.service.js
services/puppetforge/puppetforge-user-release-count.service.js

migrate examples to openApi part 9; affects [bowerlicense conda freecodecamp galaxytoolshed jenkins-plugin npmtypedefinitions puppetforge]

---

services/bitbucket/bitbucket-pipelines.service.js

Refs #9285
This one doesn't have passing service tests and I don't have the examples to hand to fix them, so I'm going to push a commit that does nothing, let the tests fail, then push a commit that does stuff so we can at least see the failures aren't new.
In general, this whole process probably will require modifying more code that doesn't have (reliably) passing service tests.

migrate examples to openApi part 10

---

.github/scripts/check-docusaurus-versions.sh
.github/workflows/check-docusaurus-versions.yml
package-lock.json

Yesterday I merged https://github.com/badges/shields/pull/9600
When I was working on shields today, I realised that docusaurus was outputting
```
[ERROR] Invalid docusaurus-plugin-content-docs version 2.4.1.
All official @docusaurus/* packages should have the exact same version as @docusaurus/core (2.4.3).
Maybe you want to check, or regenerate your yarn.lock or package-lock.json file?
[ERROR] Invalid docusaurus-plugin-content-blog version 2.4.1.
All official @docusaurus/* packages should have the exact same version as @docusaurus/core (2.4.3).
Maybe you want to check, or regenerate your yarn.lock or package-lock.json file?
[ERROR] Invalid docusaurus-plugin-content-pages version 2.4.1.
All official @docusaurus/* packages should have the exact same version as @docusaurus/core (2.4.3). …
```

sync docusaurus plugin versions

---

services/pepy/pepy-downloads.service.js
services/pepy/pepy-downloads.tester.js

Closes https://github.com/badges/shields/issues/4319
Refs https://github.com/psincraian/pepy/issues/573

add python package total downloads from [pepy] badge

---

frontend/src/pages/community.md

Refs https://github.com/opencollective/opencollective/issues/6982 and https://github.com/opencollective/opencollective-images/pull/580
tl;dr:
- The OpenCollective images URLs we were using don't accurately show our current sponsors and backers
- These new ones do
I'd quite like to get this one merged so I can deploy and close the loop with the sponsor that contacted us about this.

switch to fixed OpenCollective images

---

badge-maker/lib/xml.js
core/base-service/base-graphql.js
core/base-service/base-json.js
core/base-service/base.spec.js
core/base-service/openapi.js
services/github/github-directory-file-count.spec.js
services/packagist/packagist-license.tester.js
services/pypi/pypi-version.tester.js
services/static-badge/static-badge.service.js
services/website-status.js

I observed that "separated" was misspelled at the top of https://shields.io/badges so this PR addresses those typos.
I then ran the codespell tool, which identified some additional typos (some of which might not be user-facing). Those are included in this PR, too.

Fix several typos

---

services/greasyfork/greasyfork-base.js
services/greasyfork/greasyfork-downloads.tester.js

fix [GreasyFork] 404 bug

---

services/gitlab/gitlab-release.service.js
services/swagger/swagger.service.js

In this PR, I've started tackling query params.
Instead of converting a lot of services, I've concentrated on picking a couple of services that I think cover all of the most common variations so we can see what that looks like and establish the patterns we're going to use going forwards.
Can anyone think of a case I have missed here?

migrate examples to openApi part 16; affects [gitlabrelease swagger]

---

services/amo/amo-base.js
services/amo/amo-downloads.service.js
services/amo/amo-rating.service.js
services/amo/amo-users.service.js
services/amo/amo-version.service.js
services/bit/bit-components.service.js
services/coincap/coincap-base.js
services/coincap/coincap-changepercent24hr.service.js
services/coincap/coincap-priceusd.service.js
services/coincap/coincap-rank.service.js
services/conan/conan-version.service.js
services/cpan/cpan-license.service.js
services/cpan/cpan-version.service.js
services/cpan/cpan.js

Refs #9285
This PR comes out of a comment in the PR #9500 review: https://github.com/badges/shields/pull/9500#discussion_r1378685603
I haven't tackled every single case, but I decided to start off by taking an initial subset of services where we removed keywords when I did earlier conversion PRs, just to think it through and get a feel for this task.
In order to make text available to our search plugin, it needs to be user-visible text on the page. We can't give it "hidden" tags or keywords. In general, I don't think that's a bad thing: One of the things we should be working towards is providing clearer user-facing documentation. If you land directly on https://shields.io/badges/clojars-downloads (for the sake of argument), I think we can do more to explain "what is this thing, and why do …

add meaningful descriptions including keywords; affects [amo bitcomponents coincap conan cpan]

---

services/github/gist/github-gist-last-commit.service.js
services/github/gist/github-gist-stars.service.js
services/github/github-all-contributors.service.js
services/github/github-code-size.service.js
services/github/github-commit-status.service.js
services/github/github-deployments.service.js
services/github/github-labels.service.js
services/github/github-language-count.service.js
services/github/github-license.service.js
services/github/github-repo-size.service.js
services/github/github-search.service.js
services/github/github-sponsors.service.js
services/github/github-top-language.service.js

Refs #9285
I'm not going to repeat the same blurb. In this one I am still tackling easier cases (all path params) but I'm now moving on to the ones with a description/documentation string of some kind.

migrate examples to openApi part 12; affects [GitHub Gist]

---

services/github/github-commit-activity.tester.js

Hit failures on this in a couple of PRs lately.
This is going to be hard to write in a way that doesn't just keep breaking, so I've changed these test cases to allow `isZeroOverTimePeriod`

fix [GitHubCommitActivity] service tests

---

services/ansible/ansible-collection.service.js
services/ansible/ansible-collection.tester.js
services/ansible/ansible-quality.service.js
services/ansible/ansible-quality.tester.js
services/ansible/ansible-role.service.js
services/ansible/ansible-role.tester.js

This PR implements the proposals from https://github.com/badges/shields/issues/9631#issuecomment-1753494195
- deprecate ansible galaxy collection name
- deprecate ansible galaxy quality score
- deprecate ansible role name
- deprecate ansible role downloads and replace with a new (but non-backwards-compatible) ansible role downloads badge

deprecate/fix [ansible] galaxy services

---

package-lock.json
package.json
services/color-formatters.js
services/python/python-version-from-toml.tester.js

At some point this package moved namespace and we didn't notice.
We're already using the right copy of `@renovatebot/ruby-semver`

move from @renovate/pep440 to @renovatebot/pep440; affects [pypi piwheels python]

---

services/nodeping/nodeping-status.service.js
services/nodeping/nodeping-uptime.service.js
services/website-status.js
services/website/website.service.js

Closes #9609
Did nodeping while I was at it as it uses the same shared helpers.
Refs #9285

update website docs, migrate examples to openapi; affects [website nodeping]

---

services/bundlephobia/bundlephobia.service.js
services/discord/discord.service.js
services/opencollective/opencollective-all.service.js
services/opencollective/opencollective-backers.service.js
services/opencollective/opencollective-sponsors.service.js
services/pypi/pypi-downloads.service.js

Having merged and deployed https://github.com/badges/shields/pull/9546 there's still a bunch of services where we're regularly hitting rate limits. Upping the caches again.
I'm a bit worried I might have completely smashed our sentry allowance for the month, but I wasn't able to immediately do something about this yesterday.
There are some other rate limiting issues which I will track elsewhere.
I'm going to just merge and deploy this one today.

cache some badges for longer

---

services/discourse/discourse.service.js
services/discourse/discourse.tester.js

This PR does a simple find and replace to update the Discourse schema to use the current keys found in https://meta.discourse.org/site/statistics.json, as the older keys now return "Invalid response".
> [!NOTE] 
> I was wondering, though, if the old keys should still be preserved, as to not break backwards compatibility with servers using the old names. 
>
> (I tried finding the source of the change in Discourse's release notes/changelog, but there's surprisingly little information when querying e.g. "statistics.json" or "topic_count"/"topics_count". So, I'm not sure when this change actually took place, and thus it's hard to estimate the likelihood of there being servers out there using the old keys.)
>
> If we do want to support both sets of keys, then I'm not 100% sure what to do, as …

[Discourse] Update schema keys to use plural form (`topic_count` -> `topics_count`)

---

README.md
frontend/docusaurus.config.cjs

Follow on from https://github.com/badges/shields/pull/9678#issuecomment-1777898375
Given the one person with access to this is no longer actively checking it, I'm not convinced it is a useful thing to still be pointing people at.
So we could just.. stop.

stop linking to twitter

---

services/pub/pub.service.js

* pub.dartlang.org is replaced by pub.dev as the official pub site.
* `api/packages/<packageName>` is the official endpoint for retrieving a version listing.
see https://pub.dev/help/api#hosted-pub-repository-api -> https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md#list-all-versions-of-a-package
The `packages/<packageName>.json` endpoint is obsolete and might go away.

[pub] Use official version endpoint for pub-service

---

services/npm-stat/npm-stat-downloads.service.js
services/npm-stat/npm-stat-downloads.spec.js
services/npm-stat/npm-stat-downloads.tester.js

Add the npm downloads (by author) badge discussed in https://github.com/badges/shields/issues/9777

Add [NpmStatDownloads] Badge

---

services/dynamic/dynamic-xml.service.js

This is a follow up from https://github.com/badges/shields/issues/9784
I've attempted to document the point raised there, although I found it slightly tricky to explain it in a completely general way without referencing an example.
I also made a couple of other minor improvements while I was there.

improve documentation for [dynamicxml] service

---

services/buildkite/buildkite.service.js
services/bundlephobia/bundlephobia.service.js
services/cii-best-practices/cii-best-practices.service.js
services/codeship/codeship.service.js
services/crates/crates-base.js
services/crates/crates-downloads.service.js
services/crates/crates-license.service.js
services/crates/crates-license.tester.js
services/crates/crates-version.service.js
services/jsdelivr/jsdelivr-hits-github.service.js
services/jsdelivr/jsdelivr-hits-npm.service.js
services/npms-io/npms-io-score.service.js

I have touched fewer files in this PR as I'm starting to get into some more slightly more involved services now.
I'll be honest. 17 PRs deep into this project and knowing how many more there are to do, my enthusiasm for this endeavour is starting to decrease a bit. Staying strong though.
I've skipped the bundlephobia tests on this PR. They seem to be having some kind of outage at the moment affecting some packages but not others e.g:
https://bundlephobia.com/api/size?package=react (works)
https://bundlephobia.com/api/size?package=preact (error)
lets keep an eye on that one..

migrate examples to openApi part 17; affects [buildkite cii codeship crates jsdelivr npms] and bundlephobia

---

doc/TUTORIAL.md

Refs #9285
This PR updates the tutorial for adding a new badge to document the `openApi` object instead of the `examples` array.
Obviously we're still working through the process of migrating so the codebase itself is still a bit of a mix. That said, I think after we merge this, we should stop accepting services that use `examples` in new contributions.

migrate examples to openApi part 20: TUTORIAL.md

---

services/gitlab/gitlab-contributors.service.js
services/gitlab/gitlab-forks.service.js
services/gitlab/gitlab-helper.js
services/gitlab/gitlab-issues.service.js
services/gitlab/gitlab-languages-count.service.js
services/gitlab/gitlab-last-commit.service.js
services/gitlab/gitlab-license.service.js
services/gitlab/gitlab-license.tester.js
services/gitlab/gitlab-merge-requests.service.js
services/gitlab/gitlab-pipeline-coverage.service.js
services/gitlab/gitlab-pipeline-coverage.tester.js
services/gitlab/gitlab-pipeline-status.service.js
services/gitlab/gitlab-pipeline-status.tester.js
services/gitlab/gitlab-release.service.js
services/gitlab/gitlab-stars.service.js
services/gitlab/gitlab-tag.service.js

There's a few things going on in this PR. Slightly more than I would ideally like for one of these PRs.
dba3c60 - this test was failing due to a license change on the upstream repo
Given all we are really testing there is that we apply the right colour if the license is "other", I've just replaced this with a mock rather than finding another repo we can use.
fd67c2b , 64f6948 - these tests for the pipeline status/coverage badges (which use `BaseSvgScrapingService` but should really me migrated to use the API) were failing due to a change in the upstream behaviour. I've just updated the tests rather than handling in the code (again)
82131f9 - Most of this is pretty standard procedure. However I've also done a bit of refactoring on the …

migrate examples to openApi part 26; affects [gitlab]

---

services/github/github-common-release.js

This was something I spotted when I was thinking about the review for https://github.com/badges/shields/pull/9781
If we are requesting the latest version by semver (rather than date) we request the first page of releases and search it for the latest release. The default page size is 30 releases and the max is 100.
I'm not really sure what happened here. I don't know if GitHub changed the default page size from 100 to 30 at some point or we messed this up in a refactor somewhere, but currently we only search the most recent 30 releases not the most recent 100.
The tags badge already does this correctly https://github.com/badges/shields/blob/2814de2ecd3dffcd5206c1398a28191211cf63b5/services/github/github-tag.service.js#L87-L92

increase page size for [githubrelease] badge by semver

---

services/github/gist/github-gist-stars.service.js
services/github/github-followers.service.js
services/github/github-forks.service.js
services/github/github-stars.service.js
services/github/github-total-star.service.js
services/github/github-watchers.service.js
services/gitlab/gitlab-forks.service.js
services/gitlab/gitlab-stars.service.js
services/keybase/keybase-btc.service.js
services/keybase/keybase-pgp.service.js
services/keybase/keybase-xlm.service.js
services/keybase/keybase-zec.service.js
services/lemmy/lemmy.service.js
services/modrinth/modrinth-followers.service.js
services/reddit/subreddit-subscribers.service.js
services/reddit/user-karma.service.js
services/thunderstore/thunderstore-likes.service.js
services/twitch/twitch.service.js
services/twitch/twitch.spec.js

Fixes #9704 by rendering all badges in the social category with the social style and a logo by default.

Ensure social category badges are rendered with social style and logo; affects [gitlab keybase lemmy modrinth thunderstore twitch] gist github reddit

---

cypress/e2e/main-page.cy.js
services/discourse/discourse.service.js
services/packagecontrol/packagecontrol.service.js

I'm only touching a couple of files in this PR but there is a bit more refactoring going on here so I split them out.
For these two services, we've got a similar pattern to the one we see in https://github.com/badges/shields/pull/9841 and https://github.com/badges/shields/pull/9732 - a function that generates multiple service classes.
In both these cases, I opted to refactor the services to use an enum parameter.

migrate some services from examples to openApi part 31; affects [packagecontrol discourse]

---

services/bower/bower-version.service.js
services/drone/drone-build.service.js
services/drone/drone-build.tester.js
services/localizely/localizely.service.js
services/mozilla-observatory/mozilla-observatory.service.js
services/python/python-version-from-toml.service.js

Refs https://github.com/badges/shields/issues/9285.

migrate examples to openApi part 33; affects [bower drone localizely mozillaobservatory pythonversionfromtoml]

---

core/base-service/openapi.js
core/base-service/openapi.spec.js

Fixes the following typo:
`defauTL -> defauLT`

Fix typo in OpenAPI service documentation

---

services/github/github-actions-workflow-status.service.js
services/github/github-commit-activity.service.js
services/github/github-commits-since.service.js
services/github/github-common-release.js
services/github/github-downloads.tester.js
services/github/github-go-mod.service.js
services/github/github-pull-request-check-state.tester.js
services/github/github-release.service.js
services/github/github-tag.service.js

Refs #9285
There were a couple of failing GitHub service tests so I started off by fixing them here, just so I could run `[github]` on the PR:
1. When I did #9818 I forgot to update the tests for GitHub downloads - it uses a helper function shared with releases/tags. I fixed the mock
2. When I updated the branch protection rules for #9799 it changed the status of older PRs to pending. I updated the example
so that gets the github tests passing
---
Then I started tackling some of the meatier GitHub badges that had a lot of variants or use shared helpers. I've only touched 6 services in this PR as there is quite a lot of diff to review just for these 6 services and I'm trying to keep each PRs relatively small/easy to review.

migrate examples to openApi part 34; affects [github]

---

services/npm/npm-base.js
services/npm/npm-collaborators.service.js
services/npm/npm-dependency-version.service.js
services/npm/npm-downloads.service.js
services/npm/npm-license.service.js
services/npm/npm-type-definitions.service.js
services/npm/npm-version.service.js

migrate examples to openApi part 35; affects [npm]

---

services/crates/crates-base.js
services/crates/crates-msrv.service.js
services/crates/crates-msrv.tester.js

Proposed in #9733
Routes:
Crates.io MSRV: `/crates/msrv/:crate`
Crates.io MSRV (version): `/crates/msrv/:crate/:version`

[CratesMSRV] Badge

---

services/thunderstore/thunderstore-base.js
services/thunderstore/thunderstore-version.service.js

[thunderstore] Replace experimental API usage with newly available v1 API

---

README.md

running `npm run defs` omits the `BASE_URL=` env var

small docs fix: defs --> prestart

---

core/base-service/openapi.js
core/base-service/openapi.spec.js
scripts/export-openapi-cli.js

Closes https://github.com/badges/shields/issues/9884
I've kept core unsorted so we can put "static badge" first. The other categories now sort by title

sort categories by title (except core)

---

services/crates/crates-base.js
services/crates/crates-downloads.service.js
services/crates/crates-downloads.tester.js
services/crates/crates-license.service.js
services/crates/crates-license.spec.js
services/crates/crates-msrv.service.js
services/crates/crates-version.service.js
services/crates/crates-version.spec.js

There's a few small things here that came out of the review of https://github.com/badges/shields/pull/9871
1. Fix a failing service test. This is a change in the upstream API behaviour. That case now returns a `404 Not Found` with the body `{"errors":[{"detail":"crate `libc` does not have a version `7`"}]}`. I've updated the assertion as we now throw an error based on the response code.
2. I was originally planning to move the handling of "`200 OK` with an error body" up a level to de-dupe, and check for that condition in `BaseCratesService.fetch()`. However, given that the condition we were attempting to handle looks like it is now fixed (and that's what required us to update that test), I've decided to just completely remove the handling for this and treat a `200 OK` with an error body …

[crates] tidyup

---

core/base-service/redirector.js
core/base-service/service-definitions.js
services/gradle-plugin-portal/gradle-plugin-portal.service.js
services/maven-central/maven-central.service.js
services/maven-metadata/maven-metadata.js
services/maven-metadata/maven-metadata.service.js

I split this out because it needed some base-service changes to go along with it.

migrate some services from examples to openApi part 39; affects [maven gradle]

---

badge-maker/README.md

Minor thing I noticed while working on https://github.com/badges/shields/pull/9916
The semantic colour for build pass is brightgreen so lets get that right in the package docs

use brightgreen for build passing in package docs

---

services/sonar/sonar-coverage.service.js
services/sonar/sonar-documented-api-density.service.js
services/sonar/sonar-fortify-rating.service.js
services/sonar/sonar-generic.tester.js
services/sonar/sonar-helpers.js
services/sonar/sonar-quality-gate.service.js
services/sonar/sonar-tech-debt.service.js
services/sonar/sonar-tests.service.js
services/sonar/sonar-tests.tester.js
services/sonar/sonar-violations.service.js

Made a start on this service family. Submitting a WIP PR for now, just to lick the cookie. I'll finish it later in the week.

migrate some services from examples to openApi part 44; affects [sonar]

---

services/docker/docker-cloud-automated.service.js
services/docker/docker-cloud-build.service.js
services/docker/docker-helpers.js
services/docker/docker-size.service.js
services/docker/docker-version.service.js
services/docker/docker-version.tester.js

I'm going to cautiously say: I think this is the last one.
Once all the outstanding related PRs are merged (including https://github.com/badges/shields/pull/9932 ) I _think_ that should be every service moved over to using openApi, unless I missed a spot :crossed_fingers: and I can:
- Start on the cleanup necessary to remove all the compatibility stuff that allowed `examples` and `openApi` to exist side-by-side
- Revisit https://github.com/badges/shields/pull/9820 (it was too hard to work on with this still in flight)
Hopefully.

migrate some services from examples to openApi part 47; affects [docker]

---

services/codeclimate/codeclimate-analysis.service.js
services/codeclimate/codeclimate-analysis.tester.js
services/codeclimate/codeclimate-common.js
services/codeclimate/codeclimate-coverage.service.js
services/codeclimate/codeclimate-coverage.tester.js
services/librariesio/librariesio-dependencies.service.js
services/nexus/nexus.service.js
services/nexus/nexus.tester.js
services/security-headers/security-headers.service.js

With nexus, we don't have passing tests for nexus v3
I have actually managed to find a couple of public nexus servers running v3:
- https://repo.tomkeuper.com/
- https://repo.unnamed.team/
but I can't work out how to get a working badge out of either of them.
With Security Headers, the tests fail because the badges themselves are broken https://github.com/badges/shields/issues/9154 I figure lets just migrate the examples here and leave that as an issue for another time.

migrate some services from examples to openApi part 46; affects [codeclimate librariesio nexus] and securityheaders

---

services/bitbucket/bitbucket-issues.service.js
services/bitbucket/bitbucket-issues.tester.js
services/bitbucket/bitbucket-pipelines.service.js
services/bitbucket/bitbucket-pipelines.tester.js
services/bitbucket/bitbucket-pull-request.service.js
services/bitbucket/bitbucket-pull-request.spec.js
services/bitbucket/bitbucket-pull-request.tester.js
services/bitrise/bitrise.service.js
services/bitrise/bitrise.tester.js
services/chrome-web-store/chrome-web-store-rating.service.js
services/circleci/circleci.service.js
services/circleci/circleci.tester.js

Refs https://github.com/badges/shields/issues/9285.
~Leaving as draft for now, gonna see if I can find some good updated Bitbucket examples.~ All tests and examples fixed.

migrate examples to openApi part 37; affects [bitbucket bitrise chromewebstore circleci]

---

services/tas/tas-tests.service.js
services/tas/tas-tests.tester.js

This has been failing for a long time. As far as I can tell the upstream API endpoint is gone and has not been replaced.
Suggest we just bin this service.

deprecate TAS

---

core/token-pooling/sql-token-persistence.js

While I was worrying about https://github.com/badges/shields/issues/9978 I spent a bit of time digging into the token pool code.
I don't think this is related as such, but one of the things I realised is that when we bootstrap the server, all the VMs in the cluster load all the tokens in the same order.
Grabbing the tokens in a random order will do a better job of spreading the traffic out over the available tokens we have.

randomize tokens on token pool init

---

services/gitea/gitea-last-commit.service.js
services/gitea/gitea-last-commit.tester.js

Adds a 'Last Commit' badge with 2 route mirroring the options provided by Github which is the basis for the Gitea implementation also (they strive to be close to Github's API usage).
I believe this should be enough to close issue #4040 unless there are more badges needed before the service is considered implemented.

[GITEA]  Add last commit badge

---

services/jsr/jsr-version.service.js
services/jsr/jsr-version.tester.js

Hi, this PR adds a version service for [JSR](https://jsr.io/) packages.
Path: `/jsr/v/:scope(@[^/]+)/:packageName`
Example:
Related to #10007

Add [JSR] version service

---

services/gitea/gitea-last-commit.service.js
services/github/github-last-commit.service.js
services/gitlab/gitlab-last-commit.service.js

This is something I noticed while I was testing https://github.com/badges/shields/pull/10041
It isn't a new problem introduced by that PR, so I decided not to scope creep it there.
Basically the deal here is we only care about the most recent commit, but we're requesting an entire page of results to just use the first object. Only requesting the most recent one means we can request less data from the upstream and render the badge faster. Note this optimisation doesn't work in all situations. Specifically, Gitea ignores limit when the path param is also supplied (see https://docs.gitea.com/api/1.20/#tag/repository/operation/repoGetAllCommits ), but we might as well do this whenever we can.
Note that @ReubenFrankel has already applied the equivalent optimisation in …

improve performance of [GithubLastCommit] [GitlabLastCommit] [GiteaLastCommit]

---

services/nuget/nuget-v2-service-family.js

Fixes #10045 
The "got" package encodes spaces in `searchParams` as `+` (see https://github.com/sindresorhus/got/issues/1113) but the Chocolatey API requires spaces to be encoded as `%20` instead.
I have tested that `npm run test:services -- --only=chocolatey,nuget` passes with these changes.
Example of failing query:
https://community.chocolatey.org/api/v2/Packages()?%24filter=Id+eq+%27windynamicdesktop%27+and+IsLatestVersion+eq+true
Example of working query:
https://community.chocolatey.org/api/v2/Packages()?%24filter=Id%20eq%20%27windynamicdesktop%27%20and%20IsLatestVersion%20eq%20true

[chocolatey powershellgallery resharper] Fix "not found" error for chocolatey badge

---

package-lock.json
package.json

This reverts commit d1703c0592371c99db1c46cc3ead9cd4bc09a22e.
Not really sure what happened here.
Checked this on a review app and locally - no issues, but if I try to deploy docker image `sha256:e77392c2f4cfa1a9da6a7754fd26911f560bc522e3fc0d56ee7386b910b0c5b1` to staging, it won't pass a health check. Previous images deploy fine.
Going to try reverting this for now.

Revert simple-icons 11.11.0

---

services/github/github-go-mod.service.js
services/github/github-go-mod.spec.js

Fixes #10079.
Ignore a comment after the version in the `go.mod` file.

[GitHubGoMod] Ignore comment after version (fixes #10079)

---

services/licenses.js
services/licenses.spec.js
services/pypi/pypi-helpers.js
services/pypi/pypi-helpers.spec.js

- Added 0BSD license to public domain in licenseTypes
- Added licenseTypes tests in spec file
- Added 0BSD to PyPi helper with test in helper spec file
PyPi on production:
`https://img.shields.io/pypi/l/makemake90`
After change:
Github License on production:
`https://img.shields.io/github/license/arnavyc/aes-c`
After change:
Part of issue #10058

Add 0BSD license to licenseTypes and [PypiLicense]

---

core/base-service/legacy-request-handler.js

After I merged https://github.com/badges/shields/pull/9191 I deployed it to staging, gave it a quick test and realised we missed something.
This param was only taking effect for static badges. It was ignored for dynamic ones.
This change fixes it, but it does also raise follow up questions which I'll note in an issue

add logoSize to globalQueryParams

---

services/hexpm/hexpm.service.js
services/hexpm/hexpm.tester.js

Hex.pm's API now seems to return `null` for `latest_stable_version`, where I assume from `shields`' code that it previously did not return the property at all:
```
},
"html_url": "https://hex.pm/packages/nodelix",
"latest_stable_version": null
}
```
[source](https://hex.pm/api/packages/nodelix)
This PR aims to support that in order for badges of pre-release-only version packages work again.
Example of a broken badge:
[![](https://img.shields.io/hexpm/dt/nodelix.svg)](https://img.shields.io/hexpm/dt/nodelix.svg)
Error logs from `npm run badge -- /hexpm/dt/nodelix` on `master`:
```
Response did not match schema  🤷 
"latest_stable_version" must be a string
Handled error  🙅 
[ValidationError: "latest_stable_version" must be a string] {
prettyMessage: 'invalid response data',
cacheSeconds: …
```

[Hexpm] Fix badges for pre-release only versions

---

lib/svg-helpers.js

I attempted to deploy https://github.com/badges/shields/pull/9191
This happened
There's something in that change that has caused a big performance issue.
I haven't really benchmarked this, but my instinct is that loading the whole simple-icons set every time we invoke `getIconSize()` is at least part of the problem.
This PR moves to doing this once at module load time instead of every time we call the function.

improve performance of getIconSize()

---

.github/scripts/deploy-review-app.sh

The review app creation script is failing in #7759 with the following error:
> Error: unknown flag: --region
According to the [deploy docs](https://fly.io/docs/flyctl/deploy/), only `regions` is available now. The [launch command](https://fly.io/docs/flyctl/launch/) still seems to support both variants, I've left it alone in this script for the time being.

Update region flag name in flyctl deploy command

---

doc/server-secrets.md

This brings these services into line with the others in this file

clarify yml paths in server-secrets docs

---

services/pypi/pypi-status.service.js
services/pypi/pypi-status.tester.js

Currently if we request this badge for a package with no 'Development Status' classifier we render an 'empty' badge
e.g: ![](https://img.shields.io/pypi/status/arcgis2geojson/3.0.2) - https://img.shields.io/pypi/status/arcgis2geojson/3.0.2
This PR fixes that

fix [pypi] status badge when package has no 'Development Status' classifier

---

services/librariesio/librariesio-api-provider.js
services/librariesio/librariesio-api-provider.spec.js

Refs #9839
Couple of things here: 1 is a fix for the mismatch in units comparing times
The other is: The rate limit on one of these tokens is 60/minute, so it feels like 45 is too big a batchSize. Reduce that so we switch every 10 requests,

tweaks to libraries.io token pooling code

---

.github/workflows/test-integration-22.yml
.github/workflows/test-main-22.yml
.github/workflows/test-package-cli.yml
.github/workflows/test-package-lib.yml
.github/workflows/test-services-22.yml
README.md

Node 22 is now out :tada: 
We should migrate to node 22 at some point, but for the moment lets just start running the tests against it in preparation. I'll also do some testing with it when I'm developing locally.

run tests on node 22

---

.github/dependabot.yml

Closes https://github.com/badges/shields/issues/10135
Having read over, https://github.com/dependabot/dependabot-core/issues/6704 this should work
but I can't really confirm until I merge it.

instruct dependabot to monitor composite actions

---

services/github/gist/github-gist-last-commit-redirect.tester.js
services/github/gist/github-gist-stars.service.js
services/github/github-api-provider.js
services/github/github-created-at.service.js
services/github/github-lerna-json.service.js
services/scrutinizer/scrutinizer-build.service.js
services/scrutinizer/scrutinizer-coverage.service.js
services/scrutinizer/scrutinizer-quality.service.js

Replaces "Github" with "GitHub" in user-facing texts (badge titles and descriptions)

chore: fix spelling of GitHub in badge descriptions

---

services/github/github-checks-status.service.js
services/github/github-pull-request-check-state.service.js

As discussed in https://github.com/badges/shields/issues/4364#issuecomment-2106274450, this updates the description of the badge related to the Commit Status API. 
Similarly to the new Check Run badge, I expanded to three use cases: branch, commit, tag. 
Old: 
`GitHub tag checks state`
`GitHub pull request checks state`
New:
`GitHub tag status`
`GitHub commit status`
`GitHub branch status`
`GitHub pull request status`
Closes https://github.com/badges/shields/issues/4364

[GitHub] update description of commit status badge

---

services/bitbucket/bitbucket-pipelines.service.js
services/bitbucket/bitbucket-pipelines.tester.js

handle [BitbucketPipelines] responses with missing result key

---

README.md

It's been a while since we last updated this number (#7723), Cloudfare statistics have since then doubled:

Update number of badges served each month

---

services/github/github-commits-difference.service.js
services/github/github-commits-since.service.js
services/github/github-downloads.service.js
services/github/github-pull-request-check-state.service.js
services/github/github-release.service.js
services/liberapay/liberapay-base.js

According to our [badge guidelines](https://github.com/badges/shields/blob/master/CONTRIBUTING.md#badge-guidelines):
> Except for badges using the social style, logos and links should be turned off by default.
The following line of code does remove the logo when the badge has a non-social style, so we're not violating our guidelines per say:
https://github.com/badges/shields/blob/d68217295114c653d0a803463f368df3f146acda/core/base-service/coalesce-badge.js#L153
However, I think it's best to remove the `namedLogo` from the very few non-social badges where it is included, both from a consistency perspective, and to avoid any confusion (for example in #7759). Having something specified that is then overridden deep down somewhere else in the code is not exactly intuitive.

Remove namedLogo from defaultBadgeData of non-social badges

---

services/codeclimate/codeclimate-analysis.tester.js
services/codeclimate/codeclimate-coverage.tester.js

I introduced these two tests in #7716, but unfortunately they've broken a few times already (#9253,  #9933, and presently broken again). This probably boils down to the fact that the snapshot and test report IDs we use in the first mocked response eventually get cleaned up, making the second non-mocked query fail. I suggest we fully mock these tests, they exercise logic for edge cases so don't benefit from hitting the real upstream services as much anyway.
Closes #7833.

Fully mock flaky [CodeClimate] multi-step tests

---

services/jenkins/jenkins-coverage.service.js
services/jenkins/jenkins-coverage.tester.js

https://jenkins.sqlalchemy.org/job/alembic_coverage/ stopped reporting coverage via the Cobertura API. I noticed there had been a bunch of dependency updates and fixes related to testing in the corresponding repository, so maybe that had an impact. I've switched to https://jenkins.sqlalchemy.org/job/dogpile_coverage/ which is still configured as expected. If this breaks again in the near future, I suggest we switch to mocked tests.
Closes #8512.

Switch [JenkinsCoverage] Cobertura job URL

---

services/github/github-pull-request-check-state.tester.js

This is an amusing issue. `abc123` recently became a real ref on the repository (https://github.com/badges/shields/commit/abc123de1d2d3a83b256ccca5e17e6a4b6088097), which started making this test fail. `abcde12356` should be safe for a little while longer. 😄

Fix [GithubPullRequestCheckState] test

---

services/puppetforge/puppetforge-base.js
services/puppetforge/puppetforge-module-quality-score.service.js
services/puppetforge/puppetforge-module-quality-score.tester.js

The Puppet Forge run static analysis on modules and provide a score
through a (currently) internal API.
Waybe it will be in the public API in the future, but when this happen
adjusting the URL should be easy.  In the meantime, use this internal
API.

Add [puppetforge] quality score badges

---

services/docker/docker-helpers.js
services/docker/docker-version.tester.js

Add [Docker] support for loong64 arch

---

doc/TUTORIAL.md
doc/service-tests.md
services/docsrs/docsrs.service.js
services/docsrs/docsrs.tester.js

Updates the main tutorial and the service-tests one to use our Docs.rs service instead of the no longer existing Wercker service. It's a nice an simple service with everything publicly available. Closes #2423.
One of the error behaviours changed on the upstream API, I've also updated the implementation and tests to reflect that.

Update documentation and tests to [docsrs]

---

.github/workflows/daily-tests.yml

Refs https://github.com/badges/shields/issues/8821
This PR adds a GitHub Workflow that runs our tests every day and spits out a markdown summary.
Here's an example run: https://github.com/badges/shields/actions/runs/9749868442
This doesn't completely replicate all of the functionality of the old daily tests repo. That repo also measured and reported code coverage. However, I encountered two problems implementing this:
1. Both the markdown summary and coverage reports are implemented as mocha reporters. Out of the box, it is not possible to tell mocha to use 2 reporters at once, but there may be a way to work round this. I do want to produce human readable output as well as coverage XML though.
2. There's an issue with c8 that causes builds to fail when measuring coverage on Node 20. …

The return of daily tests

---

core/base-service/check-error-response.js
core/base-service/check-error-response.spec.js
core/server/log.js

Discord had requested Ray IDs to help investigate #10223, unfortunately we didn't have those available. I've added them as tags on the errors we log to Sentry. These IDs may be helpful for other services that are fronted by Cloudfare, I didn't condition on Discord. We can easily add other tags in the future if need-be.
Tested with Sentry hooked up to my local Shields.io copy, tweaking slightly `logErrors` to include 404s as those are easier to reproduce:

Add CF-Ray header value to Sentry errors if available

---

services/chocolatey/chocolatey.service.js
services/nuget/nuget-v2-service-family.js
services/powershellgallery/powershellgallery.service.js
services/resharper/resharper.service.js

Proposal to fix #10343.
The Chocolatey API seems to have started ignoring our `"Accept": "application/atom+json,application/json"` header, and sometimes now returns XML even when we're requesting JSON. The behaviour seems pretty inconsistent, changing slightly the filter parameter in the query can lead to a different format being returned. Switching to XML seems to produce stable results with all the examples I've tried.

Use XML for Chocolatey, affects [Chocolatey Resharper PowershellGallery]

---

.github/workflows/coveralls-code-coverage.yml

It's been exactly three years today since we last submitted a coverage report to Coveralls. This PR introduces a GitHub workflow that runs whenever a commit is pushed to master. To make sure everything was running as intended, I temporarily removed the master branch constraint before opening this PR, here's an example run: https://coveralls.io/builds/68519008

Add code coverage action

---

.c8rc.json
.gitignore
package.json

* adds a few extra ignored folders and deletes no-longer relevant ones.
* renames `.nycrc.json` to `.c8rc.json`, we hadn't done so in #6778 as we were still evaluating c8 at the time.
* stops attempting to clean up `.nyc_output`, we hadn't done so in #6778 as we were still evaluating c8 at the time.

Update c8 configuration

---

README.md

Follow up to #10320 and #10340.
I've gone ahead and archived the old https://github.com/badges/daily-tests repository.

Update daily tests reference in README

---

services/modrinth/modrinth-game-versions.service.js
services/modrinth/modrinth-game-versions.spec.js
services/modrinth/modrinth-game-versions.tester.js

Fixes #10346.
To make sure the ellipsis falls in the "middle", the list of game versions must be sorted. All the examples I've tried seem to return sorted results from the API, so I'm running under that assumption and have kept the implementation simple. We can always revisit later if need-be.

Use ellipsis when many versions returned for [ModrinthGameVersions]

---

services/bountysource/bountysource.service.js
services/bountysource/bountysource.tester.js

The company filed for bankruptcy last year, and the API has been down for several weeks.

Deprecate [Bountysource] service

---

services/gitea/gitea-helper.js
services/gitea/gitea-languages-count.service.js
services/gitea/gitea-last-commit.service.js

#9995 accidentally changed the not found message for all Gitea services, even those that don't support paths.

Fix [Gitea] not found message

---

services/ecologi/ecologi-carbon.tester.js

This test had started failing with the following error:
> ValidationError: message mismatch: "value" with value "1.2k tonnes" fails to match the required pattern: /[\d.]+ tonnes/
Let's use a more suitable validator.

Fix [EcologiCarbonOffset] test

---

services/amo/amo-version.tester.js

Mozilla added this weird `resigned1` suffix to versions of old (bumping the last updated field in the process and making old add-ons look like they were recently updated, what a silly thing to do :facepalm:):
> ValidationError: message mismatch: "value" with value "v4.5.3resigned1" fails to match the required pattern: /^v\d+(\.\d+)?(\.\d+)?$/

Fix [AmoVersion] test

---

services/freecodecamp/freecodecamp-points.service.js

The API apparently now returns a nice 404 response code we can leverage.

Fix [FreeCodeCampPoints] not found handling

---

services/python/python-version-from-toml.tester.js

Django does now specify a `python-requires` in their `pyproject.toml`. I've switched to a different repo. We could consider mocking this. This badge takes the URL to any file as a query param so we're not really testing for breaking changes in a service here.

update [PythonVersionFromToml] test example

---

services/pypi/pypi-license.tester.js

The package we're using for this test slightly changed the license value in their manifest.
https://github.com/psf/requests/commit/53a0562331c4a825036a347e77984d68b310fcf3

update [pypi] license test example

---

services/pub/pub-points.tester.js

Pub scores are now out of 160, not 140.
Instead of hard-coding this number, lets just accept a pattern.
The colours are based on `grantedPoints / maxPoints` rather than the raw score, so I think we don't really care if this number changes.

update [pub] points service test

---

core/base-service/base-static.js
core/base-service/cache-headers.js
core/base-service/redirector.js
core/server/server.spec.js

We serve a lot of static badges. `static_badge` is the single most popular badge on shields. Depending on the time of day it accounts for 10-15% of the traffic we serve from the origin (i.e: uncached). They are the least computationally expensive badges to serve, but there are a lot of them. Each one uses a connection, costs us some egress bandwidth, etc
In general, these badges don't really change. ![](https://img.shields.io/badge/foo-bar-blue) today is ![](https://img.shields.io/badge/foo-bar-blue) tomorrow.
We already serve these with quite a long cache on them (1 day), but I think we could go longer in some cases. There is a bit of churn of icon updates in simple-icons, so I think badges which use a logo should stay cached for a day, but for static badges that are just text, lets …

Cache text only static badges for longer

---

.github/ISSUE_TEMPLATE/2_Failing_service_test.md

We don't use Circle CI anymore.
It is not particularly easy to link directly to one individual test in the GH Actions markdown summary, so I suggest we just ditch this section.

remove reference to CircleCI

---

services/discord/discord.service.js
services/discord/discord.tester.js
services/revolt/revolt.service.js
services/revolt/revolt.tester.js

Refs https://github.com/badges/shields/issues/10249#issuecomment-2171684953
These badges display exact values, but they should really use `metric()`

use metric() for [discord] and [revolt] badges

---

services/bitrise/bitrise.service.js
services/bitrise/bitrise.tester.js

The `master` branch no longer exists, let's switch to the default `develop` branch.

Fix branch in [Bitrise] tests

---

Dockerfile

While I was thinking about https://github.com/badges/shields/pull/10441 I realised that these are hangovers from when we had the rasterisation libraries installed. We don't need any of these any more.

remove libraries we don't need in docker build

---

.github/workflows/build-docker-image.yml
.github/workflows/create-release.yml
.github/workflows/publish-docker-next.yml
Dockerfile

We originally did this in https://github.com/badges/shields/pull/8862 due to issues deploying on fly.io
This problem has actually been fixed upstream for quite some time
https://community.fly.io/t/images-built-with-the-latest-docker-buildx-and-or-github-actions-work-again/10816
so we don't really need to be pinned to this old version any more.

un-pin buildx version

---

.github/workflows/create-release.yml
.github/workflows/publish-docker-next.yml
doc/self-hosting.md

I did some research and it seems the correct way to publish a multi-architecture build under a single tag is to do it simultaneously.
```
0 shane@jammy [/home/shane]$ docker pull shieldsio/shields:next
next: Pulling from shieldsio/shields
no matching manifest for linux/amd64 in the manifest list entries
```
That will make the entire build take the full duration of ~35 minutes. At a glance I don't see master being merged to more frequently than 35 minutes apart, so I have also included the next build here, but that can easily be removed.

Publish linux/amd64 docker images for snapshot builds only

---

services/modrinth/modrinth-base.js

I'm not really sure what this variable name was supposed to mean.
In any case, we don't need it :laughing:

remove intermediate variable; test [modrinth]

---

frontend/src/css/custom.css

This PR removes some workarounds I put in place and then forgot to remove.
We don't need these any more because the problems were fixed upstream in docusaurus-theme-openapi. I just forgot to remove these when we upgraded.

remove docusaurus css hacks

---

services/mozilla-observatory/mozilla-observatory.service.js

Refs https://github.com/mdn/mdn-http-observatory/issues/43#issuecomment-2309912082
Mozilla now publish and document a new endpoint that returns a reduced set of data
https://github.com/mdn/mdn-http-observatory/blob/main/README.md#post-apiv2scan
This contains everything we need and moves us to relying on a documented public endpoint rather than internals, so this PR migrates us to use that

migrate [MozillaObservatory] to /scan endpoint

---

services/packagist/packagist-stars.tester.js

This tests started failing because example.com now returns a 500 for its not found pages:
I feel that these tests don't bring much value, we're exercising the base error handlers with no Packagist-specific logic. Rather than fixing them, I suggest we get rid of them.

Remove failing [Packagist] tests

---

services/discord/discord.service.js
services/discord/discord.tester.js

The widget was apparently disabled on the previous Discord server that we were targetting, let's switch to our own server.

Switch to shields server ID in [Discord] example and test

---

services/dynamic/dynamic-xml.service.js

So we deployed https://github.com/badges/shields/pull/10481
and a few of these popped up
https://shields.sentry.io/issues/5811374190
https://github.com/badges/shields/pull/10481#issuecomment-2336400034
This is not a completely new source of error. For example
https://shields.sentry.io/issues/4386982653
has been happening occasionally for a while.
I'm not really sure exactly what input triggers either of those and we might still end up making further changes following https://github.com/badges/shields/pull/10481#discussion_r1740961975
but fundamentally, a document that doesn't parse shouldn't be an unhandled error on an endpoint where we accept arbitrary input. So lets fix that.

catch xml ParseError in [DynamicXml] badge

---

services/jenkins/jenkins-plugin-installs.service.js

Related with
- https://github.com/jenkins-infra/helpdesk/issues/4265
- https://github.com/jenkins-infra/plugin-site/pull/1890

[Jenkins] Use old.stats.jenkins.io for JSON data

---

services/dynamic/dynamic-json.tester.js
services/dynamic/json-path.js

After we merged https://github.com/badges/shields/pull/10551 yesterday a new error popped up in Sentry https://shields.sentry.io/issues/5906771741?project=251614
Here's an example of a document and query that cause this
https://raw.githubusercontent.com/json-ld/json-ld.org/refs/heads/main/schemas/jsonld-schema.json
`$.definitions.common.properties.['@id'].format`
This particular document/query combination is an example of https://github.com/JSONPath-Plus/JSONPath/issues/166 but I suspect there is a wider range of cases where we can hit this
https://github.com/JSONPath-Plus/JSONPath/blob/0c8dbcf656523fadc738cacee254ee8b96894bd7/src/jsonpath.js#L527-L528
In any case, we should catch this error and return an error badge, rather than falling over with an unhandled exception.

catch queries that cause TypeError in [dynamicjson]

---

services/jenkins/jenkins-plugin-installs.service.js

Revert "Use old.stats.jenkins.io for JSON data"; test [jenkins]

---

migrations/1727809177709_add-created.cjs

One of the things that has come out of https://github.com/badges/shields-ops/issues/38 is: It would be quite useful to know how long we've held a given token for in a more explicit way then relying on the id sequence. In some ways I'm a bit late to the party, but better late than never.
This PR creates a migration that adds a column called `created` to the `github_user_tokens` table. We'll need to manually run this migration on production after deploying it.
The `created` column defaults to `CURRENT_TIMESTAMP` which means:
- When we apply the migration it will set the `created` timestamp to now when we apply the migration for any existing records
- The existing code can run with or without this migration applied
- When we add new tokens they'll automatically be timestamped at `INSERT` …

add created timestamp to tokens table

---

services/dynamic/dynamic-xml.service.js
services/dynamic/dynamic-xml.spec.js
services/dynamic/dynamic-xml.tester.js

Closes https://github.com/badges/shields/issues/10586
Refs https://github.com/badges/shields/pull/10481#discussion_r1740961975

[DynamicXml] parse doc as html if served with text/html content type

---

services/f-droid/f-droid.service.js
services/nexus/nexus.service.js
services/nexus/nexus.spec.js
services/wordpress/wordpress-version.service.js

We mostly use the short more elegant `renderVersionBadge` but some services still use older method of directly calling addv and versionColor.
These changes refactor the WordpressVersion, Nexus and FDroid services to fit usage of `renderVersionBadge`

Refactor version rendering in [wordpress nexus] and [f-droid] services

---

services/nexus/nexus.tester.js

This pull request updates the Nexus test to search for a valid version of the artifact "event" from the repository "https://repo.voxelpi.net". The previous test was searching for the artifact "bedwars-api" from the repository "https://repo.tomkeuper.com" which started failing the test recently, see also https://github.com/badges/shields/actions/runs/11306263530?pr=10608 & PR #10608

Change [Nexus] test for valid version

---

services/github/github-hacktoberfest.service.js

This should have probably been done a few weeks ago, but hey, better late than never. Maybe we could put in a Google calendar reminder or something like that for next year.

[GitHubHacktoberfest] 2024 support

---

services/archlinux/archlinux.tester.js

use iptables as its a stable long term package that uses more standard version numbers
archlinux uses upstream versions which makes version regex for tests hard to predict
see also failed test at https://github.com/badges/shields/actions/runs/11364173280?pr=10615
in PR #10615
see also https://wiki.archlinux.org/title/PKGBUILD#Version for info about pkg versions. might include letters and dates rather then fixed regex.

update failing test to use package iptables in [archlinux]

---

fly.toml

Without an explicit config in here, fly brings up our review apps with the default settings. This means our review apps get allocated 1Gb Memory which is unnecessary. 256Mb is fine for a review app serving a handful of requests.
I suspect our monthly spend on review apps is not very high in the grand scheme of things, but this will shave a bit off that cost.

set VM size to shared-cpu-1x/256Mb on staging apps

---

services/crates/crates-base.js
services/crates/crates-user-downloads.service.js
services/crates/crates-user-downloads.tester.js

This pull request adds the `CratesUserDownloads` service and tester files.
The `CratesUserDownloads` service fetches data from the crates.io API to show the total downloads for a user. 
It also includes tests for the service.
Added `BaseCratesUserService` for api route for users.
Solves #10614.

Add [CratesUserDownloads] service and tester

---

services/hackage/hackage-deps.service.js
services/hackage/hackage-deps.tester.js

Badge will always return up to date falsely as the upstream site is closed and looking for someone to take over.
The first test if a package exist will always return 200 OK even when non existing as we get the landing page.
Then we will never get "outdated dependencies" as the landing page doesn't include that text.
I looked into the https://hackage.haskell.org/api and couldn't find a quick way to replace the current upstream.
Therefor i propose we remove this badge, this is misleading at best as it's now.

Deprecate [HackageDeps] service

---

package-lock.json
package.json
services/chrome-web-store/chrome-web-store-last-updated.service.js
services/chrome-web-store/chrome-web-store-last-updated.tester.js
services/chrome-web-store/chrome-web-store-size.service.js
services/chrome-web-store/chrome-web-store-size.tester.js

[Chromewebstore] Extension size & last updated

---

core/base-service/legacy-result-sender.js
core/server/server.spec.js

This PR does not resolve an open security issue. However, it does proactively add another layer of protection on top of what we already do to prevent cross-site scripting issue.
SVGs can contain javascript.
When they're embedded with an `<img>` tag, SVGs are rendered in [secure static mode](https://www.w3.org/TR/SVG2/conform.html#secure-static-mode) which disables any embedded javascript, along with some other restrictions.
When they're embedded with a `<object>` tag or loaded directly, this is not the case.
While we take steps to prevent XSS issues, we have on at least one occasion discovered an escaping issue, which made it possible for someone to inject script into a badge image. Reference: https://github.com/badges/shields/pull/3511
In general, I think our escaping game is pretty …

add content security policy header to SVG responses

---

services/dynamic/json-path.js

Resolves https://shields.sentry.io/issues/6027856222
I don't have an example of an input that reduces this behaviour, but it looks like there is some circumstance in which `jp()` returns undefined. Lets handle this cleanly instead of throwing an unhandled runtime exception.

cleanly handle null or undefined result from jsonpath-plus in [dynamic] badges

---

services/pingpong/pingpong-base.js

Fix broken URL for https://pingpong.one for uptime status monitoring.

Fix broken URL for pingpong.one

---

services/winget/version.js
services/winget/version.spec.js
services/winget/winget-version.service.js
services/winget/winget-version.tester.js

Fixes #5548 
~~Writing test in progress (might be tomorrow in JST)~~ I wrote tests
This implementation fetches version information from https://github.com/microsoft/winget-pkgs/ with graphql api.
However, actual vrc-get command line interface retrieves package information from sqlite database file in https://cdn.winget.microsoft.com/cache/source.msix.
I don't know if this difference is acceptable for shelds.

add [WingetVersion] Badge

---

services/github/github-manifest.tester.js

We test for label manifest in results while the default label is and should be manifest.
Found the issue in pr #10656
Run results [here](https://github.com/badges/shields/actions/runs/11673579580?pr=10656)

fix [githubmanifest] service tests

---

services/npm/npm-base.js
services/npm/npm-last-update.service.js
services/npm/npm-last-update.tester.js

In this PR, I am following up on my suggestion in https://github.com/badges/shields/pull/10641#issuecomment-2453554943
- If the badge URL is `/npm/last-update/{packageName}` request the abbreviated API response
- If the badge URL is `/npm/last-update/{packageName}/{tag}` request the full version
This will reduce the amount of json we have to download and parse in order to serve a badge in the case where when a tag is not specified. For packages (e.g: npm) that produce a really large response, it would make it possible to use the tag-less variant.

reduce overhead of NPM Last Update badge; test [npm]

---

README.md

This PR reflects changes that I've already made to the relevant groups in GitHub.
Welcome to the core team, @jNullj

add jNullj, remove inactive maintainers

---

frontend/blog/2024-11-14-token-pool.md
services/github/github-helpers.js

Every documentation page for a GitHub badge has a call to action on it that says:
> If your GitHub badge errors, it might be because you hit GitHub's rate limits. You can increase Shields.io's rate limit by [adding the Shields GitHub application](https://img.shields.io/github-auth) using your GitHub account.
That sentence has been around for a very long time, and lots of people have authorised the app. However, I don't think it is very good for two reasons:
1. It doesn't really explain how this works, exactly what you're sharing with us or how to opt out later.
2. It doesn't really reflect the current reality. Today we have plenty of tokens. If you're seeing an error it almost definitely isn't going to be solved by authorising the app.
So in this PR I am attempting to write up a better …

Add blog post about token pool, improve 'authorise our app' CTA

---

services/crates/crates-base.js
services/crates/crates-size.service.js
services/crates/crates-size.tester.js

Eliminate a test case that is no longer relevant due to upstream changes that removed all null crate sizes.
see also upstream merge that removed null for versions.crate_size upstream at rust-lang/crates.io#9926

remove obsolete [CratesSize] test for null size

---

fly.toml

This PR enables Fly's auto suspend/resume feature for review apps.
This will shut review app machines down if they've been idle for 5 mins and then restart them on demand on an incoming request (pretty much how the old heroku review apps used to work).
This should save us some money on review apps.
We could also consider moving the cleanup review apps job to run less frequently so we don't have to keep re-deploying the review apps if we have long-running reviews, although I have not done it in this PR.

auto suspend/resume review apps

---

frontend/docusaurus.config.cjs
frontend/src/pages/privacy.md

closes https://github.com/badges/shields/issues/4225
There is a long-standing issue that shields doesn't declare a privacy policy
This came up again in relation to YouTube specifically, but in general we need to sort this out.
I am not a lawyer, but I reckon this is an improvement on what we are doing right now, which is nothing.
I think this a correct assessment of what we are doing, but if anyone who is familiar with our infra can think of anything I have left out (e.g: is there another service we use whose policy I should be linking to?), that would be useful feedback.

add a privacy policy

---

services/github/github-search.service.js
services/github/github-search.tester.js

provide a non-repository scoped version of Github Code Search badge
and redirect `/github/search/user/repo/query` to `/github/search?query=query%20repo:user/repo`
Closes #10686
Refs #10687

provide a non-repository scoped version of [githubcodesearch]

---

services/gitlab/gitlab-languages.service.js
services/gitlab/gitlab-top-language.service.js
services/gitlab/gitlab-top-language.tester.js

Add [GitLab] Top Language Badge

---

frontend/blog/2024-12-27-simpleicons14.md

Introduce a blog post detailing the upgrade to Simple Icons 14, highlighting the removal of 59 icons and providing a link to the release notes for further information.
follow up for PR #10771

docs: add blog post for Simple Icons 14 upgrade

---

package.json

The `parseDate` test fails on my machine:
I think it's related to the timezone of my machine (macOS). Here is my timezone info:
Should I specify the `TZ` from `package.json`?
Or apply the machine's timezone to the `dayjs` function to fix?

fix `parseDate()` test for different timezones

---

lib/logos.js

fix auto-sized logo sizes

---

services/jira/jira-issue.tester.js
services/jira/jira-sprint.tester.js

Spring.io migrated to GitHub issues some time ago. The Apache JIRA seems to do the job for these tests.

Fix [JiraSprint] tests

---

services/github/github-top-language.tester.js
services/gitlab/gitlab-top-language.tester.js

We don't really need a custom regex here

use `isDecimalPercentage` in tests for [GithubTopLanguage GitlabTopLanguage]

---

core/base-service/base.js
services/endpoint-common.js
services/endpoint/endpoint.service.js
services/endpoint/endpoint.tester.js

Currently, the endpoint badge response schema does not support `logoSize` parameter.

feat(endpoint-badge): add logoSize support; test [endpoint]

---

services/matrix/matrix.service.js

Refs #10776
This isn't a fix, but one of the things that came up in that issue is we should be caching this for a lot longer. The current `cacheLength` of 30 seconds is likely a copy & paste from elsewhere rather than a sensible value for this badge.

cache matrix badges for 4 hours

---

services/coderabbit/coderabbit-pull-request.service.js
services/coderabbit/coderabbit-pull-request.tester.js

This is something we missed in the review of https://github.com/badges/shields/pull/10749
It is an easy one to overlook when the only examples show a really small number.

use metric() in [coderabbit] badge

---

.github/ISSUE_TEMPLATE/1_Bug_report.yml
.github/ISSUE_TEMPLATE/2_Failing_service_test.md
.github/ISSUE_TEMPLATE/3_Badge_request.yml
.github/ISSUE_TEMPLATE/4_Feature_request.md
CONTRIBUTING.md
frontend/docusaurus.config.cjs
frontend/src/components/homepage-features.js
frontend/src/css/custom.css
frontend/src/pages/donate.md

We've got a bit of an issue with cashflow. In November and December this year we brought in about the same or less in donations than we paid out in costs, and our spend with Fly will be increasing in January. There are a few things going on here. Our costs with Fly are going up due to platform changes on their side, and also the amount of donations we're receiving is going down. Sponsors come and sponsors go. That said, the most significant development is that Octopus Deploy are no longer sponsoring us. Octopus Deploy were by far our largest financial donor and contributed over $5,000 to the project over the years they sponsored us. They made their last donation to us in October. To be honest, for a long time the donations from Octopus Deploy alone were enough to fully sustain our …

Improve donate Call To Action

---

README.md
doc/production-hosting.md
frontend/docusaurus.config.cjs
frontend/src/pages/community.md

https://stats.uptimerobot.com/PjXogHB5p has not worked for a long time. Same goes for https://shields.redsparr0w.com/1568/
We still have working monitoring at nodeping https://nodeping.com/reports/status/YBISBQB254
Link to that instead, ditch mentions of uptimerobot

update monitoring docs/links

---

services/matrix/matrix.service.js
services/matrix/matrix.tester.js

Refs #10776
Implements support for https://github.com/matrix-org/matrix-spec-proposals/pull/3266.  
Can be configured with the new parameter `fetchMode` and is enforced for `matrix.org` rooms.
Combined with https://github.com/badges/shields/pull/10778 (increases cache duration by a factor of 480), the amount of requests is reduced by a **factor of 1440**!
The performance is much better than the current implementation (few test runs as an example):

Support [Matrix] summary endpoint

---

services/mastodon/mastodon-follow.service.js
services/mastodon/mastodon-follow.tester.js

It's me again 👋
I updated the docs to reflect the new ID lookup method from https://github.com/badges/shields/issues/4492.
Furthermore the `domain` parameter is now handled and documented as a domain and not as an URL anymore, because that's how it should be.  
To be exact, the parameter should be called `fqdn`, as subdomains are also allowed, but that would be a breaking change.
And don't worry, to not break existing badges URLs are still accepted and "converted" to domains.
---
Closes https://github.com/badges/shields/issues/4492

Renew [Mastodon] docs and improve parameter handling

---

services/terraform/terraform-base.js
services/terraform/terraform-module-downloads.service.js
services/terraform/terraform-module-downloads.tester.js
services/terraform/terraform-provider-downloads.service.js
services/terraform/terraform-provider-downloads.tester.js

Hi!
This PR adds [Terraform Registry](https://registry.terraform.io) downloads summary support for:
* providers
* modules
It uses public API endpoints as [documented here](https://developer.hashicorp.com/terraform/registry/api-docs#get-a-module-downloads-metrics-summary)

Add [Terraform] registry providers and modules downloads

---

cypress.config.js

Fixes #10828
Cypress v13 had breaking changes where the default value for video and videoCompression changed from true to false.
This re-adds video using the cypress config as mentioned in the migration [docs](https://docs.cypress.io/app/references/migration-guide#Migrating-to-Cypress-130)

fix: cypress video

---

core/server/server.js
services/discourse/discourse.service.js
services/dynamic/dynamic-helpers.js
services/endpoint/endpoint.service.js
services/gerrit/gerrit.service.js
services/jira/jira-issue.service.js
services/jira/jira-sprint.service.js
services/maven-metadata/maven-metadata.service.js
services/nexus/nexus.service.js
services/osslifecycle/osslifecycle.service.js
services/python/python-version-from-toml.service.js
services/security-headers/security-headers.service.js
services/sonar/sonar-helpers.js
services/swagger/swagger.service.js
services/twitter/twitter.service.js
services/validators.js
services/vpm/vpm-version.service.js
services/w3c/w3c-validation.service.js
services/website/website.service.js

For most validators where we need an optional and required version, we have two. For example `optionalNonNegativeInteger` and `nonNegativeInteger`
There were lots of places where we were using `optionalUrl.required()` so I made a url validator.
Also, we were defining this validator again in server.js, so I removed that duplication.
I've skipped the tests for securityheaders, sonar, swagger, and w3c, which are all failing for unrelated reasons

URL validator tidyup; affects [discourse dynamic endpoint gerrit jira maven nexus osslifecycle python vpm website] securityheaders sonar swagger w3c

---

services/dynamic/dynamic-xml.service.js
services/dynamic/dynamic-xml.spec.js

As discussed in #10827, If the `Content-Type` header contains one of the mime types supported by `DOMParser`, the first matching mime type will be used instead of `text/xml`.
The default is still `text/xml` for cases when the header is not present or none of the mime types from the list are present.

pass matching mime type to xmldom; test [dynamicxml]

---

services/dynamic/dynamic-xml.spec.js

Refs:
- https://github.com/badges/shields/issues/10827
- https://github.com/badges/shields/pull/10830
- https://github.com/badges/shields/pull/10842
xmldom@0.9.7 fixes this issue. In this PR, I'm just adding a quick regression test for it

add tests for dynamic xml with lowercase doctype

---

frontend/src/components/homepage-features.js

Closes https://github.com/badges/shields/issues/10853
As noted in that issue, inviting users to call `docker pull shieldsio/shields` is not particularly useful because we don't publish a default tag.
More importantly, I've also replaced the description over on DockerHub with a minimal readme that just describes the docker image and available tags, rather than the full README for the repo.
See https://hub.docker.com/r/shieldsio/shields/

remove docker pull command from homepage

---

config/shields-io-production.yml

We set a [hard limit](https://github.com/badges/shields/blob/007a7e6c4739be29479bb29236b5d5355f6345db/core/server/server.js#L561-L573) on how long we'll attempt to serve a request for before we give up. At the moment this is set to 20 seconds in production. I think we should make this timeout shorter. In this PR, I propose: If we've held a connection open for 8 seconds trying to serve a request and we don't have a badge yet, its time to serve a 408 and move on.

time out long running requests more aggressively

---

__snapshots__/make-badge.spec.mjs.js
badge-maker/CHANGELOG.md
badge-maker/lib/badge-renderers.js
core/server/server.spec.js

`<a href=` and `<image href=` in SVGs are widley supported in all modern browsers since ~2019.
- https://caniuse.com/mdn-svg_elements_a_href
- https://caniuse.com/mdn-svg_elements_image_href
Switching to using `href`s instead of the old `xlink:href` syntax allows us to slightly reduce the size of every SVG response we serve.

use SVG2 hrefs

---

services/packagist/packagist-base.js

Packagist.org & Composer maintainer here.. We are trying to phase out the packagist.org/p2/... URLs as we are serving the repo.packagist.org domain via a CDN which is much more efficient for everyone involved. These URLs were historically present but right now I see a lot of the requests for these files on the main domain come from shields.io, and we will shutdown access soon so please make sure /p2/ URLs are not fetched from there. The /packages/... URLs used in fetchByJsonAPI are fine though as those hit our API which is another endpoint.

[Packagist] Update default domain for repo metadata

---

core/base-service/base.js

Quick refresher on how we set max-age:
- Individual badge classes can set a `_cacheLength` specific to that service
- If the badge class itself doesn't define a `_cacheLength` we fall back and use the default for that category. This is the code I am changing in this PR
- If there is no default set for the category, we fall back and use `defaultCacheLengthSeconds` (which we set to 120 seconds in production)
The basic principles of setting defaults by category are:
- There are some data points that need change more frequently than others. Whether your build is passing or failing might change quite frequently. You rarely change your project's license.
- There are some badges that show quite a precise value (build status, version number), whereas others show a more indicative metric (number …

tweak default cache lengths by category

---

package.json

Fixes #10923
this change makes nodemon restart on every configuration change
Scanned the project for all other yml files and we have some at cypress and .github, both don't seem to add value for nodemon reload so i added .github to the ignore list (sypress was already there)

nodemon watch yml conf files and ignore .github

---

services/sourceforge/sourceforge-last-commit-redirect.service.js
services/sourceforge/sourceforge-last-commit-redirect.tester.js
services/sourceforge/sourceforge-last-commit.service.js
services/sourceforge/sourceforge-last-commit.tester.js

some sourceforge projects have multiple repositories, so we need to
specify the repository to use for the last commit service.
should be backward compitable with redirect
fixes #10921

[sourceforge] add repo param to last commit service

---

eslint.config.js

ignore package.json in eslint.
vscode marks all package.json files as having issues without that ignore.

Ignore package.json files in eslint

---

services/sourceforge/sourceforge-commit-count-redirect.service.js
services/sourceforge/sourceforge-commit-count-redirect.tester.js
services/sourceforge/sourceforge-commit-count.service.js
services/sourceforge/sourceforge-commit-count.tester.js

Add support for a repository parameter in the SourceForge commit count service, for projects using non default or multiple repo names.
Includes a redirector for legacy use.
this is a follow up for #10935

Update [SourceForge] commit count badge to support repository parameter

---

.dockerignore
Dockerfile

Somehow `npm prune --omit=dev` does not properly remove unneeded dependencies, this is workarounded by deleting the `node_modules` folder and the running install again.
It also removes some unneeded large files in the docker container.
The container had a size of over 1gb before and now *just* 270MB:
```
moritz@moritz-cyra:~$ docker inspect -f "{{ .Size }}" shieldsio/shields:next
1135416085
moritz@moritz-cyra:~$ docker inspect -f "{{ .Size }}" sha256:1bf4a7778035604c8ce8b284ceffedcdec21671b362906583a743b2024fd887e
271256249
```

docker: cleanup some building

---

services/pypi/pypi-base.js
services/pypi/pypi-helpers.js
services/pypi/pypi-helpers.spec.js

PEP 639 states that the preferred way of documenting a Python project's license is an SPDX expression in a `License-Expression` metadata field. PyPI exposes this information in `info.license_expression` in its JSON data.
Fixes: #11000

[PyPI] Fix license for packages following PEP 639

---

core/base-service/coalesce-badge.js
core/base-service/coalesce-badge.spec.js

Currently we don't place any limit on the size of a label or message
This means you can make badges with really long text, for example:
That is not particularly useful. With the dyanmic and endpoint badges you can construct relatively small requests that force us to render a single SVG containing up to about 10Mb of text (the largest response size we will accept from an upstream URL). Here's a less extreme example that proves the concept:
In this PR, I propose imposing a limit on the size of the message and label fields we will render. 255 characters seems like more than enough to render all useful badges.
I've done this in shields.io core rather than badge-maker. Badge-maker library users can render any length of text

limit label and message to 255 chars

---

services/github/github-pull-request-check-state.tester.js

for some reason older PR are `pending` now with this API.

fix [githubpullrequestcheckstate] live tests - update pr num

---

services/github/github-pipenv.tester.js

Change the message for the locked version of the VCS dependency badge to utilize version validation instead of commit hash validation.
Looked at past pypiserver version names and i think `isVPlusDottedVersionNClausesWithOptionalSuffix` is the best fit here

fix: live test for [githubpipenv] wrong validation

---

services/amo/amo-rating.service.js
services/amo/amo-rating.tester.js

Changes the handling of decimal ratings for Firefox extensions.  
It replicates the behaviour of the Chrome extension rating badges.
Closes #11025

[Amo] Switch to decimal rating for Firefox extension

---

services/pub/pub-popularity.service.js
services/pub/pub-popularity.tester.js

The `/score` endpoint no longer returns a `.popularityScore` property.
I think we have actually ended up relying on an undocumented API endpoint here, which is just used for the pub.dev frontend :angry:  I think the relevant upstream PR is: https://github.com/dart-lang/pub-dev/pull/8435 so it seems the change is intentional. The other pub badges can continue to work.

deprecate [pub] popularity badge

---

__snapshots__/make-badge.spec.mjs.js
badge-maker/lib/badge-renderers.js

I found that the stroke attribute value in the arrow part of the social badge is invalid. It is `d5d5d5` and lacks the preceding `#`, which renders this attribute setting invalid. In actuality, it uses the stroke attribute of the `g` that wraps it.
I believe this stroke has never been effective, it should be safely removed.

Remove Non-Functional SVG Stroke Attribute in Social Badge Renderer

---

lib/load-simple-icons.js
lib/load-simple-icons.spec.js
lib/logos.js
lib/svg-helpers.js

Map vs Object (real-world) Performance - https://measurethat.net/Benchmarks/Show/11290/4/map-vs-object-real-world-performance#latest_results_block
I also removed the outdated test for checking the `get` property from the `simpleIcons` object.

improve performance of lookup simple-icons

---

badge-maker/lib/badge-cli.spec.js
badge-maker/lib/badge-renderers.js
badge-maker/lib/color.js
badge-maker/lib/color.spec.js
badge-maker/lib/index.js
badge-maker/lib/index.spec.js
badge-maker/lib/make-badge.spec.js

The `'use strict'` is no longer needed since the package is ESM.

drop use-strict from badge-maker header

---

badge-maker/package.json

Fixes typescript definition export error:
> Could not find a declaration file for module 'badge-maker'. '…/node_modules/badge-maker/lib/index.js' implicitly has an 'any' type.
>  There are types at '…/node_modules/badge-maker/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'badge-maker' library may need to update its package.json or typings.
Because the `exports` field is present and tells tools to resolve `import 'badge-maker'` (the `"."` export) to `./lib/index.js` (for both require and import conditions), TypeScript follows that path. Since the `exports` for that specific entry point does not have a corresponding `"types"` condition pointing to .`./index.d.ts`, TypeScript fails to find the types via the `exports` map, even though it knows …

badge-maker: Fix ESM type exports

---

badge-maker/CHANGELOG.md
badge-maker/package.json
package-lock.json

* Fix ESM type exports
* drop use-strict from badge-maker header
Some minor changes, should remove unused code and solve a bug with type export.

badge-maker 5.0.1 release

---

badge-maker/package.json

Requiring ESM was ported back to version 20.19.0 of NodeJS, so this PR fixes the exports field so that you can do so. Only requirement is that there is no top-level await for it to work, which doesn't look like this package relies on anyway.
before
```bash
Welcome to Node.js v20.19.2.
Type ".help" for more information.
> require('badge-maker')
Uncaught:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /.../node_modules/badge-maker/package.json
at exportsNotFound (node:internal/modules/esm/resolve:322:10)
at packageExportsResolve (node:internal/modules/esm/resolve:613:13)
at resolveExports (node:internal/modules/cjs/loader:636:36)
at Module._findPath (node:internal/modules/cjs/loader:716:31)
at Module._resolveFilename (node:internal/modules/cjs/loader:1198:27)
at …
```

badge-maker: fix exports so that it can also be required

---

badge-maker/CHANGELOG.md
badge-maker/package.json
package-lock.json

Update the version to 5.0.2 to release a bugfix for issue using require with current export (see #11181).

Release badge-maker version 5.0.2

---

lib/load-simple-icons.js

See https://github.com/simple-icons/simple-icons/issues/13520.
We're planning to deprecate the `import from 'simple-icons/icons'` entry since it's doing the same thing as `import from 'simple-icons'`.

use simple-icons main export entry

---

.github/workflows/test-bug-run-badge.yml

Make sure the link extraction is more generic and can handle extraction of links inside a markdown image format.
Fixes #11217

fix: test-bug-run-badge workflow link extraction

---

README.md
doc/production-hosting.md

I've left mentions of myself in the table in
https://github.com/badges/shields/blob/master/doc/production-hosting.md
as I do still have access to those systems but feel free to remove me as and when access is revoked

remove chris48s from maintainer team in docs

---

.github/actions/draft-release/entrypoint.sh

Related to https://github.com/badges/shields/pull/11256
The script requested the `POST /repos/badges/shields/issues/11256` API successfully, but no label change.
Not sure if it's an API-related or permission-related issue. This PR is an approach to see if we can fix the updating label process by changing the endpoint.

chore: use the modern labels API for draft release action

---

services/github/github-contributors.service.js

Found at #11244 that the endpoint does not include co-auth contriboturs.
We should clearly state that in the badge's page to avoid confusion.

docs: add note to [GithubContributors] about co-authors limitations

---

services/visual-studio-marketplace/visual-studio-marketplace-base.js

We get for some time 429 from vs marketplace.
To handle this without fine tune to every marketplace service I introduced a new cache scale for all vs marketplace services.
I picked 1.2 as cache time scale as we hit in the last 24h about 407k requests and had about 47k 429 errors.
1.2 seems like a good balance that still gives us a bit of headroom but also does not increase the cache time by too much.

increase cache length for [VisualStudioMarketplace]

---

package.json

As posted in [recent blog post](https://eslint.org/blog/2025/08/multithread-linting/)
The recently version we upgraded to of eslint 9.34.0 supports now multi threading.
On my local machine i did see some boost to linter run time.

devop: enable auto concurrency for eslint

---

doc/deprecating-badges.md

Follow up for #11321 .
As discussed at https://github.com/badges/shields/pull/11321#discussion_r2314395170
After the merge open issue about deprecated services that does not follow updated docs:
- ansible-*
- chrome-web-store-price
- github-workflow-status
- pub-popularity
- synk-vulnerability-*
- tas-tests

docs: instruct to rename label to service name at deprecation

---

services/hangar/hangar-downloads.tester.js
services/hangar/hangar-stars.tester.js
services/hangar/hangar-views.tester.js
services/hangar/hangar-watchers.tester.js

Looks like `1` has become a valid plugin name in the meantime.

Fix [Hangar] tests

---

services/github/github-workflow-status.service.js
services/github/github-workflow-status.tester.js
services/pub/pub-popularity.service.js
services/pub/pub-popularity.tester.js

Revise deprecation labels for `GithubWorkflowStatus` and `PubPopularity` to comply with updated documentation requirements to present service name in label of deprecated services.
This change addresses issue #11368.

Update labels of deprecated services [GithubWorkflowStatus PubPopularity]

---

services/codefactor/codefactor-grade.tester.js

Spring Boot is no longer available on CodeFactor (see [here](https://www.codefactor.io/repository/github/spring-projects/spring-boot)), whereas PowerToys is (see [here](https://www.codefactor.io/repository/github/microsoft/powertoys)).

Fix [CodeFactor] test

---

.github/dependabot.yml

Following #11351, [CI broke](https://github.com/badges/shields/runs/51056081421) with the following error:
```
Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'. Ecosystem 'npm' has overlapping directories.
```
TLDR: we can't easily have different update schedules for different packages. Right now, our top priority is to reduce maintenance overhead for the project. I suggest we switch to a monthly schedule for simple-icons as well. If users are eager to get a specific simple-icons update sooner, an intermediary dependency update PR can always be put together. As a positive side-effect, this might encourage more people to get involved in the project.

Fix Dependabot configuration

---

services/gerrit/gerrit.tester.js

The Eclipse Foundation has sunset most of its Gerrit infrastructure in favour of GitHub, let's update the tests accordingly.

FIx [Gerrit] test

---

.gitignore

I occasionally use VS Code to work on this repository, and typically set my projects up as workspaces. Others may do the same. Let's ignore those configuration files.

Ignore VS Code workspace files

---

services/mbin/mbin.service.js
services/mbin/mbin.tester.js

Replace the test community due to changes in public access and clarify the use of URL encoding for special characters in magazine queries as it seems like '@' is commonly used.

Fix [Mbin] test

---

services/bluesky/bluesky-followers.service.js
services/bluesky/bluesky-followers.tester.js
services/bluesky/bluesky-posts.service.js
services/bluesky/bluesky-posts.tester.js

This PR adds two new badges for the Bluesky social network:
- Followers badge: displays the number of followers a user has.
- Posts badge: displays the number of posts a user has made.
Both badges are implemented with proper schema validation and corresponding tests. This contributes to the social category of Shields.io badges.
Fixes #10788

[Bluesky] Add followers and posts badges
